### ISSUE TITLE
Sorting seems broken in 0.1.1

### ISSUE THREAD

**Issue by achan** [JSONAPI-Resources/jsonapi-resources#100]
I'm trying to hit the following url:

```
basechurch.dev/testapp/v1/announcements?sort=+position
```

where `position` is just a regular attribute in my resource. This results in:

``` json
{
  "errors": [{
    "title":"Invalid sort format",
    "detail":" position must start with a direction (+ or -)",
    "id":null,
    "href":null,
    "code":119,
    "path":null,
    "links":null,
    "status":"bad_request"
  }]
}
```

I'm fairly certain that it has to do with `Request#check_sort_criteria` trying to see if `" position"` is a sortable field (see: leading space): https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/request.rb#L193.

Or am I simply using this wrong?

**Comment by barelyknown** [comment]
I have this test in an application that I'm working on that is using the master branch. The test passes.

``` ruby
module V1
  RSpec.describe ApplicantsController do
    context "when an applicant is persisted", clean_with: :truncation do
      let! :applicant do
        FactoryGirl.create(:applicant)
      end
      describe "GET #index" do
        context "with sort param" do
          it "can sort the applicants in either direction" do
            applicant_two = FactoryGirl.create(:applicant)
            get :index, sort: "+applicant_id"
            expect(response.status).to eq 200
            applicant_ids = JSON.parse(response.body)["data"].collect { |a| a["applicant-id"] }
            expect(applicant_ids.max).to eq applicant_ids.last
            get :index, sort: "-applicant_id"
            applicant_ids = JSON.parse(response.body)["data"].collect { |a| a["applicant-id"] }
            expect(applicant_ids.min).to eq applicant_ids.last
          end
        end
      end
    end
  end
end
```

The line that you pointed out is fine.

Do you either have a test that is failing that you can paste in, or if not, can you paste in the logs from your development server for the request that is failing? I'd want to make sure that the request is formatted correctly.

**Comment by achan** [comment]
I've added some specs to demonstrate `get :index` working and `get :index sort: '+position'` not working.

This is currently on 0.1.1, but I got the same thing happening with 0.2.0, even with the changes to sorting in it. I've also tried sorting on a different field, just in case it somehow had something to do with `acts_as_list`, but it still failed.

https://github.com/openmcac/basechurch/issues/20

**Comment by achan** [comment]
Just re-read your post. This fails on 0.1.1 and 0.2.0 but **works** on master. ~~Is master the eventual RC3 for 0.2.0?~~

~~I guess I can switch to master for now.~~

I misunderstood what 0.2.0 was. I don't think I have the option of switching master or 0.2.0 at the moment, at least until I find a good ember adapter/serializer. Any suggestions?

**Comment by lgebhardt** [comment]
The requirement to sort using the + sign was added in 0.2.0 and is a requirement for JSON API 1.0. I'm surprised it fails on 0.2.0, but works on master. Could you double check that?

Master contains changes working towards JSON API 1.0, and I hope to have a new release out shortly after JSON API 1.0 is released (it's imminent) .  As far as an Ember adapter, @dgeb is updating Orbit to work with this release, though I believe it still needs a few changes to comply with the latest version of JSON API (he's been busy on the JSON API spec itself). You might want to check that out.

**Comment by achan** [comment]
My bad. It works on 0.2.0. Not sure what happened, I'm starting to think I didn't restart pow when I was testing it.

Is this something you'd issue a 0.1.2 for?

Orbit looks interesting, but I'm trying to stick with Ember Data. I guess you don't know of any good Ember Data serializers & adapters for JSONAPI..?

**Comment by barelyknown** [comment]
Ember data will support jsonapi by default in the near future (if you can hold out for that).

**Comment by lgebhardt** [comment]
I'd rather not issue a 0.1.2 for that feature as I think it's a dead end. Can you just omit the + in the sort order until a new ember data provider comes out?

**Comment by achan** [comment]
Ah! I'm totally fine with just omitting the + in the sort, I didn't know it was possible.

I'll try to out for Ember Data's built-in support... Thanks guys!

You can mark this as a wontfix/close the issue if you'd like.

**Comment by lgebhardt** [comment]
Excellent! Not using the + was the old way of specifying the sort order. When the other libraries are updated everything should then specify the direction for every sort.
