### ISSUE TITLE
BugReportTemplatesTest failure

### ISSUE THREAD

**Issue by Aryk** [JSONAPI-Resources/jsonapi-resources#1013]
The only test that fails on the master branch is the test from BugReportTemplatesTest.

It fails because Bundler is not loaded in. If I require bundler, it works but then I get this long ouput:

![screen shot 2017-03-27 at 12 01 43 am](https://cloud.githubusercontent.com/assets/525212/24344540/d2e7551a-1280-11e7-9024-540bc99d27e2.png)

Was this test intended to be run? Or can I add a defined?(Bundler) check on it so it can be run optionally?

It sucks to constantly run specs and have it fail on this one test.

**Comment by Fivell** [comment]
сс @senid231
