### ISSUE TITLE
String resource attributes

### ISSUE THREAD

**Issue by fractaledmind** [JSONAPI-Resources/jsonapi-resources#1019]
I have been hunting down some bugs in an API I've started working on, and I finally realized that every bug stems from one issue: every resource defines it `attributes` as Strings, not Symbols. Now, for my project for the time being, I can just convert them to Symbols; however, this does seem to me to be the kind of thing that should be brought up.

I have read thru a decent portion of the source code, but I haven't yet found where would be a perfect place to address this issue. I can say that for me, I have had issues with the `fields[{resource-type}]` param and with PATCHing and POSTing because of this issue. In short, wherever request attributes interact with resource attributes, if the resource attributes are Strings, the entire process will fail.

I'm happy to help with this problem, although I know I am posting this Issue without having a clear sense of direction. I apologize for that.

This is a truly wonderful gem; well-built, and amazingly functional. Thank you for all of your hardwork!

stephen

**Comment by lgebhardt** [comment]
@fractaledmind Sorry for the delay in fixing this. I'll cherry pick #1034 into a new 0.9.x release once it's reviewed and merged.
