### ISSUE TITLE
Arity of custom relationship fetch methods has changed between 0.8.3 and 0.9.0

### ISSUE THREAD

**Issue by valscion** [JSONAPI-Resources/jsonapi-resources#1024]
Hiya,

I just upgraded from JR 0.8.0.beta2 to 0.9.0 and found one weird error being raised in our code:

```
ArgumentError: wrong number of arguments (1 for 0)
```

This was coming from a custom relationship finder, `records_for_#{relationship}`.

```rb
class ListResource < BaseResource
  has_many :listings

  def records_for_listings
    # ...
  end
end
```

![screen shot 2017-04-12 at 14 15 51](https://cloud.githubusercontent.com/assets/482561/24955070/9ce391b0-1f8a-11e7-9e91-b8f5164e11b1.png)

This seems like a surprising API change: Documentation for this (which I even touched upon back in #822) does not have any mention of any arguments coming in:
http://jsonapi-resources.com/v0.9/guide/resources.html#Customizing-base-records-for-finder-methods

![screen shot 2017-04-12 at 14 25 30](https://cloud.githubusercontent.com/assets/482561/24955398/efe7d8b6-1f8b-11e7-8779-3ccb1ac77236.png)

---

It seems that #712 began calling the custom method with some sort of "options" argument:

https://github.com/cerebris/jsonapi-resources/commit/827f5db494ff8add581371db2fe6ac7f1c9abded#diff-608a15fc63beb3dbfec8dc0c490a69caR145

```diff
-        records = public_send(associated_records_method_name)
+        records = public_send(associated_records_method_name, options)
```

The new argument seems to have been added for it be available when called from the `Processor`: https://github.com/cerebris/jsonapi-resources/blob/v0.9.0/lib/jsonapi/processor.rb#L184

```rb
related_resources = nil
if params[:cache_serializer]
  # TODO Could also avoid instantiating source_resource as actual Resource by
  # allowing LinkBuilder to accept CachedResourceFragment as source in
  # relationships_related_link
  scope = source_resource.public_send(:"records_for_#{relationship_type}", rel_opts)
  relationship = source_klass._relationship(relationship_type)
  related_resources = relationship.resource_klass.find_serialized_with_caching(
    scope,
    params[:cache_serializer],
    rel_opts
  )
else
  related_resources = source_resource.public_send(relationship_type, rel_opts)
end
```

I wasn't able to find documentation for the usage of that argument, so I assume it was just a bug by @DavidMikeSimon to apply that argument over there? The reason for my suspicion is the other branch of the conditional above, where the second argument is indeed passed (as supposed to?) to the `relationship_type` method.

If this is indeed a wanted change, I could whip up a PR for updating the documentation if I'd know _why_ the `options` argument is passed here.

This is especially strange as other relationships besides *to-many* don't have this same code in https://github.com/cerebris/jsonapi-resources/blob/v0.9.0/lib/jsonapi/relationship_builder.rb — those custom methods are called _without_ the `options` argument at all.

**Comment by DavidMikeSimon** [comment]
Yep, this is indeed a breaking change in the records_for API. I didn't implement it in an override-friendly way, nor did I correctly document it, so the blame for any confusion rests squarely on my shoulders. :-)

The key here is the change in #712 in `relationship_builder.rb`. My change moves the code that implements filtering, sorting, and pagination of has_many relationships out of the auto-generated `listings` method (which returns Resources) and into the auto-generated `records_for_listings` method (which returns an AR scope). The former then just passes through its options to the latter. This allows the caching system to correctly retrieve the results for `show_related_resources` from the cache without instantiating Resources.

The way I *should* have done this would be to separate the part that applies filters/sorting/pagination from the overrideable method. In master, this has already been correctly done by @lgebhardt when they factored out `ActiveRecordAccessor` (such that the user now overrides their Resource's `records_for` method).

@lgebhardt If you'd like, I can make a patch for 0.9.0 that corrects this problem in a similar way. I'll just need a branch for the 0.9.0 tag to PR into (the `release-0-9` branch seems to be out of date).

@valscion Alternately, for the meantime, I think something like the following will work alright:

```ruby
class ListResource < BaseResource
  has_many :listings

  def records_for_listings_with_customization(options = {})
    records_for_listings_without_customization(options).includes(...)
  end
  
  alias_method_chain :records_for_listings, :customization
end
```

**Comment by valscion** [comment]
Thanks for the thorough explanation! I'm looking forward to the `ActiveRecordAccessor` :)

Do we want to update the documentation somehow in the meantime? The `alias_method_chain` trick could indeed be a good idea for this.

**Comment by DavidMikeSimon** [comment]
@valscion I'd rather change the behavior than the docs, since eventually it'll go back to something more similar to the 0.8 behavior when 0.10 is released.

**Comment by valscion** [comment]
Hmm yeah, but it might be a good idea to change the 0.9 documentation anyway to reflect this, and maybe note that this might not be needed for 0.10 release anymore. As now the documentation is outdated with regards to this case 😕

**Comment by stevenharman** [comment]
An alternative workaround for the `0.9.x` series, which doesn't rely on the deprecated `alias_method_chain` would look like this:

```ruby
class ListResource < BaseResource
  has_many :listings

  prepend Module.new do
    def records_for_listings(_options = {})
      super.includes(...)
    end
  end
end
```

Though I'd be sure to mark that for cleanup when upgrading to JAR >= `0.10` as it's supposed to be fixed there. e.g.,

```ruby
fail 'Remove jsonapi-resource patch' if Gem.loaded_specs['jsonapi-resources'].version >= Gem::Version.create('0.10.0')
```

**Comment by valscion** [comment]
The docs have been updated at some point so this issue is no longer relevant.
