### ISSUE TITLE
Param not allowed

### ISSUE THREAD

**Issue by RitterNorbert** [JSONAPI-Resources/jsonapi-resources#1036]
Hi

After calling create I have to call an other microservice. I'd like to do with the Operation Processors `after_create_resource` method.
I want to be able to use the create function with these params 
```
{
  "data": {
    "type": "registrations",
    "attributes": {
      "person_code": 7,
      "presentation_code": 1088,
      "promo_code": "WEB1000",
      "payment_plan_code": 3,
      "billing_address_line_1": "esse ex",
      "billing_city": "Excepteur ipsum cillum ad",
      "billing_region": "sed",
      "billing_postal_zip_code": "voluptate in adipisicing consectet",
      "country_billing_address": "in adipisicing irure do qui",
      "person": {
        "first_name": "in",
        "last_name": "qui tem",
        "email": "H4dRwcZt8M@avMTki.faq",
        "telephone": "laboris in",
        "highest_level_of_education": 10,
        "work_experience": 10
      }
    }
  }
}
```

but I'm getting this error
```
{
  "errors": [
    {
      "title": "Param not allowed",
      "detail": "person is not allowed.",
      "code": "105",
      "status": "400"
    }
  ]
}
```

Do you know any workaround for this error?

**Comment by senid231** [comment]
Can you give more details? 
As I see response says that `RegistrationResource` doesn't have `attribute :person` at all or in `fetchable_fields`

**Comment by RitterNorbert** [comment]
Hi

Sorry for not being clear
so basically `person` params are not used in registration at all. I just want to pass those to an other microservice after a `registration` is created

**Comment by RitterNorbert** [comment]
Is there anyway to add `person` to the permitted params?

**Comment by senid231** [comment]
@RitterNorbert you can add `person` to `fetchable_fields` but not to`creatable_fields` and pass serialized response to another microservice. But in this case your client will receive `person` in response too.

Could you give some small example of what you want to do?
You mean something like:
```ruby
# resource
class RegistrationResource < JSONAPI::Resource
  model 'RegistrationModel'
  attributes :email, :password, :person
  def self.creatable_fields(_options)
    [:login, :password]
end

# route
jsonapi_resources :registrations, only: [:create]

# processor
class RegistrationProcessor < JSONAPI::Processor
  after_create_resource do
    payload = result.to_hash(MyMicroServiceRegistrationSerializer)
    MyMicroService.new(payload).process!
  end
end

# serializer
class MyMicroServiceRegistrationSerializer < JSONAPI::ResourceSerializer
  def object_hash(source, include_directives = {})
    obj_hash = super
    unless source.is_a?(JSONAPI::CachedResourceFragment)
      attributes = attributes_hash(source, fetchable_fields + [:person])
      obj_hash['attributes'] = attributes unless attributes.empty?
    end
    obj_hash
  end
end
```
just small example. Didn't tested it

**Comment by balakirevs** [comment]
@senid231, @lgebhardt , could you please hint how 0.7.0 version [processor](https://gist.github.com/balakirevs/806bc537215f13e382ebe34f0295483d) should be upgraded to 0.9.11 ? 
otherwise how to access to request/operations which were replaced?
