### ISSUE TITLE
Setup custom route to handle with custom controller method

### ISSUE THREAD

**Issue by jakeleboeuf** [JSONAPI-Resources/jsonapi-resources#1044]
I want to handle requests to a "nested" route with a custom method in my controller. How should I be doing this?

```
Rails.application.routes.draw do
  jsonapi_resources :art_requests

  # How do I do this part the correct way?
  get '/art-requests/:id/download', to: 'art_requests#download'
end
```

**Comment by gkoehl** [comment]
It would be nice to allow for controller hinting in the resource object.  Another great feature would be to have route hinting on top of that.  As the package is currently it seems to hinder a developer's ability to structure the code as they see fit, although I could be missing something.

**Comment by zfhui** [comment]
Have you tried this?
```
jsonapi_resources :art_requests do 
  member do 
    get :download
  end
end
```

This works for me.
