### ISSUE TITLE
Cool JSONAPI hacks

### ISSUE THREAD

**Issue by krainboltgreene** [JSONAPI-Resources/jsonapi-resources#1054]
So while using JSONAPI I've created a few fun hacks. I'm not sure what to do with these, but I'll at least write them down here.

Lets say you have a `Post` and posts have `Summary` objects. These `Summary` objects aren't actually persisted, but computed! Here's how to handle this:  https://gist.github.com/krainboltgreene/e6d6d5a7299406aa15b8fba295e151c0

But the jsonapi-resources hack for this is:

``` ruby
class ApplicationResource < JSONAPI::Resource
  # ...
  def self.apply_includes(records, options = {})
    include_directives = options[:include_directives]

    return records unless include_directives

    clean_includes(records, resolve_relationship_names_to_relations(self, include_directives.model_includes, options))
  end

  def self.clean_includes(records, includes)
    includes.reduce(records) do |accumulation, including|
      if including.respond_to?(:keys)
        accumulation.includes(including.keys.reject(&records.nonincludable_associations.method(:include?)))
      else
        unless records.nonincludable_associations.include?(including)
          accumulation.includes(including)
        else
          accumulation
        end
      end
    end
  end
  # ...
end
```

The hack here is that jsonapi-resources freaks out when you try to include a resource that isn't activerecord. All we're doing here is letting jsonapi-resources know *not* to try to include some types of things. After that it's happy to just call the association function and everything works!

Okay, so this second hack is a little silly but what if you have more than one primary key? For example, a table of taxes has it's own primary key and the zipcode! You'll want to be able to look up by either, so this is how I did that:

``` ruby
class TaxResource < ApplicationResource
  additional_primary_keys :postal_code
end
```

``` ruby
class ApplicationResource < JSONAPI::Resource
  def self.additional_primary_keys(*keys)
    @_additional_primary_keys = keys
  end

  def self._additional_primary_keys
    @_additional_primary_keys || []
  end

  def self.find_by_key(key, options = {})
    records = apply_includes(records(options), options)

    model = _additional_primary_keys.reduce(records.where(_primary_key => key)) {|scope, column| scope.or(records.where(column => key))}.first

    raise JSONAPI::Exceptions::RecordNotFound.new(key) unless model

    self.resource_for_model(model).new(model, options[:context])
  end
end
```

Sadly that hack requires at least Rails 5 or the `or` gem for active record.

Okay, finally here's a fun little hack for passing context on to the model (say to authenticate a request in the model with the request's user)

``` ruby
class Post < ApplicationRecord
  attr_accessor :current_account

  before_validate do
    assign_attributes(account: current_account)
   end
end
```

``` ruby
class PostResource < ApplicationResource
  record_context :current_account
end
```

``` ruby
class ApplicationResource < JSONAPI::Resource
  def self.record_context(key)
    define_singleton_method(:create) do |context|
      super(context).tap do |resource|
        resource._model.public_send("#{key}=", context[key])
      end
    end
  end
end
```

This one is a little funky, because of the weirdness behind `create` and `create_model`. If jsonapi-resources could make this easier that'd be great!

**Comment by pelted** [comment]
@krainboltgreene these may work well being added to the [recipes](https://github.com/cerebris/jsonapi-resources/wiki/JSONAPI::Resources-Recipes) area of the wiki.
