### ISSUE TITLE
Non-fetchable fields still allow filtering

### ISSUE THREAD

**Issue by arcreative** [JSONAPI-Resources/jsonapi-resources#1055]
Sorry for yet another crazy use case here, but I was wondering if `filters` should be limited to fields specified in `fetchable_fields`?

The use case in question is that I have an `admin` flag on my user model, and we don't want this to be visible to normal users.  This works fine, as `fetchable_fields` can conditionally not display that attribute for some users.  The problem is, however, that users can still use `users?filter[admin]=true` if they guess that the property exists, and it still works as [un]intended.  Should this be limited, or is this just too edge/corner-case-y?  Or alternatively, is there a way to conditionally define/remove filters based on the context?

**Comment by senid231** [comment]
filters are fully separated from attributes
filters are declared separately from attributes and may have even different names

```ruby
class FooResource < JSONAPI::Resource
  attributes :foo, :bar, :baz

  filter :baz # if you want to disallow filtering on `baz` field just remove this line
  filter :created_at
  filter :foo

  def fetchable_fields
    super - [:baz]
  end
end
```

**Comment by arcreative** [comment]
I realize that--the issue is that I want to _conditionally_ allow filtering on that attribute, not just shut it off entirely.  I want admins to be able to filter an admin attribute, but not regular users.

**Comment by arcreative** [comment]
I can fudge it in the self.records method, I suppose, but unfortunately that would be a breaking change for my app (albeit only for admins)

**Comment by scottgonzalez** [comment]
Can you use the filter's `apply` option to do the conditional filtering?

**Comment by arcreative** [comment]
@scottgonzalez That looks like a good option--because I would imagine that non-admins getting 400 responses is not too great.  I'll try that out and see if that works!
