### ISSUE TITLE
Removing /v1 from the links e.g. self in JSON results

### ISSUE THREAD

**Issue by ghost** [JSONAPI-Resources/jsonapi-resources#1058]
I am using HTTP headers to add versioning capabilities in my API. I am accessing my API endpoint as such...
`http://localhost:3000/api/posts`
However, for the links in relationship like comments. It shows something like this...
`http://localhost:3000/api/v1/posts/1/relationships/comments`
What I want to do is to have this...
`http://localhost:3000/api/posts/1/relationships/comments`

I read the suggestion from #257 but I could not figure out where to put the monkey patch file (apologies for that.)

Thank you! 

PS: This is connected to these issues: #591 #257 #159

**Comment by bolaum** [comment]
To monkey patch, you can create an initializer like this:
```ruby
# config/initializers/jsonapi_resources_patch.rb

module JSONAPI
  class LinkBuilder
    def formatted_module_path_from_class(klass)
      '/api/'
    end
  end
end
```
