### ISSUE TITLE
Filter for null values

### ISSUE THREAD

**Issue by RitterNorbert** [JSONAPI-Resources/jsonapi-resources#1075]
Hi

I'm trying to filter for null values but its not returning anything.
eg. `/tasks?filter[task_user_id]=null` is not working

Any idea how to get this working?

**Comment by senid231** [comment]
@RitterNorbert by default `JR` filters does not handle null filter,
but you can override this behaviour easily using `verify` or `apply` filter option.

for example:
```ruby
class TaskResource < JSONAPI::Resource
  filter :task_user_id, verify: :nullable_filter
  
  def self.nullable_filter(values, _context)
    values == ['null'] ? nil : values
  end
end
```
