### ISSUE TITLE
Is there a way to create resource and attach it to parent in one request?

### ISSUE THREAD

**Issue by x-yuri** [JSONAPI-Resources/jsonapi-resources#1091]
For instance, I have a user. I want to create a photo that belongs to the user in one request. From what I can see, here's the [relevant part of the spec][1]:

```
POST /photos HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    "relationships": {
      "photographer": {
        "data": { "type": "people", "id": "9" }
      }
    }
  }
}
```

> If a relationship is provided in the relationships member of the resource object, its value MUST be a relationship object with a data member. The value of this key represents the linkage the new resource is to have.

I've been inspecting issues, source code and documentation for a while and is still not sure if this is possible.

[1]: http://jsonapi.org/format/#crud-creating

**Comment by x-yuri** [comment]
My bad. The issue is with client library not sending `relationships` part.

```
curl 'http://localhost:3000/api/posts' -H 'Accept: application/vnd.api+json' \
    -H 'Content-Type: application/vnd.api+json' \
    -d '{"data":{"type":"posts","attributes":{"text":"..."},"relationships":{"user":{"data":{"type":"users","id":1}}}}}'
```

**Comment by x-yuri** [comment]
Another way would be:

`config/routes.rb`:
```rb
Rails.application.routes.draw do
  scope '/api' do
    jsonapi_resources :users do
      post 'posts', to: 'posts#create'
      jsonapi_related_resources :posts
    end
    jsonapi_resources :posts, except: :create
  end
end
```

`app/controllers/posts_controller.rb`:
```rb
class PostsController < ApplicationController
  def create
    params[:data].merge!({relationships:
      {'user' => {data: {type: 'users', id: params[:user_id]}}}})
    super
  end
end
```

This approach seems simler than [the alternative][1].

[1]: https://github.com/cerebris/jsonapi-resources/issues/143#issuecomment-119734210

**Comment by mikemassari** [comment]
What if I want to not just reference but also create the associated resource?
E.g.

```
POST /photos HTTP/1.1

...
    "relationships": {
      "photographer": {
        "data": [
            { "type": "people", "name": "John", "surname": "Smith" },
            { "type": "people", "name": "Susan", "surname": "White" }
        ]

...
```

Would this be possible somehow?
