### ISSUE TITLE
Filtering by a boolean field

### ISSUE THREAD

**Issue by atainton** [JSONAPI-Resources/jsonapi-resources#1098]
Currently, I am trying to filter on a boolean field but unfortunately, I am getting no results when using true or false.

example: ?filter[flag_active]=true.

When I change the filter to use 1's or 0's this filter then works. 

example: ?filter[flag_active]=1.

Why is this the case and how can I fix this issue?

**Comment by senid231** [comment]
@atainton its depends on your database I think.
What DB are you using?

lets say we have table `robots` with boolean column `active`
on request like `GET /robots?filter[active]=true` DB will receive SQL like `SELECT * FROM robots WHERE active = 'true'`

for examples `MySQL` will always return zero records for requests like
```
SELECT * FROM robots WHERE active = 'true'
SELECT * FROM robots WHERE active = 'false'
SELECT * FROM robots WHERE active = '1'
SELECT * FROM robots WHERE active = '0'
```
but for this requests it will return correct qty of records
```
SELECT * FROM robots WHERE active = 't'
SELECT * FROM robots WHERE active = 'f'
```

for `PostgreSQL` all above example are valid and returns correct qty of records
