### ISSUE TITLE
ActionController::API not works

### ISSUE THREAD

**Issue by gabrielwillemann** [JSONAPI-Resources/jsonapi-resources#1124]
This code it's works:
```
class ApplicationController < ActionController::Base
  include JSONAPI::ActsAsResourceController
end
```
But this code it's not works:
```
class ApplicationController < ActionController::API
  include JSONAPI::ActsAsResourceController
end
```
Last code show this error: RuntimeError (Invalid option key: raise_on_unfiltered_parameters=)

Why this happen?

**Comment by ecamalionte** [comment]
I am having the same problem. Maybe rails delegates to the normal controllers the responsibility for validating and filtering.

**Comment by senid231** [comment]
@gabrielwillemann, @ecamalionte works fine with `jsonapi-resources 0.9.0` and `rails 5.1.4`.
What versions of gems are you using?
reproducing report
```ruby
begin
  require 'bundler/inline'
  require 'bundler'
rescue LoadError => e
  STDERR.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true, ui: ENV['SILENT'] ? Bundler::UI::Silent.new : Bundler::UI::Shell.new) do
  source 'https://rubygems.org'

  git_source(:github) do |repo_name|
    repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
    "https://github.com/#{repo_name}.git"
  end

  if ENV['RAILS_VERSION']
    gem 'rails', require: false
  else
    gem 'rails', ENV['RAILS_VERSION'], require: false
  end


  if ENV['JSONAPI_RESOURCES_PG']
    gem 'pg'
  else
    gem 'sqlite3', platform: :mri
    # gem 'activerecord-jdbcsqlite3-adapter',
    #     git: 'https://github.com/jruby/activerecord-jdbc-adapter',
    #     branch: 'rails-5',
    #     platform: :jruby
  end

  if ENV['JSONAPI_RESOURCES_PATH']
    gem 'jsonapi-resources', path: ENV['JSONAPI_RESOURCES_PATH'], require: false
  elsif ENV['JSONAPI_RESOURCES_VERSION']
    gem 'jsonapi-resources', ENV['JSONAPI_RESOURCES_VERSION'], require: false
  else
    gem 'jsonapi-resources', github: 'cerebris/jsonapi-resources', require: false
  end

end

# prepare active_record database
require 'active_record'

class NullLogger < Logger
  def initialize(*_args)
  end

  def add(*_args, &_block)
  end
end

if ENV['JSONAPI_RESOURCES_PG']
  db_name = ENV['JSONAPI_RESOURCES_PG']
  system("psql -c 'DROP DATABASE IF EXISTS #{db_name};'")
  system("psql -c 'CREATE DATABASE #{db_name};'")
  ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: db_name)
else
  ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
end

ActiveRecord::Base.logger = ENV['SILENT'] ? NullLogger.new : Logger.new(STDOUT)
ActiveRecord::Migration.verbose = !ENV['SILENT']

ActiveRecord::Schema.define do
  # Add your schema here
  create_table :users, force: true do |t|
    t.string :name
  end

  create_table :posts, force: true do |t|
    t.integer :user_id, null: false
    t.string :title
    t.string :content
  end
end

# create models
class User < ActiveRecord::Base
  has_many :posts
end

class Post < ActiveRecord::Base
  belongs_to :user
end

# prepare rails app
require 'action_controller/railtie'
require 'jsonapi-resources'

class ApplicationController < ActionController::API
end

# prepare jsonapi resources and controllers
class UsersController < ApplicationController
  include JSONAPI::ActsAsResourceController
end

class PostsController < ApplicationController
  include JSONAPI::ActsAsResourceController
end

JSONAPI.configure do |config|
  config.json_key_format = :underscored_key
  config.route_format = :underscored_key
end

class UserResource < JSONAPI::Resource
  paginator :paged
  attribute :name
  has_many :posts
  filter :name
end

class PostResource < JSONAPI::Resource
  paginator :paged
  attributes :title, :content
  has_one :user
  filter :title
end

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.logger = ENV['SILENT'] ? NullLogger.new : Logger.new(STDOUT)
  Rails.logger = config.logger

  secrets.secret_token = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.eager_load = false
end

# initialize app
Rails.application.initialize!

# draw routes
Rails.application.routes.draw do
  jsonapi_resources :users, only: :index
  jsonapi_resources :posts, only: :index
end

# prepare tests
require 'minitest/autorun'
require 'rack/test'

# Replace this with the code necessary to make your test fail.
class BugTest < Minitest::Test
  include Rack::Test::Methods

  def setup
    6.times do
      user = User.create! name: 'User'
      4.times { Post.create! user: user, title: "Post #{user.id}" }
    end
  end

  def teardown
    User.delete_all
  end

  def test_fetch_users
    query = {
        page: {size: 3, number: 1},
        include: 'posts',
        filter: {name: 'User'}
    }
    get '/users', query, json_api_headers
    assert last_response.ok?
    assert_equal 3, last_response_json[:data].size
    assert_equal 12, last_response_json[:included].size
  end

  def test_fetch_posts
    user = User.last
    query = {
        page: {size: 3, number: 1},
        include: 'user',
        filter: {title: "Post #{user.id}"}
    }
    get '/posts', query, json_api_headers
    assert last_response.ok?
    assert_equal 3, last_response_json[:data].size
    assert_equal 1, last_response_json[:included].size
  end

  private

  def json_api_headers
    {'Accept' => JSONAPI::MEDIA_TYPE, 'CONTENT_TYPE' => JSONAPI::MEDIA_TYPE}
  end

  def last_response_json
    JSON.parse(last_response.body).deep_symbolize_keys
  end

  def app
    Rails.application
  end
end
```
log
```
I, [2017-11-29T10:52:37.092011 #4087]  INFO -- : Started GET "/users?page[size]=3&page[number]=1&include=posts&filter[name]=User" for 127.0.0.1 at 2017-11-29 10:52:37 +0200
I, [2017-11-29T10:52:37.092955 #4087]  INFO -- : Processing by UsersController#index as HTML
I, [2017-11-29T10:52:37.093002 #4087]  INFO -- :   Parameters: {"page"=>{"size"=>"3", "number"=>"1"}, "include"=>"posts", "filter"=>{"name"=>"User"}}
D, [2017-11-29T10:52:37.095620 #4087] DEBUG -- :   User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."name" = 'User' ORDER BY "users"."id" ASC LIMIT ? OFFSET ?  [["LIMIT", 3], ["OFFSET", 0]]
D, [2017-11-29T10:52:37.102752 #4087] DEBUG -- :   Post Load (0.3ms)  SELECT "posts".* FROM "posts" WHERE "posts"."user_id" IN (7, 8, 9)
D, [2017-11-29T10:52:37.104574 #4087] DEBUG -- :    (0.1ms)  SELECT COUNT(*) FROM "users" WHERE "users"."name" = 'User'
I, [2017-11-29T10:52:37.106978 #4087]  INFO -- : Completed 200 OK in 14ms (Views: 0.1ms)

I, [2017-11-29T10:52:37.022974 #4087]  INFO -- : Started GET "/posts?page[size]=3&page[number]=1&include=user&filter[title]=Post+6" for 127.0.0.1 at 2017-11-29 10:52:37 +0200
I, [2017-11-29T10:52:37.025550 #4087]  INFO -- : Processing by PostsController#index as HTML
I, [2017-11-29T10:52:37.025617 #4087]  INFO -- :   Parameters: {"page"=>{"size"=>"3", "number"=>"1"}, "include"=>"user", "filter"=>{"title"=>"Post 6"}}
D, [2017-11-29T10:52:37.029485 #4087] DEBUG -- :   Post Load (0.2ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."title" = 'Post 6' ORDER BY "posts"."id" ASC LIMIT ? OFFSET ?  [["LIMIT", 3], ["OFFSET", 0]]
D, [2017-11-29T10:52:37.035615 #4087] DEBUG -- :   User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 6
D, [2017-11-29T10:52:37.036825 #4087] DEBUG -- :    (0.1ms)  SELECT COUNT(*) FROM "posts" WHERE "posts"."title" = 'Post 6'
I, [2017-11-29T10:52:37.038716 #4087]  INFO -- : Completed 200 OK in 13ms (Views: 0.1ms)

.Finished in 0.14810s
2 tests, 6 assertions, 0 failures, 0 errors, 0 skips
```

you can try to reproduce your errors with this bug report by passing different `RAILS_VERSION` and `JSONAPI_RESOURCES_VERSION` environment variables

**Comment by turbojbdx** [comment]
I am also having this issue. Brand new API install with Rails 5.1.4. 

Trace Below. Sorry, dont really have time to investigate further. 

`actionpack (5.1.4) lib/action_controller/railtie.rb:65:in `block (3 levels) in <class:Railtie>'
actionpack (5.1.4) lib/action_controller/railtie.rb:60:in `each'
actionpack (5.1.4) lib/action_controller/railtie.rb:60:in `block (2 levels) in <class:Railtie>'
activesupport (5.1.4) lib/active_support/lazy_load_hooks.rb:69:in `instance_eval'
activesupport (5.1.4) lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
activesupport (5.1.4) lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
activesupport (5.1.4) lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
activesupport (5.1.4) lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
activesupport (5.1.4) lib/active_support/lazy_load_hooks.rb:49:in `each'
activesupport (5.1.4) lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
actionpack (5.1.4) lib/action_controller/api.rb:145:in `<class:API>'
actionpack (5.1.4) lib/action_controller/api.rb:87:in `<module:ActionController>'
actionpack (5.1.4) lib/action_controller/api.rb:5:in `<top (required)>'
app/controllers/application_controller.rb:1:in `<top (required)>'
activesupport (5.1.4) lib/active_support/dependencies.rb:476:in `load'
activesupport (5.1.4) lib/active_support/dependencies.rb:476:in `block in load_file'
activesupport (5.1.4) lib/active_support/dependencies.rb:661:in `new_constants_in'
activesupport (5.1.4) lib/active_support/dependencies.rb:475:in `load_file'
activesupport (5.1.4) lib/active_support/dependencies.rb:374:in `block in require_or_load'
activesupport (5.1.4) lib/active_support/dependencies.rb:36:in `block in load_interlock'
activesupport (5.1.4) lib/active_support/dependencies/interlock.rb:12:in `block in loading'
activesupport (5.1.4) lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
activesupport (5.1.4) lib/active_support/dependencies/interlock.rb:11:in `loading'
activesupport (5.1.4) lib/active_support/dependencies.rb:36:in `load_interlock'
activesupport (5.1.4) lib/active_support/dependencies.rb:357:in `require_or_load'
activesupport (5.1.4) lib/active_support/dependencies.rb:510:in `load_missing_constant'
activesupport (5.1.4) lib/active_support/dependencies.rb:202:in `const_missing'
app/controllers/songs_controller.rb:1:in `<top (required)>'
activesupport (5.1.4) lib/active_support/dependencies.rb:476:in `load'
activesupport (5.1.4) lib/active_support/dependencies.rb:476:in `block in load_file'
activesupport (5.1.4) lib/active_support/dependencies.rb:661:in `new_constants_in'
activesupport (5.1.4) lib/active_support/dependencies.rb:475:in `load_file'
activesupport (5.1.4) lib/active_support/dependencies.rb:374:in `block in require_or_load'
activesupport (5.1.4) lib/active_support/dependencies.rb:36:in `block in load_interlock'
activesupport (5.1.4) lib/active_support/dependencies/interlock.rb:12:in `block in loading'
activesupport (5.1.4) lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
activesupport (5.1.4) lib/active_support/dependencies/interlock.rb:11:in `loading'
activesupport (5.1.4) lib/active_support/dependencies.rb:36:in `load_interlock'
activesupport (5.1.4) lib/active_support/dependencies.rb:357:in `require_or_load'
activesupport (5.1.4) lib/active_support/dependencies.rb:510:in `load_missing_constant'
activesupport (5.1.4) lib/active_support/dependencies.rb:202:in `const_missing'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:269:in `const_get'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:269:in `block in constantize'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:267:in `each'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:267:in `inject'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:267:in `constantize'
activesupport (5.1.4) lib/active_support/dependencies.rb:582:in `get'
activesupport (5.1.4) lib/active_support/dependencies.rb:613:in `constantize'
actionpack (5.1.4) lib/action_dispatch/http/request.rb:85:in `controller_class_for'
actionpack (5.1.4) lib/action_dispatch/http/parameters.rb:99:in `binary_params_for?'
actionpack (5.1.4) lib/action_dispatch/http/parameters.rb:90:in `set_binary_encoding'
actionpack (5.1.4) lib/action_dispatch/http/parameters.rb:67:in `path_parameters='
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:48:in `block in serve'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/cookies.rb:613:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
railties (5.1.4) lib/rails/engine.rb:522:in `call'
puma (3.11.0) lib/puma/configuration.rb:225:in `call'
puma (3.11.0) lib/puma/server.rb:624:in `handle_request'
puma (3.11.0) lib/puma/server.rb:438:in `process_client'
puma (3.11.0) lib/puma/server.rb:302:in `block in run'
puma (3.11.0) lib/puma/thread_pool.rb:120:in `call'
puma (3.11.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
`

**Comment by gabrielwillemann** [comment]
Issue expired!
