### ISSUE TITLE
Got an issue when change has_one to has_many

### ISSUE THREAD

**Issue by salt8015** [JSONAPI-Resources/jsonapi-resources#1125]
Hi,

When I changed one of relationships from has_one to has many, then I got an error:
errors": [
        {
            "title": "Internal Server Error",
            "detail": "Internal Server Error",
            "code": "500",
            "status": "500",
            "meta": {
                "exception": "undefined method `_model' for []:Array",
                "backtrace": [
                    "/home/tony/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jsonapi-authorization-e2d6b27e164f/lib/jsonapi/authorization/authorizing_operations_processor.rb:92:in `authorize_show_related_resource'",
                    "/home/tony/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'",
                    "/home/tony/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'",
                    "/home/tony/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'",

Anyone can help?
Many thanks,
Tony

**Comment by tony1Centre** [comment]
Fixed the issue by changing jsonapi_related_resource to jsonapi_related_resources

Thanks,
Tony

**Comment by justinfaulkner** [comment]
I had the same issue:

```
Internal Server Error: undefined method `_model' for []:Array
```
 
And the solution was the same for me: I needed to call `jsonapi_related_resources` instead of `jsonapi_related_resource` in Rails' `config/routes.rb`
