### ISSUE TITLE
Upcoming json-api sideposting

### ISSUE THREAD

**Issue by Subtletree** [JSONAPI-Resources/jsonapi-resources#1129]
Relating to the upcoming sideposting pr to json-api https://github.com/json-api/json-api/pull/1197

Has anyone put any thought into how this can be handled by `jsonapi-resources`?

We have the operations pr https://github.com/cerebris/jsonapi-resources/pull/951 which would be good to make use of if possible, treating sideposted resources as separate operations.

Does that seem like the right way to go?

**Comment by lgebhardt** [comment]
JR will support the eventual outcome of [ json-api/json-api#1197](https://github.com/json-api/json-api/pull/1197). I'm in favor of the [Local ID](https://github.com/json-api/json-api/pull/1244) terminology. 

Beyond sideposting I think there's still a need for operations. I hope local ids could be used to replace the JSON pointers in #951.
