### ISSUE TITLE
access to url params in resources class?

### ISSUE THREAD

**Issue by gamesover** [JSONAPI-Resources/jsonapi-resources#1158]
## This issue is a (choose one):
I want to access to params in resources class
- [ ] Problem/bug report.
- [x] Feature request.
- [ ] Request for support. **Note: Please try to avoid submitting issues for support requests. Use [Gitter](https://gitter.im/cerebris/jsonapi-resources) instead.** 

## Checklist before submitting:

- [x] I've searched for an existing issue.
- [ ] I've asked my question on [Gitter](https://gitter.im/cerebris/jsonapi-resources) and have not received a satisfactory answer.
- [ ] I've included a complete [bug report template](https://github.com/cerebris/jsonapi-resources/blob/master/lib/bug_report_templates/rails_5_master.rb). This step helps us and allows us to see the bug without trying to reproduce the problem from your description. It helps you because you will frequently detect if it's a problem specific to your project.
- [ ] The feature I'm asking for is compliant with the [JSON:API](http://jsonapi.org/) spec.

## Description
```
class ContactResource < JSONAPI::Resource
  def fetchable_fields
      if params['hello'] == 'world'
          # I cannot access to params
      else
          super
       end
  end
end
```

**Comment by BobrImperator** [comment]
What about 
```rb
# class JSONAPIBaseController < JSONAPI::ResourceControllerMetal
def context
    {
    params: params
    }
end
```

**Comment by gamesover** [comment]
@BobrImperator , thank you. Yes, this is the way I am currently using. Not sure it is recommended officially.
