### ISSUE TITLE
JSON API RC3 tracking

### ISSUE THREAD

**Issue by steveklabnik** [JSONAPI-Resources/jsonapi-resources#119]
Hey there! I just wanted to let you know that JSON API has hit RC3, and we'd like client libraries to start implementing it like it was 1.0, as a final check that we're good for 1.0. I wanted to make this issue to let you know!

https://github.com/json-api/json-api/issues/484

**Comment by lgebhardt** [comment]
@steveklabnik Thanks. I've been following things, though I know I've missed a few discussions. I've started implementing the changes and so far things are working well.

**Comment by steveklabnik** [comment]
:+1:

**Comment by vrybas** [comment]
@lgebhardt can be closed now :)
