### ISSUE TITLE
rails routes is break after namespace routing resources jsonapi

### ISSUE THREAD

**Issue by jerome-diver** [JSONAPI-Resources/jsonapi-resources#1210]
## This issue is a (choose one):

- [ ] Problem/bug report.
- [ ] Feature request.

### Bug reports:

Not sure it is a bug, but i follow the documentation there and the rails server is running fine(but not rails route).
My Rails application is rails-5.2.1 version
I do implement a namespace (api and v1) in the same way the example is showing, then routing access, create controller and resources.
I choose a namespace because the json data access is separate from html data access of the same models (application is for web ui client and provide json data as well): 

- Category has_many :subjects
- Subject belongs_to :category and has_many :articles
- Article belongs_to :subject

So controller:
`module Api module V1 CategoryController < JSONAPI::ResourceController `
is also inside same category_controller.rb file (i don't know where to write this code... i don't see any precision on that particular point when mix html render view of same models with json render).

By the time, rails server is running fine and provide the data (html and json render together for domain_name/categories (html) and domain_name/api/v1/categories (json)).

BUT
An error occur at:
`rails routes`
times.
said that (first error line):
JSONAPI could not find resource: 'api/v1/categories' (Class Api::V1::CategoryResource not found)

but the server is running, find route and the namespace is define (module Api module V1 ) and the class is also defined inside.

**Comment by lgebhardt** [comment]
Is your resource also in the Api::V1 namespace?

**Comment by jerome-diver** [comment]
i didn't do more than what is explained inside the official documentation.
Now i delete everything and stop to loose time with that, but anyway, maybe you can create a test case application who share models for html access and jsonapi the same way and test it. If something in the documentation is not indicate, maybe you would like to add it ?
thank you and have a good day.

**Comment by Chilinot** [comment]
I have the same issue. The server works fine, and querying the resources from for example curl works great. But attempting to run `rails routes` crashes with the `JSONAPI: Could not find resource 'api/v1/accounts'. (Class Api::V1::AccountResource not found)` error.

This also fails whenever i attempt to run `rspec`, so i cant setup a testing suite at the moment, atleast until i find a workaround.

**Comment by Chilinot** [comment]
I have found the issue. The controller and resource have to be in specific directories as well. In my case, I had the namespaces `/api/v1/controller`. This meant i also had to move my controller in to the `app/controllers/api/v1` directory.

**Comment by jerome-diver** [comment]
Thank you @Chilinot , i have to try it again so.
