### ISSUE TITLE
.default_sort seems broken

### ISSUE THREAD

**Issue by alishersadikov** [JSONAPI-Resources/jsonapi-resources#1213]
## This issue:

- [x] Problem/bug report.

## Description

Default sorting is not taking another field but the primary id. In my resource, I had a default_sort method as such: 
```
      def self.default_sort
        [{ field: :created_at, direction: :desc }]
      end
```
Which now is throwing an error message: 
```
/Users/<some-user>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/jsonapi-resources-69b1d7396eed/lib/jsonapi/active_relation_resource_finder.rb:83
          Error raised through API::BaseResourceController#handle_exceptions
          PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ... $16, $17, $18, $19, $20, $21, $22, $23) ORDER BY funding_re...
                                                             ^
: SELECT  DISTINCT funding_records.id AS funding_records_id FROM "funding_records" LEFT OUTER JOIN "model_one" ON "model_ones"."id" = "model_two"."model_one_id" AND ("model_one"."type" IS NULL) LEFT OUTER JOIN "model_three" ON "model_threes"."id" = "model_ones"."model_three_id" LEFT OUTER JOIN "model_four" ON "model_fours"."id" = "model_twos"."model_four_id" AND "model_fours"."type" IN ('ModelFour') WHERE "model_twos"."model_four_id" IN ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23) ORDER BY model_twos.created_at desc LIMIT $24 OFFSET $25
          Non dev environments will return a 400
```
Based on that error message, I have experimented with changing the default sorting to the primary key: 
```
      def self.default_sort
        [{ field: :id, direction: :desc }]
      end
```
and that works. 

This commit https://github.com/cerebris/jsonapi-resources/commit/4c3c771a29ad5e06681332b5984f563e9cd45eea by @lgebhardt seems to have broken it. In my Gemfile, I am pointing to the commit right before that as a workaround. 

I do not have enough context to point at what exactly has broken it, but lib/jsonapi/active_relation_resource_finder.rb changes might have caused it.

**Comment by CharlieIGG** [comment]
I'm also having trouble with the same, but I cannot pinpoint the culprit in @lgebhardt's commit mentioned above... :\

Also this appears to affect ALL sorting functionality, not just the `default`

---- 

EDIT: For now, staying in non-beta (0.9.5) gem version makes everything 👌

**Comment by lgebhardt** [comment]
@CharlieIGG If you have time could you test this against #1218?

**Comment by CharlieIGG** [comment]
@lgebhardt I'll probably get a chance to tests this during the weekend, I'll come back to this

**Comment by alishersadikov** [comment]
@lgebhardt took me a while to get back but I ran some tests based on the master branch and the default_sort by created_at worked like a charm. I am assuming #1218 has fixed it  - thank you!

**Comment by lgebhardt** [comment]
@alishersadikov Thanks for confirming
