### ISSUE TITLE
Support for scoped queries

### ISSUE THREAD

**Issue by realityendshere** [JSONAPI-Resources/jsonapi-resources#123]
I am curious if there's a plan to incorporate support for ActiveRecord scopes (or ActiveRecord-like scopes) as described in http://guides.rubyonrails.org/active_record_querying.html#scopes into JR.

I can write my own scope filters by overriding the `find` and `apply_filter` methods on a resource. If there are thoughts about supporting scopes in JR, I would be happy to contribute code back to the gem.

**Comment by lgebhardt** [comment]
@realityendshere You can override the `self.records` and `records_for` functions to apply a scope to the ActiveRecord relation that is the basis for the `find` method. https://github.com/cerebris/jsonapi-resources#customizing-base-records-for-finder-methods

I'm not sure if that is what you are looking to do or not. If not, could you provide a pseudo code example of what you have in mind.

**Comment by realityendshere** [comment]
Thanks for the response @lgebhardt 

I think scopes can be useful from an authorization perspective. For example, if I override `self.records` I can put authorization logic in to prevent a user from accessing records outside of a given scope.

Alternatively, I can use scopes as shorthand for a complex combination of filters. For example, I have a scope that looks for `active_users` that applies a packaged combination of queries to make sure the resulting records are in an active state and certain time stamps are before/after the current time.

Overriding `self.apply_filter` for every scope I may want to provide as filtering shorthand works, though the case/when block shown in the JR docs example can get verbose (and potentially mistake prone) if there are a lot of available filtering scopes.

I have found it useful to use something like:

``` ruby
def apply_filter(records, filter, value)
  if records.scopes.has_key?(filter.to_sym)
    records.send(filter, value)
  else
    records.where(filter => value)
  end
end
```

I hope that adds a little clarity to my question. Thanks for all your work on the gem.

Cheers!

**Comment by lgebhardt** [comment]
@realityendshere I use the `records` method like you say to apply security with a scope. Any time you want to apply the same scope to every request it makes sense to use the `records` method.

I'm not sure on applying scopes automatically based on the filters. It seems useful, and could be a nice simplification.  However I'm a bit worried about conflicts if we were to make that the default behavior, especially for existing apps that may have named scopes on their models, and also want to use filters with the same name, but not directly tie the two. Maybe some sort of prefix like `filter_` could be used for any scope that is to be applied by by the apply_filter method. I'm open to other ideas as well.

**Comment by realityendshere** [comment]
@lgebhardt I would be a bit confused to discover a filter and a scope with the same name that return different results. But that's just me. Otherwise, you have a fair point.

A prefix seems reasonable. I guess I would have a mild concern about `_`. I can imagine URLs with `filter_birthdate_filtered` or something redundant or unclear like that. Perhaps something like:

```
GET /users?filter[:active_users]=1
```

or

```
GET /users?filter[scope:active_users]=1
```

I like the first option because it's super short. I like the second option because it's communicating a clear intent.

Thanks!

**Comment by lgebhardt** [comment]
@realityendshere, I was thinking the preface would be used in the scope name, not in the filter name. For example:

```
GET /users?filter[:active_users]=1
```

would look for a scope named `filter_active_users`. I'm not set on the `filter_` preface, just trying for an example. I think the public API should hide the fact that it's using scopes, since those are a Rails concept.

**Comment by realityendshere** [comment]
If

```
GET /users?filter[:active_users]=1
```

connects a scope named `filter_active_users`, I will have to rename/alias all my scopes!

Perhaps, I am underestimating the number of filter names that match scope names in production apps; it seems as if requiring special scope names would be a more painful adjustment for apps with many existing scopes. Some of our scopes are used both within the Ruby code AND as API filters. The `active_users` scope is a good example: I can iterate over only `active_users` within the `User` model or a controller. And I can display a list of active users in a client app. The logic is the same internally and externally. It's nice, DRY code.

I was hoping a prefix or flag would distinguish the filter as scope-based rather than requiring special scopes for the public API and minimize the impact on APIs with filters and scopes that share the exact same name.

**Comment by lgebhardt** [comment]
I see. Given you have an existing app with a lot of scopes do you seen any filter names you wish to use that would conflict with the existing set of scope names? Maybe my worry about name conflicts is overblown.

How about requiring a setting before a scope is used. That could be set global and/or at the resource level. For example:

``` ruby
def _filter_with_scopes
  @_filter_with_scopes ||= JSONAPI.configuration.filter_with_scopes
end

def filter_with_scopes(filter_with_scopes = true)
  @_filter_with_scopes = filter_with_scopes
end

def apply_filter(records, filter, value)
  if _filter_with_scopes? && records.scopes.has_key?(filter.to_sym)
    records.send(filter, value)
  else
    records.where(filter => value)
  end
end
```

There's probably a better name than `filter_with_scopes`, but I hope that get's the idea across. What do you think?

**Comment by realityendshere** [comment]
@lgebhardt In the project I am trying to migrate to JR, filtering operations are performed in the controller.

First, I look for a method on the controller with a given prefix (in my case, the prefix is `query_`). I typically use this strategy for filters that require a combination of multiple query params to work. The best example I have in my API is a `near` filter that finds locations (airports, to be exact) near a given set of lat, long coordinates. The filter combines the lat, long params with a distance param to find matching results.

Second, I look for a matching scope on the model class. The query param value is passed as an argument to the scope.

And lastly, I assemble queries against a specific model attribute (e.g. `first_name == "Tom"`).

We have not run into any scenarios where we had an absolutely unresolvable conflict in naming.

The JR docs already feature instructions for how to override `apply_filter` to inject custom filtering logic into a resource. Therefore, JR clearly allows developers to intercept a particular filter and do anything they want with it before or instead of calling `super`.

While it would be reasonable to offer a config flag to allow devs to choose to automagically tie filters to model scopes, it seems like the currently available options (descriptive scope naming, method overrides) would be plenty enough to handle a very broad range of needs. The filter-to-scope concept would be out of the box, default behavior that could be selectively turned off in the rare instance of a severe naming conflict.

As always, thanks for your time and consideration!

**Comment by pixelhandler** [comment]
@lgebhardt @realityendshere for using a search filter and associated search class method (scope) I used:

``` ruby
filter :search
class << self
  def apply_filter(records, filter, value, _options = {})
    if records.respond_to? filter.to_sym
      value = value.join(' ') if filter.to_sym == :search
      records.send(filter.to_sym, value)
    else
      records.where(filter => value)
    end
  end
def
```

Using the above class method in a Resource class supports a request like so: `/api/v1/things?filter[search]=brain` the model has a class method for `search` which returns `where…`

**Comment by lgebhardt** [comment]
@pixelhandler Thanks. That looks like a nice and simple solution.
