### ISSUE TITLE
Pagination does not have access to the full params hash

### ISSUE THREAD

**Issue by nickyleach** [JSONAPI-Resources/jsonapi-resources#124]
Paginator instances are being created only with the value of `params[:page]`, not the full `params` hash. This breaks the `OffsetPaginator` and limits the utility of custom paginators.

**Comment by lgebhardt** [comment]
JSON API is changing to a group all of the pagination parameters under the `page` parameter:https://github.com/json-api/json-api/blob/gh-pages/format/index.md#pagination-

The paginators should get all of the params under the `page` param. So specify the offset parameters as `page[offset]` and `page[limit]`.

**Comment by nickyleach** [comment]
Thanks. Just read through the docs again and I totally missed that on the first pass :+1:
