### ISSUE TITLE
Save error handling relies on ActiveRecord::RecordInvalid

### ISSUE THREAD

**Issue by realityendshere** [JSONAPI-Resources/jsonapi-resources#127]
I know I am the crazy developer who doesn't use ActiveRecord.

The `JSONAPI::Resource._save` method looks for ActiveRecord exceptions as seen in the code block below. Unfortunately, this throws even worse exceptions about not finding ActiveRecord.

``` ruby
    def _save
      @model.save!
      @save_needed = false
    rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotSaved => e
      raise JSONAPI::Exceptions::ValidationErrors.new(e.record.errors.messages)
    end
```

**Comment by lgebhardt** [comment]
@realityendshere I can't say I'm surprised. I haven't done any more testing than what's in the tests regarding use without ActiveRecord. It would be great if we had a sample app that we could test against that didn't use AR. I don't know if that's something you want to tackle.

**Comment by realityendshere** [comment]
@lgebhardt

Like Peeps without AR?

I could take a look.

I may be mostly away from tech for the next few days. (Opening the issue was partly a reminder to myself to look into this more.)

Thanks.

**Comment by lgebhardt** [comment]
@realityendshere Peeps without AR is what I had in mind.

**Comment by realityendshere** [comment]
Hello! Got busy converting some apps to Ember v1.11...

Here's a first pass at Peeps without AR:

https://github.com/realityendshere/peeps/tree/mongoid

It uses MongoDB and the Mongoid/Moped gems. If it "just works," I'd be pleasantly surprised. Please let me know if I can be of further assistance.

I hope this helps.

Thanks!

**Comment by lgebhardt** [comment]
Thanks for adding the Peeps without AR.

I've added a branch https://github.com/cerebris/jsonapi-resources/tree/remove_ar that moves the AR stuff into the `active_record_operations_processor`. I'm not quite happy with the `_save` method on resources. I'm not yet testing the case where it doesn't save, but it passes all the validations.

I hope once that's done it will be ready for a PR, but I'd appreciate any feedback.

**Comment by pixelhandler** [comment]
@lgebhardt can I help in any way on the https://github.com/cerebris/jsonapi-resources/tree/remove_ar branch, Fridays we work on open source only so we want to use JR with out active record so would be happy to contribute.

**Comment by lgebhardt** [comment]
@pixelhandler Thanks! If you could try out the branch against your code that would be great. I think I've got all the active record exceptions removed from the base classes, but maybe not. So a quick look through would be appreciated.

 As I mentioned above I'd like to rework the _save method, which I hope to get to soon. But if you want to look at that I've got no problem turning that over. It needs to account for callbacks canceling the save as well as validation errors (which should probably be checked after it fails, not before since I think it's now running validations twice).

**Comment by pixelhandler** [comment]
@realityendshere I tried out your 'mongoid' fork/branch of the peeps app with the 'remove_ar' branch of JR that @lgebhardt mentioned. I had trouble running the gem locally. After `be rake build` and changing the Gemfile in the peeps app to the local path the rails app won't start (I was able to install the local gem build from the remove_ar branch). After that the initializer borks out as it doesn't find `require 'jsonapi/resource_controller'` I figured I man not need that initializer with the work in remove_ar branch so commented out. But then the `jsonapi_resources` method in config/routes.rb doesn't work.

I'm using ruby 2.2.2 (with rbenv).

@realityendshere have you tried running the JR gem locally?

**Comment by pixelhandler** [comment]
@lgebhardt I get the same error on the master branch of the peeps app

```
/Users/myusername/code/peeps/config/routes.rb:2:in `block in <top (required)>': undefined method `jsonapi_resources' for #<ActionDispatch::Routing::Mapper:0x007fbf7440aa20> (NoMethodError)
```

I setup the JR gem to run locally in my Gemfile using `gem 'jsonapi-resources', '0.3.2', path: '/Users/myusername/code/jsonapi-resources/pkg'` in `~/code/jsonapi-resources` I built the gem with `bundle exec rake build`

**Comment by lgebhardt** [comment]
Sorry. I was cleaning up what I thought were superfluous require statements. I suspect that's what's going on. I'll look at it soon.

**Comment by lgebhardt** [comment]
If I use the gem from the remove_ar branch in the Peeps/Moingoid project it starts up just fine.

Gemfile:

``` ruby
gem 'jsonapi-resources', :github => 'cerebris/jsonapi-resources', branch: 'remove_ar'
```

and then `bundle`

**Comment by pixelhandler** [comment]
@lgebhardt I'll give that a try thanks! 

Update: Yeah that works fine using the branch on github vs local gem.

**Comment by pixelhandler** [comment]
@realityendshere I rebased your mongoid branch on the upstream master and added a commit to use the remove_ar branch of the gem I'm getting some errors adding a phone number to a contact. I used the curl test examples from the readme. See https://github.com/realityendshere/peeps/compare/mongoid...pixelhandler:mongoid

**Comment by lgebhardt** [comment]
@pixelhandler That's almost certainly due to the change in JSON-API's linkage format. The Peeps version @realityendshere based the Peeps/Moingoid branch on hadn't been updated at the time. See https://github.com/cerebris/peeps/issues/2 for the new format.

**Comment by wzowee** [comment]
Is the remove_ar branch no longer available? I can't see it in the branches dropdown on Github.

I'm trying to get jsonapi-resources working with Mongoid and am having issues with Validations not firing, and records still being created even though fields marked with presence:true have no value present

Resource creation works fine using the @realityendshere approach to setting the Operations Processor to just be the JSONAPI::OperationsProcessor implementation.

**Comment by dgeb** [comment]
@wzowee the remove_ar branch was merged to master today - see https://github.com/cerebris/jsonapi-resources/pull/192
