### ISSUE TITLE
Include all fields of relationship

### ISSUE THREAD

**Issue by rusikf** [JSONAPI-Resources/jsonapi-resources#1321]
## This issue is a (choose one):

- [x] Problem/bug report.
- [ ] Feature request.
- [ ] Request for support. **Note: Please try to avoid submitting issues for support requests. Use [Gitter](https://gitter.im/cerebris/jsonapi-resources) instead.** 

## Checklist before submitting:

- [x] I've searched for an existing issue.
- [ ] I've asked my question on [Gitter](https://gitter.im/cerebris/jsonapi-resources) and have not received a satisfactory answer.
- [ ] I've included a complete [bug report template](https://github.com/cerebris/jsonapi-resources/blob/master/lib/bug_report_templates/rails_5_master.rb). This step helps us and allows us to see the bug without trying to reproduce the problem from your description. It helps you because you will frequently detect if it's a problem specific to your project.
- [ ] The feature I'm asking for is compliant with the [JSON:API](http://jsonapi.org/) spec.

## Description
I have
```
 class PostResource < JSONAPI::Resource
   attributes :title, :content, :published
    has_many :comments, always_include_linkage_data: true
  end

class CommentResource < JSONAPI::Resource
   attributes :content, :post_id
     belongs_to :post, optional: true
   end
```
  How to include comments all fields? I can include it via /posts?include=comments
But this, include comments separately in response 'include' field

Is it possible to include it directly in post relationships?
```

"relationships": {
"comments": {
"data": [
{
"type": "comments",
"id": "1",
 # here I want comment content
}
}
```
}

**Comment by scottgonzalez** [comment]
What you're asking for does not comply with JSON:API. See https://jsonapi.org/format/#fetching-includes
