### ISSUE TITLE
0.10 double loads data from the db on create. Why?

### ISSUE THREAD

**Issue by KevinColemanInc** [JSONAPI-Resources/jsonapi-resources#1325]
## This issue is a (choose one):

- [x] Problem/bug report.
- [ ] Feature request.
- [ ] Request for support. **Note: Please try to avoid submitting issues for support requests. Use [Gitter](https://gitter.im/cerebris/jsonapi-resources) instead.** 

## Checklist before submitting:

- [x] I've searched for an existing issue.
- [x] I've asked my question on [Gitter](https://gitter.im/cerebris/jsonapi-resources) and have not received a satisfactory answer.
- [x] I've included a complete [bug report template](https://github.com/cerebris/jsonapi-resources/blob/master/lib/bug_report_templates/rails_5_master.rb). This step helps us and allows us to see the bug without trying to reproduce the problem from your description. It helps you because you will frequently detect if it's a problem specific to your project.
- [x] The feature I'm asking for is compliant with the [JSON:API](http://jsonapi.org/) spec.

## Description

Currently, I have a user_resource that overrides "#records" so that only the current user (via auth context) can query the user records
```
# UserResource.rb
  def self.records(options = {})
    if options.dig(:context, :current_user)
      User.none
    else
      _model_class.where(id: user&.id)
    end
  end
```

When a resource is created in 0.10, we persist the resource to the db and then try to re-load it by calling UserResource#records. But since this is a registration request and there is no current user, the records returns nothing and thus the json response returns {"data": null}, even though the user was successfully created.

Any ideas how to fix this? For this particular modal, I could look at patching in the current_user to the context, but in general, how would you support a resource the user can only write to, but not (typically) read from? E.g. you create a log record and the api returns a created_at, but the user can't fetch that record again

code flow:
In the processor, we call find_fragments after creating a resource:
https://github.com/cerebris/jsonapi-resources/blob/5517f173a55ba2960c4f0852e8c51f8dd76194cc/lib/jsonapi/processor.rb#L404
find_fragments calls resource.records to reload the model that was created based on the _primary_id
https://github.com/cerebris/jsonapi-resources/blob/5517f173a55ba2960c4f0852e8c51f8dd76194cc/lib/jsonapi/active_relation_resource.rb#L107

   

1. Am I doing this right?
2. Why do we need to reload the object from the db that was just created?

**Comment by tommy-russoniello** [comment]
You can put the action type into the context in your controller, and then use that to skip the filtering for create actions in `records`.

**Comment by KevinColemanInc** [comment]
yeah... but why re-load at all? it seems inefficient. with normal rails, its just:
```
user = User.create(...)
```
This is 1 sql call. Whereas this design is 2?

**Comment by tommy-russoniello** [comment]
I think it is so that creates use the same fetching logic as the other operations. It was confusing for me at first too, but it has actually made overriding and customizing my use of the gem easier. Would you like some help getting this working?

**Comment by KevinColemanInc** [comment]
Ruby is already a slow language. By doubling the number of requests to the db, you're halving the system's efficiency. Lets say your db can handle api 500rps, after this change it would only be api 250rps. 

The benefit being the code is slightly more maintainable for _some_ use cases?

This just feels like a step backwards.

**Comment by tommy-russoniello** [comment]
That would be assuming the insert is the only query generated in the whole request, that 100% of your requests are creates, and that the database is your system's bottleneck though. Either way, I didn't write it so you'd have to ask @lgebhardt for more insight. Let me know if you'd like any help with implementation.
