### ISSUE TITLE
Inclusive Terminology

### ISSUE THREAD

**Issue by vgsantoniazzi** [JSONAPI-Resources/jsonapi-resources#1328]
## This issue is a (choose one):

- [ ] Problem/bug report.
- [x] Feature request.
- [ ] Request for support. **Note: Please try to avoid submitting issues for support requests. Use [Gitter](https://gitter.im/cerebris/jsonapi-resources) instead.** 

## Checklist before submitting:

- [x] I've searched for an existing issue.
- [ ] I've asked my question on [Gitter](https://gitter.im/cerebris/jsonapi-resources) and have not received a satisfactory answer.
- [] I've included a complete [bug report template](https://github.com/cerebris/jsonapi-resources/blob/master/lib/bug_report_templates/rails_5_master.rb). This step helps us and allows us to see the bug without trying to reproduce the problem from your description. It helps you because you will frequently detect if it's a problem specific to your project.
- [ ] The feature I'm asking for is compliant with the [JSON:API](http://jsonapi.org/) spec.

## Description

Use inclusive terminology

### Features:

For symbol names and documentation, avoid introducing new usage of 'master / slave' (or 'slave' independent of 'master') and 'blacklist / whitelist'.

Recommended replacements for 'master / slave' are:

'{primary,main} / {secondary,replica,subordinate}'
'{initiator,requester} / {target,responder}'
'{controller,host} / {device,worker,proxy}'
'leader / follower'
'director / performer'

Recommended replacements for 'blacklist/whitelist' are:
'denylist / allowlist'
'blocklist / passlist'

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=49decddd39e5f6132ccd7d9fdc3d7c470b0061bb

**Comment by tommy-russoniello** [comment]
Fixed in https://github.com/cerebris/jsonapi-resources/commit/fd861d2a73dfa8378fd23fbd2ebb335b45b8939e.
