### ISSUE TITLE
URI.unescape is obsolete

### ISSUE THREAD

**Issue by bf4** [JSONAPI-Resources/jsonapi-resources#1339]
## This issue is a (choose one):

- [x] Problem/bug report.
- [ ] Feature request.
- [ ] Request for support. **Note: Please try to avoid submitting issues for support requests. Use [Gitter](https://gitter.im/cerebris/jsonapi-resources) instead.** 

## Checklist before submitting:

- [x] I've searched for an existing issue.
- [ ] I've asked my question on [Gitter](https://gitter.im/cerebris/jsonapi-resources) and have not received a satisfactory answer.
- [ ] I've included a complete [bug report template](https://github.com/cerebris/jsonapi-resources/blob/master/lib/bug_report_templates/rails_5_master.rb). This step helps us and allows us to see the bug without trying to reproduce the problem from your description. It helps you because you will frequently detect if it's a problem specific to your project.
- [x] The feature I'm asking for is compliant with the [JSON:API](http://jsonapi.org/) spec.

## Description

It's throwing warnings on Ruby 2.7.2 (jr 0.9.10)

> 2020-12-01T01:31:31.730709+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/jsonapi-resources-0.9.10/lib/jsonapi/request_parser.rb:317: warning: URI.unescape is obsolete

per https://github.com/rails/rails/pull/39733 changing `URI.unescape` to `URI::DEFAULT_PARSER.unescape` should be fine

**Comment by marcelolx** [comment]
@bf4 Could you please close this issue since your PR is already merged? 😃

**Comment by bf4** [comment]
Closed by https://github.com/cerebris/jsonapi-resources/pull/1340
