### ISSUE TITLE
show certain fields on show action only

### ISSUE THREAD

**Issue by ahmadabdelhalim** [JSONAPI-Resources/jsonapi-resources#1342]
I have some fields that I only want to show for the show action, not the index action, is there's a way to do that?

**Comment by tommy-russoniello** [comment]
One way to do this (the preferred way as far as I know) is with `fetchable_fields`. You can override it on your resource and remove some fields from the list depending on the current action. You can read about it [here](https://jsonapi-resources.com/v0.10/guide/resources.html#Fetchable-Attributes). Let me know if you need any help.

**Comment by ahmadabdelhalim** [comment]
@tommy-russoniello I thought about using fetchable_fields, but I don't know how to get the current action. Should I pass it to the context?

**Comment by tommy-russoniello** [comment]
I would recommend putting the action in the context, yes. In can be very useful to have easily accessible. In my own app, I just memoize the initial context data (the action as well as other things like the current user) in my base controller for every action. Then it can be accessed anywhere in the controller or resource.

**Comment by ahmadabdelhalim** [comment]
That makes sense. Thank you so much!

**Comment by NikitaKrivov** [comment]
It's possible to use `action: :show` on attribute or attributes list, seems more straightforward way
```
attribute :large_field, action: :show
attributes :content, :description, action: :show
```
