### ISSUE TITLE
NilClass error when using self.updateable fields

### ISSUE THREAD

**Issue by mmartinson** [JSONAPI-Resources/jsonapi-resources#141]
To make sure that I'm using self.createable fields and self.updateable fields in the right way, is the intention that you can use these to add as well as limited attributes that can be written? Could you, for example not an attribute in the attributes macro-style method but instead include it in the above mentioned and still allow it to be written. 

When calling a create using this code:

``` ruby
  attributes :request_status

  has_many :time_off_request_components, class_name: 'TimeOffRequestComponent'

  def request_status
    @model.current_state
  end

  def self.updateble_fields(context)
   super +  [:time_off_request_components]
  end

  def self.createable_fields(context)
   super +  [:time_off_request_components, :comment]
  end
```

The error I get is:

 TypeError:
       no implicit conversion of nil into Hash

It has no useful backtrace but stepping through with the debugger suggests that it is coming from jsonapi/resource.rb @ line 424. @_attributes[attr] can't be merged with default_attribute_options because it is nil. 

If this is from using these methods incorrectly, maybe you could let me know if there is a clean way to accomplish what I'm trying to do using the existing API. As mentioned in #129 and #133, I'm trying to do a complex post that involves sending data under the time_off_request_components key nested inside the primary object. I then want this nested object to be serialized in the default side-loaded way. 

Calling `@request.include << 'time_off_request_components'` in a controller before_filter gets it right when it is not whitelisted in the resource, but when it is listed I can't seem to get the side-loaded format to serialize. Should I be whitelisting and explicitly calling a serializer from inside the resource from a reader-override method, or is there a way to get around whitelisting that lets the default include functionality work?

**Comment by lgebhardt** [comment]
As the code is written you can't add additional fields into the `self.createable_fields` and `self.updateble_fields` fields functions, only remove them. The problem is `@_attributes[attr]` returns nil for the added fields, which breaks things as you can see.

What is the use case for adding a field that isn't an attribute on the resource?

**Comment by mmartinson** [comment]
As I was describing in the other issue threads that I referenced above, I have been trying to find the best way to accept a complicated set of post params that don't map onto a single model and then return the saved data in the side-loaded forward under 'includes'. I realize it sounds contrived, but we have decided to diverge from the spec by accepting a nested post/put until the JSONAPI spec authors include a more clear alternative in 1.1. [https://github.com/json-api/json-api/issues/205]

What I end up getting is that the associated resources are returned from the POST both nested under the main data object as well as included at the top level, where I really only want them at the top level. 

I've managed to use a clean enough hack as an after filter in the controller that deletes the unwanted nested params. It seems removing the nested resource (:time_off_request_components) from the fetchable fields meant that they couldn't be loaded as a side-loaded included resource either.

**Comment by lgebhardt** [comment]
I'm having a bit of trouble wrapping my head around this. What I can say is the resource does not need to be a one-to-one mapping to a model. It seems that should allow you to create the a structure that at least returns the data properly side loaded, though without seeing the code I can't be sure.

**Comment by mmartinson** [comment]
Ya thanks for the quick reply. I've got workable hack figured out so if this seems confounding feel free to consider it closed. I'll attempt to give it one more go though in case you're the curious type and this is bothering you.
- I want to accept a parameter key that has the same name as a has_many association defined on the builder, so I can manually create the record it as a nested resource. The key needs to be listed as an attribute so that an error is not thrown
- Listing the parameter as an attributes means that, when being serialized, the resource expects either an attribute on the model or a custom method to match this name, instead of inferring the resource to include from the association (I presume, because this works seamlessly for other simpler resources).
- Writing a custom method that manually calls the appropriate serializer gives me both nested and side loaded data.

```
model_name 'TimeOffRequest'

  attributes :id,
             :request_status,
             :time_off_request_components,
             :comment

  has_many :time_off_request_components, class_name: 'TimeOffRequestComponent'

  def time_off_request_components
    serializer = JSONAPI::ResourceSerializer.new(TimeOffRequestComponentResource)
    component_resources = @model.time_off_request_components.map { |component| TimeOffRequestComponentResource.new(component) }
    component_resources.each { |component_resource| serializer.serialize_to_hash(component_resource) }
  end
```
