### ISSUE TITLE
Better handling of routes that don't conform to JSON API

### ISSUE THREAD

**Issue by fotinakis** [JSONAPI-Resources/jsonapi-resources#143]
I had a resource like this:

``` ruby
jsonapi_resources :builds, only: [:index, :show]
```

Underneath this, I wanted an explicitly non-RESTful/non-JSON-API endpoint called "finalize", so I did this:

``` ruby
jsonapi_resources :builds, only: [:index, :show] do
  post :finalize
end
```

However, I didn't find out until days later that simply passing a block to jsonapi_resources silently removes ALL nested routes for related resources (ie. /builds/123/subresources). It would be nice if this block was merged in instead of replacing all the implicit routes, or if this behavior was documented.

**Comment by lgebhardt** [comment]
@fotinakis, Sorry for the confusion. It's sort of documented in https://github.com/cerebris/jsonapi-resources#jsonapi_links: "An empty block will not create any relationship routes." I agree this should be called out more visibly. The intent was to allow you full control over the routes by using a block and only adding the ones you need. I didn't foresee the use of the block for non-RESTful routes.

**Comment by lgebhardt** [comment]
Would it make sense to add a method to put in all the default relationship routes? Then you could still get the default behavior (though it would require a single method in the block) along with the non-RESTful routes. Of course you could also keep it the way it is currently and add back only the relationship routes you need.

**Comment by fotinakis** [comment]
Oh I see where I got confused, I thought "jsonapi_links" was only about the "/links" part of the URL, but it also means the nested/related resource. Gotcha.

The add-all method could be useful, but now that I understand this I'll just add blocks everywhere and specifically list the relationships I care about exposing, plus my non-RESTful routes. Thanks!

**Comment by fotinakis** [comment]
Actually was just testing it, looks like my assumption was right — adding a plain `jsonapi_links :comments` under a `jsonapi_resources :posts` will only create the `/posts/:post_id/links/comments/...` routes and _not_ the actual `/posts/:post_id/comments` route.

Is there a supported way to do that when providing a block arg?

**Comment by fotinakis** [comment]
Looks like this works?

``` ruby
    jsonapi_resources :posts, only: [:show, :index] do
      jsonapi_links :comments, only: [:show]
      jsonapi_resources :comments, only: [:index] { }
    end
```

Notice the empty code block, to avoid creating all the implicit routes while nested. :/

**Comment by fotinakis** [comment]
:x: Found the failure mode of that ^ —for the nested resources it doesn't actually treat them as related to the top-level, so requesting the related resources returns ALL of them, without regard to their parent.

Replacing `jsonapi_resources` with the (undocumented) `jsonapi_related_resources` works.

**Comment by lgebhardt** [comment]
Glad you found `jsonapi_related_resources`, and thanks for pointing out the missing documentation. I'll update the README soon.

**Comment by senid231** [comment]
jsonapi_related_resources allows only get resources
i use workaround to have ability to create/update/destroy nested resources

``` ruby
jsonapi_resources :authors do
  jsonapi_resources :posts
end
```

``` ruby
class PostsController < ApplicationController
  def context
    super.merge author_id: params[:author_id]
  end
end
```

``` ruby
class PostResource < JSONAPI::Resource
  def records_for(options = {})
    key = options.fetch(:context, {})[:author_id]
    key.present? ? super.where(author_id: key) : super
  end
end
```
