### ISSUE TITLE
Routing Error - No route matches [GET] "/api/v2/blacklist_emails"

### ISSUE THREAD

**Issue by jamonholmgren** [JSONAPI-Resources/jsonapi-resources#149]
I'm getting a Routing Error when using the `jsonapi_resources` route helper.

``` ruby
  namespace :api do
    namespace :v1, :defaults => { :format => :json } do
      # ... omitted
    end
    namespace :v2, :defaults => { :format => :json } do
      # get :blacklist_emails, to: "blacklist_emails#index" # enabling this works
      jsonapi_resources :blacklist_emails
      jsonapi_resources :activities
    end
  end
```

Enabling the specific `get` request works fine. What could I be doing wrong?

![screen shot 2015-04-06 at 6 11 18 pm](https://cloud.githubusercontent.com/assets/1479215/7015425/7d2af97c-dc88-11e4-800f-7f404e81525e.png)

**Comment by jamonholmgren** [comment]
Doh...I ran `rake routes` like Rails said to and realized the URL is dasherized. Never mind!

**Comment by lgebhardt** [comment]
The default is dasherized, but you can change that in the configuration section.

``` ruby
JSONAPI.configure do |config|
      #:underscored_route, :camelized_route, :dasherized_route, or custom
      config.route_format = : underscored_route
end
```

See https://github.com/cerebris/jsonapi-resources#key-format for more details on the configure method. It looks like the documentation for this didn't make it into the readme. Sorry for that.

**Comment by jamonholmgren** [comment]
No worries, I should have guessed it would be dasherized. :-)
