### ISSUE TITLE
Request spec (RSpec-Rails) returns "The required parameter, data, is missing."

### ISSUE THREAD

**Issue by jamonholmgren** [JSONAPI-Resources/jsonapi-resources#151]
I'm trying to test my API with an RSpec-Rails request spec. Here's the spec:

``` ruby
    # logged_in_headers is defined above

    describe "POST /create" do
      it "creates a new campaign" do
        post "/api/v2/campaigns", { "data" => {} }, logged_in_headers
        expect(JSON.parse(response.body)).to eq({ not_sure: "what" })
      end
    end
```

I'm getting this error:

```
  1) /api/v2/campaigns logged in POST /create creates a new campaign
     Failure/Error: expect(JSON.parse(response.body)).to eq({ not_sure: "what" })

       expected: {:not_sure=>"what"}
            got: {"errors"=>[{"title"=>"Missing Parameter", "detail"=>"The required parameter, data, is missing.", "id"=>nil, "href"=>nil, "code"=>106, "path"=>nil, "links"=>nil, "status"=>"bad_request"}]}

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -:not_sure => "what"
       +"errors" => [{"title"=>"Missing Parameter", "detail"=>"The required parameter, data, is missing.", "id"=>nil, "href"=>nil, "code"=>106, "path"=>nil, "links"=>nil, "status"=>"bad_request"}]
```

It appears the params is not passing through when we're posting. Any ideas?

**Comment by jamonholmgren** [comment]
Could be related to the fact I'm on Rails 3.2. See issue #152.

**Comment by adamworrall** [comment]
To be a valid JSON-API request you need to at least have the "type" attribute set in the data object, so I believe your request should give an error of some kind.

There is something funny going on with blank data requests though - it seems like attributes whose values are empty are getting discarded altogether - I have a POST endpoint I'd like to work without requiring any parameters at all but I'm not able to get a "data": {"type": "tokens"} request to complete properly. It works fine if I add just an id. 

Additionally, I tried to see if I could replicate your issue and I succeeded on Rails 4.2. When I add a "type" attribute, though, it returns 201 and fires my after_create callbacks even though the model didn't save correctly. Seems like this case ignores the model validations?

**Comment by lgebhardt** [comment]
The request is certainly invalid, but the error message doesn't look like what we should be returning in that case. However it's returned that way under Rails 4 as well. I'll look into what's going on soon.

**Comment by lgebhardt** [comment]
Looks like it's coming from https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/request.rb#L49, which is using strong parameters. It's failing because there is no content.

~~Having thought about it for a few more minutes I'm not actually sure the empty request is actually invalid. I'll see if I can fix it so an empty data is acceptable and then it's up to your model validation as to whether it's a valid operation.~~

It is invalid, as @adamworrall pointed out. http://jsonapi.org/format/#crud-creating specifies it must have at least a `type` member. Sorry for the confusion. Time for sleep.

**Comment by jamonholmgren** [comment]
Thanks for the help, @adamworrall and @lgebhardt. It does seem like the error message is wrong in this case with the missing "type" parameter.

I updated the spec with the "type" and am getting a new error:

``` ruby
    describe "POST /create" do
      it "creates a new campaign" do
        post "/api/v2/campaigns", { "data" => { "type" => "campaign" } }, logged_in_headers
        expect(JSON.parse(response.body)).to eq({ not_sure: "what" })
      end
    end
```

Error:

```
     Failure/Error: post "/api/v2/campaigns", { "data" => { "type" => "campaign" } }, logged_in_headers
     JSON::ParserError:
       757: unexpected token at 'data[type]=campaign'
```

Any ideas?

**Comment by adamworrall** [comment]
@jamonholmgren try encoding your body hash as JSON? If that works, you should run into the problem I mentioned earlier. #153 should fix that.

**Comment by jamonholmgren** [comment]
Okay, we're getting somewhere @adamworrall ! 

``` ruby
    describe "POST /create" do
      it "creates a new campaign" do
        post "/api/v2/campaigns", { "data" => { "type" => "campaign", "name" => "test campaign" } }.to_json, logged_in_headers
        expect(JSON.parse(response.body)).to eq({ not_sure: "what" })
      end
    end
```

Now I get:

``` ruby
{
  "errors" => [{
    "title" => "Invalid resource", "detail" => "Campaign is not a valid resource.", "id" => nil, "href" => nil, "code" => 101, "path" => nil, "links" => nil, "status" => "bad_request"
  }]
}
```

I for sure have a Campaign resource.

``` ruby
class Api::V2::CampaignResource < JSONAPI::Resource
  attributes :id, :name
end

```

**Comment by jamonholmgren** [comment]
Ah, it was supposed to be `"type" => "campaigns"` (plural). Working now!

I submitted a PR for preliminary Rails 3.2 support ( #156 ), so I think we can consider this closed.

**Comment by lgebhardt** [comment]
Types are always plural in JSON API. You have it as singular "campaign".

Also, you don't need the :id in attribute, which is a new fix. :id is now always included. But it doesn't hurt to have it.

I'm not sure if you caught it, but I released a new version that includes #153

**Comment by lgebhardt** [comment]
What timing. Glad you figured it out. I'll look into the PR. Thanks.

**Comment by jamonholmgren** [comment]
:+1:

**Comment by amosjyng** [comment]
Having a similar problem, in RSpec

```
      it "returns 201 with corresponding location" do
        request.env['CONTENT_TYPE'] = 'application/vnd.api+json'
        post :create, '{ "data": { "type": "concepts", "attributes": { "description": "Lorem ipsum" } } }',
             valid_session
        expect(response.status).to eq(201), "Request #{valid_attributes.to_json} failed: #{response_body}"
        expect(response.location).to eq(v1_concept_url(Concept.last))
      end
```

produces

```
  3) V1::ConceptsController POST #create with valid params returns 201 with corresponding location
     Failure/Error: expect(response.status).to eq(201), "Request #{valid_attributes.to_json} failed: #{response_body}"
       Request {"data":{"type":"concepts","attributes":{"description":""}}} failed: {"errors"=>[{"title"=>"Missing Parameter", "detail"=>"The required parameter, data, is missing.", "id"=>nil, "href"=>nil, "code"=>106, "path"=>nil, "links"=>nil, "status"=>"bad_request"}]}
     # ./spec/controllers/v1/concepts_controller_spec.rb:58:in `block (4 levels) in <top (required)>'
```

But the same request using the Postman app seems to work just fine. Any ideas how to fix this?

**Comment by lgebhardt** [comment]
You have quotes wrapped around the payload. I'm not using RSpec, but that should probably be a hash.

``` ruby
it "returns 201 with corresponding location" do
  request.env['CONTENT_TYPE'] = 'application/vnd.api+json'
  post :create, { "data": { "type": "concepts", "attributes": { "description": "Lorem ipsum" } } }, valid_session
  expect(response.status).to eq(201), "Request #{valid_attributes.to_json} failed: #{response_body}"
  expect(response.location).to eq(v1_concept_url(Concept.last))
end
```

**Comment by amosjyng** [comment]
Well that was embarrassing. Haha works now, thanks a lot :)
