### ISSUE TITLE
Error in Value Formatter documentation / implementation?

### ISSUE THREAD

**Issue by gavinballard** [JSONAPI-Resources/jsonapi-resources#162]
Hi there!

The documentation for the value formatters says:

> The format method takes the raw_value, and context parameters. raw_value is the value as read from the model, and context is the context of the current user/request.

Maybe I'm just reading this incorrectly, but the `context` parameter that's actually being passed by `ResourceSerializer` seems to be the resource instance being serialized.

It could just be that I'm getting confused by the `context` label, but I was expecting to have access to the `context` I was setting inside my controller here.

**Comment by lgebhardt** [comment]
Thanks for pointing this out. The code is indeed inconsistent. I originally was providing both `source` and `context` to the value formatters. @dgeb and I decided that we were going to make the formatters more focused. It looks like I completely fumbled that code(https://github.com/cerebris/jsonapi-resources/commit/1c53c3f9346365073813fc11e2aeac5383d0be18?diff=split), and I don't remember whether the intention was to remove source, context or both. 

I'm thinking we should remove both, though I'm open to good use cases to justify other options. My reasoning is resources have the context, and the serializer does not. Resources also can have a custom method to override the default getter or setter and this method would have access to the context as well as to the other fields on the resource. Thus a custom getter can provide all the functions that a ValueFormatter can when provided with both source and context. This has the added benefit of keeping more logic in the resource, which I think is more appropriate than in a ValueFormatter.

Thoughts?

**Comment by gavinballard** [comment]
Thanks for the super-quick response, @lgebhardt! Today has been my first day working with the library, so take everything I say with a grain of salt :).

For context, my use case is actually pretty close to that in the docs - I want to format a Datetime in the timezone of the requesting user's locale. From the sound of it, you'd recommend customising the getter on the resource to perform the timezone conversion before passing it on to the formatter.

Your reasoning around removing both source and context from the formatter makes sense and that would certainly work for my case - I can use eg `created_at.in_time_zone('AEST')` before I hand the value off to the formatter, which simply does `raw_value.strftime('%e %b %I:%M%P %Z')`.

However, I do however wonder about situations where the underlying `raw_value` being passed to the formatter is the same, but actual format to be used is context-dependent.

The example I can think of that's quite close to my current situation would be if users were able to select a preferred date format, eg `2015-02-01` instead of `02/01/15`. In that situation, I'd guess the custom getter could utilise the context and simply return the value as a string, but that does seem to defeat the purpose of having custom formatter.

**Comment by lgebhardt** [comment]
Formatting dates to a user's preference is the use case I first envisioned. It was the original reason I added the context to the ValueFormatters.  However I'm now not even sure this is an appropriate action for an API. My current line of thinking is it would be better for the server to speak in UTC and the API client to do the formatting. But what I think is appropriate and what we want the library to enforce are separate things.

I'm not sure why I didn't focus on this earlier, but if we leave the code passing in the source resource you will have access to the context through the resource. Then you can use either method (formatter or resource method override) to produce the intended result. I just need to fix the code up so it always sends the source. I'll see if I can get this done soon.

**Comment by gavinballard** [comment]
What you say makes a lot of sense :).

Thanks for the help here and with the project in general - it's been super easy to get up and running!

**Comment by lgebhardt** [comment]
Glad to hear it's been easy to get started with.

**Comment by dgeb** [comment]
I think we're just confusing the interface of value formatters by allowing either `source` or `context` as arguments. It muddies the responsibilities of formatters vs. resources.

I'd like to remove both arguments from value formatters in favor of custom getters on resources themselves, unless a strong case can be made to keep either. Context-specific presentation logic really doesn't belong in an API.

**Comment by lgebhardt** [comment]
Ok, I simplified the ValueFormatters by removing both `source` and `context`. I think that's the correct choice.

**Comment by dgeb** [comment]
Thanks @lgebhardt :+1:

**Comment by vrybas** [comment]
@gavinballard can be closed?

**Comment by gavinballard** [comment]
Looks like it, thanks!
