### ISSUE TITLE
Formatting the resource `type` field as dasherized

### ISSUE THREAD

**Issue by wvteijlingen** [JSONAPI-Resources/jsonapi-resources#171]
Currently the value of the `type` field is formatted using underscore_notation. JSON:API recommends formatting this as dasherized:

> It is recommended that resource types, attribute names, and association names be "dasherized". (...) Dasherized and pluralized resource types can be used as URL segments without translation

Is this implemented somewhere? I looked into value formatters but it seems that reserved fields like `type` don't use these formatters.

**Comment by lgebhardt** [comment]
The type formatting is controlled by the key_formatter. https://github.com/cerebris/jsonapi-resources#key-format By default this should be dasherized. Do you have an alternate key formatter specified?

**Comment by wvteijlingen** [comment]
Nope, I don't have any custom key formatters configured. Just to be sure, I'm talking about the _value_ of the `type` field. So the current response is:

``` json
{
    "id": "1",
    "type": "redeemed_vouchers"
}
```

While I expected:

``` json
{
    "id": "1",
    "type": "redeemed-vouchers"
}
```

**Comment by lgebhardt** [comment]
I'd expect that too. I'll look into this. Which version are you using?

**Comment by wvteijlingen** [comment]
Using version `0.3.1`. Thanks for looking into it!

**Comment by john-griffin** [comment]
Confirmed, same issue here on `0.3.1`.

**Comment by lgebhardt** [comment]
There were a couple things wrong in there. I've updated PR #168 with the fixes, and some additional tests. If you want to test against that branch I'd appreciate some confirmation that it's now right.

**Comment by john-griffin** [comment]
@lgebhardt switching to that branch fixes the issue. I now get dashed types back in the response. Thanks for that! All my other tests still pass too.

**Comment by lgebhardt** [comment]
@john-griffin thanks for testing. I'll see if we can get a new version (0.3.2) out today.

**Comment by john-griffin** [comment]
That would be great, thanks Larry!

**Comment by barelyknown** [comment]
I noticed a similar problem related to the `linkage` object. It was not being unformatted during requests. This PR (https://github.com/cerebris/jsonapi-resources/pull/173) fixes that.
