### ISSUE TITLE
Inbetween nested join resource is being lost in `?include`

### ISSUE THREAD

**Issue by slaskis** [JSONAPI-Resources/jsonapi-resources#178]
I just bumped in to this little gem. It's a bit tricky to explain so I'll just start with a few examples:
- `/list?include=x` - :+1: Includes `x`
- `/list?include=x.y` - :+1: Includes `y` (through `x`) 
- `/list?include=x,x.y` - :+1: Includes `x` and `y` (through `x`)
- `/list?include=x,x.y.z` - :+1: Includes `x` and `z` (through `y`, through `x`)
- `/list?include=x,x.y,x.y.z` - :-1: Includes `x` and `z` (through `y`, through `x`) but **not** `y` (through `x`) as I would have expected.

I'm guessing I get's lost somewhere in the AREL query or serialised away somehow but I just wanted to see if it's the expected results.

**Comment by lgebhardt** [comment]
All the cases you list should be :+1: . I'll take a look at why `y` isn't being included.
