### ISSUE TITLE
Updating associations does not work when primary key is set to permalink key

### ISSUE THREAD

**Issue by soeffing** [JSONAPI-Resources/jsonapi-resources#179]
Hi,

we use JR with our ember app. In order to have pretty URLs we specified the `permalink` attribute of our `Ad` model to be the primary link. This causes problems when I want to update the association of an `Ad` model to another model.

Example:

When I do a request to update the `Ad` association of our `Award` model and I inspect the `field_data` variable inside the `_replace_fields` [method](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource.rb#L169) I see the following:

```
{:attributes=>
  {:description=>"new description v3",
   :permalink=>"4198-rock-deodorant",
   :amount=>"999",
   :ad_id=>108622,
   :contest_id=>440,
   :ad_type=>"Video",
   :state=>"assigned"},
 :has_one=>{:ad=>"ad-permalink", :contest=>"contest-permalink"},
 :has_many=>{}}
```

The values inside the `:has_one` key are use inside the `_replace_has_one_link` [method](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource.rb#L149) where the foreign key is `ad_id` (`send("#{association.foreign_key}="`  on this [line](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource.rb#L152) ) and expects an integer. Hence the update does not happen.

Is this a bug of JR or are we doing smth wrong?

**Comment by lgebhardt** [comment]
I think [this](https://github.com/cerebris/jsonapi-resources#primary-key) will help.

**Comment by soeffing** [comment]
No, unfortunately it does not. We had exactly this setup (`primary_key` and `self.verify_key` method) but experience this error nevertheless.

**Comment by lgebhardt** [comment]
I'm not sure I'm following the description of the problem. I'm guessing you need a translation between the permalink and the ad_id, but I'm not sure if I'm reading things correctly. Could you show some simplified resources so I can see if I can duplicate the issue?

**Comment by soeffing** [comment]
Ok, so that are our `Award` and `Ad` resources:

```
class AwardResource < BaseResource
      has_one :ad
      has_one :contest

      attributes :id, :description, :amount, :ad_id, :ad_type, :state, :permalink

      primary_key :permalink

      def self.verify_key(key, _context = nil)
        key && String(key)
      end
end
```

```
class AdResource < BaseResource
      primary_key :permalink

      paginator :paged
      attributes :id, :title, :description, :real_id, :current_user_ratings,
                 :average_rating, :created_at
      has_one :user
      has_one :contest

      def self.verify_key(key, _context = nil)
        key && String(key)
      end
end
```

When I try to update the association of an `Ad` to an `Award` by essentially passing a new `permalink` of an `Ad` model into the `:has_one` key of the request, like here:

```
{:attributes=>
  {:description=>"new description v3",
   :permalink=>"4198-rock-deodorant",
   :amount=>"999",
   :ad_type=>"Video",
   :state=>"assigned"},
 :has_one=>{:ad=>"NEW-AD-PERMALINK", :contest=>"contest-permalink"},
 :has_many=>{}}
```

Then this update won't work, because inside this [method](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource.rb#L149) the expected foreign key is a `ad_id` or rather the numerical actual id.

So now I don't know if this is a bug from `ember-data` which sends those parameters from our ember app. And maybe instead of using the permalinks inside the `:had_one` key it should use the actual id. But I don't think it is a `ember-data` bug. 

I am wondering if JR should handle this in the backend.

Please let me know if I still do not make sense. Thx for your time!

**Comment by lgebhardt** [comment]
JSON-API specifies that all resource objects have an `id` and a `type` (see [here](http://jsonapi.org/format/#document-structure-resource-objects)). The `primary_key` method is used to map the `id` used in the resource to another field on the model.

Assuming your permalinks are guaranteed unique you should be using them as the `id` field. By setting them as the `primary_key` you are doing that. In your requests you should pass them in as `id` to be compliant with JSON-API. You could then remove the permalink as an attribute (or keep it, but make it readonly, and it will be redundant with `id`).

On the Award's `has_one` associations you will also need to specify the `foreign_key` to map to the Ad's permalink.

I think you will still run into issues if the actual relationships use the integer ids in the model. JR doesn't have a built in way to completely hide this. I hope I'm understanding your situation correctly.

Note: The old JR readme showed examples with the `id` listed as an attribute, but this is no longer needed. I've updated the JR readme recently.

**Comment by leonardo-b-meira** [comment]
Does jsonapi-resources support composite primary keys?

For example, the following Rails Model has composite primary keys:

```
class ImageType < ActiveRecord::Base
  self.primary_keys = :key, :type
  ...
end
```

And I tried the following on the Resource, but it doesn't work, because primary_key method expect only one argument.

```
class ImageTypeResource < JSONAPI::Resource
  primary_key :key, :type
  ...
end
```

**Comment by lgebhardt** [comment]
Composite primary keys are not supported at this point, as you have observed.

**Comment by leonardo-b-meira** [comment]
Thank you for the prompt response
