### ISSUE TITLE
Bulk extension support

### ISSUE THREAD

**Issue by thibaudgg** [JSONAPI-Resources/jsonapi-resources#183]
Hey, 

Is the [bulk extension](http://jsonapi.org/extensions/bulk) already supported in some way? 
If not, what would be the best way to add it?

**Comment by lgebhardt** [comment]
Currently the project doesn't support any extensions. So there's some up front work that needs to be done around supporting extensions in the mime types. I also want to make extensions optional through the configuration options.

Once that's done I anticipate adding support for bulk should be fairly straight forward. The architecture was designed with this in mind. If bulk is supported the `Request` should create multiple `Operations`. I believe that's all that will need to be done, though there may be some additional changes needed to generate the proper responses.

I'd also like to consider the option of supporting custom extensions (code that doesn't exist in the JR gem). It may make sense to create all extensions as custom and provide appropriate hooks in the base code. So I'd like to take the implementation slowly see if we can provide a nice architecture to allow adding extensions.

**Comment by thibaudgg** [comment]
@lgebhardt Thanks for the detailed answer. I think we could need the `bulk` extension in the next few months. Let me know when the front work is done and how I could help from there!

**Comment by thibaudgg** [comment]
Any update on the [bulk extension](http://jsonapi.org/extensions/bulk) support. I will need it soon, maybe I can help with the implementation? I've the feeling that adding extensions support would required a deep understanding of JR.

**Comment by lgebhardt** [comment]
What's the status on the Bulk Extension?  We have "Extensions are an experimental feature and should be considered a work in progress. There is no official support for extensions in the base JSON API specification." and "The 'Bulk extension' is an official extension of the JSON API specification." That leaves me wondering how much things will change in the future.

**Comment by dgeb** [comment]
JSON API 1.1 has two primary goals:
- support for an extension mechanism
- an official extension or two to support multiple operations in a single request

We are trying to complete 1.1 beta by Sept. 30. 1.1 final should be launched Dec. 31.

Just today we have put forward a proposal for an "operations extension" - see https://github.com/json-api/json-api/issues/795.  This extension will probably replace the json-patch extension, which is not additive to the base spec.

It is likely that the bulk extension will also be supported as an "official extension".

We still need to formalize the extension mechanism.

Hopefully JR can begin supporting these extensions after 1.1 beta. Of course, there's still much TBD between now and then.

**Comment by thibaudgg** [comment]
Thanks for the updates, sounds promising!

**Comment by hankwallace** [comment]
Any updates on this?

**Comment by jsquirrelz** [comment]
+1

**Comment by davidgoli** [comment]
+1

**Comment by galiat** [comment]
I'm wondering if this extension was recently deprecated via https://github.com/json-api/json-api/pull/1026 
@dgeb am I reading that correctly? If so, would this issue get closed?

**Comment by johnnncodes** [comment]
+1

**Comment by caseyprovost** [comment]
+1

**Comment by Lobesitdoll** [comment]
Will give this a whirl, thank you

**Comment by KerryJones** [comment]
+1

**Comment by heidar** [comment]
I believe the bulk extension has been deprecated?

**Comment by lgebhardt** [comment]
Yes, with the extension deprecated this should have been closed a while ago.
