### ISSUE TITLE
Updating toOne relationship incompatible with jsonapi-resources?

### ISSUE THREAD

**Issue by opsb** [JSONAPI-Resources/jsonapi-resources#19]
Hard to say which project this issue belongs in but this seems as good a place as any.

I'm putting together an example app [integrating JR with ember-orbit](https://github.com/opsb/jr-ember-orbit-todos). I'm trying to create a new record with a hasOne relationship set. It works on the ember side but the update to the server is a put and [JR expects a post](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/routing_ext.rb#L73). I've tried just switching the verb to PUT but JR and things progress further but the update from orbit has a pluralised key and JR seems to expect a singular key. @dgeb perhaps you could provide some clarity on what the payload should look like (I think it's correct on the ember-orbit side, see spec at http://jsonapi.org/format/#crud-updating-to-one-relationships).

The example is pretty easy to setup, if you want to look at a concrete example that's probably the best place to look, https://github.com/opsb/jr-ember-orbit-todos. If you do have a look you'll see that adding users works fine but adding todos fails with the above error (click on a user to see their todos).

**Comment by opsb** [comment]
Actually, according to the spec it should be a POST, so it looks like it might be ember-orbit that needs correcting. The key should be plural though which needs correcting on the JR side.

> A to-one relationship MAY be added by sending a POST request with an individual primary resource to the URL of the relationship. For example:
> 
>    POST /articles/1/links/author
> Content-Type: application/vnd.api+json
> Accept: application/vnd.api+json
> {
>   "people": "12"
> }

**Comment by opsb** [comment]
Looks like there's a couple of issues with the json generation on the orbit.js side. I think a change at https://github.com/orbitjs/orbit.js/blob/master/lib/orbit-common/jsonapi-source.js#L284 to something like:

```
  _transformAddLinkStd: function(operation) {
    var _this = this;

    var type = operation.path[0];
    var id = operation.path[1];
    var link = operation.path[3];
    var relId = operation.path[4] || operation.value;

    var linkDef = this.schema.models[type].links[link];
    var relType = linkDef.model;
    var relResourceType = this.resourceType(relType);
    var relResourceId = this.resourceId(relType, relId);

    var method ='POST';
    var json = {};
    json[relType] = linkDef.type === 'hasMany' ? [relResourceId] : relResourceId;

    return this.ajax(this.resourceLinkURL(type, id, link), method, {data: json}).then(
      function() {
        _this._transformCache(operation);
      }
    );
  },
```

**Comment by dgeb** [comment]
@opsb good catch! That is a mistake in orbit.js. If the `resourceLinkURL` is used, the `POST` method should be used to update both has-one and has-many relationships.

Note that [an alternative allowed by JSONAPI](http://jsonapi.org/format/#crud-updating-to-one-relationships) would be a `PUT` request to the `resourceURL` that includes just the link. However, let's keep symmetry with the has-many relationship updates and make the change you suggested.

A PR would be most welcome - thanks in advance!

**Comment by opsb** [comment]
@dgeb note I've also changed 

```
json[relResourceType] = linkDef.type === 'hasMany' ? [relResourceId] : relResourceId;
```

to

```
json[relType] = linkDef.type === 'hasMany' ? [relResourceId] : relResourceId;
```

but I'm not sure if this is correct. jsonapi-resources expects a singular key but it looks like it should be expecting a pluralised key (according to the extract from the spec above). Shall I just make the change to

```
var method ='POST';
```

?

**Comment by opsb** [comment]
Actually there's two changes on that line, I'm also putting the hasMany payload in an array, is this correct?

**Comment by dgeb** [comment]
@opsb the following is correct:

```
json[relResourceType] = linkDef.type === 'hasMany' ? [relResourceId] : relResourceId;
```

where `relResourceType = this.resourceType(relType);`

The `resourceType()` method translates an Orbit type (typically singularized to match model names) to a JSON API resource type (typically pluralized to match URL segments). The important thing is that a resource type is the same throughout JSONAPI, whether it be singular or plural. Therefore, even though we're posting a single object, it should be keyed by its resource type (whether it be singular or plural).

**Comment by dgeb** [comment]
@opsb general note: throughout JSONAPISource and JSONAPISerializer, the term "resource" is used to express the representation expected by JSON API. For example, `resourceType`, `resourceId`, `resourceURL`, etc.

Sorry for the current lack of docs that could clear these concepts up better.

**Comment by opsb** [comment]
Solved by PR for orbit.js, https://github.com/orbitjs/orbit.js/pull/53
