### ISSUE TITLE
Using ResourceSerializer for integration tests

### ISSUE THREAD

**Issue by utilityboy** [JSONAPI-Resources/jsonapi-resources#191]
Hello,

I'm using trying to write some end-to-end tests for my jsonapi-resources application.  Currently I build simple hashes and POST/PUT json representations of them but thought it would be nice to start with a resource object and use the serializer to build some jsonapi compliant payload to send across in my tests.

Do you have any guidance on how to use the serializer to do this with a new object for POSTs?  Existing objects work fine based on the guidelines in the README.

Many thanks.

**Comment by lgebhardt** [comment]
I haven't tried to do what you are asking. In my own testing I simply pass in a hand coded hash in the controller tests.

The Resource object can be initialized with any model. You could create a simple wrapper around a hash that mocks the expected methods on the models. I'm not sure how much that would help over simply maintaining a hash in the JSON-API format however.

**Comment by utilityboy** [comment]
Thanks @lgebhardt .  I'll stick to hashes myself then as well.  Great job with this.  I hope to contribute in the future.
