### ISSUE TITLE
Guidance on STI models

### ISSUE THREAD

**Issue by utilityboy** [JSONAPI-Resources/jsonapi-resources#197]
Hello,

I have a model that has a couple subclasses and is using STI as a persistence mechanism.

Ideally I'd like to have a single route to this resource, but I'm not clear on how to navigate the whole JSONAPI "type" vs the STI "type".

To work around the issue, I've created a computed attribute and return that in lieu of the model "type" attribute.  This works fine and I've overridden `apply_filter` for displaying records. 

I feel it's the proper approach to keep this defined in the resource, but wanted to double-check with the community here.

```
class ConnectorInstanceResource < JSONAPI::Resource
  attributes :id, :key, :name, :configuration, :connector_type

  filter :connector_type

  def connector_type
    @model.type
  end

  def connector_type=(str)
    @model.type = str
  end

  def self.apply_filter(records, filter, value)
    case filter
    when :connector_type
      # TODO: tighten this up a little bit
      begin
        value[0].constantize.all
      rescue
        return records.none
      end
    else
      return super(records, filter, value)
    end
  end

end

```

**Comment by john-griffin** [comment]
:+1:  this is how I would do it at the moment.

**Comment by john-griffin** [comment]
@bjubinville I believe with the recent changes to the spec and what is currently on JR `master` you will now be able to just use the `type` attr inside the nested `attributes` hash.

**Comment by lgebhardt** [comment]
Currently on master we now use the new `attributes` key, but I wasn't able to remove the restriction on having an attribute named `type` due to the spec:

> The value of the "attributes" key is a JSON object (an "attributes object") that represents information about the resource object it is contained within.
> 
> The top level of this object shares a namespace with the members of links and MUST reserve the id and type keys. Apart from these restrictions this object can contain members keyed by any string valid for this specification.

I'll say this with the caveats that if you do add a type attribute, it **won't be valid JSON API**, and I haven't tested if it will work. I dont think there's a technical reason in JR now that would stop you from having an attribute named type. The `check_reserved_attribute_name` will emit a warning about an attribute named type. You could ignore this, or override the method.

**Comment by john-griffin** [comment]
@lgebhardt thanks for clarifying

**Comment by utilityboy** [comment]
Thanks @john-griffin and @lgebhardt.  I'll look into this a little bit this week and report back.
