### ISSUE TITLE
Adding complex links

### ISSUE THREAD

**Issue by jakubrohleder** [JSONAPI-Resources/jsonapi-resources#208]
Within my resource I have some complex links that are created by many-to-many tables. No wonder when I want to add them through normal interface i recive an error:

```
ActiveRecord::HasManyThroughNestedAssociationsAreReadonly (Cannot modify association 'Activity#users' because it goes through more than one other association.):
```

Currenty I'm tackling this issue by modifing controller like this:

```
ActivityController < JSONAPI::ResourceController
 # ...
  def create
    attendees = @request.operations[0].values[:has_many].delete(:attendees)
    # do something with attendees
    super
  end
end
```

Is there any other, more 'standard' way to do it? Are there any possible issues i can encounter with this approach?

**Comment by lgebhardt** [comment]
I don't know if this will work for your scenario, but take a look at the `acts_as_set` option in https://github.com/cerebris/jsonapi-resources#associations.

My guess is you're trying to do something a bit more complicated than a simple linking table. If so could you provide a bit more information, maybe with tables, models and resources simplified to highlight the issue.

**Comment by jakubrohleder** [comment]
Basically my schama is like this:

```
class Activity < ActiveRecord::Base
  # (...)
  belongs_to :event
  has_many :activity_roles, :dependent => :destroy
  has_many :event_invitations, through: :activity_roles
  has_many :users, through: :event_invitations, source_type: 'User' do
    def hosts() merge(ActivityRole.hosts) end
    def attendees() merge(ActivityRole.attendees) end
  end
  # (...)
end

class V1::ActivityResource < AuthorizedResource
  # (...)
  has_many :attendees, class_name: 'User', foreign_key: 'user_ids'
  has_many :hosts, class_name: 'User', foreign_key: 'user_ids'
  has_one :event

  def records_for_hosts(options = {})
    @model.users.hosts
  end

  def records_for_attendees(options = {})
    @model.users.attendees
  end
  # (...)
end
```

When i want to create activity with some attendee I what my backend needs to do is to:
- create ativity linked to event
- find_or_create event_invitation for user (attendee)
- create activity_role linked to event_invitation and user

So as you see the flow is quite complex and by no means just passing attendees in a 'link' (like in example below) can make rails to do it 'out of the box'. What I want to do is to implement this logic somehow.

```
"data":{
  "type": "activities",
  "attributes": {
    "name": "New Activity",
    "abstract": "Lorem"
  }, "links": {
    "event": {
      "linkage": {
        "type": "events",
        "id": "99f42e7f-a11c-41b4-a354-d3a0265f2e80"
      }
    }, "attendees": {
      "linkage": [{
        "type": "users",
        "id": "10abf7b8-8d68-4ef9-97c2-f19ca812e07a"
      }]
    }
  }
}
```

**Comment by lgebhardt** [comment]
It looks like the "has_many :users" is computed on the model, yet you are trying to add in a user with the resource. Maybe you could override the `user_ids=` method.

**Comment by jakubrohleder** [comment]
Yep it is computed on the model by joining some tables.

 I don't know if rails is smart enough to recreate the logic just by associations, i.e. how can it tell that only one event_invitation must be created per (event, user).

My idea was to 'take out' those complex links from the request and process them manully.

By overwriting `user_ids` u mean doing in in a model, controller or resource?

**Comment by lgebhardt** [comment]
> By overwriting user_ids u mean doing in in a model, controller or resource?

Sorry, I meant in the Resource.

**Comment by jakubrohleder** [comment]
Sorry for long pause in the converstion - I was pretty busy lately with my other projects.

It seems that your idea with `user_ids=` pretty much works. I got access to user_ids and I can implement some custom logic up there. The only thing i can't do is to distinguish between attendees and hosts (both triggers `user_ids=` method). Is it possible?

Example of a request with both attendees and hosts:

```
  "data":{
  "type": "activities",
  "attributes": {
    "name": "New Activity",
    "abstract": "Lorem"
  }, "links": {
    "event": {
      "linkage": {
        "type": "events",
        "id": "5b7d30ea-ca82-49b0-9f2d-024300456029"
      }
    }, "attendees": {
      "linkage": [{
        "type": "users",
        "id": "10abf7b8-8d68-4ef9-97c2-f19ca812e07a"
      }]
    }, "hosts": {
      "linkage": [{
        "type": "users",
        "id": "67421333-0e28-4a19-baf8-abc2277182ee"
      }]
    }
  }
}
```

**Comment by jakubrohleder** [comment]
It seem that was impossible but I've made some changes to resource implementation that makes user defined methods such as `user_ids=` to be called with two arguments: `association_key_values` and `association_type`, instead of just `values`. I'll prepare a pull request shortly.
