### ISSUE TITLE
Single resource rendered as array

### ISSUE THREAD

**Issue by dchacke** [JSONAPI-Resources/jsonapi-resources#21]
A single resource seems to be rendered as an array in the resulting JSON, even though the JSON API documentation [states](http://jsonapi.org/format/#document-structure-individual-resource-representations) that it should simply be a single part of the hash.

The repository's documentation [states](https://github.com/cerebris/jsonapi-resources#serializer) the following:

> ``` ruby
> require 'jsonapi/resource_serializer'
> post = Post.find(1)
> JSONAPI::ResourceSerializer.new.serialize(PostResource.new(post))
> ```

which results in

> ``` ruby
> {
>   posts: [{
>     id: 1,
>     title: 'New post',
>     body: 'A body!!!',
>     links: {
>       section: nil,
>       author: 1,
>       tags: [1,2,3],
>       comments: [1,2]
>     }
>   }]
> }
> ```

even though `post = Post.find(1)` indicates that we're dealing with only one resource.

The desired json would look like this:

``` ruby
{
  post: {
    id: 1,
    title: 'New post',
    body: 'A body!!!',
    links: {
      section: nil,
      author: 1,
      tags: [1,2,3],
      comments: [1,2]
    }
  }
}
```

Is there a way to return a single resource to comply with the JSON API? I perused the [source code](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource_serializer.rb) but couldn't find any method that would do that.

**Comment by lgebhardt** [comment]
@dchacke Looks like I didn't catch that change to JSONAPI. I knew there was a lot of discussion around it, but I didn't focus on changing JR when it went into effect. I'll get a fix for this up soon.

**Comment by dchacke** [comment]
@lgebhardt Thanks very much for that commit! Two small things:

First, I guess it would be helpful to mention in the Readme that what used to be

``` ruby
JSONAPI::ResourceSerializer.new.serialize(resource, {})
```

is now

``` ruby
JSONAPI::ResourceSerializer.new.serialize_to_hash(resource, {})
```

(something I was unaware of).

Second, even though the hash now returns a single resource, the key to the hash is still the plural of the resource. E.g., if you have a UserResource, the resulting hash should be

``` ruby
{ user: ... }
     # ^ notice missing s
```

I guess then it's perfect :-)

**Comment by dchacke** [comment]
On second thought, I just looked at the json api docs again and it seems like using a plural word is fine for singular resources. So nevermind on that account :-)

**Comment by lgebhardt** [comment]
@dchacke, thanks for catching the `serialize` method name change. I've updated the readme to reflect the change.

Funny, I had assumed it should be singular as well and had to change it back when I double checked the JSONAPI spec.

**Comment by dgeb** [comment]
Resource type is not required to be singular or plural, just consistent throughout an API. The JSON API spec uses plural examples because the recommendation is for resource collection names to be used to form resource URLs, and the convention for RESTful APIs is for resource URLs to be plural (e.g. `/posts`). This approach allows the spec to avoid taking a stance on inflection issues and simplifies implementations.
