### ISSUE TITLE
Sorting by id does not use primary_key

### ISSUE THREAD

**Issue by slaskis** [JSONAPI-Resources/jsonapi-resources#210]
I have a resource which uses `key` as the "primary_key". 

But when I try to sort using `?sort=+id` it uses the internal `id`-column instead of the `key`-column as expected.

I've done this little monkey patch locally for [this code](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource.rb#L512-L516) for now:

```
      def construct_order_options(sort_params)
        sort_params.each_with_object({}) { |sort, order_hash|
          field = sort[:field] == 'id' ? _primary_key : sort[:field]
          order_hash[field] = sort[:direction]
        }
      end
```

Not sure if that's where this should be fixed or if it should be dealt with in the request.

But if this is ok, just say the word and I'll make a PR. :)

**Comment by lgebhardt** [comment]
I think this is the right way to fix this. Thanks in advance for the PR.

Also, I think we need a default sort, and I think `id` is the only possible option. It should always exist (once your fix is in) and will always be indexed. If you fix [this](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/request.rb#L18) with this:

``` ruby
      @sort_criteria = [{field: 'id', direction: :asc}]
```

it should work. I'm pretty sure this will be required for consistent pagination with some (maybe most) databases.

We could go farther and let the default sort be set on the resource, but I'm not sure this is necessary.

**Comment by slaskis** [comment]
Sure, I'll add it but since Rails 4 I believe it always orders by id unless anything else is specified.

**Comment by slaskis** [comment]
I noticed the tests I added failed with that default sort added without the primary key fix so it was a good addition I think :+1:

**Comment by lgebhardt** [comment]
> since Rails 4 I believe it always orders by id unless anything else is specified.

I looked at the queries run without a sort and there wasn't an order specified.
