### ISSUE TITLE
Missing ActsAsResourceController module

### ISSUE THREAD

**Issue by oliverbarnes** [JSONAPI-Resources/jsonapi-resources#219]
Couldn't include it, and then couldn't find ActsAsResourceController anywhere in the source... Am I missing something? No pun intended

**Comment by lgebhardt** [comment]
It's only in the master branch. I haven't released a new version with this yet so you will need to temporarily specify the branch in your Gemfile.

**Comment by oliverbarnes** [comment]
Solves my problem :) 

thanks for the super quick response, Larry.

Oliver

On May 26, 2015 at 3:26:32 PM, Larry Gebhardt (notifications@github.com) wrote:

It's only in the master branch. I haven't released a new version with this yet so you will need to temporarily specify the branch in your Gemfile.
