### ISSUE TITLE
Route for updating relationships has 'links' not 'relationships' in uri

### ISSUE THREAD

**Issue by pixelhandler** [JSONAPI-Resources/jsonapi-resources#228]
I'm curious is the routing for updating relationships needs a change to match the spec.

In the readme I see a path for "/phone-numbers/:phone_number_id/links/contact" but thought the 1.0 release mentioned using "relationships" in the URI, perhaps like so: "/phone-numbers/:phone_number_id/relationships/contact"

```
phone_number_links_contact GET       /phone-numbers/:phone_number_id/links/contact(.:format)   phone_numbers#show_association {:association=>"contact"}
                           PUT|PATCH /phone-numbers/:phone_number_id/links/contact(.:format)   phone_numbers#update_association {:association=>"contact"}
                           DELETE    /phone-numbers/:phone_number_id/links/contact(.:format)   phone_numbers#destroy_association {:association=>"contact"}
```

The spec page for updating relationships at http://jsonapi.org/format/#crud-updating-relationships list an example like…

```
PATCH /articles/1/relationships/author HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": { "type": "people", "id": "12" }
}
```

It seems that the current routing uses links not relationships e.g. `PATCH /articles/1/links/author`; but the above should be used instead.

**Comment by lgebhardt** [comment]
@pixelhandler Thanks for catching this.
