### ISSUE TITLE
Inserting an relationship on resource creation

### ISSUE THREAD

**Issue by oliverbarnes** [JSONAPI-Resources/jsonapi-resources#233]
Sorry if this is a stackoverflowy question...

What's the recommended way to associate, say, a controller's `current_user` to a resource being created? I've been going through the readme and the source, and see some leads like setting the context on the controller and passing it on to the resource, and using the before_create callback, but I don't grok yet how to set the relationship through it. 

I also see the operations callbacks, but am lost to how where I'd add an operation override. And it seems I should be able to do it in a less involved way.

Also looked into simply overriding resource controller's `update` action, since I've overriden a `show` action for another controller and it was pretty straightforward, but it's turning out it's not so easy as the latter.

Anyway, any nudge in the right direction would be appreciated :) Hope I'm making sense, long day here. 

Thanks for JR, btw, I'm enjoying using it a lot.

**Comment by lgebhardt** [comment]
Glad you're finding JR useful.  You can set the context to contain the current user in the controller (probably in a base controller that you derive your other controllers from is better). In the example to follow the controller has a method to get the current user, called `current_user` and this is being set in the context as a hash value with a key also called `current_user`: 

``` ruby
  # in a controller
  def context
    {current_user: current_user}
  end
```

Then on a resource you can override the save method to use the `current_user` set in the context.

``` ruby
  # in a resource
  def save
    @model.editor ||= context[:current_user]
    super
  end
```

You could also do this using the events on the resource. For example this should work, though I haven't tried it, to set a property only on update.

``` ruby
  # in a resource
  before_update do
    @model.updated_by ||= context[:current_user]
  end
```

The operation callbacks would probably not be my first choice for what you are trying to do.

**Comment by oliverbarnes** [comment]
Thanks, this helps a lot. Should have guessed the resource would have a reference to the model :) makes sense.

**Comment by esasse** [comment]
I'm trying to follow these instructions but the object I'm putting in the context hash never gets to the model.

My base API controller is this:

``` ruby
module Api
  class ApiController < JSONAPI::ResourceController
    before_action :authenticate

    def context
      { current_station: @station }
    end

    private

    def authenticate
      authenticate_or_request_with_http_token do |token, _|
        @station = Station.where(api_key: token).first
      end
    end
  end
end
```

And in my resource I have:

``` ruby
def save
  @model.station = context[:current_station]
  super
end
```

But `context[:current_station]` is allways `nil`.

Any help would be very appreciated, thanks!

**Comment by lgebhardt** [comment]
That looks correct. Have you checked that `@station` has been set when context is called? Are you sure your save method is being called. Some operations do not call the save method.

**Comment by esasse** [comment]
Looks like the `context` method is being called before `authenticate` and then `@station` is still not set. But why would that happen?

BTW, the authentication is working properly.

**Comment by lgebhardt** [comment]
My guess is it's happening because the request is also using a before_filter and the order is wrong. Try using `prepend_before_action`.

I guess I should revisit the use of the `before_filter`.

**Comment by esasse** [comment]
That did it, thanks a lot! :smile:

**Comment by lgebhardt** [comment]
Great. Thanks for letting me know. I'll look into whether we can setup the request another way. Maybe using `append_before_action` will do it.
