### ISSUE TITLE
202 Accepted response on POST

### ISSUE THREAD

**Issue by thibaudgg** [JSONAPI-Resources/jsonapi-resources#234]
I'd need to return `202 Accepted` response on some resource creation and I didn't find anything about it on the codebase. 
Is it already supported? Thanks

From the [jsonapi docs](http://jsonapi.org/format/#crud-creating-responses-202):

> **202 Accepted**
> If a request to create a resource has been accepted for processing, but the processing has not been completed by the time the server responds, the server **MUST** return a `202 Accepted` status code.

**Comment by lgebhardt** [comment]
It's not currently supported. How will you know that you need to return a 202? I'm thinking we could have the `replace_fields` method on the resource return whether the save was completed or delayed. Then the operations could reference this to determine which response code is appropriate. Do you think that could work?

**Comment by thibaudgg** [comment]
We would always return a 202 for some model creation/update, not sure if `replace_fields` would works here, what about returning `:delayed` on `create`/`update` to automatically set the response?

**Comment by lgebhardt** [comment]
`create` returns the new resource. `replace_fields` is actually where the save occurs and is used in both the create and the update/replace fields operations.

**Comment by thibaudgg** [comment]
Ok makes sense then, `replace_fields` would not have been the first thing to look at for such behaviour, could worth some documentation on the README. Thanks!

**Comment by lgebhardt** [comment]
I agree it's probably not very clear. Really I think `_save` should be what returns whether the result was `:completed` or `:delayed`. This can then flow through `replace_fields` to the operation.

**Comment by lgebhardt** [comment]
Or maybe not. I forgot `save` on ActiveRecord already has a return value.

**Comment by lgebhardt** [comment]
How are you handling the delayed saves in the model?

**Comment by thibaudgg** [comment]
Nothing special on the model, it's just delayed from the controller with ActiveJob.

The usecase is an `/actions` endpoint where API client are just posting some random action without caring about the response body. (There's even no Action#id at the end)

``` http
POST /actions HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "actions",
    "attributes": {
      "name": "foo",
      "timestamp": "2015-05-12T18:25:43.511Z"
    },
    "relationships": {
      "user": {
        "data": { "type": "users", "id": "1" }
      }
    }
  }
}

HTTP/1.1 202 Accepted
```

**Comment by lgebhardt** [comment]
I'm a bit confused. Do you have this working, but just need the response code changed? Or is it that you need the resource to also handle creating the Action as an ActiveJob?

I'm sure I'm not understanding this correctly, but it seems like you could create a model for the actions that returns a `201 Created` and would have an id in the database. This would also make a new ActiveJob that could reference the new Action record for the details of the Job. The Action could store the status of the Action as well so it could be queried to see if it's been processed.

**Comment by thibaudgg** [comment]
Sorry, I wasn't clear enough. 
In our app (still in development) the Action resources will not be saved in the db, the data will just be processed through a background job without being stored in an `actions` table. Because of that, there is no action#id to return and then `201 Created` is a not possible if we follow the spec. 
My idea was that returning `202 Accepted` was ok in that case, maybe I'm completely wrong :).

**Comment by lgebhardt** [comment]
Yes, 202 would be correct in your case. I'm just trying to figure out the best way to handle this in JR.

I'll dive into the code soon and see if I can retrofit a solution.

**Comment by lgebhardt** [comment]
Take a look at the op_response_codes branch (https://github.com/cerebris/jsonapi-resources/tree/op_response_codes). From the `_save`, `_create_has_many_links`, and `_replace_has_many_links` you can now return an alternate response code. Returning `:accepted` will result in a 202 response instead of a 201. Simply override the `_save` method on your resource like this:

``` ruby
def _save
  super
  return :accepted
end
```

Let me know if that will work for you.

**Comment by lgebhardt** [comment]
I'm also open to other implementations if anyone has any better ideas.

**Comment by thibaudgg** [comment]
Hmm, `_save` is a private Resource method right? I'm not sure if it's safe to ask the overriding of a private method. What do you think?

What about a Resource class method to override the `:default` response?

``` ruby
class BreedResource < JSONAPI::Resource
  default_save_response :accepted
end
```

Thanks for the quick PR, much appreciated!

**Comment by lgebhardt** [comment]
@thibaudgg I reworked the PR a bit. I think it's cleaner now, with a better separation of concerns.

There are other methods besides save that could defer the action and need to return `:accepted`. So a single `default_save_response` setting would not suffice. I don't see an issue with overriding the `_save` method if you need to, and this would allow you to sometimes defer and sometimes complete the save immediately.

**Comment by thibaudgg** [comment]
I think it's good practice to prevent private method overriding, it makes the library more stable and less problematic to upgrade (do you remember Rails 2 where everybody was monkey patching private method?, It was a big pain to upgrade.). Maybe later you would want/need to change the internal of `Resource` and removing this method will be problematic if people are overriding it. It doesn't feels super future proof to me.

Maybe we could try without any public method or the need of overriding a private one, what about checking the presence of an `id` on the resource? If there's no `errors` and no `id` we should return `202 Accepted` don't you think?

Thanks for your work!

**Comment by dgeb** [comment]
If we never want to allow `_save` to be called externally, it should remain `private` (or perhaps `protected`).

We don't want to force a class to reveal more of its internals than necessary just to communicate with developers that a particular method can be overridden. It's perfectly valid to suggest overriding a private method, but we should be explicit that this is expected for each method with clear comments / docs. As a developer, I understand how important it is to know that the rug won't be pulled out from under you.

On a side note, I think C++ does a better job than Ruby with `protected` vs. `private` visibility. The C++ concept of `protected` would be ideal here.

**Comment by thibaudgg** [comment]
@dgeb agreed, great now with the comment on top of `_save`. :+1: 
@lgebhardt Thanks for the PR!
