### ISSUE TITLE
Update to JSONAPI 1.0

### ISSUE THREAD

**Issue by mrcasals** [JSONAPI-Resources/jsonapi-resources#244]
JSONAPI has been updated to version 1.0. This gem seems to be updated to RC2, seeing #119 is still open. How can I help?

**Comment by barelyknown** [comment]
It's updated to 1.0. We just need to close that issue.

**Comment by brettchalupa** [comment]
@mrcasals It is worth noting that there has not been a new release cut w/ the JSON API 1.0 support yet. I would suggest using a recent master commit from GitHub in your Gemfile. :smile:

**Comment by mrcasals** [comment]
Then maybe the code is not released in a new version of the gem? Just installed the gem, and I'm seeing `linkage` keys.

**Comment by barelyknown** [comment]
@brettchalupa is right. Use the master branch for now, but it's updated to 1.0 and being actively worked on.

**Comment by lgebhardt** [comment]
We are working a few issues to complete compliance with 1.0. Once those are finished a new version of the gem will be released. For now use the master branch in your Gemfile and you will get a version that's 95%\*  compatible with the 1.0 spec.

\* not an accurate statistic

**Comment by mrcasals** [comment]
Awesome, just tried it. Thanks, and sorry for not checking it in advance.

I'll close this issue.
