### ISSUE TITLE
How can I specify the collection I want to render?

### ISSUE THREAD

**Issue by mrcasals** [JSONAPI-Resources/jsonapi-resources#252]
Hi!

I have a `Post` model in my app, and I want  my API to return just a subset of those posts (say, for example, `Post.published`, or `Post.all.select { |post| post.comments.empty? }`. I found the code of the controller, but it looks like there's no good way to customize the collection I'm rendering:

https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/acts_as_resource_controller.rb

Kind of related to #251, as this issue is also asking for a way to overwrite defaults.

Thank you!

**Comment by lgebhardt** [comment]
The ability to set a default filter on a resource is in the master branch. I'm getting a new release ready, which will include this, along with some documentation in the readme that's currently missing. If you are using the master branch you can specify a default on the filter, for example:

``` ruby
 class CommentResource < JSONAPI::Resource
  attributes :body, :status
  has_one :post
  has_one :author

  filter :status, default: 'published,pending'
end
```

This uses the filtering logic on the resource. I sense from your two recent questions that you are trying to put a lot more logic on the Controller than we intended as we designed this gem. In most cases I'd expect your controllers to have little to no additional code in them, and most customizations would happen in the resource classes.

**Comment by lgebhardt** [comment]
I should add that there isn't anything wrong with overriding the logic in the controller, just that it isn't necessary in most cases. I hope my earlier comment didn't come across as critical. I'm just trying to explain the design decisions a bit.

**Comment by mrcasals** [comment]
No offense taken, don't worry about that. I'll give it a go, thanks!
