### ISSUE TITLE
PATCH request results in 105 errors on all params (0.4.0)

### ISSUE THREAD

**Issue by sirvine** [JSONAPI-Resources/jsonapi-resources#259]
After bumping to 0.4.0, I'm getting 105 errors (Param not allowed) for every param included in the payload.  Everything was working fine under 0.3.3, and the payload should be JSONAPI 1.0-compliant.  

The changelog for 0.4.0 is a bit vague...have I missed an obvious breaking API change?

**Comment by lgebhardt** [comment]
@sirvine The [JSONAPI 1.0](http://jsonapi.org/format/#crud) format has the parameters moved into an `attributes` key. My guess is that's the cause of the errors you are getting. If that's not it could you provide an example of the request payload?

**Comment by sirvine** [comment]
Here's an example of my PATCH payload:

```
    {
      "data"=>
      {
        "id"=>"42", 
        "name"=>"New", 
        "startsAt"=>"2012-06-20T15:00:00.000Z", 
        "expiresAt"=>"2016-06-21T15:00:00.000Z", 
        "annualizedSpendCents"=>2000000, 
        "annualizedSpendCurrency"=>"USD", 
        "createdAt"=>"2015-05-22T15:58:03.243Z", 
        "updatedAt"=>"2015-06-18T10:09:12.244Z", 
        "links"=>
        {
          "contract"=>
          {
            "linkage"=>
            {
              "id"=>"18", 
              "type"=>"contracts"
            }
          }, 
          "documents"=>
          {
            "linkage"=>[]
          }, 
          "products"=>
          {
            "linkage"=>[
            {
              "id"=>"49", 
              "type"=>"products"
            }, 
            {
              "id"=>"48", 
              "type"=>"products"
            }, 
            {
              "id"=>"47", 
              "type"=>"products"
            }, 
            {
              "id"=>"32", 
              "type"=>"products"
            }, 
            {
              "id"=>"26", 
              "type"=>"products"
            }]
          }, 
          "productAssignments"=>
          {
            "linkage"=>[
            {
              "id"=>"86", 
              "type"=>"productAssignments"
            }, 
            {
              "id"=>"115", 
              "type"=>"productAssignments"
            }, 
            {
              "id"=>"117", 
              "type"=>"productAssignments"
            }, 
            {
              "id"=>"119", 
              "type"=>"productAssignments"
            }, 
            {
              "id"=>"137", 
              "type"=>"productAssignments"
            }]
          }
        }, 
        "type"=>"cycles"
      }, 
      "id"=>"42"
    }
```

I guess it's not 1.0-compliant after all.  I'm using ember-json-api 0.4.5. I'm not having any issue with GET requests, FWIW.

**Comment by lgebhardt** [comment]
Yes, that's the old format. You will probably need to continue using 0.3.3 until ember-json-api is updated.

I'm surprised the get requests are really working. Check out the actual data.  All the attributes are probably under one key called attributes and I imagine the linkages are probably broken.

Let's leave this open for a little bit in case others have the same issue.

**Comment by sirvine** [comment]
It looks like I was still serializing with AMS.  Hence the difference between inbound and outbound structure.

**Comment by esasse** [comment]
The demo app is still using the old format and it took me some time to understand what was wrong.

**Comment by lgebhardt** [comment]
@esasse Sorry about that. I forgot to update the demo to the new format.

**Comment by esasse** [comment]
@lgebhardt don't worry, you're doing such a great job. I probably should have sent a PR to update the demo. Want me to do that?

**Comment by lgebhardt** [comment]
@esasse Thanks! I would greatly appreciate a PR to update the demo.
