### ISSUE TITLE
Reworking Context in Resources

### ISSUE THREAD

**Issue by lgebhardt** [JSONAPI-Resources/jsonapi-resources#26]
I have a need to access the context when overriding the attribute setters and getters on a resource. Adding a context parameter to these methods is cumbersome. I think a better approach is to rework the way resources interact with context.

I am proposing that a resource instance will posses a context which is set when the resource is created. Resource class methods will continue to require an optional context parameter.

This change will break some methods that override the default resource methods. But it will also simplify quite a lot of code. Making all resource instances exist relative to a context removes the need to pass context around across many layers. For example we could remove the context from the ResourceSerializer, where it only exists to pass it through to the resource methods. In addition the context will be available in any method you need to override, without the need to explicitly pass it in. The downside is all resource creations will require a context.

I would like to make this change for the next version.

**Comment by dgeb** [comment]
Instance-specific contexts make a lot of sense to me :+1:

**Comment by lgebhardt** [comment]
Implemented in 0.0.7
