### ISSUE TITLE
Removing edit routes?

### ISSUE THREAD

**Issue by thibaudgg** [JSONAPI-Resources/jsonapi-resources#261]
I'm not sure why having the `/edit` routes is useful when using `jsonapi_resources` routes helper, is it not exactly the same than `:show`?
Should JR skip that routes generation?

https://github.com/cerebris/jsonapi-resources/blob/master/README.md#routing

**Comment by dgeb** [comment]
Good catch. Those routes shouldn't be generated.

**Comment by thibaudgg** [comment]
:+1:

**Comment by lgebhardt** [comment]
Agreed, it shouldn't be generated. Also the `:new` routes.

**Comment by thibaudgg** [comment]
Right, don't know why I skipped the `:new` one. :ok_hand:

**Comment by lgebhardt** [comment]
Probably the same reason we didn't notice the `:edit` routes. :smile:

**Comment by thibaudgg** [comment]
:smile_cat:

**Comment by thibaudgg** [comment]
:+1: Thanks!
