### ISSUE TITLE
v0.4.1: @context never set for JSONAPI::FindOperation.record_count

### ISSUE THREAD

**Issue by realityendshere** [JSONAPI-Resources/jsonapi-resources#263]
The `record_count` method seen below references `@context`, but that attribute does not appear to be set anywhere. As a result, trying to narrow results with a custom `self.records` in a resource results in a variety of nil-does-not-have-that-method style errors.

https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/operation.rb#L26-L30

``` ruby
def record_count
  @_record_count ||= @resource_klass.find_count(@resource_klass.verify_filters(@filters, @context),
                                                     context: @context,
                                                     include_directives: @include_directives)
end
```

This seems to impact top level links and pagination totals.

As a quick patch, I set `@context` in a patch included in an initializer:

``` ruby
module JSONAPIFindOperationPatch
  def apply(context)
    @context = context
    super
  end
end

module JSONAPI
  class FindOperation
    prepend JSONAPIFindOperationPatch
  end
end
```

v0.4.0 does not appear to to have this issue with misplaced context. If I am missing something obvious, let me know!

**Comment by lgebhardt** [comment]
Thanks for reporting this. I should have a fix for this up soon. I'm going to try to rework the way context is passed around in the operations.

**Comment by realityendshere** [comment]
Awesome! Thanks for the quick fix. Seems to be working quite well.
