### ISSUE TITLE
uninitialized constant JSONAPI::ActsAsResourceController

### ISSUE THREAD

**Issue by samselikoff** [JSONAPI-Resources/jsonapi-resources#265]
I'm trying to include resource behavior in a base resource controller

``` rb
# /app/controllers/api/v1/resource_controller
class Api::V1::ResourceController < Api::V1::ApplicationController
  include JSONAPI::ActsAsResourceController

end
```

and am getting this error:

> uninitialized constant JSONAPI::ActsAsResourceController

Do I need to `require` something somewhere?

**Comment by lgebhardt** [comment]
@samselikoff There are two ways to create a controller using JR. The original way was to derive from `JSONAPI::ResourceController`. The other is to keep your controller derived from `ActionController::Base` and include `JSONAPI::ActsAsResourceController`. In your case where you wish to create a base controller the following are functionally equivalent:

``` ruby
class Api::V1::BaseResourceController < ActionController::Base
  include JSONAPI::ActsAsResourceController
end
```

is functionally equivalent to

``` ruby
class Api::V1::BaseResourceController < JSONAPI::ResourceController
end
```

You would then derive your controllers from the base controller. For example:

``` ruby
class Api::V1::ContactsController < Api::V1::BaseResourceController
end
```

You should not need to `require` anything else. If the above does not work let me know.

**Comment by samselikoff** [comment]
Upgrading from 3.3 to 4.2 fixed it. Thanks Larry!
