### ISSUE TITLE
Using slugs as IDs, relationships -> links attribute

### ISSUE THREAD

**Issue by brandonparsons** [JSONAPI-Resources/jsonapi-resources#269]
Hi there,

I'm just starting to play around with JR.  I'm using slugs as primary keys for a few models in my API (and have set `primary_key :slug` in my serializer.

The issue seems to be that JR is outputting the integer ID in the relationships/links section. E.g.:

``` ruby
 "relationships"=>
    {"locations"=>
      {:links=>{:self=>"/cities/toronto/relationships/locations", :related=>"/cities/toronto/locations"},
       :data=>
        [{:type=>"locations", :id=>"15"},
         {:type=>"locations", :id=>"14"},
         {:type=>"locations", :id=>"7"},
         {:type=>"locations", :id=>"4"},
         {:type=>"locations", :id=>"10"},
         {:type=>"locations", :id=>"1"},
         {:type=>"locations", :id=>"9"},
         {:type=>"locations", :id=>"12"},
         {:type=>"locations", :id=>"11"},
         {:type=>"locations", :id=>"17"},
         {:type=>"locations", :id=>"8"},
```

I would have expected slugs here.  Help would be appreciated!

**Comment by lgebhardt** [comment]
The JSON API format now specifies that we return identifiers as `id`. The `primary_key :slug` in a resource class (not the serializer) tells the resource that internally the `id` field should pull from the model field `slug`.

If that doesn't answer your question please post an example with the resources and models and let us know what you are trying to do.

**Comment by brandonparsons** [comment]
Thanks for the quick reply. Doesn't quite answer my question :)

What I'd like to do is for all public facing information (i.e. every single response from my API) to show ID's for specific models as slugs, not as ID's. Said differently, `location ID = 15` should never be seen. It should _always_ show `ID = 'toronto'`.  Both in responses from the `SHOW` action of the model, and in all links.

``` ruby
class City < ActiveRecord::Base
  has_many :locations
end

class Location < ActiveRecord::Base
  belongs_to :city
end

class CityResource < JSONAPI::Resource
  primary_key :slug
  attributes :country, :latitude, :longitude, :name, :state_province

  has_many :locations

  # Allow UUIDs or slugs as IDs
  def self.verify_key(key, context = nil)
    key && String(key)
  end
end

class LocationResource < JSONAPI::Resource
  primary_key :slug
  attributes :address, :description, :email, :name

  has_one :city

  # Allow UUIDs or slugs as IDs
  def self.verify_key(key, context = nil)
    key && String(key)
  end
end
```

I want this to always show ID's like `toronto` `calgary` , not integer IDs.

In the example I pasted above, you can see that the `relationships` information is coming back with integer IDs, despite the fact that I set `primary_key :slug` in the resource. I've also tried doing

``` ruby
attributes :id, #.......
def id
  @model.slug
end
```

But this doesn't work either.

Hopefully this is a bit more clear.

**Comment by slaskis** [comment]
This works for me exactly the way you describe - set primary_key and override verify_key. 

I'm still on a pre 0.4.0 version though so maybe it's a regression?

**Comment by lgebhardt** [comment]
@brandonparsons It looks like you are doing it correctly. Which version are you using?

**Comment by brandonparsons** [comment]
@slaskis @lgebhardt I am using `0.4.2` - should I try going back a few versions?

**Comment by brandonparsons** [comment]
@slaskis @lgebhardt I must be doing something wrong? I've tried back to `0.3.3` and I'm still getting the behaviour with IDs.

**Comment by rahult** [comment]
I am using 0.4.2 and have the same issue.

**Comment by slaskis** [comment]
It's strange because there are even tests for this: 

https://github.com/cerebris/jsonapi-resources/blob/4e46ed00606440f7136b041a6ead4c8353bc4a4b/test/controllers/controller_test.rb#L1534
https://github.com/cerebris/jsonapi-resources/blob/master/test/fixtures/active_record.rb#L660

**Comment by lgebhardt** [comment]
@brandonparsons I suspect the difference is the tests assume that the `code` is the actual primary identifier on the model. The primary_key is being set on the model with `self.primary_key = :code`. It sounds like on your `slug` example the `id` is still the primary key, but you wish for the resources to hide this and use `slug`. Is this correct?

There should be no reason to go to an earlier version. I only asked because there were a few changes related to the primary key since the earliest versions of JR.

**Comment by brandonparsons** [comment]
@lgebhardt Yep - that is correct. Internally, I'm not using the slug as a primary key (I'm actually using UUID's), but I want the resources to completely hide this fact. To the outside world, the slugs should appear to be the ID.

**Comment by lgebhardt** [comment]
@brandonparsons With the current architecture of JR completely hiding the actual primary key isn't possible. We can mask it when retrieving the `locations`, but the relationships are still using the `id`. To display those using the `slug` a translation from `id` to `slug` would be needed. When creating a new relationship the reverse translation would be needed. Unless I'm missing something, I see this adding a lot of overhead to the code, with multiple extra queries in some cases. For example a `CreateHasManyAssociationOperation` could result in a huge number unless a bulk lookup method was also implemented. It is certainly possible, but it won't be a trivial code change.

Since I don't know your reasoning for this architecture this may be off-base, but why not simply use the slug for the internal primary key? It seems you need to generate a unique string for each location, so the uuid becomes superfluous.

**Comment by brandonparsons** [comment]
@lgebhardt Thanks for the detailed reply. I certainly don't want to add a pile of work for you guys!

In general, I prefer to leave my database primary keys as integer IDs or UUIDs, and not do anything special (i.e. use slugs as primary keys). That being said, I want my ember application to use the slugs as IDs, as that is how it generates routes that are displayed to the user.  To accomplish this, I had been treating UUIDs/PK's as an internal concern (exposing it for models where I don't care about the URLs), but for routes that need humanized URLs returning slugs as the IDs from my API so ember "Just Works" and generates the right paths.

Can you think of a better way to do this?

**Comment by rahult** [comment]
@lgebhardt @brandonparsons I have exactly the same use case. Want to use slugs within our ember app without changing the internal id:uuid representation. However, just in case this is going to be a lot of work. I tried the approach of changing id:uuid to id:string format with my rails application and it working just fine.

Just feels a bit weird storing strings as ID's instead of UUID or Integers

**Comment by dgeb** [comment]
@rahult @brandonparsons I've seen plenty of ember implementations that use a combination of the `model` and `serialize` hooks on a route to accomplish your goal. See http://emberjs.com/api/classes/Ember.Route.html#method_serialize

This allows you to maintain consistent IDs on both sides of your application, and provides the potential benefit that your slugs can be mutable (note: JSON API doesn't support mutable types or IDs).

On the other hand, if your slugs are immutable and unique, then it's worth considering promoting them to be the primary key on both sides.

Either approach should allow you to avoid the extra overhead of all these translation lookups in your API layer.

**Comment by brandonparsons** [comment]
Cool - thanks @dgeb. If you are all comfortable, feel free to close this ticket.

**Comment by dgeb** [comment]
@brandonparsons ok, I'll close for now but feel free to comment further here if you have any questions / problems.

**Comment by brandonparsons** [comment]
@dgeb  - perhaps the following sentence in the README can be changed?

`Note: this doesn't have to be the actual primary key of the model. For example you may wish to use integers internally and a different scheme publicly.`

**Comment by lgebhardt** [comment]
@brandonparsons Yes, we should remove that as it is definitely wrong. Thanks for pointing that out.

**Comment by Dhaulagiri** [comment]
@brandonparsons did you ever get this working in practice?  I'm trying to do something similar in my Ember app and I'm a little confused by @dgeb's suggestion.

**Comment by brandonparsons** [comment]
@Dhaulagiri That's a negative. I've just resorted to sending both the `uuid` and the `slug` from the API, serializing/deserializing on the ember side to make the URLs do what they should be.

**Comment by Dhaulagiri** [comment]
@brandonparsons how do you handle a situation where you are on the ember side with a slug in the url and no way to figure out what id to send to the server because that doesn't exist in the store yet?

**Comment by brandonparsons** [comment]
@Dhaulagiri I'm doing the following on the rails side to get `JR` to lookup by slug as well:

``` ruby
    def self.find_by_key(key, options = {})
      # If you leave JSONAPI to deal with AR::RnF here, it can't figure out the
      # associated_key (because it can be a slug) and throws an exception.
      begin
        record = records(options).friendly.find(key)
      rescue ActiveRecord::RecordNotFound
        raise JSONAPI::Exceptions::RecordNotFound.new(key)
      end
      self.new(record)
    end
```

I'm not using the full suite of `JR` functionality for the records I'm doing this with, so this did it for me. I'm not sure if it will work for everything or not :)

**Comment by Dhaulagiri** [comment]
@brandonparson In combination with setting `key_type` to `:string`, that did the trick.  Thanks!

**Comment by leom806** [comment]
Hey everyone, the project I'm working on currently also uses different IDs internally and I would like to expose friendly IDs to public-facing functionality so I thought about asking in this issue if there are any updates related to this since? I'm currently on version 0.10.7 - Thank you!
