### ISSUE TITLE
Support for has_one :through Association

### ISSUE THREAD

**Issue by pmukerji** [JSONAPI-Resources/jsonapi-resources#271]
We're working on an endpoint where the ActiveRecord model makes use of has_one :through

Demo example:

``` ruby
class User < ActiveRecord::Base
  has_one :outfit
  has_one :shirt, through: outfit
end
```

In this case we might want to have the User's Shirt directly in API as a relationship when retrieving User data:

``` ruby
class UserResource < JSONAPI::Resource
  has_one :shirt

  def creatable_fields(*args)
    super - %i[shirt]
  end

  def updatable_fields(*args)
    super - %i[shirt]
  end
end
```

At the moment the foreign key for an association is set here:

https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/association.rb#L22

In cases where the underlying model uses a has_one :through Association this method (in the example `#shirt_id`) will be undefined on the model (`User`) during serialization:

https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource_serializer.rb#L283-L292

At the moment, defining this method on the model allows things to work as expected:

``` ruby
class User < ActiveRecord::Base
  has_one :outfit
  has_one :shirt, through: outfit

  def shirt_id
    outfit.shirt_id
  end
end
```

but we were wondering if there's a better way to go about doing this?

Thanks!

**Comment by lgebhardt** [comment]
I'm not sure it's better, but you could also put the `shirt_id` method on the resource. That would limit the impact of the hack incase you don't want the `shirt_id` on the model.

``` ruby
class UserResource < JSONAPI::Resource
  has_one :shirt

  def shirt_id
    @model.outfit.shirt_id #should also check for a nil outfit, unless that can't happen
  end

  def self.creatable_fields(*args)
    super - %i[shirt]
  end

  def self.updatable_fields(*args)
    super - %i[shirt]
  end
end
```

Maybe in a future release we could add the `through` option to resource associations to handle this automatically. But it doesn't exist now.

**Comment by pmukerji** [comment]
Thanks for the quick response. We'll go with defining it on the resource as you suggested.
