### ISSUE TITLE
How to use ActiveRecord's `include` in my base queries?

### ISSUE THREAD

**Issue by brandonparsons** [JSONAPI-Resources/jsonapi-resources#276]
Hi there,

This may be covered already, but I can't figure it out.

Because of a particular method on my base ActiveRecord model, I need to use `include(:something_else)` for queries of that resource.

How can I get `JR` to do this?

I've tried this: 

``` ruby
    def self.records(options = {})
      Location.includes(:operator)
    end
```

But it doesn't appear to work.

Thanks!

**Comment by slaskis** [comment]
It does include the requested resources by default but if you abuse attributes and require some custom includes (as I do) you may override [`Resource#apply_includes`](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource.rb#L367-L370) to do this. 

As an example, I do something like this in some of my resources:

```
class MyResource < JSONAPI::Resource

    ... your attributes and has_one/has_many ...

    class << self

      def apply_includes(records, directives)
        if directives
          includes = directives.model_includes.dup
          includes << :another_resource
          records = records.includes(*includes)
        end
        records
      end
   end
end
```

Mind you my code is still in pre 0.4.x so it might have changed but I don't think so.

**Comment by brandonparsons** [comment]
Thanks @slaskis ! I'll give that shot :)

**Comment by brandonparsons** [comment]
@slaskis This doesn't appear to be working for me.

@lgebhardt Is there an "approved" way to make this work? I'm trying to include a `has_one` on `model A` to `model B`. `model A` is not a true rails `belongs_to` to `model B` (it's the other way around, but I need to include the association in this direction in the API.  The reason I'm getting n+1 is because I've done (in `model_a_resource.rb`):

``` ruby
def model_b_id
  @model.model_b.id
end
```

**Comment by slaskis** [comment]
@brandonparsons that's too bad :(

I have a similar situation (or I have a bunch of different similar situations, but this is one) which might help:

I abuse the attributes a bit to "embed" a preview (that is an image resource) in a project. But the preview is really just the first associated _content_ resource.

The `EmbeddedAttributes` module adds `embedded`-method which does pretty much the same as `attribute(s)` but expects an object and serializes the keys accordingly.

```
# app/resources/v1/project_resource.rb
module V1
  class ProjectResource < JSONAPI::Resource
    include ::EmbeddedAttributes

    attributes :name, :description

    embedded :preview

    has_one :owner, class_name: 'User', foreign_key: 'user_id'
    has_many :contents

    class << self

      def apply_includes(records, directives)
        includes = directives ? directives.model_includes.dup : []
        includes << :preview
        records.includes(*includes)
      end

    end
  end
end
```

```
# app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :owner, class_name: 'User', foreign_key: :user_id, touch: true

  has_one :preview, ->{order(:index)}, class_name: 'Content', foreign_key: :project_id, dependent: :destroy
  has_many :contents, dependent: :destroy

end
```

As you can see it's not a proper `belongs_to` but it still includes/preloads it appropriately for me. But as mentioned before this is pre 0.4.x so it might be a regression of sorts.

You might want to log what the includes are to make sure the _model_b_ is in it.

**Comment by lgebhardt** [comment]
I don't know if this will change anything, but I just made #284 which mainly allows you to use an alternate relation based on the context. But to make that work I needed to fix a few things with the current code to avoid N+1 queries. Specifically getting the IDs was using different code than getting the related records and Rails wasn't able to use the eager loaded records. Before spending too much time trying to make this work on the current version I'd test things on #284.

**Comment by brandonparsons** [comment]
@slaskis Not sure what I was doing wrong before, but your approach does appear to be working for me now. Will close this issue.

**Comment by bartoszkopinski** [comment]
This doesn't seem to be working anymore.

@lgebhardt Can we get a working solution for this in the readme? 
"Flattening a rails relationship" (https://github.com/cerebris/jsonapi-resources#flattening-a-rails-relationship) produces n+1 queries and there is no mention of that.
