### ISSUE TITLE
CreateResourceOperation must return 204 No Content with Client-Generated ID 

### ISSUE THREAD

**Issue by thibaudgg** [JSONAPI-Resources/jsonapi-resources#281]
Hey!

According to the format: 

> **204 No Content**
> If a POST request did include a Client-Generated ID and the requested resource has been created successfully, the server MUST return either a 201 Created status code and response document (as described above) or a 204 No Content status code with no response document.

At the moment only `201 Created` and `202 Accepted` are supported (https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/operation.rb#L181) and `201 Created` is returned instead of `204 No Content` when the `id` is sent.

**Comment by vrybas** [comment]
@thibaudgg,

> ... 201 Created is returned instead of 204 No Content when the id
> is sent.

Even if the client sends generated ID, you can't be sure that the server
haven't set default values for attributes or haven't computed certain
attributes dynamically on response.

One solution would be to compare the amount and values of an attributes
in request object with attributes in response object. But this seems to
be bug-prone. I'm not sure it's worth the trouble of implementing and
supporting it. I would close this issue.

Related discussion here: https://github.com/json-api/json-api/pull/947

**Comment by thibaudgg** [comment]
I agree, it would be cumbersome to check for that. We can close that one. Thanks @vrybas.

**Comment by vrybas** [comment]
@thibaudgg thanks :+1:
