### ISSUE TITLE
Why integers for primary key?

### ISSUE THREAD

**Issue by iamvery** [JSONAPI-Resources/jsonapi-resources#291]
Hopefully this is an appropriate channel for a question like this.

I'm curious why it was decided that the type of a resource's `primary_key` [must be an integer](By default only integer values are allowed for primary key.) by default.

> By default only integer values are allowed for primary key.

It struck me as odd because the JSON API specification says that the `id` of a resource object, [must be a string](http://jsonapi.org/format/#document-resource-object-identification).

> The values of the id and type members MUST be strings.

So what inspired this decision?

**Comment by lgebhardt** [comment]
Simply that rails by default uses integer values for ids. It was a decision made early on. At that point I don't believe that JSON API specified that ids must be strings (but my memory is full of cobwebs as far as the early spec goes). We figured that the two most common key formats would be ids and guids. Guids will have differing logic based on the system, so we stuck with integer ids for the default. Switching to another system should be as easy as overriding the `verify_key` method.

Also, rereading the Primary Key section of the Readme made me realize it's a bit out of date. You should ignore the Note in the first paragraph as it's wrong.

**Comment by iamvery** [comment]
That makes sense! I wonder if it'd be worth reconsidering now that the standard is string? It's not really a big deal, but the `verify_key` convention feels a little messy (noisy?). No big deal, just thinking out loud :smile_cat: 

Another question if you don't mind, we set a custom primary key in a resource:

``` ruby
class SomeResource < JSONAPI::Resource
  primary_key :foo
  has_many :bars
end
```

This was enough to allow us to do things like:

```
$ curl http://localhost:3000/somes/FOO123
# where FOO123 is the value of `foo`
```

Interestingly there is still something wrong with following the link to make a request for related resources.

```
$ curl http://localhost:3000/somes/FOO123/relationships/bars
{
    "errors": [
        {
            "code": 106,
            "detail": "The required parameter, some_foo, is missing.",
            "href": null,
            "id": null,
            "links": null,
            "path": null,
            "status": "bad_request",
            "title": "Missing Parameter"
        }
    ]
}
```

I was able to get it working by explicitly providing a query parameter, but this feels repetitive. I'm sure I don't understand something fully.

```
$ curl http://localhost:3000/somes/FOO123/relationships/bars?some_foo=FOO123
{
    "data": [
        {
            "id": "1",
            "type": "bars"
        }
    ],
    "links": {
        "related": "http://localhost:3000/somes/FOO123/bars",
        "self": "http://localhost:3000/somes/FOO123/relationships/bars"
    }
}
```

I confirmed that things worked as expected (without an explicit query param) when using the "default" primary key (`id`).

Thank you so much for the help! It's all very interesting. I'm looking forward to learning more. Also, let me know if there is a better medium for these kinds of discussion.

**Comment by iamvery** [comment]
I'm already feeling some additional pain from our custom "primary key". I think the _key_ (pun!) is that we haven't changed the actual primary key of the underlying model. I believe this confuses things, such as relationships between records using the default `id` as PK. When creating relationships, you would use `id`, but PK should be consistent in representation. This sounding legit?

**Comment by lgebhardt** [comment]
@iamvery For now this is an ok place for questions, though I would like to get a discussion forum in place to keep the email down for people following the project.

The primary_key logic is old, and outdated. Your resource's primary key really must match the model's primary key for the relationships to work. I'm going to look into the best way to make this clear in the readme, and maybe automate this in the code.

**Comment by iamvery** [comment]
That makes sense to me. Thanks for you patience with me! Hopefully we can contribute value back here as we continue to realize our domain. :heart:

**Comment by iamvery** [comment]
@lgebhardt after having used the framework a little more, I'm curious what went into the decision of having resource primary keys map directly to db primary keys? It seems reasonable to me that you could model your resource differently than the database.

In recent experimentation, I ran into the same issue outlined in #296. Non-standard primary keys seem to have made relationships quirky as well. Unfortunately, I don't recall the specifics right now.

Would this be something you'd consider?

**Comment by lgebhardt** [comment]
@iamvery I would certainly be open to making that work. Decoupling the resource a bit from the model was in fact the original plan. However I ran into problems once we started dealing with the associations. I don't think it's a simple nut to crack, but I'm sure it's possible in some form.

**Comment by iamvery** [comment]
Good to know! I'm really interested in the standard and the project. Hopefully I can take some time to get more acquainted with the tests and code and attempt to contribute something.

**Comment by xdmx** [comment]
@lgebhardt you could ask the guys at http://discuss.jsonapi.org/ to have a section for jsonapi-resources maybe? otherwise I've seen some projects here on github using gitter.im although it'd be more like a chat and it could become quite confusing (I've never used it)
