### ISSUE TITLE
Missing resource linkage in the relationship object for has_many associations?

### ISSUE THREAD

**Issue by haydn** [JSONAPI-Resources/jsonapi-resources#294]
Is there a way to include the [resource linkage](http://jsonapi.org/format/#document-resource-object-linkage) in a `has_many` relationship? For me it's coming through for `has_one` relationships as I'd expect, but not for `has_many` relationships.

Here's a snippet of what I'd expect to see:

``` cson
// ...
    "relationships": {
      "author": {
        "links": {
          "self": "http://example.com/posts/1/relationships/author",
          "related": "http://example.com/posts/1/author"
        },
        "data": { "type": "people", "id": "9" }
      },
      "comments": {
        "links": {
          "self": "http://example.com/posts/1/relationships/comments",
          "related": "http://example.com/posts/1/comments"
        },
        "data": [
          { "type": "comments", "id": "5" },
          { "type": "comments", "id": "12" }
        ]
      }
    },
// ...
```

This is an example of what I'm actually getting:

``` cson
// ...
    "relationships": {
      "author": {
        "links": {
          "self": "http://example.com/posts/1/relationships/author",
          "related": "http://example.com/posts/1/author"
        },
        "data": { "type": "people", "id": "9" }
      },
      "comments": {
        "links": {
          "self": "http://example.com/posts/1/relationships/comments",
          "related": "http://example.com/posts/1/comments"
        }
      }
    },
// ...
```

I added the following test to [controller_test.rb](https://github.com/cerebris/jsonapi-resources/blob/master/test/controllers/controller_test.rb) (on master) and it fails:

``` ruby
  def test_show_single_with_has_many_fields
    get :show, {id: '1', fields: {posts: 'comments'}}
    assert_response :success
    assert json_response['data'].is_a?(Hash)
    assert_nil json_response['data']['attributes']
    assert_equal '1', json_response['data']['relationships']['comments']['data'][0]['id']
  end
```

Is this intended behaviour? Is there something I'm missing?

**Comment by lgebhardt** [comment]
The short answer is that this is intended behavior, and it's compliant with the JSON API spec. To fetch the relationship data specify the relationship in `include`, or follow the provided `related` link.

The longer answer is we currently are taking the option to exclude the relationship data for has_many relationships because we do not yet have a working sub pagination system in place for associated data. By excluding the data we prevent the system from being forced to return extremely large data sets in the default response. 

I hope to have the pagination of relationship data working fairly soon and at that point we will revisit what data is returned for has_many relationships by default.

This test should pass:

``` ruby
  def test_show_single_with_has_many_fields
    get :show, {id: '1', fields: {posts: 'comments'}, include: 'comments'}
    assert_response :success
    assert json_response['data'].is_a?(Hash)
    assert_nil json_response['data']['attributes']
    assert_equal '1', json_response['data']['relationships']['comments']['data'][0]['id']
  end
```

The above is valid, but given that you are excluding the attributes it might be more logical to simply fetch the relationship instead of the resource. That will allow pagination of the comments as such:

``` ruby
  def test_show_single_with_has_many_fields
    get :show_association, {post_id: '1', association: 'comments'}    
    assert_response :success
    assert json_response['data'].is_a?(Hash)
    assert_equal '1', json_response['data'][0]['id']
  end
```

I understand you are writing tests, so you want to cover all scenarios. I just pointed out the alternative since you explicitly excluded all other fields.

**Comment by haydn** [comment]
@lgebhardt Thanks for the great response. That all sounds perfectly reasonable and makes sense to me.

The particular project I'm working on is an Ember app that is getting migrated over to JSONAPI from Active Model Serializer. Because of the way things are already setup we're having a problem where hundreds of relationships are getting looked-up only to discover that the related models have already been loaded. Using `include` to side-load them is a step in the right direction, and is a viable fallback, but I'm thinking the best approach at the moment is to patch our project to include relationship data in `has_many` relationships. Could you point me to where in the code it prevents `has_many` relationships from including the relationship data (or where it enables `has_one` relationship to include relationship data)?

FYI, I was under the impression that the relationship data would be included because of [this paragraph about the serialiser's `fields` option](https://github.com/cerebris/jsonapi-resources#fields) in the README:

>   _Purpose_: determines which fields are serialized for a resource type. This encompasses both attributes and association ids in the links section for a resource. Fields are global for a resource type.

Maybe that could be changed to:

>   _Purpose_: determines which fields are serialized for a resource type. This encompasses both attributes and relationships for a resource. Fields are global for a resource type.

**Comment by lgebhardt** [comment]
Sorry about that. That section of the readme is out of date. Your proposed change is correct.

The relevant function is `link_object_has_many` in resource_serializer.rb. You can probably just remove the `if include_linkage`

``` ruby
    def link_object_has_many(source, association, include_linkage)
      link_object_hash = {}
      link_object_hash[:links] = {}
      link_object_hash[:links][:self] = self_link(source, association)
      link_object_hash[:links][:related] = related_link(source, association)
      # link_object_hash[:data] = has_many_linkage(source, association) if include_linkage
      link_object_hash[:data] = has_many_linkage(source, association)
      link_object_hash
    end
```
