### ISSUE TITLE
"Virtual" or "Meta" Resource

### ISSUE THREAD

**Issue by iamvery** [JSONAPI-Resources/jsonapi-resources#295]
I'm interested in how we might be able to accomplish the behavior of a "virtual" resource, i.e. a resource that is not backed by a model and table sharing its name.
## Example

Say we have a table, `employees`. The table has an traditional AR `id` and a `badge_number` column which is unique. We may have an `EmployeeResource` which looks up employees by their db `id`, but what if we also wanted to expose an `BadgeResource` which exposes a virtual resource that is in effect a resource with an `id` of the employee's badge number and a relationship to the employee resource.

I started experimenting and came up with something like this for the `BadgeResource`:

``` ruby
class BadgeResource < JSONAPI::Resource
  primary_key :badge_number

  # has_one :employee # how even?

  def self.verify_key(key, *)
    key && String(key)
  end

  def self.records(*)
    Employee
  end
end
```

This works for the purposes of querying the badge as a resource, but I'm not sure how to set up the relationship to the employee. It's actually just the `model` of the resource with this approach.

We tried using `has_one` with a `:foreign_key` option, and it worked. But the problem was that the `id` for the associated employee was the badge number instead of their db `id` which wouldn't make sense to a client of the API.

We'll keep playing with this. Our next experiment will be creating a virtual `BadgeNumber` model and seeing where that leads us.

Thanks so much! (hopefully all the questions aren't becoming burdensome)

**Comment by lgebhardt** [comment]
I imagine there are a few ways you could accomplish this. Given you are using ActiveRecord I'd try to create a Model that's not backed by the database. See: http://asciicasts.com/episodes/193-tableless-model

I haven't tried that, but it seems like it should be adaptable to your needs.

**Comment by iamvery** [comment]
@lgebhardt thanks for the reply. We'll see what I can get working and post back what we come up with as a solution.

**Comment by iamvery** [comment]
We were able to pull this off with your suggestion of using a PORO model. So given a resource:

``` ruby
class BadgeResource < JSONAPI::Resource
  primary_key :number

  has_one :employee, foreign_key: :number

  def self.verify_key(key, *)
    key && String(key)
  end
end
```

The model got a little awkward because it had to quack like an AR model.

``` ruby
class Badge
  def self.where(number:)
    employee = Employee.find_by(badge_number: number))
    if employee
      [new(number: number, employee: employee)]
    else
      []
    end
  end

  def self.includes(*)
    self
  end

  attr_reader :number, :employee

  def initialize(number:, employee:)
    @number = number
    @employee = employee
  end
end
```

It feels like maybe we're still a little over-coupled to the assumption that resources are backed by db models. A problem, but not one that can't be fixed :dancer:
