### ISSUE TITLE
why relationships for has_one association have data inside?

### ISSUE THREAD

**Issue by senid231** [JSONAPI-Resources/jsonapi-resources#299]
``` ruby
jsonapi_resources :authors do
    jsonapi_relationships
    jsonapi_resources :posts
    jsonapi_resources :comments
  end
```

``` ruby
class AuthorResource < JSONAPI::Resource
  has_one :author_detail
  has_one :author_type
  has_many :posts
  has_many :comments
end
```

`Started GET "/authors/1"`

``` ruby
{
    :data => {
                   "id" => "1",
                 "type" => "authors",
                "links" => {
            :self => "http://127.0.0.1:3000/authors/1"
        },
           "attributes" => {
                   "name" => "john",
               "username" => "johny",
              "is_active" => true,
            "description" => nil,
             "created_at" => Wed, 08 Jul 2015 20:22:40 UTC +00:00
        },
        "relationships" => {
            "author_detail" => {
                :links => {
                       :self => "http://127.0.0.1:3000/authors/1/relationships/author_detail",
                    :related => "http://127.0.0.1:3000/authors/1/author_detail"
                },
                 :data => {
                    :type => "author_details",
                      :id => "1"
                }
            },
              "author_type" => {
                :links => {
                       :self => "http://127.0.0.1:3000/authors/1/relationships/author_type",
                    :related => "http://127.0.0.1:3000/authors/1/author_type"
                },
                 :data => {
                    :type => "author_types",
                      :id => "1"
                }
            },
                    "posts" => {
                :links => {
                       :self => "http://127.0.0.1:3000/authors/1/relationships/posts",
                    :related => "http://127.0.0.1:3000/authors/1/posts"
                }
            },
                 "comments" => {
                :links => {
                       :self => "http://127.0.0.1:3000/authors/1/relationships/comments",
                    :related => "http://127.0.0.1:3000/authors/1/comments"
                }
            }
        }
    }
}
```

i thought that according to [documentation](http://jsonapi.org/format/#fetching-relationships) relationships should have data hash only when you include this relation or fetching data using related link like `http://127.0.0.1:3000/authors/1/relationships/author_type`

**Comment by senid231** [comment]
when we using workaround from #300 `Author` fetch additional data when generating data for `relationships: author_detail`

**Comment by lgebhardt** [comment]
http://jsonapi.org/format/#document-resource-object-relationships

For has_one relationships it does return the resource linkage, but not currently for has_many relationships. As I read the spec that is in compliance, but it is not consistent. Maybe we should change that.

**Comment by senid231** [comment]
specification says that: 
"Resource linkage in a compound document allows a client to link together all of the included resource objects without having to GET any URLs via links" 

so we should not add it if resource is not included.
i think data for not included relationships i redundant

**Comment by lgebhardt** [comment]
That's for compound documents, which is additionally restrictive over the case for a regular document, which states:

> The value of the `relationships` key **MUST** be an object (a "relationships
> object"). Members of the relationships object ("relationships") represent
> references from the resource object in which it's defined to other resource
> objects.
> 
> Relationships may be to-one or to-many.
> 
> A "relationship object" **MUST** contain at least one of the following:
> - `links`: a [links object][links] containing at least one of the following:
>   - `self`: a link for the relationship itself (a "relationship link"). This
>     link allows the client to directly manipulate the relationship. For example,
>     it would allow a client to remove an `author` from an `article` without
>     deleting the `people` resource itself.
>   - `related`: a [related resource link]
> - `data`: [resource linkage]
> - `meta`: a [meta object][meta] that contains non-standard meta-information about the
>   relationship.
> 
> A relationship object that represents a to-many relationship **MAY** also contain
> [pagination] links under the `links` member, as described below.
> 
> Note: See [fields] and [member names] for more restrictions on this container.

That's why I say we are in compliance with the spec. Whether it's the "right" default behavior is certainly something I'm open to discuss.

**Comment by lgebhardt** [comment]
I've just been looking at the code changes needed to change this behavior, which should be minimal. This reminded me of the primary reason I chose to include the the resource linkage for has_ones, which is the ability to see nil/null values.

@dgeb, and anyone else, do you have an opinion on the stance JR should take on serializing resource linkage for a has_one relationship that is not included? A compromise is to make this a configuration option.

**Comment by dgeb** [comment]
@lgebhardt you're right - it is still compliant to include relationship data even in a non-compound document. However, I think this has limited utility. The knowledge that a relationship is currently empty could prevent another fetch. But on the other hand, if a fetch of related data _might_ be done why not request a compound document in the first place?

I would favor consistency between has-one and has-many relationships. To me, it makes the most sense to leave off relationship data by default except to establish resource linkage in compound documents. I'd also have no problem with flags that could be set on individual relationship fields to force the inclusion of data in non-compound documents (`always_include_data` perhaps?), since this option will undoubtedly be requested and is still spec-compliant.

**Comment by senid231** [comment]
on my opinion, configurable option with default that fits for most of cases is the best solution. maybe, links objects for relation can be optional and configurable too.

we have situations when there are no `jsonapi_relationships` in `routes.rb` but response generate relationships with `related` links (and they are not valid). 
or resource have association that didn't have its own controller but relationships have `self` links with invalid path.

**Comment by lgebhardt** [comment]
I'll work up a PR.
