### ISSUE TITLE
raises InvalidLinksObject when request have has_many relationship without data

### ISSUE THREAD

**Issue by senid231** [JSONAPI-Resources/jsonapi-resources#307]
i just fetch author using json_api_client (without including posts), change name and try to save it

```
Started PATCH "/authors/1" for 127.0.0.1 at 2015-07-13 09:46:13 +0300
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by AuthorsController#update as API_JSON
  Parameters: {"data"=>{"id"=>"1", "type"=>"authors", "relationships"=>{"posts"=>{"links"=>{"self"=>"http://127.0.0.1:3000/authors/1/relationships/posts", "related"=>"http://127.0.0.1:3000/authors/1/posts"}}}, "attributes"=>{"name"=>"qwe", "is_active"=>true, "description"=>nil}}, :controller=>"authors", :action=>"update", :id=>"1"}
```

in `JSONAPI::Request`

``` ruby
def parse_has_many_links_object(raw)
  fail JSONAPI::Exceptions::InvalidLinksObject.new if raw.nil?

  links_object = {}
  if raw.is_a?(Array)
    raw.each do |link|
      link_object = parse_has_one_links_object(link)
      links_object[link_object[:type]] ||= []
      links_object[link_object[:type]].push(link_object[:id])
    end
  else
    fail JSONAPI::Exceptions::InvalidLinksObject.new
  end
  links_object
end


def parse_has_one_links_object(raw)
   if raw.nil?
    return { type: nil, id: nil }
 end

  if !raw.is_a?(Hash) || raw.length != 2 || !(raw.key?('type') && raw.key?('id'))
    fail JSONAPI::Exceptions::InvalidLinksObject.new
  end

  {  type: unformat_key(raw['type']).to_s, id: raw['id'] }
end
```

`raw` is a `data` from `relationships: posts` (in my case)
so when i send `PATCH` with relation without data linkage it fails

``` ruby
{
    :errors => [
        [0] #<JSONAPI::Error:0x007f61cc2c1de0 @title="Invalid Links Object", @detail="Data is not a valid Links Object.", @id=nil, @href=nil, @code=115, @path=nil, @links=nil, @status=:bad_request>
    ]
}
```

``` ruby
class AuthorResource < JSONAPI::Resource
  has_many :posts
end

class PostResource < JSONAPI::Resource
  def self.records(options = {})
   author_id = options[:context].try!(:[], :author_id)
   author_id.nil? ? super : super.where(author_id: author_id)
 end
end
```

i think it isn't correct behaviour. resource should ignore data linkage of relationships if it is nil
guys, what do you think about this?

**Comment by lgebhardt** [comment]
The spec says:

> If a relationship is provided in the relationships member of a resource object in a PATCH request, its value MUST be a relationship object with a data member

so it's fairly clear to me we need the `data` member for the relationship. But I'm open to different interpretations.

Currently the `links` object is ignored in an update. When I wrote the update section I was wondering if we should be rejecting requests that contain it. The spec doesn't address that scenario. So any opinions on whether this is the correct course of action would also be appreciated.

**Comment by senid231** [comment]
i read specification again.. and i agree with you.
im using [json_api_client](https://github.com/chingor13/json_api_client) as a client and it have no dirty tracking on attributes/relationships (i think about creating PR for this feature when i will have time for it).
it sends all (realtionships, attributes, links) in patch request
so i will change it at the client side

**Comment by senid231** [comment]
but now i'm thinking about something like updatable_relationships/creatable_relationships that will work same as similar methods for attributes.
it will send error when client trying to update restricted relation.

i think it will be very useful feature for public API

**Comment by senid231** [comment]
no need to create new methods
we can write 

``` ruby
def updatable_fields(context = nil)
  super(context) - [:posts]
end
```

that will exclude realtionship `posts` from allowed_fields list and server will return correct error
