### ISSUE TITLE
Validating ownership of associated objects

### ISSUE THREAD

**Issue by wijet** [JSONAPI-Resources/jsonapi-resources#31]
I got the following models

``` ruby
class Account < ActiveRecord::Base
  has_many :issuers
  has_many :invoices, through: :issuers
end

class Invoice < ActiveRecord::Base
  belongs_to :issuer
end

class Issuer < ActiveRecord::Base
  has_many :invoices
end
```

I want to allow user to create/update an invoice with provided issuer ID, but I want it to be an issuer only from the scope of his account. I can't validate it on model level (unless I add redundant account association to the invoice). I'm wondering if you have a way to approach this issue?

In ordinary rails app where you create/update only a single record I would probably do something like this:

``` ruby
@invoice.issuer = current_account.issuers.find(params[:invoice][:issuer_id])
```

In an application using JSON API controllers I don't see a clean way to achieve the same when creating/updating multiple records at once is possible. What do you recommend?

**Comment by lgebhardt** [comment]
You could add an approval layer to the operations processor. In your controller (ideally in a common base controller) override the `create_operations_processor` method to create your own custom processor.

``` ruby
class BaseController < JSONAPI::ResourceController

private
  def context
    {current_account: current_account}
  end

  def create_operations_processor
    ApprovingOperationsProcessor.new
  end
end
```

In your new ApprovingOperationsProcessor (feel free to pick a better name) you would override the before_operation method.

``` ruby
class ApprovingOperationsProcessor < JSONAPI::ActiveRecordOperationsProcessor

  def before_operation(context, operation)
    operation.resource_klass.approve_operation(context, operation)
  end
end
```

This will allow you to put an `approve_operation` method on each of your resources where you can check the values before they are applied. Ideally you would make a BaseResource which implements a stub `approve_operation` method that you could override as needed.

``` ruby
class InvoiceResource < JSONAPI::Resource

  has_one :issuer
  # ... other resource stuff

  def self.approve_operation(context, operation)
    current_account = context[: current_account]
    case operation
      when JSONAPI::CreateResourceOperation, CreateHasOneAssociationOperation, ReplaceHasOneAssociationOperation
        issuer = current_account.issuers.find(operation.values[:has_one][:issuer])
        raise InvalidIssuer.new(operation.values[:has_one][:issuer]) unless issuer
      else
        # Other checks here if needed
    end
  end
end
```

It's kind of a hack, but it lets you add any sort of preprocessing logic you might need to the resources.

**Comment by wijet** [comment]
Thank you! I'm closing this one.
