### ISSUE TITLE
Infer class_name for associations

### ISSUE THREAD

**Issue by wagenet** [JSONAPI-Resources/jsonapi-resources#316]
Consider the following model:

``` ruby
class User
  has_many :billing_addresses, class_name: 'Address'
end
```

The resource would have to be:

``` ruby
class UserResource < JSONAPI::Resource
  has_many :billing_addresses, class_name: 'Address'
end
```

Would it be possible to infer the `class_name` from the model to avoid having to duplicate information?

**Comment by lgebhardt** [comment]
Good idea, and yes, it looks like it can be done. I'll try to get a change in soon.
