### ISSUE TITLE
Support for coalesce / batch find queries

### ISSUE THREAD

**Issue by krzkrzkrz** [JSONAPI-Resources/jsonapi-resources#319]
Does the library support coalesce find requests? So lets say I need to find 3 `items` with ids: 1,2,3.

Instead of performing 3 api calls. It does it in one, passing the id as a param. So the request URL would look something like:

```
http://localhost/api/v1/items?filter[id]=1,2,3
```

Which also avoids `n+1` queries. Ember for example will allow sending this type request. More details at http://emberjs.com/api/data/classes/DS.JSONAPIAdapter.html#property_coalesceFindRequests

**Comment by lgebhardt** [comment]
It should only run one query. it should be something like this:

``` sql
SELECT "items".* FROM "items" WHERE "items"."id" IN (1, 2, 3)  ORDER BY "items"."id" ASC
```

**Comment by henrymazza** [comment]
It’s not working here. 

See:

```
Started GET "/api/v2/sizes?filter%5Bid%5D=6%2C16%2C2%2C5%2C1%2C7%2C18%2C3%2C4%2C9%2C17%2C8%2C14%2C13%2C10%2C11%2C12" for ::1 at 2016-01-08 22:49:26 -0200
Processing by Api::V2::SizesController#index as API_JSON
  Parameters: {"filter"=>{"id"=>"6,16,2,5,1,7,18,3,4,9,17,8,14,13,10,11,12"}}
  Size Load (0.3ms)  SELECT "sizes".* FROM "sizes" WHERE "sizes"."id" = $1  ORDER BY position, "sizes"."id" ASC  [["id", 6]]
Completed 200 OK in 14ms (Views: 0.6ms | ActiveRecord: 0.6ms)
```

running rails 4.2, jsonapi-resources 0.7.0

**Comment by vrybas** [comment]
Works on current `master`:

``` ruby
get "/articles?filter[id]=1,2,3"
```

``` sh
Started GET "/articles?filter[id]=1,2,3" for 127.0.0.1 at 2016-02-29 22:39:22 +0700
Processing by ArticlesController#index as HTML
  Parameters: {"filter"=>{"id"=>"1,2,3"}}
  Article Load (0.5ms)  SELECT "articles".* FROM "articles" WHERE "articles"."id" IN (1, 2, 3)
```

@krzkrzkrz can issue be closed?

**Comment by henrymazza** [comment]
Yes, it always worked. My issue was bad interface between keyboard and chair: I overrode the filter method and caused the issue myself.

+1 to close

**Comment by lgebhardt** [comment]
Closing. Feel free to reopen this, or create a new issue, if needed.
