### ISSUE TITLE
Preferred way to add current_user to newly created resource

### ISSUE THREAD

**Issue by kagemusha** [JSONAPI-Resources/jsonapi-resources#320]
I'm trying to add current_user to a newly created item.  I could do this is a controller, but seems would result in lots of mucking getting strong params to work.  Docs seem to suggest this type of stuff done in the resources?

So I was thinking of adding in an after_create in the resource file but current_user is not available there.  I thought that doing something like this in base ApplicationController:

  def context
    {current_user: current_user}
  end

would expose current_user in the context in a resource but doesn't seem to be the case.

Suggestions?

**Comment by lgebhardt** [comment]
It looks like your context method is correct. The context should should be available on the resource. Is it possible the current_user method isn't returning a user?

I assume you are trying to access the current user through the `context` and not directly as `current_user`.

One other option, besides the callback, is to override the `save` method on the resource:

``` ruby
def save
  @model.editor ||= context[:current_user]
  super
end
```

But again that will require that context is properly being provided to the resource. You should not need to resort to trying to do this in the controller, other than the `context` method.

**Comment by kagemusha** [comment]
Ok think the problem may have been that I had context in ApplicationController, which doesn't include JSONAPI::ActsAsResourceController.  This is in a subclass which is the base class for all controllers which need this.  Moving the context method there  and overriding save as you suggest works.  Thanks!

**Comment by lgebhardt** [comment]
That makes sense. Importing `JSONAPI::ActsAsResourceController` is overriding the `context` method you have defined in your base class. That's a scenario I hadn't considered. I'll at least add a note about this in the readme. Thanks for following up with the cause.

**Comment by kagemusha** [comment]
@lgebhardt no problem.  btw the app this relates to is an [example rails api server](https://github.com/kagemusha/crambear-api) with ember-cli pair of apps.  would love suggestions for improvements in jsonapi-resources usage and feel free to cite it as a somewhat more extensive example than peeps.  In any event, will have more questions for you in near future.

**Comment by jbonhag** [comment]
Brilliant, thanks to @lgebhardt for the suggestion and @kagemusha for the example app.

**Comment by ramontayag** [comment]
Thanks this helped. Didn't know how to get from the `context` to the resource model having it.

**Comment by theirishpenguin** [comment]
In the docs, it would be great to note how to set context (in something like your application controller by defining the method). I now know how from reading this thread :-)

**Comment by koriroys** [comment]
@lgebhardt can probably close this issue?

**Comment by koriroys** [comment]
@theirishpenguin It's there, quite far down the readme: https://github.com/cerebris/jsonapi-resources#context

**Comment by theirishpenguin** [comment]
Thanks for the reply @koriroys. The problem is it's a bit late by then and it could use a user friendly 1 line blurb to give a bit of context to the concept of context :smile: just for newcomers to the jsonapi-resources project.

I propose moving it higher up the docs so that readers have an understanding of what context is as they read the remainder of the docs - such as this in PR https://github.com/cerebris/jsonapi-resources/pull/631/files
