### ISSUE TITLE
Support for creation/deletion of relationships via join_tables?

### ISSUE THREAD

**Issue by johantell** [JSONAPI-Resources/jsonapi-resources#323]
Is this possible right now or is it something waiting to be implemented? I've been trying to setup a follower pattern but cannot seem to make it work. I can list existing relationships but not create any new.

Should i think about the relationships as it's own object and handle the creation via attributes maybe?

**Comment by lgebhardt** [comment]
It's definitely something that should be in there, and its absence is an oversight. We don't have tests for this scenario, and in my own use of JR the join tables happen to be resources themselves. So I guess I'm not surprised this doesn't work.

Until this get's fixed the easiest work around may just be to treat the join table as a resource.

**Comment by vrybas** [comment]
@mintcore have you found a solution for that?

**Comment by vrybas** [comment]
Actually this kind of works. Is this issue still relevant?

model:

``` ruby
class Article < ActiveRecord::Base
  has_many :article_tags
  has_many :tags, through: :article_tags
end
```

spec:

``` ruby
it "creates article with tags" do
  params = {
    "data" => {
      "type" => "article",
      "attributes" => { "title" => Faker::Lorem.sentence },
      "relationships": {
        "tags" => {
          "data" => [{ "type" => "tags", "id" => tag.id.to_s }]
        }
      }
    }
  }

  post "/api/articles", params.to_json, default_api_headers
  expect(response.status).to eq 201

  article = Article.find(JSON.parse(response.body)["data"]["id"])
  expect(article.tags).to eq([tag])
end
```

resource:

``` ruby
class Api::ArticleResource < JSONAPI::Resource
  attributes :title
  relationship :tags, to: :many

  class << self
    def creatable_fields(context)
      super + [:tags]
    end
  end
end
```

**Comment by johantell** [comment]
@vrybas I ended up treating them as resources. Not sure that this is still relevant as there have been some new versions since i wrote it

**Comment by barelyknown** [comment]
This is supported now in the way that is outlined in @vrybas's comment. You can also treat them as resources, but then you need to create the join table resources individually.

**Comment by kevinmtrowbridge** [comment]
I'm trying to use similar functionality, creating a relationship with the following JSON:

```
{
    "data": {
        "type": "project_notes",
        "attributes": {
            "project_note_date": "2016-11-09"
        },
        "relationships": {
            "projects": {
                "data": [
                    {
                        "type": "projects",
                        "id": "166"
                    }
                ]
            }
        }
    }
}
```

But, I get an `InvalidLinksObject` exception, and it comes down to [this spot](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/request_parser.rb#L397):

```
      links_object = {}
      if raw.is_a?(Array)
        raw.each do |link|
```

At this point, `raw` is an object of type `ActionController::Parameters` ... it contains the right data, but the code doesn't seem to be parsing it out correctly.

I must be off track somehow?

More details:

```
Started POST "/api/jsonapi/project-notes.json" for 127.0.0.1 at 2016-11-20 12:36:59 -0800
Processing by Api::Jsonapi::ProjectNotesController#create as JSON
  Parameters: {"data"=>{"type"=>"project_notes", "attributes"=>{"project_note_date"=>"2016-11-16"}, "relationships"=>{"projects"=>{"data"=>{"0"=>{"type"=>"projects", "id"=>"166"}}}}}}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 2]]
Completed 400 Bad Request in 47620ms (Views: 0.8ms | ActiveRecord: 0.5ms | Solr: 0.0ms)
```

**Comment by kevinmtrowbridge** [comment]
Ok -- it was my fault, apologies -- it was something dumb -- the problem was just that I wasn't setting the contentType correctly on the API request.  This SO post describes the problem exactly: http://stackoverflow.com/questions/6410810/rails-not-decoding-json-from-jquery-correctly-array-becoming-a-hash-with-intege
