### ISSUE TITLE
fetchable_fields doc or implementation bug

### ISSUE THREAD

**Issue by thomassnielsen** [JSONAPI-Resources/jsonapi-resources#325]
In readme.md there's a code sample for using fetchable fields:

``` ruby
class AuthorResource < JSONAPI::Resource
  attributes :name, :email
  model_name 'Person'
  has_many :posts

  def fetchable_fields
    if (context.current_user.guest)
      super(context) - [:email]
    else
      super(context)
    end
  end
end
```

When I tried to implement this, I got an error that super doesn't take any arguments. Removing `(context)` made the code work as expected. Is this a doc bug or a bug in the fetchable_fields implementation? I'm using `JSONAPI::ActsAsResourceController`, if that has anything to do with it.

**Comment by lgebhardt** [comment]
Sorry, that's a documentation error. If I remember correctly we removed passing in the context because it's available on the resource instance. We should have cleaned up the super calls as well.
