### ISSUE TITLE
Filter by NULL

### ISSUE THREAD

**Issue by henrymazza** [JSONAPI-Resources/jsonapi-resources#326]
How to filter by NULL on a GET request? 

If I make a query without the equal sign the parser even finds out the right parameters hash, but the filter code ignores it!

```
Started GET "/api/v2/sales?filter%5BclosedAt%5D" for ::1 at 2015-07-18 17:42:22 -0300
Processing by Api::V2::SalesController#index as API_JSON
  Parameters: {"filter"=>{"closedAt"=>nil}}
  Sale Load (0.6ms)  SELECT "sales".* FROM "sales" WHERE 1=0  ORDER BY nfe desc, updated_at desc, "sales"."id" ASC
Completed 200 OK in 4ms (Views: 0.2ms | ActiveRecord: 0.6ms)
```

**Comment by lgebhardt** [comment]
If you specify an empty filter the find method does not by default assume you are looking for null values. There are several options you could take. To make an empty search for relationships find null values you could override the `verify_relationship_filter`

``` ruby
def self.verify_relationship_filter(filter, raw, _context = nil)
  if raw.is_a?(Array) && raw.length == 0
    return [filter, nil]
  else
    super
  end
end
```

You could also override the `apply_filter` method to implement a keyword that indicates a search for null, such as 'none':

``` ruby
def self.apply_filter(records, filter, value, options)
  if value == 'none' || (value.is_a?(Array) && value[0] == 'none')
    records.where(filter => nil)
  else
    return super
  end
end
```

Of course you may only want that filter to work on select fields. You could then check the filter as well.

**Comment by henrymazza** [comment]
Great! For searches of strings should I override apply_filter or find? Who’s that?

**Comment by lgebhardt** [comment]
@henrymazza I think apply_filter is easier implement since it's setup to let you modify each filter. But the same thing could be done by overriding find, however it's probably more complicated and would be overkill in most situations. 

For your string searches you could do this (not tested code, so there are possible errors):

``` ruby
def apply_filter(records, filter, value, _options = {})
  t = _model_class.arel_table
  records.where(t[filter].matches("%#{value}%"))
end
```

That should make all filters do a case insensitive like search. You should probably conditionally add the text search on just some fields by looking at filter. The same could be done in find, but it's going to be more work, and won't work any better.

**Comment by henrymazza** [comment]
Works great (if you delete the colon :smile_cat:)!

`apply_filter` is really growing here. It’s checking for NULL, if query is asking for a different scope and now searching. It’s probably the main method to look after when porting an old rails app. I was asking for more switches, but now I’m felling home.

**Comment by lgebhardt** [comment]
Great, glad it mostly worked! Also, I cleaned up the colon in the example.

**Comment by henrymazza** [comment]
When `@top_level_meta_include_record_count=false` should it still make the second query to database asking for the counting? It’s breaking me when I include some fancy stuff on select clausule because Postgres wants it there (order by similarity).

If it’s really a bug I can open another issue.

**Comment by lgebhardt** [comment]
Sounds like a bug to me. It shouldn't be running the count query if you don't ask for the count.

**Comment by henrymazza** [comment]
Ok. Here it is: https://github.com/cerebris/jsonapi-resources/issues/335

**Comment by senid231** [comment]
ActiveRecord don't like to filter by empty array. it use `WHEN 1=0` condition to show it.
we could sort by `NULL` like this:

``` ruby
def apply_filter(records, filter, value, _options = {})
  value = value.is_a?(Array) && value.empty? ? nil : value
  super(records, filter, value, _options)
end
```

**Comment by digitalcora** [comment]
@lgebhardt Regarding the original topic of this issue (filtering with NULL as the value), now that overriding `apply_filter` is deprecated, is there a new preferred way to do this?

**Comment by lgebhardt** [comment]
@grantovich I think something like this would work:

``` ruby
filter :open, apply: ->(records, value, _options) {
  if value == 'none'
    records.where('date_resolved' => nil)
  else
    return records.where.not('date_resolved' => nil)
  end
}
```

And you can still override `apply_filter`, it's just cleaner to use a callable on the filter definition.

**Comment by digitalcora** [comment]
Thanks @lgebhardt, in fact I already implemented a solution similar to that – what I'd like to know is whether there's a good non-deprecated way to permit the use of `'none'` on _all_ filters without having to configure it on each new filter. This is what the old `apply_filter` override enabled, I think.

From the README:

> Note: It is also possible to override the `self.apply_filter` method, though this approach is now deprecated

**Comment by lgebhardt** [comment]
It's deprecated only in the sense that for most use cases it's cleaner to handle it with a callable so you don't have to also switch on the filter. In your case for wanting `none` for all filters I would override the `apply_filter` method. I can't promise we won't change it, but I don't see it as likely that we will either.

**Comment by digitalcora** [comment]
Okay 👍 Usually when I see "deprecated" I read it as "this will definitely be removed in a future release, so don't write any new code that depends on it". It sounds like overriding `apply_filter` is merely "not recommended" at this point, rather than officially "deprecated". 😃

**Comment by lgebhardt** [comment]
@grantovich In this case deprecated was meant to convey that there is a better way to do something, though I can certainly see how you might be worried about removal as that is a common reason to deprecate a feature. I'll update the docs soon to clarify.

https://en.wikipedia.org/wiki/Deprecation

**Comment by blindMoe** [comment]
We had an issue where we need to search for nil values in the database and I figured I would share my solution.  Keep in mind that I am setting context[:params] in my base controller for my API.

```
      filter :wifi_network, apply: lambda { |records, value, options|
        if options.dig(:context, :params, :filter, 'wifi-network').nil?
          records.where(wifi_network: nil)
        else
          records.where(wifi_network: value)
        end
      }
```

**Comment by senid231** [comment]
```ruby
class ApplicationResource < JSONAPI::Resource
  def self.verify_filter(_filter, _raw, _context = nil)
    result = super
    result[1].empty? ? [result[0], nil] : result
  end
end
```
