### ISSUE TITLE
Best way to do optimistic locking?

### ISSUE THREAD

**Issue by adamworrall** [JSONAPI-Resources/jsonapi-resources#327]
I've got a resource that multiple users could potentially edit at the same time, and I'd like to implement optimistic locking.

What would be the best way to require the `lock_version` attribute is present in any update requests made to this resource, and also provide useful error messages for the end user if they've got a stale model? Is this where you'd make a custom `OperationsProcessor`?

**Comment by lgebhardt** [comment]
The `ActiveRecordOperationsProcessor` doesn't handle the `ActiveRecord::StaleObjectError`, so you would definitely want to override that and create a custom error for that case.

I think you would also need to add the `lock_version` field to the resources. Not having tried this, I'm not sure what else would need to be done.

This seems general enough that we should probably get this into the main codebase. if you get this working could you post the details so we can support this?

**Comment by adamworrall** [comment]
Sounds good, I'll take a crack at it!
