### ISSUE TITLE
Custom primary key issue

### ISSUE THREAD

**Issue by macasek** [JSONAPI-Resources/jsonapi-resources#332]
Hello, I recently started playing around with jsonapi-resources for a project. I am hoping to convert an existing Rails 4 service to use JSON API. While I was experimenting with jsonapi-resources I ran into issues with a model that has a `primary_key` other than `id`. After some debugging I believe I tracked down the issues but before I take it too far I wanted to get some feedback to make sure I am not just doing something wrong.

This is all based on master where the latest commit was 4f2e4592efeb34d18a37fab66ba84688b087bf1a

Consider this simplified example:

```
# config/routes.rb
jsonapi_resources :users
jsonapi_resources :organizations
```

```
# app/resources/organization_resource.rb 
class OrganizationResource < JSONAPI::Resource
  attribute :name

  has_many :members, class_name: "User"
end
```

```
# app/resources/user_resource.rb
class UserResource < JSONAPI::Resource
  primary_key :uuid
  attributes :uuid, :email

  has_many :orgs, class_name: "Organization"

  def self.verify_key(key, context = nil)
    key && String(key)
  end
end
```

The controllers are empty so I did not include them here.

As I worked though getting this up and running I ran into the following issues, all related to the UserResource uuid primary key.
1. Users routes were generated using `id` and `user_id` and jsonapi-resources was expecting `uuid` and `user_uuid`.
2. `organizations/:id/members` was trying to order by `users.id`
3. `users/:uuid/orgs` was trying to sort by `orgs.uuid`
4. `users/:uuid` added `users.uuid IS NULL` to the where clause

To solve these problems I made the following changes to jsonapi-resources locally:

To solve the first issue:

```
# ActionDispatch::Routing::Mapper#jsonapi_resources

options = resources.extract_options!.dup
options[:controller] ||= @resource_type
options.merge!(res.routing_resource_options)

# options[:param] = :id
options[:param] = res._primary_key

options[:path] = format_route(@resource_type)
```

To solve 2nd and 3rd issues:

```
# JSONAPI::Resource#_add_relationship

sort_criteria =  options.fetch(:sort_criteria, {})
unless sort_criteria.nil? || sort_criteria.empty?
  # order_options = self.class.construct_order_options(sort_criteria)
  order_options = relationship.resource_klass.construct_order_options(sort_criteria)
  records = resource_klass.apply_sort(records, order_options)
end

```

To solve final issue:

```
# JSONAPI::Request

def setup_show_action(params)
  parse_fields(params[:fields])
  parse_include_directives(params[:include])
  # @id = params[:id]
  @id = params[@resource_klass._primary_key]
  add_show_operation
end
```

Are these actual issues with jsonapi-resources or am I just doing something wrong?

Thanks!

**Comment by lgebhardt** [comment]
Which version are you using?

On your User model is the actual primary key `:uuid`, or is it internally `:id`?

**Comment by macasek** [comment]
I am using the head of master.

The User model has an actual primary key of `:uuid`

**Comment by lgebhardt** [comment]
Sounds like a bug then. I'll see if I can reproduce and fix it.

**Comment by macasek** [comment]
Ok. Let me know if you can reproduce it, I would be happy to open a PR with my changes (and tests).
