### ISSUE TITLE
How to create a new record

### ISSUE THREAD

**Issue by lionelrudaz** [JSONAPI-Resources/jsonapi-resources#345]
Hi guys,

I know this is a pure newbie question. I'm currently building an app with Ember JS for the frontend and Rails for the backend. I'm recently trying to switch from Grape to jsonapi-resources for the API, because I had many troubles formatting responses with JSONAPI.

Now I'm trying to do my first creation of record.

I'm doing that in Ember like that: 

this.store.createRecord('search', {category: selectedCategory, lat: search_params.lat, lon: search_params.lon}).save();

Unfortunately, this doesn't send data in JSONAPI, so I have the following error: {"errors":[{"title":"Missing Parameter","detail":"The required parameter, data, is missing."

I don't know if any of you had the opportunity to deal with that. Can I handle it with a custom controller? 

Thanks in advance for your help

**Comment by yawboakye** [comment]
Ember Data's default RESTSerializer doesn't know how to serialize to the JSON API standard. That's why you're getting `The required parameter, data, is missing.` error. If you inspect the JSON it generates, it has no `data` root. You should check out https://github.com/kurko/ember-json-api.

**Comment by lionelrudaz** [comment]
Sure, but I'm not using RESTSerializer, but JSONAPISerializer. It works perfectly when I get data, but not when I try to push a new record. I'll ask the same question there, maybe I'll get more luck.

Thanks a lot for your answer.

Cheers,

Lionel

**Comment by lionelrudaz** [comment]
Damn, of course, I forgot to update a serializer for this specific model. Upgrading to latest version of Ember helped, so do you. Thanks man.
