### ISSUE TITLE
undefined method '_attribute_options' when trying to include nested resource

### ISSUE THREAD

**Issue by dbwieland18** [JSONAPI-Resources/jsonapi-resources#346]
I'm serializing a User that has_many "master_schedules", each of which has_many "items." The include array looks like:

```
["master_schedules", "master_schedules.items"]
```

```
JSONAPI::ResourceSerializer.new(API::V2::UserResource, include: ["master_schedules", "master_schedules.items"]).serialize_to_hash(API::V2::UserResource.new(user))
```

The relationships are defined in the resources, but this fails with a NoMethodError: undefined method '_attribute_options.'

Been stuck on this for awhile--anyone seen anything similar?

**Comment by lgebhardt** [comment]
Is it failing trying to call `_attribute_options` on a nil object? I'd look to see if the included resources are being correctly retrieved.

**Comment by dbwieland18** [comment]
It's trying to call _attribute_options on this:

```
#<Class:0x007fbe423f1eb8>
```

And here is the source of the error:

```
from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.3/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
```

... Best I can figure is that it might be trying to call it on the Active Record Association object--but if so, I'm not sure why. The code matches the guides on serializing a nested resource by specifying it with dot notation.

**Comment by lgebhardt** [comment]
I missed that you were passing the includes array directly into the serializer. The serializer counts on the includes having been parsed into `include_directives`, usually by the `parse_include_directives` method on the request. Looking at again it doesn't look like it will be easy to call from outside a request object. This is something I would like to fix as part of a refactor of the request and operation logic. But you could look at the IncludeDirectives class and create them yourself, especially if the includes are going to be hard coded.

**Comment by dbwieland18** [comment]
Turned out my issue was having an attribute on the resource with the same name as the has_many association (:items)... I'd copied the attributes from an older serializer that overrode the association... Removing :items from the attribute list cleared this up.

**Comment by arcreative** [comment]
@dbwieland18 Ohhhh thank you so much for posting a follow-up.  I did the same with my `skills` has_many association, and didn't realize I had accidentally put it in attributes 🍻
