### ISSUE TITLE
Autocount is breaking on custom SELECTs

### ISSUE THREAD

**Issue by henrymazza** [JSONAPI-Resources/jsonapi-resources#348]
The method `JSONAPI::Resource#find_count` should be changed to:

``` ruby
 def self.find_count(filters, options = {})
  filter_records(filters, options).count(:all)
 end
```

so the SELECT is cleared. This is how `ActiveRecord::Relation#size` is implemented, BTW.

This problem emerges as a syntax error on any custom select, specially the ones you make just to please Postgres’s GROUP BY clauses.

**Comment by senid231** [comment]
:+1:
