### ISSUE TITLE
Mongoid embedded relationships

### ISSUE THREAD

**Issue by sebyx07** [JSONAPI-Resources/jsonapi-resources#349]
Is there a way to embed subdocuments as relationships ?

**Comment by oliverbarnes** [comment]
@sebyx07 my guess is there isn't at the moment, Mongoid isn't directly supported yet. You need to roll a custom operations processor just to get it going, and until recently there were direct references to Active Record in the codebase. 

One of us Mongoid users will probably have to write a Mongoid adapter :) things like support for embedded documents would be a pain to tackle for a somebody who doesn't use it at all. And there'd need to be enough demand for it to become a priority

**Comment by vladimir-e** [comment]
I hope I will have a chance to start working on mongoid adapter soon, for now let me share how I made it work in my project. It might be a starting for further development on this issue.

Override `apply_includes` method on your base resource so it doesn't try to eager-load embedded relationships, which otherwise causes error `undefined method eager_load_klass for Mongoid embedded_in`.

``` Ruby
# app/resources/base_resource.rb
class BaseResource < JSONAPI::Resource
  abstract

  class << self

    def apply_includes(records, options = {})
      include_directives = options[:include_directives]
      if include_directives
        model_includes = resolve_relationship_names_to_relations(self, include_directives.model_includes, options)
        # Filter out embedded relationships
        model_includes.delete_if do |relationship_name|
          [:embeds_many, :embedded_in].include?(_model_class.relations[relationship_name.to_s].macro)
        end
        records = records.includes(model_includes)
      end

      records
    end

  end

end
```

And provide own finder method for embedded resource:

``` Ruby
class DatasetResource < BaseResource
  attributes :key, :name
  has_one :project

  class << self

  def find_by_key(key, options = {})
      # Find the record through the parent resource which it is embedded into
      records = Project.where("datasets._id" => BSON::ObjectId(key)).first.try(:datasets)
      fail JSONAPI::Exceptions::RecordNotFound.new(key) if records.nil?
      # we have the record among its siblings in the records variable
      # the rest is standard finder code
      # database hit only once in the first query
      records = apply_includes(records, options)
      model = records.where({_primary_key => key}).first
      fail JSONAPI::Exceptions::RecordNotFound.new(key) if model.nil?
      self.resource_for_model(model).new(model, options[:context])
    end

  end

end

```
