### ISSUE TITLE
Add id to has_many

### ISSUE THREAD

**Issue by sebyx07** [JSONAPI-Resources/jsonapi-resources#355]
Can have_many relationships have also the ids in the data{ } ? 
like they do with the JSONAPI::ResourceSerializer

**Comment by lgebhardt** [comment]
In a response `id`s will be in the `relationships` section of `data` as long as the relationship's resource(s) are included.

In the payload for a Create/Update operation you may provide the `id`s for a has_many if the relationship has the `acts_as_set` options set. In this case the entire set of related data will be replaced with the new data.

**Comment by sebyx07** [comment]
it would be nice to have some examples on how to render custom responses using paginator, filtering and error handling. Because i also want to integrate it with websockets
