### ISSUE TITLE
Question regarding modiying _save on a resource to use custom nested_attributes

### ISSUE THREAD

**Issue by selaromi** [JSONAPI-Resources/jsonapi-resources#357]
Hello! We have implemented a very straightforward way (albeit not very jsonapi compliant) to generate nested resources for a record. 
Our api receives this kind of json:

``` json
{
   "data":{
       "type":"deposits",
       "attributes":{
           "reference":"PAY-7MN52443P87632445KW7TWWI",
           "nested-resources":[
               {
                   "operation":{
                       "user_id":"2",
                       "amount":"5.23",
                       "date":"25/03/05"
                   },
                   "credit":{
                       "user_id":"2"
                   }
               }
           ]

       }
   }
}
```

To make it work we modified the _save function (as explained in the comments) to generate all on a single transaction: 
- models that our model depends on.
- himself and.. 
- the models that depend on him.

To do this, we accept :nested_resources as a virtual attribute inside our model and modify the _save to generate the previously commented elements inside the _save transaction (and roll all of them back in case of error). 

My question is: we are trusting this behavior (_save being processed inside a transaction) will not change in the future, and would like to know if you consider it will remain that way or if it is possible it will change soon.

Thank you for your formidable work!

**Comment by lgebhardt** [comment]
I won't make any promises, but I don't see us moving `_save` out of a transaction. I can say that when/if the spec starts supporting nested resources we will be implementing it in a different manner. I envision the Request will create multiple operations and the operations will be linked to allow the new ids to propagate. All of that will be inside a transaction.

**Comment by selaromi** [comment]
Hello Larry, Thank you very much for your answer :+1: We look forward to moving to the standard when in comes out, so we consider our version temporary :ok_hand:
