### ISSUE TITLE
Resource#records_for should expose relationship details

### ISSUE THREAD

**Issue by jcarlson** [JSONAPI-Resources/jsonapi-resources#363]
I'm trying to integrate an authorization scheme with my resources.

I've gotten as far as overriding `records_for` on my resource classes, but `records_for` is responsible for loading both `ToOne` and `ToMany` relationships, it would really be helpful to know which one we are working with during authorization.

Here's an example (integrating with `CanCanCan`):

```
  def records_for(relation, options = {})
    relationship = self.class._relationship(relation)
    case relationship
    when JSONAPI::Relationship::ToMany
      super.accessible_by(ability)
    else
      super
    end
  end
```

A couple suggestions that would help:

1) `Resource` should offer a public method for retrieving the relationship metadata, e.g., `#relationship`.

2) The generated `records_for_#{relation}` methods should forward their options to the `records_for` method:
https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource.rb#L723
(Here, the options defined on the relationship are not passed along; only options at call time, e.g., the `context`, are available

3) `ToOne` relationships should generate an overridable `record_for(relation, options = {})` (singular) method

Any of those above options would alleviate the problem without relying on the private `self.class._relationship` method. 

Many thanks for the great work on this gem so far!

**Comment by lgebhardt** [comment]
It's pretty safe to rely on the `self.class._relationship`, but I can see how a public method would be an improvement and give peace of mind down the road. I'll give your suggestions some consideration.
