### ISSUE TITLE
Polymorphic 'No such column type' error

### ISSUE THREAD

**Issue by kevintraver** [JSONAPI-Resources/jsonapi-resources#365]
When using a polymorphic relationship `notable`, and the following routes:

```
jsonapi_resources :customers do
  jsonapi_relationships
end
```

I get the following error when accessing the following route `/customers/1/relationships/notes`

`no such column: type: SELECT type, "notes"."id" FROM "notes" WHERE "notes"."notable_id" = ? AND "notes"."notable_type" = ?`

I believe it should be `notable_type`, not `type`.

**Comment by kevintraver** [comment]
Accessing `/customers/1/notes` works just fine, and has the correct SQL using `notable_type`.

**Comment by demersus** [comment]
Kevin,
I solved this today.  You must leave the `polymorphic: true` flag off on the `has_many`  in the resource.  I think the polymorphic flag is used for STI situations when you would have a `type` column in the table.

Including the note relationship works fine without it.  

Maybe this can be clarified in the docs?
