### ISSUE TITLE
filter data attributes in params based on `creatable_fields` and `updatable_fields`

### ISSUE THREAD

**Issue by gniquil** [JSONAPI-Resources/jsonapi-resources#368]
Hi All,

I am using Ember Data. When a model is created or updated, ember data sends the entire serialized model to the api end point. However, when I override `creatable_fields` (or update), i get error saying params not allowed, due to the extra attributes. I can't find anything on how to "fix" this problem. Here's my hack for now:

``` javascript
  def setup_request
    if params[:action] == "create"
      resource = (self.class.name.sub(/Controller$/, "").singularize + "Resource").constantize
      fields = resource.creatable_fields(context).map { |f| f.to_s.dasherize }
      params[:data][:attributes] = params[:data][:attributes].select { |k, _| fields.include?(k) }
    end
    super
  end
```

Is this the right thing to do or there's a flag somewhere that I can set so that all the extra fields could be ignored or dropped?

**Comment by barelyknown** [comment]
I don't believe that there is currently a flag to cause fields that are not in the `creatable_fields` or `updatable_fields` to be dropped. I think that's an interesting idea that would definitely solve a practical problem. @lgebhardt, how would you feel about adding that flag?

If you'd rather handle the issue on the Ember side (instead of preprocessing the attributes), you could create customized serializers to remove the unsupported fields. See http://emberjs.com/api/data/classes/DS.RESTSerializer.html#method_serialize

**Comment by gniquil** [comment]
@barelyknown (first of all, long time fan of your show!), I'm slightly torn. Doing it on the Ember side feels more right, but much less practical. 

The reason is the createable and updatable fields have already been defined on the server side. I'd rather not redefine it all over again, especially when there's logic in creatable and updatable fields definition on the rails side for all my 20+ models. Currently my models can be accessed by 3 different roles, admin, tenant, and landlords, each could perform create/update slightly differently. On the server side, context[:current_user] gives me a simple way to distinguish them and set what's allowed. To do this in Ember, I have to somehow get access to the "session" service (from a serializer?) and redefine the same rules again for all 20+ models. (Or please let me know if there's a better to way to override `serialize`.)

Also the behavior of filtering out the extra attributes on the server side is in-line with what Rails does with strong params. So I think it will be less surprising for those who use Rails.

**Comment by barelyknown** [comment]
First, thanks about your nice words. I appreciate it.

I basically agree with everything you said. Handling it on the client _feels_ right, but it would be a bit of a pain for the reasons that you stated. And, I also believe that filtering them out is idiomatic within Rails given the approach with strong parameters - you're right about that too.

Are you up for creating a PR with the feature? I'd like to see a configuration that controls whether or not fields should be discarded that aren't allowed, and then a filter like the one from your original comment that discards them. If you can create the PR, please make sure to add tests for both config cases.

**Comment by gniquil** [comment]
ok will submit a PR within a day or so.

**Comment by gniquil** [comment]
@barelyknown The PR should achieve mostly what we discussed here, but I am not sure if my PR work for this sentence: "filter like the one form your original comment...". As far as I can tell, `verify_permitted_params` seems to be the place to make the change, rather than using a filter (or maybe I am misunderstanding you completely). Anyway, let me know.

**Comment by lgebhardt** [comment]
I see the need for adding the configuration option, though it seems like it does open the door for some confusion on the client. For example the client that misspells a parameter may be at a loss for why something isn't updating as they expect. What do you think about adding a warning to the metadata when a parameter is skipped? We could also make this optional.

**Comment by gniquil** [comment]
:+1: for warnings. I think if allow `raise_if_parameters_not_allowed` is set to false, then warnings should be generated (i.e. no additional config option to enable the warnings).

I took a look at the code but don't see any existing warnings generated in Request parsing (maybe I missed it?). So to implement it, perhaps I should do the following:
1. add an attr called "warning" to the request object
2. collect warnings in `verify_permitted_params` if applicable
3. merge the warnings into `ActsAsResourceController#base_response_meta`

Does the above sound right? Any suggestions for name? Should "warnings" be a key in the meta object (since I don't see any suggestions for warning in the JSONAPI spec)? For the messages, should I reuse the same in `ParametersNotAllowed` error?

**Comment by gniquil** [comment]
@barelyknown @lgebhardt Added warnings in the latest commit. Let me know if you want me to change anything else. And sorry about the changes this time turned out to be much bigger; I discovered after the last update that I forked this project months ago and master wasn't up to date. Anyway, all should be fixed now.
