### ISSUE TITLE
Use show related resources functionality, but disable "adjust" relationship actions.

### ISSUE THREAD

**Issue by brandonparsons** [JSONAPI-Resources/jsonapi-resources#369]
Hi there,

I'd like to use all of the default `related_resources` functionality for my resources (e.g. `GET /api/posts/12345/comments`) but disable the actions that allow individual assocations to be created/destroyed.

Is there a way to do this without manually setting all the `jsonapi_related_resources :posts` calls on every route?

**Comment by barelyknown** [comment]
I haven't taken a look, but if you exclude the `relationship` (`comments` in your example) from the `updatable_fields` does that have the same effect?
