### ISSUE TITLE
Example of including related objects?

### ISSUE THREAD

**Issue by oliverbarnes** [JSONAPI-Resources/jsonapi-resources#377]
I've been looking and looking at both JR's repo and Peeps, haven't found one. I know a `include: [:resource]` option can be passed to `serialize_to_hash`, but I'm lost on where to override the call to it. My guess would have been to override the `FindOperation` as the case at hand is a collection of resources. But I'm only seeing `serialize_to_hash` on the result document. 

Before `ActsAsResourceController`'s actions were all directed to `process_request_operations` it was simpler to override the serialization.

**Comment by lgebhardt** [comment]
The `include` request param is parsed into an [`include_directives`](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/include_directives.rb) hash in the [`parse_include_directives`](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/request.rb#L197) method in the Request object. The `include_directives` hash is used in the serializer (passed into the constructor), which is instantiated in the ResponseDocument.

What exactly are you trying to do?

**Comment by oliverbarnes** [comment]
Trying to get a list of Proposal resources with its Author resource included.

Hmmmm, request param you said? That jugged my memory about [the spec](http://jsonapi.org/format/#fetching-includes) :) 

Thanks. I think stating this explicitly on the readme could be helpful? though the spec is clear about it, somebody could be on drone doc-reading mode and forget it, like me. I'll submit a PR with this

**Comment by lgebhardt** [comment]
Glad you got it figured out. We should explicitly call out that you just follow the spec as far as the request parameters go for includes, fields, and sorting. I hadn't focused on how unclear that could be. I assumed you were trying to only use pieces/parts of the library.

Thanks in advance for the PR.
