### ISSUE TITLE
jruby support

### ISSUE THREAD

**Issue by sebyx07** [JSONAPI-Resources/jsonapi-resources#385]
is there a plan for jruby compatibility ?

**Comment by lgebhardt** [comment]
It's not something I've thought about. I'm certainly not opposed to supporting jruby, but since I've never used it I'm not sure what would be involved.

Does it fail under jruby?

**Comment by sebyx07** [comment]
yeah, the requirement is ruby >= 2.0, i tried to run the test from the master branch and most of them fail. I used jruby 1.7.19 and 9.0.0.0

**Comment by lgebhardt** [comment]
Are most of the issues related to the Ruby 2.0 hash syntax?

**Comment by barelyknown** [comment]
jruby 9.0.0.0 is 2.2 compatible, so it shouldn't be that. http://jruby.org/2015/07/22/jruby-9-0-0-0.html

**Comment by NuckChorris** [comment]
It might be wise to add jruby and rbx to the Travis build matrix but mark them as failable (that is, don't worry if it fails under them) to help move this forward
