### ISSUE TITLE
Creating relationship that differs in name from type 

### ISSUE THREAD

**Issue by mmartinson** [JSONAPI-Resources/jsonapi-resources#386]
In the json:api spec there is this example, suggesting that is is possible to post a people resource identifier object to the author relationship. I am trying to so something similar and am getting some different behaviour than I would expect from JR.

```
PATCH /articles/1/relationships/author HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": { "type": "people", "id": "12" }
}
```

Using this example, I would expect JR to look up the article and person objects and call something like this `article.author = person`. This assumes that the article model implements an author association that represents an instance of Person.

The example above using the to_one, but assume for example's sake it's a too_many authors, since that's where I've been having the problem.

In `Resource#_create_to_many_links` this code `@model.public_send(relationship.type) << related_resource.model` would call `article.people` instead of `article.author(s)`, since `relationship.type` is derived from the `class_name` option of the association in the resource class.

Not sure if this is a bug or a feature and my problem stems from a misunderstanding of the spec. Should the association be modified so that some attribute of the relationship object other than type can be used to make associations, or is there a way to make this work with the options that are currently implemented?

Just to be clear, what I would like to achieve is for JR to call the name of the relationship in the url as the relationship method on the model, and not the class_name option from the relationship in the JR Resource class. Changing the relationship class name in the resource class to make it work but then have my relationship pointing to a class that doesn't actually exist.

**Comment by mmartinson** [comment]
I made a pr to demonstrate the change that would fix it for me. Would this implement the intended behaviour? 
https://github.com/cerebris/jsonapi-resources/pull/387

**Comment by lgebhardt** [comment]
I don't think that's right. I think this would be better solved with an option on the to_many relationship that indicates the method on the model. That way we maintain the independence of the resource from the model methods. The `foreign_key` option was supposed to do this, but it is a bit wonky in that it's used for `_replace_to_many_links` but not `_create_to_many_links`.

**Comment by mmartinson** [comment]
I would think that using the foreign_key option may bit confusing, but like the idea of adding a method to the relationship. Do you think it best to keep the foreign key option for `_replace_to_many_links` or use a different option entirely for to_many relationships? Alternatively, I could change `_create_to_many_links` to use the foreign key in the same way.

 I missed this option before because it did not seem intuitive to me to use the concept of foreign key with a to_many relationship. If we keep it, what about adding an alias option for the `to_many` like `association_method`?

**Comment by barelyknown** [comment]
@mmartinson Can you check if the PR that @lgebhardt made solves this problem?

**Comment by mmartinson** [comment]
@barelyknown @lgebhardt Fixed. Thanks
