### ISSUE TITLE
foreign_key_on has_one clarification

### ISSUE THREAD

**Issue by utilityboy** [JSONAPI-Resources/jsonapi-resources#391]
Hi,

I believe I'm using the new direction mechanism properly for has_one relationships, but I'm running into an issue where the foreign key is still being looked for on one of the models (in the current release and also on master):

```
class Master < ActiveRecord::Base
  has_one :detail
end

class Detail < ActiveRecord::Base
  belongs_to :master
end

class MasterResource < JSONAPI::Resource
  has_one :detail, foreign_key_on: :related
end

class DetailResource < JSONAPI::Resource
  has_one :master
end
```

Produces:

```
undefined method `detail_id' for #<Master:0x007f94f4a13bd8>
```

If this looks correct, I'll dig in and try to track this down.  Thanks.

**Comment by utilityboy** [comment]
This is in fact correct, and works as expected on **master** as of Aug 19th.  Local branch was slightly behind.  Apologies for the cruft.

**Comment by mupkoo** [comment]
Just updated to 0.6.1 and this seems to be not working.

Here is what I have in my resource

``` ruby
module Api::V1
    class CountryResource < JSONAPI::Resource
        attributes :iso, :name, :threat_level, :updated_at

        relationship :overview, to: :one, foreign_key_on: :related
        relationship :institutions, to: :many
    end
end
```

and I get 

```
Internal Server Error: undefined method `overview_id=' for class `Country'
```

**Comment by lgebhardt** [comment]
What version where you previously using? Could you post the line number of the error?

**Comment by lgebhardt** [comment]
Also, what do your models and tables look like?

**Comment by mupkoo** [comment]
I was using 0.5.9, so I did not have this working.

``` ruby
class Country < ActiveRecord::Base
    has_one :overview
end

class Overview < ActiveRecord::Base
    belongs_to :country, touch: true
end
```

and my I have `country_id` field in the `overviews` table, but I don't have `overview_id` in the `countries` table.

Here is the full stack trace of the error - https://gist.github.com/mupkoo/9df938d790fdc003e0a1

**Comment by mupkoo** [comment]
Adding the following method to my Country model does the trick

``` ruby
def overview_id=(_value)
   # TODO: Remove once it's fixed
end
```

**Comment by jakeonfire** [comment]
@lgebhardt @bjubinville i believe this is an issue. the `foreign_key_on: :related` resource option works when looking up `has_one` related resources, but when saving those resources the code does not take this option into consideration (jsonapi-resources v0.7.0, `jsonapi/resource.rb:211,797-799`).

is this a missing feature or is it intended that saving a has_one active record association on a model/resource requires a patch like mupkoo's recommendation on the underlying model? or more completely:

``` ruby
def overview_id=(id)
  self.overview = Overview.find_by_id(id)
end
```

**Comment by toobulkeh** [comment]
👍  that this still exists on 0.7.0. Supporting a proper belongs_to has_one relationship at the jsonapi-resources level would be more ideal than the current implementation.

**Comment by maprihoda** [comment]
IMHO, using has_one in place for belongs_to (as in Rails) is just **wrong** as it is very confusing for people used to working with Rails where has_one and belongs_to are opposite to each other. Introducing the `foreign_key_on` option makes things even more confusing. What is wrong with good old belongs_to?

**Comment by lgebhardt** [comment]
@maprihoda `belongs_to` was added to the project in I believe the 0.8 release, though it has a deprecation warning. JSON API does not differentiate between a `has_one` and a `belongs_to` relationship, and it was decided that the `resource` declaration should try to reflect this. Therefore the preferred notation is to have the relationship describe the JSON API relationship with options to resolve to the rails model. The `belongs_to` method was added as a shortcut.

**Comment by fsmanuel** [comment]
@lgebhardt what is the recommended way for a

```rb
has_one :user, through: :authentication
```

I added

```rb
def user_id=(_value)
end
```

but that feels wrong.

**Comment by lgebhardt** [comment]
@fsmanuel I'm not sure I've tested a "has_one through" relationship.  To work like the "has_many through" you should be able to declare the `has_one :user, through: :authentication` on the model and a `has_one :user` on the resource.

**Comment by fsmanuel** [comment]
@lgebhardt that is what I'm doing and it works but I get the same error as above and have to define `user_id=`. Should we think about an option to prevent the`foreign_key` thing? I'm not so much into the internals of jsonapi-resources to say what that means. Not even sure where `foreign_key` is used.

**Comment by krainboltgreene** [comment]
This appears to still be an issue?

**Comment by krainboltgreene** [comment]
Nevermind, I should have just used `foreign_key_on: :related`. However, I think there's room to improve the exception description.
