### ISSUE TITLE
The controller specs don't run the callbacks setup in JSONAPI::ActsAsResourceController

### ISSUE THREAD

**Issue by apraditya** [JSONAPI-Resources/jsonapi-resources#397]
I have the following controller spec

```
describe "'POST' create" do
  before do
    @data = body_params[:data]
  end

  subject do
    -> { post :create, data: @data }
  end

  it 'creates the article' do
    is_expected.to change(Article, :count).by(1)
  end

  it 'does not respond with error' do
    subject.call
    expect(data['errors']).to eql(nil)
  end
end
```

which passes the test. However if I request to the same call with the same body, I get an error from the `#setup_request` from `JSONAPI::ActsAsResourceController` module. Does this mean on the controller spec didn't run the callback? How to set the spec to make sure it's running the same way on an actual request call?

**Comment by vrybas** [comment]
@apraditya are you still having this problem?

Let me suggest using request specs instead of controller specs.
Especially for testing API endpoints.

There are talks around community to remove controller tests from Rails
completely.

https://github.com/rails/rails/issues/18950#issuecomment-77924771
