### ISSUE TITLE
Issue with alias for resources

### ISSUE THREAD

**Issue by selaromi** [JSONAPI-Resources/jsonapi-resources#399]
Hello, I have the following situation:

I'm generating the json-api resources urls by hand. I have a resource that has a alias in the url path. I need the external scope '/users' since I'm using nginx to redirect from the entrypoint to this service.
I wanted to avoid having '/users/users', so I called it 'accounts'.

```
Rails.application.routes.draw do
  scope 'users' do
    as :user do
      get '/accounts/:id',       to: 'users#show',   as: 'user_info'
      get '/accounts',           to: 'users#index',   as: 'users_index'
    end
  end
end
```

But when i return a resource rendered by jsonapi, it uses '/users' and skips the scope, so it's basically '/users' for index.

Any recommendations on how to tackle this situation?

Thanks!

**Comment by pboling** [comment]
I also need to alias my JSON API resources.

Here is what I was hoping would work, but does not:
```
      jsonapi_resources :users, only: [:index]
      jsonapi_resources :people, only: [:index], as: 'users'
```

What is the correct way to do this?

~Ninja edit:~

**Update**

The right way to do this is...
```
      jsonapi_resources :users, only: [:index]
      get :people, to: 'users#index'
```
