### ISSUE TITLE
Update/Create multiple ressources in one request

### ISSUE THREAD

**Issue by webpapaya** [JSONAPI-Resources/jsonapi-resources#400]
Hey,

I'm using the ember jsonapi-adapter with jsonapi-resources. In my application i need to update multiple models in a has many relationship in a single request. Now I realized that jsonapi currently doesn't have the support for multiple operations in a single request. (https://github.com/json-api/json-api/issues/795)

For the ember case i can probably make a manual ajax request to the server, but are there any suggestions or best practices on how to add this behaviour to jsonapi-ressources. 

Thanks

**Comment by barelyknown** [comment]
See https://github.com/cerebris/jsonapi-resources/issues/183. I'm going to close this issue so that we can keep the conversation in one place.
