### ISSUE TITLE
Documentation for serialize_to_hash method incorrect/misleading

### ISSUE THREAD

**Issue by master-chu** [JSONAPI-Resources/jsonapi-resources#402]
Hi, could you please take a look at the #serialize_to_hash-method-options section of the README? It says that the method has optional parameters, when it's actually the serializer that needs to be instantiated with the parameters before calling the single-argument serialize_to_hash method. The example has the correct syntax.

Here are the offending lines:

"You can also pass an include option to Serializer#serialize_to_hash if you want to define this inline."
"The serialize_to_hash method also takes some optional parameters:"

**Comment by gniquil** [comment]
@lgebhardt The serializer readme still doesn't look right. The serializer initalize method does not do anything with `:context`. One has to pass it to `Resource` initializer as the second argument (this is what I am doing right now). 

Perhaps we should add an attribute `context` to serializer and adjust the `initialize` method?

**Comment by lgebhardt** [comment]
@gniquil Good catch. `context` in the initializer is leftover from an earlier version.
