### ISSUE TITLE
Related source with `relation_name` throws undefined method error on create / update actions

### ISSUE THREAD

**Issue by apraditya** [JSONAPI-Resources/jsonapi-resources#404]
I have this resource

```
class PostResource < JSONAPI::Resource
  has_many  :categories,   relation_name: 'internal_categories'
end
```

and I get this error on POST create and PUT update calls

```
Internal Server Error: undefined method `category_ids=' for class `Post' /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.7/lib/jsonapi/resource.rb:705:in `method'
```

Shouldn't it run based on `relation_name` options? Probably similar to #378 (in a way). Thanks

**Comment by jcarlson** [comment]
Yeah I just noticed this too and left a comment in a commit somewhere: https://github.com/cerebris/jsonapi-resources/commit/494e869ab3739ddb149b3dd6ed897e280a0ee960#commitcomment-13165776

This may be related to #378 but is definitely a different issue.

**Comment by lgebhardt** [comment]
I'll see if I can get a fix for this soon.

**Comment by lgebhardt** [comment]
#447 fixes `_remove_to_many_link` to use the relation_name. This won't fix the error on the POST and PUT calls. For that I think setting the `foreign_key` option on the relationship is going to be required. Can you check if this solves the problem?
