### ISSUE TITLE
Pagination parameter documentation

### ISSUE THREAD

**Issue by arcreative** [JSONAPI-Resources/jsonapi-resources#406]
I thought pagination was broken, but I think it just needs to be documented a bit better.  Perhaps mentioning somewhere that the format is `page[limit]=5&page[offset]=2` would be helpful!

**Comment by lgebhardt** [comment]
The documentation is a bit lacking on the format for the pagination, filtering, and sorting request parameters. The format for these follow the JSON API spec, and this project defines the valid parameters for the different paginators. But the examples that put it all together are missing as you have pointed out. I'll see if I can get some basic examples added soon.

**Comment by tiagopog** [comment]
I went through the same problem @arcreative went and spent a few minutes until I get the insight of how it should work. We know that having a good self-explained documentation is an important point of adoption for new gems such as `jsonapi-resources`. It's really worth to apply some examples for pagination, filtering, sorting, fields etc, and decrease the learning curve of new adopters.

**Comment by utilityboy** [comment]
@lgebhardt I ran into this as well.  I'm happy to work up a PR over the weekend for the docs.

**Comment by lgebhardt** [comment]
@bjubinville Thanks, that would be great!

**Comment by utilityboy** [comment]
@lgebhardt very happy to.  This project is stellar.

**Comment by utilityboy** [comment]
I've finally started working this up here:

https://github.com/cerebris/jsonapi-resources/wiki/JSONAPI::Resources-Querystring-Examples

@lgebhardt Would you like to link to this from the readme?  If so, I can make a PR.
