### ISSUE TITLE
How to send appropriate error codes?

### ISSUE THREAD

**Issue by jagthedrummer** [JSONAPI-Resources/jsonapi-resources#407]
I'm trying to use `records_for` and/or `before_create` to verify that a user is allowed to view/create a given record. Raising any type of error in these methods seems to force `jsonapi-resources` into responding with an error code of `500`. How do I get it to send something like `401`?

**Comment by barelyknown** [comment]
Good news! I ran across that trouble and added a feature for it. From the README.

``` ruby
JSONAPI.configure do |config|
  # List of classes that should not be rescued by the operations processor.
  # For example, if you use Pundit for authorization, you might
  # raise a Pundit::NotAuthorizedError at some point during operations
  # processing. If you want to use Rails' `rescue_from` macro to
  # catch this error and render a 403 status code, you should add
  # the `Pundit::NotAuthorizedError` to the `exception_class_whitelist`.
  # Subclasses of the whitelisted classes will also be whitelisted.
  config.exception_class_whitelist = []
end
```

I'm gonna close the issue. Let me know if this doesn't work for you.

**Comment by jagthedrummer** [comment]
What do I do if I'm not using Pundit? I feel like this need much more documentation.

**Comment by barelyknown** [comment]
That documentation looks pretty clear to me! Just add the exception classes that should not be rescued to that array. There's nothing Pundit specific at all about the feature - it's just an example of an exception class.
