### ISSUE TITLE
Update docs for raising appropriate error codes

### ISSUE THREAD

**Issue by jagthedrummer** [JSONAPI-Resources/jsonapi-resources#408]
Apparently it's possible to get `jsonapi-resources` to raise appropriate error codes for different situations (see #407), but this is not documented well. We should show an example that does not rely on some other library and we should show enough code to help people understand exactly what's happening top to bottom.

**Comment by barelyknown** [comment]
Send a PR if you'd like.

**Comment by jagthedrummer** [comment]
Aren't PRs usually preceded by an open issue?

**Comment by dgeb** [comment]
I see where @jagthedrummer is coming from and think we should leave this open until the docs can be expanded.

**Comment by barelyknown** [comment]
Doesn't seem to be an issue to me (that was my point), but ¯_(ツ)_/¯.
