### ISSUE TITLE
error objects status value

### ISSUE THREAD

**Issue by amkirwan** [JSONAPI-Resources/jsonapi-resources#412]
I was looking at the JSON-API documentation and I think the error object that JSONAPI-Resources is generating are incorrect. Looking at the docs it says the 
- status:  the HTTP status code applicable to this problem, expressed as a string value
- code: an application-specific error code, expressed as a string value.

On a simple little app I created to tryout jsonapi-resource the following error object is generate when attempting to get a post that doesn't exist.

```
$ curl -X GET -H "Accept: application/vnd.api+json" http://test-json-api.dev/api/posts/7

$ {"errors":[{"title":"Record not found","detail":"The record identified by 7 could not be found.","id":null,"href":null,"code":404,"source":null,"links":null,"status":"not_found"}]}[amkirwan@boba-fett:~/code/rails/test-json-api]
```

From reading the JSON-API docs it seems as though `status` should be the string `404` not `not_found`. Therefore the `code` attribute should be some error code specific to the given API.

Maybe I'm totally wrong reading the JSON-API docs but that is how it appears to me the error object should be. Therefore the previous GET request would return the following. The "1100" in the response would be the app specific identifier code for the error.

```
$ {"errors":[{"title":"Record not found","detail":"The record identified by 7 could not be found.","id":null,"href":null,"code":"1100","source":null,"links":null,"status":"404"}]}[amkirwan@boba-fett:~/code/rails/test-json-api]
```

**Comment by lgebhardt** [comment]
I think you are correct. I'll get a fix out soon. Thanks.

**Comment by amkirwan** [comment]
If you want me to I take a look at fixing it.

**Comment by lgebhardt** [comment]
@amkirwan I just made #413, which converted the status codes from symbols to the actual status codes. I think that should fix things.

**Comment by amkirwan** [comment]
Thanks for the fast response.

I haven't looked through all the code to see how the `JSONAPI::Error` is generated into JSON but shouldn't the status codes be strings here #413? In the docs it says the `status` should be expressed as a string. 

```
def errors
  [JSONAPI::Error.new(code: JSONAPI::RECORD_NOT_FOUND,
    status: 404,
    title: 'Record not found',
    detail: "The record identified by #{id} could not be found.")]
end
```

**Comment by lgebhardt** [comment]
Woops. Yes, they should strings.

**Comment by lgebhardt** [comment]
I backtracked and left the errors using the symbols as it's easier to read. And now I convert the symbols to the appropriate HTTP status code string.
