### ISSUE TITLE
Issue with "id" format

### ISSUE THREAD

**Issue by tiagopog** [JSONAPI-Resources/jsonapi-resources#417]
Hi, there! Today I started to migrate a REST API in order to use the jsonapi-resources' serialization and fully accomplish with JSON API's specs. For my surprise, it was a hard work to set up my resources, just because things were breaking with the `JSONAPI::ResourceSerializer#format_value` method.

When I called this:

``` ruby
JSONAPI::ResourceSerializer.new(API::V2::BusinessResource).serialize_to_hash(API::V2::BusinessResource.new(Business.first))
```

I got this:

``` shell
NoMethodError: private method `format' called for nil:NilClass
from /Users/tiagopog/.rvm/gems/ruby-2.2.2/gems/jsonapi-resources-0.5.7/lib/jsonapi/resource_serializer.rb:317:in `format_value'
```

For this sample resource:

``` ruby
class API::V2::BusinessResource < JSONAPI::Resource
  attributes :name, :description
end
```

After a little debugging I figured out that the actual problem was happening in the line `id_format = 'id' if id_format == :default` in `JSONAPI::ResourceSerializer#object_hash` method. This line is always setting `"id"` into `id_format` variable, then the `format_value` method only returns the proper format when it takes the value `"Id"` rather than `"id"`.

As I was not explicitly setting a format for my `id` attribute, at the end of the day this was my workaround:

``` ruby
class API::V2::BusinessResource < JSONAPI::Resource
  attribute :id, format: :Id
  attributes :name, :description
end
```

Is this the proper way to work with resource's id formats (in terms of the gem's DSL)?  Am I missing something?

**Comment by lgebhardt** [comment]
You should not need to specify the id as an attribute, and the format should work as any of `:id`, `id`, or `Id`. The format value will be converted to a string and camelized in:

``` ruby
def value_formatter_for(type)
  formatter_name = "#{type.to_s.camelize}Value"
  formatter_for(formatter_name)
end
```

I am not sure why you are having this issue.

**Comment by tiagopog** [comment]
Thanks for replying, @lgebhardt.

Let me show you a quick debug that I just made now, so this issue should get a little bit clearer to you.

When I make this call:

``` ruby
JSONAPI::ResourceSerializer.new(API::V2::BusinessResource).serialize_to_hash(API::V2::BusinessResource.new(Business.first))
```

For a resource such as this one:

``` ruby
class API::V2::BusinessResource < JSONAPI::Resource
  attributes :name, :description
end
```

Then I don't get a proper format in the `JSONAPI::ValueFormatter.value_formatter_for` method. As shown below:

<img width="638" alt="screen shot 2015-09-02 at 4 08 59 pm" src="https://cloud.githubusercontent.com/assets/760933/9642948/ff031e60-518c-11e5-9b84-503aeb36dbf9.png">

**Comment by lgebhardt** [comment]
So the problem is formatter_name is `IDValue` instead of `IdValue`. I'm not sure why that would be happening. Seems likely it's the `camelize` call. Which version of rails are you using?

**Comment by tiagopog** [comment]
4.2.3

**Comment by lgebhardt** [comment]
Can you check what the value of `type` is at line 55 or 56. I predict it's `ID`, which I think would mean you are setting it to that somewhere.

**Comment by tiagopog** [comment]
I checked here that the problem is happening with `camelize` indeed. I loaded another Rails version (4.2.1) and it did the job nicely.

**Comment by tiagopog** [comment]
You can see the value of `type` in that screenshot above.

**Comment by lgebhardt** [comment]
Sorry, I missed the type in screenshot. That's all very odd. I just checked in rails 4.2.3 and it's working fine. Is any other gem patching the `camelize` method? One that's not loaded in your 4.2.1 environment?

**Comment by tiagopog** [comment]
Maybe, I was thinking on that right now. Let me check.

**Comment by lgebhardt** [comment]
Also check your inflections. Looking at the code it seems if Id is registered as an acronym that could cause it too.

``` ruby
ActiveSupport::Inflector.inflections.acronyms
```

**Comment by tiagopog** [comment]
That's it! Removing the acronym 'ID' in my inflections, the format worked properly.

``` ruby
ActiveSupport::Inflector.inflections(:en) do |inflect|
  # ...
  inflect.acronym 'ID'
end
```

Thanks, @lgebhardt. Cheers!

**Comment by lgebhardt** [comment]
@tiagopog Glad you found it. If you do need to treat `Id`s as an acronym you could create a custom value formatter (just copy the `IdValueFormatter` with a new name and use that for all your ids.

**Comment by tiagopog** [comment]
Seems like a neat workaround for that case.
