### ISSUE TITLE
"Param not allowed" error for hasMany with acts_as_set

### ISSUE THREAD

**Issue by jagthedrummer** [JSONAPI-Resources/jsonapi-resources#418]
I'm trying to use `acts_as_set` to allow a single call to update/create a record. My `OrderResource` looks like this:

``` ruby
class OrderResource < JSONAPI::Resource
  attributes :number, :date
  has_many :line_items, :acts_as_set => true
end
```

And the payload I'm sending to the server looks like this:

``` ruby
{
  "data"=>{
    "attributes"=>{"number"=>"123"},
    "line-items"=>[{
      "data"=>{
        "attributes"=>{"quantity"=>45},
        "relationships"=>{
          "product"=>{"data"=>{"type"=>"products", "id"=>"1"}},
          "order"=>{"data"=>{"type"=>"orders", "id"=>nil}}
        },
        "type"=>"line-items"
      }
    }], 
    "type"=>"orders"
  }
}
```

The error coming back is:

``` ruby
{
  "errors":[{
    "title":"Param not allowed",
    "detail":"line-items is not allowed.",
    "id":null,
    "href":null,
    "code":105,
    "source":null,
    "links":null,
    "status":"bad_request"
  }]
}
```

Is it possible that `line-items` isn't being correctly translated to `line_items` when looking for the `has_many` relationship in the resource? (I haven't had a chance to check what happens with a non-dasherized child type.)

**Comment by jagthedrummer** [comment]
Wait, I think maybe I'm not sending the proper document format. Lemme double check that...

**Comment by lgebhardt** [comment]
Yes, the payload format is wrong. You will need to send the line items as resource identifiers in the relationships key (see http://jsonapi.org/format/#crud-creatin). However for this to work the line items will need to already exist. The acts as set option is really only useful for connecting existing resources through a linking table.

Once JSON API supports bulk updates we will add this to JR and you will then be able to create multiple resources in one request (and hence one transaction).

Hope that helps.

**Comment by jagthedrummer** [comment]
Yep! Thanks for the clarification. I was just reading up on the status of that in JSON API and realized that it's not quite there yet. I'll keep my fingers crossed that it lands soon. Cheers!

**Comment by lgebhardt** [comment]
There's a lot of us waiting for that to land.

**Comment by dgeb** [comment]
If all goes well bulk operation support should be in 1.1 beta by the end of September.

No pressure! :sweat_drops:
