### ISSUE TITLE
Removing relationships via relationship URL

### ISSUE THREAD

**Issue by timabdulla** [JSONAPI-Resources/jsonapi-resources#422]
Currently, it appears that JR does not comply with the spec with regard to how it handles the removing of relationships via a relationship URL. The spec dictates that relationships are to be removed by sending a request with the DELETE method to the relationship URL with a request body that specifies the resources for which the relationships should be removed.[0] JR allows for this operation by accepting a comma-separated list of IDs of the resources for which the relationships should be removed at the end of the relationship URL. It is not only incongruent with the spec, but it also forecloses the possibility of allowing for a heterogeneous collection of relationships to exist at the URL, as it assumes that primary key alone is enough to uniquely identify a resource, when only the tuple of type and ID are truly enough to uniquely identify a resource.

Was there a reason for this decision, or is this simply an oversight? It looks fairly easy to correct if it's the latter, and I'd be happy to step in and help!

[0] = http://jsonapi.org/format/#crud-updating-to-many-relationships

**Comment by lgebhardt** [comment]
That's an oversight. It looks like I missed that as the spec changed. I would greatly appreciate the help in fixing this. Thanks!

**Comment by timabdulla** [comment]
we @paysavvy are pretty heavy users of JR, so always happy to help out! we'll get on this right away. thanks for this great project!

**Comment by timabdulla** [comment]
cc @mmartinson

**Comment by vrybas** [comment]
@timabdulla fixed by #423?
