### ISSUE TITLE
Error with documentation's context use case

### ISSUE THREAD

**Issue by tiagopog** [JSONAPI-Resources/jsonapi-resources#425]
Recently I had an issue when I tried to use contexts, following the examples provided by the gem's documentation, such as:

``` ruby
class PostResource < JSONAPI::Resource
  attribute :title, :body

  def self.records(options = {})
    context = options[:context]
    context.current_user.posts
  end
end
```

Since it returns a `Hash` the right way to call `current_user` should be: `context[:current_user]`. I suggest a revisions in doc's places where `context` is pointed.

**Comment by lgebhardt** [comment]
Thanks. Fixed.
