### ISSUE TITLE
Ember-data warning about non-async relationships and links

### ISSUE THREAD

**Issue by bartocc** [JSONAPI-Resources/jsonapi-resources#431]
When we define an {async: false} relationship in ember-data 1.13, and use an 'include' to fetch the resources, we constantly get the following warning

> You have pushed a record of type 'X' with 'Y' as a link, but the association is not an async relationship

Should we suppress the links from JR's response payload (and if so, how) ? Should Ember-data be less noisy about it ?

Any thoughts on this appreciated

**Comment by toandv** [comment]
I'm having the same problem. Is yours solved?

**Comment by kevinwmerritt** [comment]
I am seeing this ember warning also.

**Comment by brancusi** [comment]
Same here. Any ideas?

**Comment by lolmaus** [comment]
Bump.

**Comment by arthur5005** [comment]
Does anyone have any information on this?

**Comment by ianpetzer** [comment]
Hi All,

Did anyone figure out a solution for this issue? I'm migrating my API to json-api-resources and running into this.

Thanks for any help!
