### ISSUE TITLE
Request: Include operation arguments in callbacks

### ISSUE THREAD

**Issue by jcarlson** [JSONAPI-Resources/jsonapi-resources#440]
It would be super helpful in `Resource` callbacks to get some context on what the operation is...

For example, I am adding a `before_remove_to_many_link` callback that will halt the removal if the parent object is in a specific state (e.g., you cannot remove `OrderLineItems` from an `Order` that is "finalized").

The `remove_to_many_link` method receives the `relationship_type` and `key` arguments from the corresponding `*Operation`, but those arguments are not passed through to callbacks.

Since my `Order` resource has more than one relationship, it would be useful to know, in my callback, which relationship we are trying to remove a link from.

Same goes for other callbacks, especially `replace_fields`.

**Comment by lgebhardt** [comment]
I agree that would be useful. We're using ActiveSupport callbacks. I know I looked when we initially set this up, but I don't know if it's possible to pass parameters to the callback methods. 

This isn't exactly what you are asking for, but if you create your own OperationsProcessor you will have access to the full stack of operations (`@operations) and the current operation (`@operation`). Using those I added a method on all my resources called`approve_operation` and in the custom operations processor I call this before every operation:

``` ruby
class MyOperationsProcessor < ActiveRecordOperationsProcessor
  before_operation :approve_operation

  def approve_operation
    @operation.resource_klass.approve_operation(@request.context, @operation)
  end
end
```

``` ruby
class MyResource < JSONAPI::Resource
...
  def approve_operation(context, operation)
    case operation
      when JSONAPI::RemoveToManyRelationshipOperation
        #your code here
      else
    end
  end
end
```

It's not the most elegant solution, but it works fairly well.
