### ISSUE TITLE
[Question] Is there an option to omit optional members of a resource (links)

### ISSUE THREAD

**Issue by pixelhandler** [JSONAPI-Resources/jsonapi-resources#444]
In a resource object I'd like to omit the `links` object, see http://jsonapi.org/format/#document-resource-objects 

I have a long list of objects with one attribute and only need the `id`, `type` and `attributes` members of the resource object.

Is there an option to omit optional members of a resource (links)?

**Comment by lgebhardt** [comment]
There isn't an option for excluding `links`, though it's a good idea. We should probably add this as a global configuration option, and also allow it per resource.

**Comment by DavidVII** [comment]
:+1:

**Comment by clumsysnake** [comment]
in the meantime, what's the best way of getting this done in the application layer? subclass the serializer and override #serialize_to_links_hash?

**Comment by mecampbellsoup** [comment]
@lgebhardt @clumsysnake any ideas on this? Having same issue, i.e. would like to omit `links` object from the serialized response object produced by an API endpoint.

**Comment by lgebhardt** [comment]
I haven't worked on this feature yet. I don't have a good work around at this point.

**Comment by mecampbellsoup** [comment]
@lgebhardt how about just making it an option that can be passed to `serialize_to_hash`? Or adding it as an `include_directive`? https://github.com/mecampbellsoup/jsonapi-resources/blob/c358cb7515441ee7a958b37bcc3be44acc05d0ef/lib/jsonapi/resource_serializer.rb#L46

**Comment by mecampbellsoup** [comment]
@lgebhardt if you can point me in the right direction I'll take a shot at implementing this, we _really_ need it 😅

**Comment by mecampbellsoup** [comment]
#735

**Comment by utilityboy** [comment]
I get around this by specifying the fields I want.  Not sure if it's supposed to work like this or not, but:

`machines?fields[machines]=name`

produces:

```
{
  "data": [
    {
      "id": "1",
      "type": "machines",
      "links": {
        "self": "http://my.api.com/machines/1"
      },
      "attributes": {
        "name": "M1"
      }
    },
    {
      "id": "2",
      "type": "machines",
      "links": {
        "self": "http://my.api.com/machines/2"
      },
      "attributes": {
        "name": "M2"
      }
    },
    {
      "id": "3",
      "type": "machines",
      "links": {
        "self": "http://my.api.com/machines/3"
      },
      "attributes": {
        "name": "M3"
      }
    }
...
```

If you need any of the related resources, include them as well.  It's ugly but does cut down on payload sizes when you don't need related resources.

**Comment by senid231** [comment]
after PR #893 it will be possible to allow resource to decide if his relationships has links.

For example: add options to relationships like `include_self_route` and `include_related_route`, and make `jsonapi_relationships`, `jsonapi_related_resource(s)` and `jsonapi_link(s)` respect these options

default values for `include_self_route` and `include_related_route` can be stored in `JSONAPI.configuration`

**Comment by tommy-russoniello** [comment]
Closed in favor of https://github.com/cerebris/jsonapi-resources/issues/594.
