### ISSUE TITLE
_replace_to_many_links increments counter_cached attribute by 1 on create

### ISSUE THREAD

**Issue by byelipk** [JSONAPI-Resources/jsonapi-resources#445]
I have a task model that can have many posts. It's a polymorphic association with a counter cache on the `posts_count` column of the tasks table. `posts_count` defaults to 0.

```
class Task < ActiveRecord::Base
  has_many :posts, as: :commentable
end

class Post < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true, counter_cache: :posts_count
end
```

The problem: When `_replace_to_many_links` is called, it increments the `posts_count` attribute on `TaskResource#model` by 1, but it should remain at 0.

```
.../gems/jsonapi-resources-0.5.9/lib/jsonapi/resource.rb 
@ line 185 JSONAPI::Resource#_replace_to_many_links:


    181: def _replace_to_many_links(relationship_type, relationship_key_values)
    182:   relationship = self.class._relationships[relationship_type]
    183:
    184:   binding.pry
 => 185:   send("#{relationship.foreign_key}=", relationship_key_values)
    186:   @save_needed = true
    187:
    188:   :completed
    189: end
```

`relationship` is an instance of `JSONAPI::Relationship::ToMany`.

`relationship.foreign_key` evaluates to `post_ids`.

`relationship_key_values` evaluates to an empty array.

What line 185 is doing is setting `post_ids` to an empty array, and for some reason that is incrementing `model.posts_count` by 1.

While the actual value in the database remains at 0, the json document returned from `TasksController#create` has the `posts-count` attribute equal to 1.

Fetching the task resource again after create returns a json document with `posts-count` equal to 0.

Unfortunately I cannot reproduce this in a controller test - it returns the correct `posts-count` value.

**Comment by lgebhardt** [comment]
Are you sure this is an issue with jsonapi-resources? I ask because it seems the Resource is just making a fairly common call to the underlying model. Does this happen if you take the resource out of the mix?

Note this is the first I have seen of the `counter_cache` feature, so I could obviously be missing something major.

**Comment by byelipk** [comment]
I didn't dig any deeper than `_replace_to_many_links`, but from what I saw it seemed that the call to `send` modified the local copy of the model and in doing so it set `posts_count` from 0 to 1.

For now my current solution is to override the create action - I create the task myself and then use `JSONAPI::ResourceSerializer` and `TaskResource` to return the json document. It returns the correct value of `"posts-count":0`.

My controller includes `JSONAPI::ActsAsResourceController`.
