### ISSUE TITLE
Filter by joined attribute

### ISSUE THREAD

**Issue by thomassnielsen** [JSONAPI-Resources/jsonapi-resources#446]
We've got a use case where we need to filter by a joined attribute.

Say you have a table `users` with name and email. Then you have an `user_extras` table where you have the `address` and `phone`. We might have a default scope on the User model:

```
default_scope { joins("LEFT JOIN user_extras ON user_extras.user_id = users.id") }
```

At this point, we have a User model that has all the attributes of both tables.

Then we want to allow the following query: `users?filter[phone]=12346789`

Currently this produces a query like this: 

```
SELECT * FROM users LEFT JOIN user_extras ON user_extras.user_id = users.id WHERE users.phone = '123456789';
```

Specifically the issue is this: `users.phone = '123456789'` which should really be `user_extras.phone = '123456789'` if the query should work.

Is there currently a way to query by a joined table, and if not, is there an override point that would allow us to do this? I haven't found much while poking through the code. It seems that filtering happens pretty deep in the core of jsonapi-resources.

**Comment by lgebhardt** [comment]
On your resource you could override the `apply_filter` method. Here's an example from the [tests](https://github.com/cerebris/jsonapi-resources/blob/master/test/fixtures/active_record.rb#L1057-L1112):

``` ruby
        def self.apply_filter(records, filter, value, options)
          context = options[:context]
          current_user = context ? context[:current_user] : nil

          case filter
            when :banned
              # Only book admins my filter for banned books
              if current_user && current_user.book_admin
                return records.where('books.banned = ?', value[0] == 'true')
              end
            else
              return super(records, filter, value)
          end
        end
```

You may also want to override the `records` method to ensure the `user_extra` table is joined in by default.

**Comment by thomassnielsen** [comment]
Thanks a lot, this was exactly what I was looking for. As I mentioned in #432 it would be nice to collect these kinds of customizations some place. Should we keep these issues open until then, or just close them as they are resolved? (also depending on if we want to implement an official, documented solution for any of them, of course).

**Comment by kimroen** [comment]
For this particular case, some of these things are documented in the README:

https://github.com/cerebris/jsonapi-resources#finders
and
https://github.com/cerebris/jsonapi-resources#applying-filters

So the thing to figure out here regarding documentation is probably how to make it more obvious that doing this is possible given the independently documented pieces. The solution to that might be to give examples of specific use cases in something like a wiki.

**Comment by lgebhardt** [comment]
Let's leave this open until we get the Wiki setup. It seems having some pages on common use cases would be best way to go.

**Comment by lgebhardt** [comment]
Ok, I've started a wiki and added a recipe for [this](https://github.com/cerebris/jsonapi-resources/wiki/Filter-on-joined-table). Feel free to make corrections and add new content to the wiki. I'm going to close this now, but feel free to reopen if needed.
