### ISSUE TITLE
Integrate with kaminari or will_paginate

### ISSUE THREAD

**Issue by xdmx** [JSONAPI-Resources/jsonapi-resources#45]
I find this project the best one to implement the json api under a rails project.

The only thing I really miss is some kind of pagination integration (I know that it's still not in the json api spec, sadly), anyway, it'd be very useful some kind of integration with kaminari or will_paginate, with the ability to pass the page and page size to return.

It'd be awesome to also support different page size for included resources and to have some kind of config for a max_size (to block requests for 100000 items)

I guess this will be a placeholder until json-api/json-api#236 gets resolved

**Comment by lgebhardt** [comment]
Yes pagination is a big missing feature. I plan on implementing pagination, however I've been holding off until the details are resolved in json-api.

I'm not sure about paginating related resources. This seems like a thorny problem that potentially has serious performance issues for the way JR is implemented (and I think has to be implemented to support nested includes). I've been thinking we would have a configurable cap on the number of related records. Once that is exceeded I'm not sure how the code should behave.

**Comment by whatthewhat** [comment]
@lgebhardt @xdmx do you think [providing access to the Active Record relation](https://github.com/cerebris/jsonapi-resources/pull/46) could be a good option in the meanwhile?

**Comment by xdmx** [comment]
I'm not sure about the pagination, since it'd also require to return some data in the response/body.

For sure it's very useful to set a context on resources like: find all orders for the current user (it'd be very bad if it returns all orders from all users!), without having to rewrite the find method (I'm still new to JS, I don't know if there is already a better way, that seems the one suggested in the readme)

**Comment by whatthewhat** [comment]
I thought I saw a way to specify the response `meta` key (where the pagination data could be), but I can't find it now..

**Comment by lgebhardt** [comment]
Is this it? http://jsonapi.org/extending/

**Comment by whatthewhat** [comment]
Oh, I meant specifying `meta` with jsonapi-resources gem, but I don't think it can be done right now.

**Comment by lgebhardt** [comment]
No, jsonapi-resources doesn't yet use the meta tag.

**Comment by lgebhardt** [comment]
> do you think providing access to the Active Record relation could be a good option in the meanwhile?

@whatthewhat I like the solution you're proposing. Not only will it make implementing pagination cleaner, but it also simplifies overriding the find logic (for most apps).

**Comment by whatthewhat** [comment]
@lgebhardt Great! I'll update the PR when I'll have some spare time.

It does not however completely resolve this issue, the pagination data would need to be added to the response somehow..

**Comment by lgebhardt** [comment]
Thanks. Understood about it not adding pagination. But it does give a single place to manipulate the Arel. So when we get to pagination we'll have a clean way of adding it.

**Comment by 7h3kk1d** [comment]
I could really use this feature and can help if needed.

**Comment by 7h3kk1d** [comment]
I've gotten a paginated sample using the [api-pagination](https://github.com/davidcelis/api-pagination) gem to achieve link headers. It would be nice to be able to use a mixin or something instead of overwriting the index fully as well as an alternative for the filter hack (maybe a extra params option?). 

Controller:

``` ruby
def index
    resources = paginate (resource_klass.find(resource_klass.verify_filters(@request.filters, context),
                                context: context, sort_params: @request.sort_params)), per_page: 10
    render json: JSONAPI::ResourceSerializer.new(resource_klass).serialize_to_hash(resources,
                                include: @request.include,
                                fields: @request.fields,
                                attribute_formatters: attribute_formatters,
                                key_formatter: key_formatter)
end
```

Resource:

``` ruby
filter :page
def self.apply_filter(records, filter, value)
  case filter
    when :page
      records
    else
      return super(records, filter, value)
  end
end
```

**Comment by lgebhardt** [comment]
@7h3kk1d, I'm starting to look at pagination today. At this point I'm thinking the system will support multiple pagination systems, with the option to define a default paginator and each resource can override this with a different paginator. The idea being that as a resource evolves, over several supported versions, there may be a desire to switch pagination styles.

A paginator will be involved in parsing the request parameters, as well as contributing to the Arel relations used to build up the result set. Thus there won't be a need to override the index method.

I'm hoping to create several default paginators, and allow the creation of others in individual projects.

Of course all of this is subject to change. I'm open to any suggestions.

I'm starting the work in the jsonapi_rc2 branch, since I believe that will be released before I get the pagination complete. I'll post a note here when I get an initial version pushed, hopefully in a day or two.

**Comment by 7h3kk1d** [comment]
@lgebhardt Yeah that sounds good. It's similar to how activemodel serializer handles serializers. It would be nice for the paginator  to also be able to modify the link headers and/or response hash to give pagination data. Are you looking at any sort of change that would introduce the meta attribute?

If you need anything just let me know.

**Comment by lgebhardt** [comment]
@7h3kk1d I plan on having the paginator produce the required links. The location and format will conform to the updated spec.

I do need some help in defining what the default types of pagination should be. At this point I have a rough idea that we will support "paged", "offset", and possibly "cursored" styles. But I'm not sure on the full set of details of how each of these will work. So any help on defining paginators would be most appreciated.

**Comment by 7h3kk1d** [comment]
Does the spec actually outline pagination?

Default should probably be no pagination. Cursor/limitoffset/paged would be the 3 most common I think. Should also probably give custom cursor names for either timestamps or ids.

**Comment by lgebhardt** [comment]
I've pushed some changes to https://github.com/cerebris/jsonapi-resources/tree/jsonapi_rc2 that start the pagination work. There are currently two very similar paginators, offset and paged. Paged is really a specialized version of the offset, so they are very similar. No docs yet, but they'll added soon. And the default is no pagination.

**Comment by xdmx** [comment]
Is there any plan on adding the cursor pagination?

I ask because in the readme there is `# built in paginators are :none, :offset, :cursor, :paged`, but it's the only part in the repo where it mentions the cursor paging, in the code there is only offset and paged

**Comment by john-griffin** [comment]
@xdmx it is possible to write [custom paginators](https://github.com/cerebris/jsonapi-resources#custom-paginators) that live outside of core JR. However I have been digging into this and believe to implement cursor based pagination the current sort context will need to be available inside the paginator, which it currently isn't.

@lgebhardt shall I go ahead and submit a PR for passing the `order_options` to pagination classes?
