### ISSUE TITLE
Unable to autoload constant Engine in LinkBuilder#build_engine_name

### ISSUE THREAD

**Issue by nsarno** [JSONAPI-Resources/jsonapi-resources#450]
Hi guys,

The line **58** from `link_builder.rb` gives the following error (`Unable to autoload constant Engine`) when used with another gem containing an `engine.rb` file.

``` ruby
 "#{ scopes.first.to_s.camelize }::Engine".safe_constantize
```

To reproduce this issue:
- clone [duboff/peeps](https://github.com/duboff/peeps)
- run the server
- visit [/api/contacts](http://localhost:3000/api/contacts)

[This issue was first opened on this repo](https://github.com/nsarno/knock/issues/5), but I think it should actually be fixed here as this could happen with any rails engine having a  file named `engine.rb`.

In this case, the autoloader expect `lib/knock/engine.rb` to define an `Engine` constant, even though by convention it is namespaced as `Knock::Engine`.

Somehow I feel like this is actually a weird behaviour from the autoloader, but maybe it would still be good to add a rescue here anyway or something like this.

If you think there is actually something wrong in my code, don't hesitate to reopen the issue on my side and letting me know what you think.

Cheers!

**Comment by christophermlne** [comment]
why is this issue closed? what was the resolution?

**Comment by lgebhardt** [comment]
@christophermlne This issue is still open. It was the issue in the nsarno/knock project that is closed.

**Comment by christophermlne** [comment]
my bad.

**Comment by aldesantis** [comment]
Has this been fixed? Is there a workaround of any kind?

**Comment by nsarno** [comment]
I'm not aware of anything yet. I'll try and see if I can submit a PR here in the coming weeks.

**Comment by aldesantis** [comment]
A workaround for the time being is to create an initializer containing:

``` ruby
module JSONAPI
  class LinkBuilder
    private

    def build_engine_name
      scopes = module_scopes_from_class(primary_resource_klass)

      unless scopes.empty?
        begin
          "#{ scopes.first.to_s.camelize }::Engine".safe_constantize
        rescue LoadError => e
        end
      end
    end
  end
end
```

**Comment by johnmosesman** [comment]
I ran into the same issue with:

```
rails 5.0.0.1
jsonapi-resources 0.8.1
knock 2.0
```

The fix by @alessandro1997 above worked.

**Comment by gnfisher** [comment]
This is an autoloader issue. The Rails guide [covers it here](http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-algorithms). There may be another way to check if the controller is from an Engine or not without relying on LoadError to be thrown (going to look into this) but as the code stands, just wrapping this in a begin/rescue to catch it should be fine. If the controller is part of an engine, the proper engine paths and urls are formatted, and if not, the expected LoadError from the Rails autoloader is caught and non engine paths and urls are formatted. 

Should I look for an alternative way to handle the Engine check? Or is the fix by @alessandro1997 okay to be put into a PR?

**Comment by hoverlover** [comment]
It would be nice if someone maintaining this project would attempt to address this issue.  I don't like the idea of a monkey patch long term.  1 1/2 years is a long time for this not to be at least acknowledged by the maintainers.

**Comment by lgebhardt** [comment]
@hoverlover I'll see what I can do, but it's a relatively low priority for me since I don't use engines and I'm not sure how to demonstrate the issue off the top of my head. Any help such as a failing test in a PR would be appreciated.

**Comment by tindron** [comment]
This issue is with knock and not jsonapi-resources so it should be closed here.  It can be reproduced without jsonapi-resources.

**Comment by sebasjimenez10** [comment]
Just confirmed what @tindron said the issue is on the `knock` side. 👍
