### ISSUE TITLE
Mailing list / chat

### ISSUE THREAD

**Issue by beechnut** [JSONAPI-Resources/jsonapi-resources#453]
**EDIT**
So, I posted a nice long issue description here, only to read over my issue and realize I just needed a rubber duck.

Is there a mailing list or chat channel for this gem, so we (a.k.a. "I") can not rely on issues for questions?

Thanks!

**Comment by abargnesi** [comment]
+1

I've seen a lot of folks set up [gitter.im](https://gitter.im) for simple chat functionality. You can do at-mentions as well as reference issue numbers for the associated project.

**Comment by lgebhardt** [comment]
I've just set up a [gitter.im chat](https://gitter.im/cerebris/jsonapi-resources) for the project. The links now at the top of the readme.
