### ISSUE TITLE
Resource#records_for README outdated?

### ISSUE THREAD

**Issue by gniquil** [JSONAPI-Resources/jsonapi-resources#455]
In the readme, in the relevant sections for `records_for`, it is indicated:

``` javascript
class PostResource < JSONAPI::Resource
  has_one :author
  has_many :comments

  # def record_for_author(options = {})
  #   records_for("author", options)
  # end

  # def records_for_comments(options = {})
  #   records_for("comments", options)
  # end
end
```

There's the options argument. By as of 0.5.9, `options` is not passed in (always get {}). however, if one only needs access to `context`, it can be accessed directly.

**Comment by lgebhardt** [comment]
You are correct. This method should have the options removed (and the docs updated) since they aren't used. I've issued #456 to clean this up.

**Comment by gniquil** [comment]
:+1:
