### ISSUE TITLE
Relationships with underscore on the name

### ISSUE THREAD

**Issue by danielbm** [JSONAPI-Resources/jsonapi-resources#463]
Hi,

I have a has_many relationship named "inverse_friends" on my code. When I try to GET it, the server responds with:

```
"No route matches [GET] "/users/25/relationships/inverse_friends"
```

Executing `rake routes`, I discovered that this endpoint was described as:

```
GET       /users/:user_id/relationships/inverse-friends(.:format)
```

The underscore was replaced for a dash. I searched the JSON API documentation, and could not find any rule about this behaviour. Is this expected? Or is it a bug?

Thank you!

Daniel

**Comment by lgebhardt** [comment]
By default the routes are formatted as dasherized. You can change this in the [configuration](https://github.com/cerebris/jsonapi-resources#configuration) by creating an initializer to set an alternate route format.

**Comment by danielbm** [comment]
Ok! Thanks!

**Comment by lgebhardt** [comment]
I should add that JSON API is officially agnostic on the format of the routes and keys, but does [recommend dasherized](http://jsonapi.org/recommendations/), so that's why we set that as our default.
