### ISSUE TITLE
Render an array of POROs

### ISSUE THREAD

**Issue by simonedamico** [JSONAPI-Resources/jsonapi-resources#467]
Hello,
I'm trying to render an array of plain ruby object (no AR model), 
how do I approach the problem with jsonapi-resources.
I saw that on the global level you can set a custom operation processor, 
how do I do that for a single resource?

**Comment by lgebhardt** [comment]
You can set the OperationsProcessor on a per controller basis by overriding the 'create_operations_processor' method on your controller.
