### ISSUE TITLE
[Question] It's possible to use this lib outside of rails? (sinatra, lotus, ...)

### ISSUE THREAD

**Issue by ziggurat** [JSONAPI-Resources/jsonapi-resources#471]
[Question] It's possible to use this lib outside of rails? (sinatra, lotus, ...)

How big is the effort to use this outside rails? Do you recommend it?

Thanks!

**Comment by lgebhardt** [comment]
I have never tried to use it outside of rails. My guess is it's going to take a lot of work to pull that off since it's pretty heavily based on Rails.
