### ISSUE TITLE
Make acts_as_resource_controller's base_url method be compatible with custom Rails config.relative_url_root

### ISSUE THREAD

**Issue by masda70** [JSONAPI-Resources/jsonapi-resources#473]
Right now, if the Rails app uses a custom `relative_url_root`, the JSONAPI link builder will use the wrong base url to build its links.

In my own app, I set for instance `config.relative_url_root = '/api'`, and this change broke my app. I had to override the ResourceController's `base_url` method to fix this.

``` ruby
  def base_url
    @base_url ||= request.protocol + request.host_with_port + self.config.relative_url_root
  end
```

`lib/jsonapi/acts_as_resource_controller.rb` could use something like that as new default.

**Comment by hlogmans** [comment]
self.config.relative_url_root can be nil, and then the + will throw an error. First check for nil.

**Comment by iirving** [comment]
:+1: I'm seeing this as well, in that a show method, customized as per the example,  in a JSONAPI::ResourceController creates a json with relative url's missing the protocol and the host_with_port; whereas the default jsons have full absolute urls.
