### ISSUE TITLE
Param not allowed on nested route

### ISSUE THREAD

**Issue by jimmybaker** [JSONAPI-Resources/jsonapi-resources#474]
I have a nested resource `/api/v1/companies/1/brands`. When trying to create a brand using that endpoint I would like the new brand's company id to be 1 obviously. By default this doesn't happen so I thought I would need to add a relationship to the data key but that gives me "Param not allowed"

Here's what I'm posting:

```
{ 
    "data": {
        "type": "brands",
        "attributes": {
            "name": "Goofy Co"
        },
        "relationships": {
            "company": {
                "data": { "type": "companies", "id": "1" }
            }
        }
    }
}
```

It seems like this is the hard way of doing it. Is there a better way?

**Comment by lgebhardt** [comment]
This library doesn't support adding a new resource through the relationship endpoint. 

I'm not sure if the JSON-API spec supports this. In my reading it seems ambiguous on whether you can POST to the relationship url and expect the server to create the new resource and whether it would need the relationship to be inferred (and enforced to match the url). @dgeb do you have any input on this?

**Comment by jimmybaker** [comment]
@lgebhardt Thanks for the reply. Most of the resources in my app are scoped to a company. Some aren't but most are. This isn't a huge deal for me as I was planning on using this library for the next revision of my api anyway. I just wasn't clear on the specs.

I might have to setup additional validations in the backend if everything has to be created in a non-nested manner though. Take a SalesOrder, for example. A SalesOrder belongs to a company and a customer. A customer also must belong to a company. This means that I could post a new SalesOrder which links to a customer that belongs to a different company than the sales order. Get what I mean?

**Comment by jimmybaker** [comment]
I also still get the same error when posting to a non-nested endpoint /api/v1/brands (no company nesting)

**Comment by jrnk** [comment]
Did you forget to define `has_one :company` on the BrandResource by chance?

**Comment by jbschrades** [comment]
I ran into this problem and found it confusing as a Rails developer.  @jrnk is right, you need to define `has_one :company` on the BrandResource even though the brand belongs_to a company in Rails speak.

**Comment by idengager** [comment]
> This library doesn't support adding a new resource through the relationship endpoint.

@lgebhardt Is this still true? 

JSONAPI supports these kinds of requests: http://jsonapi.org/format/#crud-updating-relationships I've been trying to get them working on v0.9.0 and I'm still getting `Param not allowed`. If it can't be done, it would be cool to see it mentioned as a limitation somewhere in the docs.
