### ISSUE TITLE
Attribute named model renders the actual AR model

### ISSUE THREAD

**Issue by jimmybaker** [JSONAPI-Resources/jsonapi-resources#480]
![2015-10-06 at 1 24 am](https://cloud.githubusercontent.com/assets/50668/10301549/0e5b7802-6bc9-11e5-91bf-317ab16eb40f.png)

Is this a bug? If not, how do I get around this without renaming this attribute?

**Comment by lgebhardt** [comment]
Yes, this is a bug. It'll be a day or so before I can look into a solution.

**Comment by lgebhardt** [comment]
I'm changing my stance that this is a bug. I forgot we had reserved the attribute name of `model` but only emit a warning, not explicitly prohibiting the method. We should probably look at renaming the internal attribute named `model` to allow it to be used as an attribute. Until that happens I'm not sure there's a great workaround.

**Comment by ggordon** [comment]
I can look into this, I need it for my app.

**Comment by lgebhardt** [comment]
Thanks again @ggordon

**Comment by ggordon** [comment]
You're welcome.
