### ISSUE TITLE
JSONAPI: Could not find resource 'api/v1/accounts'. (Class Api::V1::AccountResource not found) (NameError)

### ISSUE THREAD

**Issue by DrSayre** [JSONAPI-Resources/jsonapi-resources#481]
This is my resources/api/v1/account.rb file

```
module Api
  module V1
    # app/resources/account_resource.rb
    class AccountResource < JSONAPI::Resource
      has_one :user
      has_many :groups
    end
  end
end
```

This is my routes.rb file:

```
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      jsonapi_resources :accounts
      jsonapi_resources :users
    end
  end
end
```

When ever I try to generate a new controller or do rake routes I get `Could not find resource` error.

**Comment by lgebhardt** [comment]
That all looks right to me. Do you have a resource setup for both users and groups? Check if they are named correctly.

**Comment by DrSayre** [comment]
Looks like it works now.  I guess I had one of the files with the wrong class name.  Awesome job on this project!
