### ISSUE TITLE
Support for sorting by relationship attributes

### ISSUE THREAD

**Issue by ghost** [JSONAPI-Resources/jsonapi-resources#490]
Seems like this isn't supported right now.

The spec says:

> Note: It is recommended that dot-separated (U+002E FULL-STOP, ".") sort fields be used to request sorting based upon relationship attributes. For example, a sort field of author.name could be used to request that the primary data be sorted based upon the name attribute of the author relationship.

Will see if I can whip up a PR.

**Comment by davidgoli** [comment]
:+1: also for filtering

**Comment by aldhsu** [comment]
Closed by #494
