### ISSUE TITLE
Why does :type show a NAME COLLISION?

### ISSUE THREAD

**Issue by nathanpalmer** [JSONAPI-Resources/jsonapi-resources#491]
If our models have a property called type it shows this `NAME COLLISION` error. However since the properties for a model go under attribute it shouldn't conflict with the jsonapi spec (and also seems to be serializing properly in my tests.)

``` ruby
def check_reserved_attribute_name(name)
  # Allow :id since it can be used to specify the format. Since it is a method on the base Resource
  # an attribute method won't be created for it.
  if [:type, :href, :links, :model].include?(name.to_sym)
    warn "[NAME COLLISION] `#{name}` is a reserved key in #{@@resource_types[_type]}."
  end
end 
```

**Comment by dgeb** [comment]
It's not jsonapi-compliant to allow `type` attributes. See http://jsonapi.org/format/#document-resource-object-fields

The rationale is that attributes, relationships, `type`, and `id` all occupy the same namespace. There are situations in which they are addressed as part of this single namespace such as sorting, filtering, and specifying sparse fieldsets.

With that said, that list is old and should probably be revised to include just `type`.

**Comment by nathanpalmer** [comment]
Ok, I was hoping it wasn't that way (we'll need to rename our attributes.) Thanks for the info.
