### ISSUE TITLE
@model attributes are not populated in before_create

### ISSUE THREAD

**Issue by atistler** [JSONAPI-Resources/jsonapi-resources#493]
One would expect that in a before_create callback, the @model's attributes would be set, however they are not.  Is this expected behavior?

**Comment by lgebhardt** [comment]
It is expected behavior. The model's attributes are set as part of the `replace_fields` method which fires the `*_replace_fields` events. So the attributes on the model are first available in `after_replace_fields`.

**Comment by achan** [comment]
Is it expected that I'd lose the attribute changes I make in before_create?

https://github.com/openmcac/basechurch/pull/51

Moving my changes into a `before_replace_fields` callback fixed it seemed to do the trick, but I'd much rather only perform these changes when creating / updating.

**Comment by jagthedrummer** [comment]
Is there a way to do something like this?

```
after_replace_fields :do_something, :on => :create
```

For background, I need to check for ownership on a related record before allowing a new resource to be created. I've tried `before_create`, but at that step the model doesn't have any data set for me to check against.

**Comment by krainboltgreene** [comment]
Sadly `before_replace_fields` happens *after* model validations for some reason.

**Comment by tommy-russoniello** [comment]
For anyone referencing this later
- Replace fields callbacks are only fired for create and update actions
- What @jagthedrummer referenced can be achieved by adding a check that the model is already persisted to the callback method (e.g., `return if @model.persisted?`). You could also put the request type in the context in your controller and reference that.

**Comment by elCorsaiR** [comment]
The issue is closed. So now attributes are populate in before_create?
