### ISSUE TITLE
Booleans serialized to string

### ISSUE THREAD

**Issue by wvteijlingen** [JSONAPI-Resources/jsonapi-resources#50]
I have a custom attribute in my model that returns a boolean. These are always serialized into either "false" or "true" instead of true boolean values.

Am I missing something or is this a bug?

**Comment by lgebhardt** [comment]
You're not missing anything. That's a deficiency in the `DefaultValueFormatter`. It should detect booleans and output true or false without quotes.

This will fix the boolean issue.

``` ruby
class DefaultValueFormatter < JSONAPI::ValueFormatter
  class << self
    def format(raw_value, context)
      case raw_value
        when String, Integer
          return raw_value
        else
          if !!raw_value == raw_value #Boolean
            raw_value
          else
            return raw_value.to_s
          end
      end
    end
  end
end
```

But I should also get some logic in there for some other types as well, e.g. floating point numbers. I'll see if I can get a fix done in the next few days. If you need it sooner you could create your own ValueFormatter that handles it like I have above (or override DefaultValueFormatter) temporarily.

**Comment by wvteijlingen** [comment]
Thanks for the workaround. Is there any reason for not just always returning `raw_value` or a switch like this? I my quick testing, it seems always returning `raw_value` generates correct JSON.

``` ruby
case raw_value
  when NilClass, String, Integer, Fixnum, Float, TrueClass, FalseClass
    return raw_value
  else
    return raw_value.to_s
  end
```

Also, specifying a custom formatter in `default_attribute_options` doesn't seem to work. I can only get it to work when I set a custom formatter per attribute.

**Comment by lgebhardt** [comment]
@wvteijlingen, I didn't know about testing for a boolean using the `TrueClass` and `FalseClass`, so that's a definite improvement. As far as just returning raw_value, I think that would be ideal. However there are some issues with how JR serializes floating points (and possibly other types). Currently the code serializes floating point numbers as strings. I'll need to add a fix for that. Once I do I suspect we can get to just returning raw_value for all.

I'll look into the `default_attribute_options` issue.

**Comment by tadast** [comment]
Just to add to this issue: Hash and Array type values are also serialised incorrectly :) 

Would it be difficult to just use JSON.dump by default? And then the attribute serialization could be custmized by overriding the method on the Resource class

**Comment by dgeb** [comment]
@lgebhardt this can be closed now, right?

**Comment by lgebhardt** [comment]
Yes, I think this is all set. Please reopen it if that is not the case.

**Comment by lgebhardt** [comment]
@tadast, could you please open a new issue if Hash and Array types are not being serialized correctly.

**Comment by kevinmtrowbridge** [comment]
> specifying a custom formatter in default_attribute_options doesn't seem to work

I also am having trouble getting this to work, today.  I can't seem to override the `default_attribute_options` method and, a bit confused as to why.  I will update if I figure it out.

**Comment by kevinmtrowbridge** [comment]
My apologies -- it was just my own error -- when you override `default_attribute_options` you must use a class method:

```
def self.default_attribute_options
  {format: :my_default}
end
```

It might be worth updating the documentation to include that little `self.` -- took me about 20m to figure that out just now!

**Comment by lgebhardt** [comment]
@kevinmtrowbridge Thanks for pointing that out.
