### ISSUE TITLE
Underlying validation error messages lost if save fails in an after_save block

### ISSUE THREAD

**Issue by theirishpenguin** [JSONAPI-Resources/jsonapi-resources#504]
Not best practice but it is possible to have validation errors set in an ActiveRecord after_save block raising an ActiveRecord::RecordInvalid exception - as outlined at http://tech.taskrabbit.com/blog/2013/05/23/rollback-after-save. A conventional rails web application will correctly handle this and display the correct errors on the UI.

However, when using jsonapi-resources this does not happen because jsonapi-resources assumes that if `@model.save` is false then it is not worth polling the object for errors. The code is here...

https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource.rb#L148

**Comment by theirishpenguin** [comment]
Potential solution... https://github.com/cerebris/jsonapi-resources/pull/505/files

**Comment by vrybas** [comment]
@theirishpenguin fixed by #505 ?

**Comment by theirishpenguin** [comment]
Indeed it is, closing now. Thanks @vrybas
