### ISSUE TITLE
Grandchildren of same type not serialized in `included`

### ISSUE THREAD

**Issue by thedeeno** [JSONAPI-Resources/jsonapi-resources#506]
Suppose I have the following model:

```
paystub: has-many deductions, has-many earnings
deduction: has-one category
earning: has-one category
```

And in my `paystub_resource_controller` I override `setup_request` to the following:

```
def setup_request
  params["include"] = "earnings,earnings.category,deductions,deductions.category"
  super
end
```

When I request the `paystub` resource rails will correctly query the tables:

```
Paystub LOAD
Deduction LOAD
Earning LOAD
Category LOAD
Category LOAD
```

But `jsonapi-resources` only serializes the results of the first `Category LOAD` into the `included` segment of the payload. The rest of the categories are left in the ether.

I can see that this is probably an edge case, but I'm not sure the best place to hook into to support this.

Thoughts?

**Comment by lgebhardt** [comment]
Do the included earnings and deductions both have the correct relationship to category? I assume so, but if they don't that's another clue. What do your resources look like?

Also the include path should only need the most specific part as the intermediate resources should also be included. For example:

``` ruby
  params["include"] = "earnings.category,deductions.category"
  super
end
```

I don't however think that's related to your problem, but it's possible.

**Comment by thedeeno** [comment]
Below are my resource definitions.

Thanks for the tip about params["include"] including the intermediates. The intermediates _are_ still included with the simplified array you provided, but my problem with the grandchildren categories remains (as you expected).

```
class CategoryResource < JSONAPI::Resource
  attribute :name

  has_many :paystub_deductions
  has_many :paystub_earnings
end

class PaystubDeductionResource < JSONAPI::Resource
  attribute :amount
  attribute :ytd_amount

  has_one :paystub
  has_one :category
end

class PaystubEarningResource < JSONAPI::Resource
  attribute :units
  attribute :amount
  attribute :ytd_amount

  has_one :paystub
  has_one :category
end

class PaystubResource < JSONAPI::Resource
  attribute :created_on
  attribute :period_start_on
  attribute :period_end_on
  attribute :rate
  attribute :net

  has_many :deductions, class_name: 'PaystubDeduction'
  has_many :earnings, class_name: 'PaystubEarning'

  def self.records(options={})
    options[:context].current_business_unit.paystubs
  end
end
```

**Comment by thedeeno** [comment]
I've confirmed that `@included_objects` inside [`ResourceSerializer#seriazlie_to_hash`](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource_serializer.rb#L41) doesn't include all the expected categories.

The `include_directives` look correct though:

```
#<JSONAPI::IncludeDirectives:0x007fa6dd920500
 @include_directives_hash={
  :include_related=>{
    :deductions=>{
      :include=>true,
      :include_related=>{ :category=>{:include=>true, :include_related=>{}}}
    },
     :earnings=>{ 
      :include=>true,
      :include_related=>{:category=>{:include=>true, :include_related=>{}}}}
    }
}>
```

So if there's a bug it looks like it's coming from:

[`process_primary(source, @include_directives.include_directives)`](process_primary%28source, @include_directives.include_directives%29)

**Comment by lgebhardt** [comment]
@thedeeno It's sure looking like it's a bug. I'll see if I can reproduce it.

**Comment by thedeeno** [comment]
@lgebhardt I've dove really deep and everything looks to be working well in `jsonapi-resources`. I'm closing this. I suspect the issue is coming from somewhere else in my application. I'll reopen if I end up back in `jsonapi-resources`'s source.

Thanks for the help and sanity check!
