### ISSUE TITLE
Set paginator for Resource created by hand

### ISSUE THREAD

**Issue by selaromi** [JSONAPI-Resources/jsonapi-resources#516]
Hello everyone, just a quick question here. I'm creating a list of resources by using Resource Serializer in the following way:

```
    visible_leagues =  League.find_custom
    visible_leagues.each do |league|
      leagues_array.push LeagueResource.new(league)
    end

    render json: JSONAPI::ResourceSerializer.new(
      LeagueResource
      ).serialize_to_hash(
               leagues_array
     ), status: :ok
```

The situation is the following: I want to add pagination directly inside the controller. And then add the links to the rendered json. I can do it manually with merge! but I wanted to ask if there's a way to do it via jsonapi-resources.

Thank you very much! Great great lib!

**Comment by lgebhardt** [comment]
The `ResponseDocument` is what calls the serializer and also generates the pagination links. It uses `merge!` to combine the two. I guess the way to do it by way of the jsonapi-resources would be to create your own custom `Paginator` (if needed) and then use a `ResponseDocument` to put it all together. You would need to pass your `leagues_array` into the `ResponseDocument` as an `OperationsResult`. If your really don't need any of that overhead I'd say your proposed way would be more efficient.
