### ISSUE TITLE
Using an UUID filed as the ID of r a resource creates error when fetching 

### ISSUE THREAD

**Issue by AlyBadawy** [JSONAPI-Resources/jsonapi-resources#519]
When using a resource that uses `uuid` as the id instead of incremental integer, the following error is generated when trying

```
GET /resource/:id
    {
  "errors": [
    {
      "title": "Invalid field value",
      "detail": "3db209cc-eada-4bbf-a54d-81f4c6587a54 is not a valid value for id.",
      "id": null,
      "href": null,
      "code": 103,
      "source": null,
      "links": null,
      "status": "400"
    }
  ]
}
```

while using GET /resource shows the exact correct link in the response:

```
    {
  "data": [
    {
      "id": "3db209cc-eada-4bbf-a54d-81f4c6587a54",
      "type": "users",
      "links": {
        "self": "http://localhost:3000/v1/users/3db209cc-eada-4bbf-a54d-81f4c6587a54"
      },
      "attributes": {
        "name": "aly",
        "email-address": "me@alybadawy.com"
      }
    }
  ],
  "meta": {
    "record-count": 1
  },
  "links": {
    "first": "http://localhost:3000/v1/users?page%5Blimit%5D=50&page%5Boffset%5D=0",
    "last": "http://localhost:3000/v1/users?page%5Blimit%5D=50&page%5Boffset%5D=0"
  }
}
```

**Comment by lgebhardt** [comment]
Are you setting the `key_type` globally or per resource? https://github.com/cerebris/jsonapi-resources#primary-key

**Comment by AlyBadawy** [comment]
@lgebhardt Actually, I didn't know I should set the key_type.
I only had the primary key6 set to `uuid` in the table migration. I will try this tonight and will let you know if this should fix the error.

But thanks in advance :+1:  :smile:

**Comment by AlyBadawy** [comment]
Yes. this worked. Thanks a lot.
And P.S: if using doorkeeper gem for authentication and the user_id is a :uuid, make sure to change that in the doorkeeper migration to reflect this on resource_owner_id (it took me 40 mins to find why my tests were failing :smile: )

**Comment by campgurus** [comment]
just in case anyone still looking for this: https://jsonapi-resources.com/v0.10/guide/resources.html#Primary-Key
