### ISSUE TITLE
Custom filter with callable

### ISSUE THREAD

**Issue by iamvery** [JSONAPI-Resources/jsonapi-resources#526]
# What?

Currently in order to define a custom filter, you must override `self.apply_filter` on the resource and switch over the `filter` being applied.

``` ruby
def self.apply_filter(records, filter, value, options)
  case filter
  when :custom
    records.custom(value)
  else
    super(records, filter, value, options)
  end
end
```

This style of overriding methods for custom functionality is admittedly proliferate in this lib, but I might find it more idiomatic (in a Ruby and Ruby on Rails sense) to specify a callable at the point the filter is defined to state the strategy for filtering.
# How?

The interface I imagine would be similar to ActiveRecord's `scope` class method. Here are a few options:

As a second argument...

``` ruby
filter :custom, ->(records, value) { records.custom(value) }
```

As an option...

``` ruby
filter :custom, with: -> (records, value) { records.custom(value) }
```

As a block...

``` ruby
filter :custom { |records, value| records.custom(value) }
```
# Why?

There are a number of reasons this strikes me as an improvement over the current style.
1. The filtering strategy is defined at the same time as the filter itself. They're "close" visually in context.
2. It takes considerable less lines to express the behavior.
3. It removes the need to switch over filter types.
4. It (possibly) removes the need entirely for overriding the `apply_filter` method.

Do you think this would be a useful addition the library?
If so, which style would be preferred?

**Comment by lgebhardt** [comment]
@iamvery Yes, I think this would be a very nice addition to the library. I like the simplicity of the first, but the second option would be preferable as it leaves more room for expansion without changing the method signature. One expansion might be to have both an `apply` and a `verify` lambda for each filter. That could get rid of the `verify_custom_filter` and `verify_relationship_filter` methods (or at least allow us to deprecate them).

**Comment by iamvery** [comment]
I've opened a PR for this #537. I haven't used the filter verification myself, so I may need help understanding how/why one might do that. I've found a couple cases in the test suite, so I'll try to take a closer look.

I'm closing this issue in favor of the PR. We can continue discussion there :+1:
