### ISSUE TITLE
Could not find resource - Class not found (working on local machine but not when deployed)

### ISSUE THREAD

**Issue by halorium** [JSONAPI-Resources/jsonapi-resources#527]
I am at a loss on this one. I have everything working on my local machine but when I try to deploy via Docker to a VM I get the following error.

`
'resource_for': JSONAPI: Could not find resource 'api/v1/categories'. (Class Api::V1::CategoryResource not found) (NameError)
`

My structure is as follows:
- app
  - controllers
    - Api
      - V1
        - categories_controller.rb
  - models
    - Api
      - V1
        - category.rb
  - resources
    - Api
      - V1
        - category_resource.rb

Category Resource:

``` Ruby
module Api
  module V1
    class CategoryResource < JSONAPI::Resource
      model_name "Api::V1::Category"
      # ...
    end
  end
end
```

Routes as follows:

``` Ruby
  namespace :api do
    namespace :v1, defaults: { format: 'json' } do
      jsonapi_resources :categories, except: [:create, :destroy, :update]
    end
  end
```

I appreciate any help in figuring out what is going on between local machine and deployed version

**Comment by lgebhardt** [comment]
Everything looks right at first glance, and the fact that it works on your dev system seems to confirm that.  So I'll ask an obvious question first: are you sure the resources are being deployed and are readable by the server? How is the app being added to the docker container - linked volume, copied, etc?

**Comment by halorium** [comment]
I finally figured this out. I am new to deployment and made the silly mistake of using snake case in my directory naming as you can see above.
I changed it to lowercase as follows:
- app
  - controllers
    - api
      - v1
        - categories_controller.rb
  - models
    - api
      - v1
        - category.rb
  - resources
    - api
      - v1
        - category_resource.rb

All is working in a Linux environment now.
I didn't realize the difference between OSX and Linux regarding OSX ignoring case.
