### ISSUE TITLE
Filters on associations

### ISSUE THREAD

**Issue by johantell** [JSONAPI-Resources/jsonapi-resources#546]
Is there a way to use filters on associations?

I'm stranded in a place where I'd like to include associated records like this:

`/books?include=authors,authors.books&filter=[authors.books.that_my_friends_like_from_the_same_author]` 

If there isn't a way to use make this happen with filters, does anybody have another idea of how i can make it happen?

**Comment by lgebhardt** [comment]
In the master branch there is a new way of filtering using the `:apply` callable on the filter. Using that you could do:

``` ruby
 class BookResource < JSONAPI::Resource
  filter :that_my_friends_like_from_the_same_author, apply: ->(records, value, _options) {
    # records.where(friends like this author)
}
end

```

You'll need to provide the actual ActiveResource functions to perform the filtering.

**Comment by raycchan** [comment]
@mintcore did you figure out a solution? The one @lgebhardt mentioned did not work for me
