### ISSUE TITLE
Can't remove a resource that doesn't have an `id`

### ISSUE THREAD

**Issue by benjyhirsch** [JSONAPI-Resources/jsonapi-resources#548]
It seems like `require`-ing an `id` parameter (9655a9a0095e45069a41e059abe0bf17a3c36b0e) makes it impossible to remove resources at urls generated by the `jsonapi_resource` (singular) route helper, which don't have an `id` parameter. For instance if you wanted a client to be able to log out by sending a `DELETE` request to `/session`--does that violate the JSONAPI spec in some way that I don't understand?

**Comment by jpkeane** [comment]
My understanding from the API Spec is that the Deletion must happen on a specific resource. When deleting to the collection name it, it is assuming you would be using the 'Bulk Extension' - but even then you must specify IDs.

**Comment by beechnut** [comment]
`DELETE /session` without an ID isn't referencing a resource. There is no way for the server to know which session you are trying to delete.

@benjyhirsch: I would recommend using the [Gitter chat](https://gitter.im/cerebris/jsonapi-resources) to ask questions like this in the future.

**Comment by vrybas** [comment]
@benjyhirsch please close
