### ISSUE TITLE
Rails autoloading (development code reload) doesn't work for resources

### ISSUE THREAD

**Issue by SimonKaluza** [JSONAPI-Resources/jsonapi-resources#551]
Resources instantiated and cached for retrieval by `JSONAPI::Resource::resource_for` (such as any used by subclasses of `JSONAPI::ResourceController`) will not be reloaded by Rails autoloading when they are modified, as the `@@resource_types` class variable holds on to the stale Resource subclass object.

**Comment by SimonKaluza** [comment]
https://github.com/cerebris/jsonapi-resources/pull/552 implements a naive fix to this, which basically re-instantiates the resource each time `Resource::resource_for` is called in the Rails development environment (only using the caching when `Rails::configuration.cache_classes` is true).

**Comment by chamnap** [comment]
:+1:
