### ISSUE TITLE
Related resources in resource data node through roles

### ISSUE THREAD

**Issue by PoslinskiNet** [JSONAPI-Resources/jsonapi-resources#553]
Hi,

I would like to add related resources for specific resource.

For example users have many projects. Client app requires to fetch this data, as typical related objects (many-to-many) relation. Because system permits access through roles (via rolify) & I couldn't find the way how to do it without "included" (I wish to have it in relationships).

Does anyone did it or have any idea how to achieve it easily?

Best option I think, would be to use method in resource and put it into relationships.

Thanks in advance for any help.

**Comment by Exelord** [comment]
+1

**Comment by PoslinskiNet** [comment]
I think we have found a solution with @Exelord 

```
# app/models/user.rb
has_many :accounts, through: :roles, class_name: 'Account', source: 'resource', source_type: 'Account'
```

Enjoy!

**Comment by vrybas** [comment]
@PoslinskiNet close this issue?

**Comment by PoslinskiNet** [comment]
@vrybas yes :+1:
