### ISSUE TITLE
How to specify host for links?

### ISSUE THREAD

**Issue by brandonparsons** [JSONAPI-Resources/jsonapi-resources#558]
Hi there,

I'm trying to use a slightly different setup in my development environment, and need to tell JSONAPI-Resources to use a specific host in the links attributes that it returns, rather than the host that rails is currently bound to.

Is this possible?

**Comment by lgebhardt** [comment]
The LinkBuilder is responsible for generating the links. If you override the `base_url` method on your controller it should flow down to the LinkBuilder. Note that all links being serialized will use this `base_url`, so that may create issues depending on your requirements.

Here's the default:

``` ruby
    def base_url
      @base_url ||= request.protocol + request.host_with_port
    end
```

**Comment by brandonparsons** [comment]
Thanks @lgebhardt , I'll give that a shot!
