### ISSUE TITLE
Stepping outside the box with transactions

### ISSUE THREAD

**Issue by halorium** [JSONAPI-Resources/jsonapi-resources#562]
I unfortunately need to create a user in the user table and store a password in a user_auth table.

This needs to happen in the UserController#create method and should be transactional so it all happens or nothing happens just like if my password was in my user table and I was simply creating a user.

I'm having a hard time digging through the code to see where I should be customizing for this functionality.

Thank you for your help in advance.

**Comment by lgebhardt** [comment]
Two options:
1) Use a callback on the model such as `after_save` and update the second table. It should all run in a transaction, and you could raise an exception which would trigger the rollback in the OperationsProcessor and return an appropriate error response.

2) To do it all with resources you could add a second operation. Unfortunately there's not yet a good way to create extra operations.  I'm planning to rework this section of code to allow more flexibility for this sort of thing.

To work around this I think you could modify a copy of `process_request` and use it to override your controller action. In there add a second operation to `@request`. It's a hack, but should work.

I'd try option 1 first.

**Comment by halorium** [comment]
@lgebhardt How do I handle the extra fields on the model / resource? If the user table doesn't have a password_digest field and the user model doesn't implement has_secure_password for example then how can I tell the user resource to accept password and password_confirmation fields but then split them out of the params before save and use them to update the second table etc. This would all normally happen in the controller create method and before_create action, etc.

**Comment by lgebhardt** [comment]
This might work. Declare the attributes on the resource and implement setters on the model that store the values in instance variables on the model. They would then be available for you to use in your callbacks, but wouldn't be stored in the model's table.

**Comment by patrickgordon** [comment]
Hey @lgebhardt and @boobooninja, in regards to this would it be possible to do something like this?

``` ruby
...

around_create :handle_update_auth

def handle_update_auth
  ActiveRecord::Base.transaction do
    yield
    # your code to update auth_table here
  end
end

...
```

**Comment by tommy-russoniello** [comment]
For anyone referencing this later, what @patrickgordon mentioned works (I have done it before). The only tricky part is: when using a database that does not support nested transactions (such as MySQL), you will have to prevent JR from wrapping the whole operation in a transaction otherwise the one you define in the callback will do nothing.

One way to do this is to override `process_operations` in your base controller to call a new `transactional?` method to determine if it should wrap the operation in a transaction. Then you can define this method on any controllers where you need to do this e.g.,

```ruby
class SomeController < ApplicationController
  def transactional?
    context[:action] != :create
  end
end
```
