### ISSUE TITLE
How to access the resource (model object) in a controller callback?

### ISSUE THREAD

**Issue by apraditya** [JSONAPI-Resources/jsonapi-resources#563]
Let's say I want to increase the view count of a Post object in the controller below

```
class PostsController < ApplicationController
  include JSONAPI::ActsAsResourceController
  after_action  :increment_counter,         only: :show

  private

  def increment_counter
    # ???
  end
end
```

How do I access the model? I did a workaround on `@request` object like this:

```
  def json_api_resource
    operation_results = create_operations_processor.process(@request)
    resource_operation_result = operation_results.results.first
    resource_operation_result.try(:resource)
  end

  def resource
    json_api_resource.try(:model)
  end
```

But it breaks on 0.6.2. I know there's a callback on the OperationsProcessor, but on the README it's like for every resource, not on the individual resource level.

**Comment by aldhsu** [comment]
You should have access to the model as an instance variable `@model`. You can see the docs use it under attributes.

**Comment by lgebhardt** [comment]
If you create an `after_show_operation` callback on a custom OperationsProcessor you will be able to access the `@result`, which will have the found resource as a member called `@resource`.

``` ruby
class CountingActiveRecordOperationsProcessor < ActiveRecordOperationsProcessor
  after_show_operation do
    #Do some counting related to 
    #@result.resource._model
  end
end
```

**Comment by apraditya** [comment]
If I'm reading it correctly, that's `JSONAPI::Resource` object. The
question is inside the controller.

**Comment by apraditya** [comment]
Does that occur on every controller? How do I set this custom
`OperationsProcessor` to run the callback only to a certain controller?

**Comment by lgebhardt** [comment]
Yes, it's a global callback for the OperationsProcessor. You could simply check the `@operation.resource_klass`. The operations are abstracted away from the controller, so if you really need to track per controller access to a resource this won't work.

**Comment by vrybas** [comment]
@apraditya, you can hook in before rendering like this

``` ruby
class PostsController < ActionController::Base
  include JSONAPI::ActsAsResourceController

  def show
    define_singleton_method(:render_results) do |operation_results|
      result = operation_results.results[0]
      increment_counter(result.resource._model) if result.code == :ok
      super(operation_results)
    end

    super
  end
end
```

**Comment by vrybas** [comment]
@apraditya (if you have no more questions, please close the issue)

**Comment by apraditya** [comment]
Not bad. I'll use that for now. Thanks @vrybas

**Comment by greyblake** [comment]
Another way to dig to the model is:

```ruby
@operation_results.results.first.resource._model
```
