### ISSUE TITLE
access the model.errors serializer

### ISSUE THREAD

**Issue by drhenner** [JSONAPI-Resources/jsonapi-resources#567]
Pre-apologize I assume I missed something but want to do something like this

```
def create
   comment = current_user.comments.new(params)
   if comment.save
     comment_json = JSONAPI::ResourceSerializer.new(Api::External::CommentResource).serialize_to_hash(Api::External::CommentResource.new(comment, nil))
     render json: comment_json
  else
    comment_json = JSONAPI::ResourceSerializer.new(Api::External::CommentResource).serialize_to_hash(Api::External::CommentResource.new(comment, nil))
    render json: comment_json.errors
  end
```

I am having 2 issues. 

1) `comment = current_user.comments.new(params)` isn't easy without overriding the default create in the controller.  (I have no problem overriding the controller if I can solve question 2)

2) I don't know how to get the JSONAPI Error formatting from the gem.  

```
{"errors":[{"title":"is required","detail":"user_id - is required","id":null,"href":null,"code":100,"source":{"pointer":"/data/attributes/user_id"},"links":null,"status":"422"},{"title":"is required","detail":"status - is required","id":null,"href":null,"code":100,"source":{"pointer":"/data/attributes/status"},"links":null,"status":"422"}]}

```

**Comment by lgebhardt** [comment]
I hope I haven't misunderstood your question. Try leaving the default controller create method alone. You should rarely need to override the controller methods, and this seems to be a common point of confusion.

Make sure you set the context to hold the current user in the controller. One option is to override the `create` method on the `CommentResource`:

``` ruby
class CommentResource < JSONAPI::Resource
  def self.create(context)
    new(context[:current_user].comments.new
  end

  def creatable_fields(_context = nil)
    super - [:user]
  end
end
```

I think that would fill in the user_id for you from the current user. The rest of the params will be filled in later as part of the normal operation of the gem. I would also make sure the user isn't a creatable field so it can only be set from the context.

**Comment by drhenner** [comment]
I think you answered the correct question but I'm not sure why it isn't working.  I get a 500 error in my tests.  I guess I should test this manually.  rspec isn't giving me anything to go off of for debugging.  

I haven't found any documentation for having `def self.create(context)` am I missing it someplace?  If not I'll do a wiki page or PR once I figure out what is going wrong.

I'll take a longer look in the morning.

Thanks

**Comment by drhenner** [comment]
I think I found the issue.  My example above was just a simplified example.  the real case I have:

```
module Api
  module External
    class TeamsController < Api::External::BaseController
    end
  end
end
```

But Team is really the Company model in Active Record:

```
class Api::External::TeamResource < JSONAPI::Resource
  model_name 'Company'
  attributes :name, :slug

  def self.create(context)
     context[:current_firm].companies.new
  end
end
```

Hence now in `jsonapi/operation.rb` I get the following:

```
[201, 210] in /Users/davidhenner/.rvm/gems/ruby-2.1.2@backops/gems/jsonapi-resources-0.6.2/lib/jsonapi/operation.rb
   201:     end
   202: 
   203:     def apply
   204:       resource = @resource_klass.create(@context)
   205:       byebug
=> 206:       result = resource.replace_fields(@data)
   207: 
   208:       return JSONAPI::ResourceOperationResult.new((result == :completed ? :created : :accepted), resource)
   209: 
   210:     rescue JSONAPI::Exceptions::Error => e
(byebug) @data
{:attributes=>{:name=>"test 123", :slug=>"ejejejej123123"}, :to_one=>{}, :to_many=>{}}
(byebug) resource
#<Company:0x007fa308787708>
(byebug) resource.class
Company
(byebug) @resource_klass
Api::External::TeamResource
```

NOTE: I believe `resource.class` should be `Api::External::TeamResource`

Is there an easy work around?  I'm going to try 

```
class Team < Company
end
```

Then remove `model_name 'Company'` from `Api::External::TeamResource`

**Comment by lgebhardt** [comment]
Looks like you are on 0.6.2. The 0.7.0 release fixed some issues with model and resource names.

**Comment by drhenner** [comment]
Upgraded.  
NOTE: I like the detailed error response.  AWESOME

I found my issue.  

```
   # I thought this typo
   new(context[:current_user].comments.new
   # was suppose to be 
   new(context[:current_user].comments.new)
  # but was really suppose to be
  new(context[:current_user].comments.new, nil)
```

Thanks for all your prompt responses.  I can't speak highly enough.  :) I'd like to do a PR into the readme or create a wiki page on this use-case.  Do you have a preference for adding to the readme vs wiki?

FYI: this was the actual code I eventually used.

```
class Api::External::TeamResource < JSONAPI::Resource
  model_name 'Company'
  attributes :name, :slug

  def self.create(context)
    Api::External::TeamResource.new(context[:current_firm].companies.new(status: Company::ACTIVE), nil)
  end
end
```

**Comment by lgebhardt** [comment]
@drhenner Glad it's all working. I think it would probably be best in the Wiki. And we should probably add a section to the Readme noting there are examples of specialized use cases in the wiki.
