### ISSUE TITLE
Exception whitelist not working in 0.7.0, but is fine on 0.6.2

### ISSUE THREAD

**Issue by ioagel** [JSONAPI-Resources/jsonapi-resources#569]
I have a compound 3 field unique index in postgresql, that raises PG::UniqueViolation which is properly translated to ActiveRecord::RecordNotUnique.

Using config.exception_class_whitelist = [ActiveRecord::RecordNotUnique] in 0.6.2, i can properly handle it in the controller with 'rescue_from'.
However in 0.7.0 i get 500 internal server error, indicating that is handled internally bypassing the whitelist in the initializer.

**Comment by brandonparsons** [comment]
I am getting an issue that might be related.

I raise custom errors inside resource classes to check some information that can only be processed with knowledge of the current user, e.g.:

``` ruby
before_remove :verify_parent_can_remove_parent_listing

    private

    def verify_parent_can_remove_parent_listing
      unless context[:current_parent].can_destroy_parent?
        raise CustomError::Unprocessable.new(
          "At least one parent is required.",
          title: "Insufficient parents"
        )
      end
    end
```

I am catching this custom exception (`CustomError::Unprocessable`) elsewhere and it works just fine. The only place this isn't working is when I try to raise the error from the resource.

I think this may have had spotty support over the last few versions of JR (I have gotten intermittent test failures in the past), but it isn't currently working for me on 0.7.0. Am I doing something wrong?

/cc @barelyknown

**Comment by barelyknown** [comment]
I'm not able to look at it now, but take a look at this commit, https://github.com/cerebris/jsonapi-resources/commit/4a02b3734eb4568a9fca7f4ab8c47d95f29c4d47.

It might be the culprit.

**Comment by ioagel** [comment]
Yep, thats the problem...
By reverting the changes in this commit https://github.com/cerebris/jsonapi-resources/commit/4a02b3734eb4568a9fca7f4ab8c47d95f29c4d47, exception whitelisting works again.
