### ISSUE TITLE
limit result set

### ISSUE THREAD

**Issue by brancusi** [JSONAPI-Resources/jsonapi-resources#570]
Hi, wondering what the best approach would be for the client to query the following:
1. Sort by `field`
2. Limit to `n` records

Thanks

**Comment by johantell** [comment]
have you tried `page[size]=n` ?

**Comment by lgebhardt** [comment]
Enable the paged paginator (https://github.com/cerebris/jsonapi-resources#pagination) and specify the page size. Use the sort option for the field.

**Comment by brancusi** [comment]
worked!
