### ISSUE TITLE
Rails 5.0.0.beta-1 Support

### ISSUE THREAD

**Issue by makabde** [JSONAPI-Resources/jsonapi-resources#575]
With the first beta of Rails 5 out; I am wondering what are the steps to take in order to use this gem with a new Rails 5 app in api mode.

When trying to generate a resource, I am facing the following error:

```
/Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'jsonapi-resources'. (Bundler::GemRequireError)
```

**Comment by quinn** [comment]
dup of #466 ?
