### ISSUE TITLE
@model in resource hook is inaccurate

### ISSUE THREAD

**Issue by alexlafroscia** [JSONAPI-Resources/jsonapi-resources#576]
I'm a little new to rails, and especially this gem, but I'm trying to add some custom validation that ensures that a `List` can only be updated by it's `owner`, which is a `User` object.  I've created some test data, a `List` object with a particular owner, and a `current_user` that is a different user.  I implemented a `before_update` hook in the resource that attempts to lookup `@model.owner` and compare it to `context[:current_user]`. 

This part all works fine, but for some very strange reason, `@model.owner` is appearing _as_ the current user, despite the fact that this is not the way that the `List` object was constructed.  By this, i mean that `@model.owner == context[:current_user]` despite the fact that there's no code anywhere that might be setting that to be true.  If I overwrite the controller's `update` method and look up the model's owner from there, it returns the correct user.  Any ideas what might be happening?

**Comment by barelyknown** [comment]
Is `context[:current_user]` nil?

**Comment by alexlafroscia** [comment]
No, they were both a `User` model object (and the same one, at that)
