### ISSUE TITLE
Devise - current_user

### ISSUE THREAD

**Issue by brancusi** [JSONAPI-Resources/jsonapi-resources#580]
Hi,

Trying to access the current_user as described in the docs in the the finder section:

``` ruby
 def self.records(options = {})
    context = options[:context]
    context[:current_user].posts
  end
```

For some reason though, context is empty of both the controller and the current_user.

Tried the solutions from #458 but I am still unable to access current_user.

Any ideas?

**Comment by alexeyShumakov** [comment]
you can create custom ApiController 

``` ruby
class ApiController < ApplicationController
  include JSONAPI::ActsAsResourceController
  def context
    { current_user: current_user }
  end
end
```

after extend your Api controller

``` ruby
class Api::PostsController < ApiController
end
```

now you can get current_user from context
it work nice for me.

**Comment by brancusi** [comment]
Thanks @alexeyShumakov, I will try right away. For some reason I thought the context object was auto created by JR. Makes sense that it wouldn't be now that you shared this.

Thank you

**Comment by brancusi** [comment]
Worked!
