### ISSUE TITLE
Error code should be a string

### ISSUE THREAD

**Issue by greyblake** [JSONAPI-Resources/jsonapi-resources#582]
First at all, thanks for the nice gem! It does extremally huge work! And really easy to use! 

I've discovered that errors codes are returned as strings, but according to [JSONAPI specification](http://jsonapi.org/format/#errors), as I understood they should be strings.

> code: an application-specific error code, expressed as a string value.

 E.g. instead of `100` should be returned `"100"`. 

Do I understoond it right?

Thanks in advance!

**Comment by beechnut** [comment]
I'm seeing that as well. :+1: When I inspect my response body during an error, I see:

``` json
{"errors":[{"title":"can't be blank","detail":"user - can't be blank","id":null,"href":null,"code":100,"source":{"pointer":"/data/attributes/user"},"links":null,"status":"422","meta":null}]}
```

Specifically, `"code": 100`, when it should be `"code": "100"`.
