### ISSUE TITLE
Rename property/attribute in resource

### ISSUE THREAD

**Issue by greyblake** [JSONAPI-Resources/jsonapi-resources#585]
Let's say I have model User with attribute `login`.

``` ruby
class User < ActiveRecord::Base
  attr_accessor :login
end
```

Is it possible to remap this `login` attribute to `username` in resource, so API consumer use `username` instead of login?

Something like this:

``` ruby
class UserResource < JSONAPI::Resource
  attribute :username, map: :login
end
```

Thanks !

**Comment by andrewtimberlake** [comment]
You can use a method like this:

``` ruby
class UserResource < JSONAPI::Resource
  attribute :username

  def username
    @model.login
  end
end
```

**Comment by greyblake** [comment]
@andrewtimberlake Thanks! But will it work with search/filtering ?

**Comment by greyblake** [comment]
I asked this question at StackOverflow: http://stackoverflow.com/questions/34659691/how-to-rename-property-attribute-of-resource-with-jsonapi-resources-ruby-gem/

The best work around seems to be to use `alias_attribute` at model level:

``` ruby
class User < ActiveRecord::Base
  attr_accessor :login

  alias_attribute :username, :login
end

class UserResource < JSONAPI::Resource
  attribute :username
end
```

**Comment by beechnut** [comment]
@greyblake Is this solved? If so, would you close the issue?

**Comment by greyblake** [comment]
@beechnut I've found the work around. Thanks)
