### ISSUE TITLE
Require jsonapi/resource_controller in main file?

### ISSUE THREAD

**Issue by barelyknown** [JSONAPI-Resources/jsonapi-resources#59]
`jsonapi/resource_controller` is not required in the main, but it feels like it should be. How do you feel about making that change?

**Comment by lgebhardt** [comment]
@barelyknown I think that makes sense. But I'd like to get `active_record_operations_processor` out of the required list for `jsonapi/resource_controller` at the same time. Ideally JR would be agnostic on the choice of ORM. As it is now it's closely tied to ActiveRecord. I think that's the reason I left `jsonapi/resource_controller` out.

**Comment by barelyknown** [comment]
OK. Maybe wait until it's agnostic to make that change then. It's not a big deal to require it in the controller, but I just wanted to make things easier for new users.

**Comment by lgebhardt** [comment]
I agree that it would make things easier for new users. I hope to get back to the ORM issue (#51) soon.

**Comment by barelyknown** [comment]
Closing this for now.
