### ISSUE TITLE
Inclusion of Related Resources (include params) on POST/PATCH requests

### ISSUE THREAD

**Issue by thibaudgg** [JSONAPI-Resources/jsonapi-resources#607]
At the end of [Inclusion of Related Resources](http://jsonapi.org/format/#fetching-includes) JSONAPI spec section it's mentioned:

> Note: This section applies to any endpoint that responds with primary data, regardless of the request type. For instance, a server could support the inclusion of related resources along with a POST request to create a resource or relationship.

In the current JR implementation, I think that only [FindOperation](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/operation.rb#L22) and [ShowOperation](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/operation.rb#L75) support the `include` params. Correct?

Would it make sense to add support on other endpoints?

If have the case where we want to create an object and get related resources in the response. Something like: `POST /articles?include=author.articles` (create an article and get all existing articles from the same author).

Am I getting the spec wrong?

**Comment by valscion** [comment]
Actually, the case is that JR already supports using `include` in POST/PATCH requests, too. I am able to confirm that from the current (ce94ced08c3f) master version, and on v0.7.0, too. https://github.com/venuu/jsonapi-authorization even authorizes such includes properly. `master` version of JR has a bug, I think, in where it doesn't pass the `params[:include_directives]` properly downstream to processors. See https://github.com/venuu/jsonapi-authorization/pull/24#issuecomment-229958455 for more details if you're interested — I'm gonna open up a new issue here for this particular case, though, and try to fix it.
