### ISSUE TITLE
Disable association updates

### ISSUE THREAD

**Issue by lcpriest** [JSONAPI-Resources/jsonapi-resources#608]
In a `Resource` class, is there a way to disable setting of relationships other than just using the updatable_fields method?

I read the docs on relationships and saw no option to be passed in, just wanted to check if I missed something. An example would be a CommentResource.

It has a body, belongs_to a task and to an author. The author is set automatically by a context[:current_user] and the task_id is set on create, so the author_id should not be `settable` in any case and the task_id should not be `settable` on update.

If it is just updatable_fields, that is totally fine, just looking for some clarification.

**Comment by lcpriest** [comment]
Is there an API to make a relationship immutable, or writable_on: :create or similar?

**Comment by lgebhardt** [comment]
Just the `updatable_fields` and limiting the routes that are created. It's an idea I've considered but haven't pursued.

**Comment by lcpriest** [comment]
Cool, thanks for the clarification!
