### ISSUE TITLE
Make hook available to authorize resource?

### ISSUE THREAD

**Issue by barelyknown** [JSONAPI-Resources/jsonapi-resources#62]
I'd like to authorize resources using an approach like the convention followed by [`pundit`](https://github.com/elabs/pundit). Here's what a typical controller action would look like (from the `pundit` documentation).

``` ruby
def update
  @post = Post.find(params[:id])
  authorize @post
  if @post.update(post_params)
    redirect_to @post
  else
    render :edit
  end
end
```

First you get the resource, then authorize it (which raises an exception if it fails), and then proceed.

For the index action, `pundit` provides the concept of a "scope" which gets the set of resources that the user has access to.

``` ruby
def index
  @posts = policy_scope(Post)
end
```

Anyhow, I don't see a straight forward way to hook into the controller methods since so much happens in the `process_request_operations` method. I think that it would be great for it to yield the resources so that they could be authorized in the middle of that method's execution.

What do you think?

**Comment by lgebhardt** [comment]
@barelyknown In my code we're using the `before_operation` method on a custom OperationsProcessor to add a callback:

``` ruby
require 'jsonapi/operations_processor'

class CustomOperationsProcessor < JSONAPI::ActiveRecordOperationsProcessor

  def before_operation(context, operation)
    operation.resource_klass.approve_operation(context, operation)
  end
end
```

We then derive all of our resources from an intermediate `BaseResource` that implements the `approve_operation` method.

We initially had a before_save callback implemented in almost exactly the same way #63 does, but I pulled it in favor of the `before_operation` on the `OperationsProcessor`. One reason is it's anticipated that users will override the `save` method and may inadvertently break the callback. Another is I thought having access to the full operation details gave more power to the callback.

Would this type of approach work for you?

**Comment by barelyknown** [comment]
I didn't even notice that option! Serves me right for not waiting to hear back from you on the issue.

The problem that I see is that I need to build the records to authorize the action. But, the records are built inside of the `apply` method. So, I like the `before_operation` approach, but it feels like we need a similar idea inserted between when we build the records and when we take the action.

As an example, here's `CreateResourceOperation#apply`:

``` ruby
def apply(context)
  resource = @resource_klass.create(context)
  # The resource isn't available until right here,
  # after the `before_operation` method is called.
  resource.replace_fields(@values)
  resource.save(context)

  return JSONAPI::OperationResult.new(:created, resource)

  rescue JSONAPI::Exceptions::Error => e
    return JSONAPI::OperationResult.new(e.errors[0].code, nil, e.errors)
  end
end
```

**Comment by lgebhardt** [comment]
I see. We could put the `before_save` and `after_save` callbacks in place and have them called from the `apply` method, like this:

``` ruby
def apply(context)
  resource = @resource_klass.create(context)
  resource.replace_fields(@values)

  resource.before_save(context)
  resource.save(context)
  resource.after_save(context)

  return JSONAPI::OperationResult.new(:created, resource)

  rescue JSONAPI::Exceptions::Error => e
    return JSONAPI::OperationResult.new(e.errors[0].code, nil, e.errors)
  end
end
```

That way you could choose the appropriate place for the call back, either on the operation or the resource. And users could override `save` on the resource without disabling the callbacks.

**Comment by barelyknown** [comment]
That seems right. Want me to make that adjustment?

**Comment by lgebhardt** [comment]
To be complete we should probably also have callbacks for `before_remove` and `after_remove`. 

And the `CreateHasManyAssociationOperation` and `RemoveHasManyAssociationOperation` don't call `save`, but it feels like maybe we should have a callback for those.

I also wonder if we want to include any additional meta information, like which operation is making the `save` call, or even the operation itself.

Before you make any changes I'd like to get @dgeb's opinion on this.

**Comment by dgeb** [comment]
I've been talking with @lgebhardt and we are leaning towards making actions such as `replace_fields` more discrete on the resources themselves by having them internally call `save` (instead of having the operations processor call `replace_fields` _then_ `save`).

@barelyknown what is your use case for a callback between replacing fields and saving the record? If you're looking for a general authentication callback, `save` is probably not a good trigger, since it is not called for every operation.

**Comment by barelyknown** [comment]
I didn't want a callback between `replace_fields` and `save`. I wanted one between getting the resource and `save`. The use case is authorizing that the action can be taken on the resource by the user. I am using [`pundit`](https://github.com/elabs/pundit) to manage authorization.

**Comment by lgebhardt** [comment]
Sorry, I misunderstood what the issue was. It makes a lot more sense now.

**Comment by lgebhardt** [comment]
I'm going to start a branch for calling the `save` method from the resource. That will let us move the origination of any callbacks into the resource.

@dgeb and I talked about changing the operations processor callbacks to use the Rails callback chain pattern. This should be cleaner than the way it currently is. I'll also rework the operations processor callbacks in this branch.

We still need to decide which, if any, callbacks the resource will support by default.

**Comment by dgeb** [comment]
Thanks for the clarification. I was thrown by the location of @lgebhardt's `before_save` hook in his code snippet above:

```
  resource = @resource_klass.create(context)
  resource.replace_fields(@values)

  resource.before_save(context)
  resource.save(context)
  resource.after_save(context)
```

I'd prefer that `save` be called from within the call to `replace_fields`. Sounds like that won't be an issue for you, as long as you have a chance to authorize the operation before it's invoked.

**Comment by dgeb** [comment]
(whoops - my reply above was sent before seeing either of @lgebhardt's replies)

**Comment by barelyknown** [comment]
Let me know if you need a hand with it.

**Comment by lgebhardt** [comment]
@barelyknown, if you want to help that would be great. Are you up for reworking the `OperationsProcessor` callbacks?

Ideally they would use ActiveSupport::Callbacks (http://apidock.com/rails/ActiveSupport/Callbacks). For example my custom operations processor above would become:

``` ruby
class CustomOperationsProcessor < JSONAPI::ActiveRecordOperationsProcessor
  set_callback :apply, :before, :approve_operation
  #or
  before_apply :approve_operation

  def approve_operation(context, operation)
    operation.resource_klass.approve_operation(context, operation)
  end
end
```

**Comment by barelyknown** [comment]
How are you imagining the callback would have access to the resources that had been loaded by the operation?

**Comment by lgebhardt** [comment]
Sorry, I'm thinking we would be adding callbacks to the resource. And I'd want the callbacks on the operations processor to work the same way. I'll add them to resource for now and we can see if we like it. Then we can change the operations processor to match the style.

**Comment by barelyknown** [comment]
Oh, right. I just didn't read carefully. So, the resource would just use its `@model`. That makes sense.

**Comment by barelyknown** [comment]
I actually did come across the need for the callback between `replace_fields` and `save` this morning. The use case required authorization to check if the user had permission to save the record in its updated form.

**Comment by lgebhardt** [comment]
@barelyknown, https://github.com/cerebris/jsonapi-resources/pull/65 adds callbacks to all the methods called by the operations processor as well as to the save method and a general create and update callback.

**Comment by barelyknown** [comment]
Wow, that was fast. Thanks so much.

It looks like `save` includes `create` and `update`, and `remove` is not included in `save`. That's correct? 

If you're not already working on it, I'd be happy to document it for the README. Should I?

**Comment by lgebhardt** [comment]
@barelyknown I can't believe I forgot the readme again. I guess I really hate documentation. If you're up for the task I'd definitely appreciate it.

The `save` method is not called by every operation, only those that directly change the model. The `save` callbacks are only fired when the `save` method is called. I'm not sure if that answers your question, or if the `save` callbacks will fully work for your purpose.

**Comment by barelyknown** [comment]
Really great work. It only took 10 minutes to swap in your branch.

For what it's worth, the design allowed me to handle authorization on every action in a really nice way.

``` ruby
module V1
  class BaseResource < JSONAPI::Resource
    [:create, :update, :remove].each do |action|
      set_callback action, :before, :authorize
    end
    # ...
  end
end
```

**Comment by barelyknown** [comment]
I'll document the feature in the README now.
