### ISSUE TITLE
How to customize an error's attributes?

### ISSUE THREAD

**Issue by johnnncodes** [JSONAPI-Resources/jsonapi-resources#620]
I have a League and Sport model:

```
class League < ActiveRecord::Base
  belongs_to :sport

  validates :name, presence: true
  validates :sport_id, presence: true

  # validate that sport exists in the db
  validates :sport, :presence => { :message => "Sport doesn't exist." }
end

class Sport < ActiveRecord::Base
  has_many :leagues

  validates :name, presence: true
end
```

The valid request to create a league should be:
`POST /leagues`

```
{
  "data": {
    "type": "leagues",
    "attributes": {
      "name": "Test league"
    },
    "relationships": {
      "sport": {
        "data": {
          "type": "sports",
          "id": "31"
        }
      }
    }
  }
}
```

If I don't provide a sport id when creating a league:
`POST /leagues`

```
{
  "data": {
    "type": "leagues",
    "attributes": {
      "name": "Test league"
    }
  }
}
```

I'm getting this validation error:

```

{
    "errors": [
        {
            "title": "can't be blank",
            "detail": "sport-id - can't be blank",
            "id": null,
            "href": null,
            "code": 100,
            "source": {
                "pointer": "/data/attributes/sport-id"
            },
            "links": null,
            "status": "422",
            "meta": null
        }
    ]
}
```

How can I change the `pointer`? I think it should be `/date/relationships/sport/data/id` instead of `/data/attributes/sport-id`

**Comment by lgebhardt** [comment]
That seems to be a bug. The system is supposed to return `/data/relationships/sport` in this case.

**Comment by johnnncodes** [comment]
@lgebhardt Hmm. Maybe. Is there a way to customize it while waiting for a fix?

**Comment by lgebhardt** [comment]
@basco-johnkevin looking a little closer I think you should change the `validates :sport_id, presence: true` to `validates :sport, presence: true` See http://guides.rubyonrails.org/active_record_validations.html#presence and check out the `order` example.

**Comment by johnnncodes** [comment]
@lgebhardt I already have that validation. The problem if I only use that is when the sport doesn't exist in the database, this will be the error:

```
{
    "errors": [
        {
            "title": "can't be blank",
            "detail": "sport - can't be blank",
            "id": null,
            "href": null,
            "code": 100,
            "source": {
                "pointer": "/data/relationships/sport"
            },
            "links": null,
            "status": "422",
            "meta": null
        }
    ]
}
```

Which I think should only happen when the payload when creating a league doesn't provide a sport id.

So what I did is to use these two:

```
 # validate that sport id is present
  validates :sport_id, presence: true

  # validate that sport exists in the db
  validates :sport, :presence => { :message => "Sport doesn't exist." }
```

Then I guess I should also add an if in the sport validator so it will only run when sport id is present.

But the issue that I discussed is still present:

```

{
    "errors": [
        {
            "title": "can't be blank",
            "detail": "sport-id - can't be blank",
            "id": null,
            "href": null,
            "code": 100,
            "source": {
                "pointer": "/data/attributes/sport-id"
            },
            "links": null,
            "status": "422",
            "meta": null
        }
    ]
}
```

I need to change the `pointer`

**Comment by lgebhardt** [comment]
@basco-johnkevin sorry, I missed that you had both validations in there. The reason you are getting the wrong pointer message is the simple way the pointer is calculated: https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/exceptions.rb#L393-L401 `sport-id` isn't a relationship so it's assumed to be an attribute. You could monkey patch this code to get it working. I'll consider how to best handle this.

You could also try a custom validator and put the error on the relationship. Such as (note: untested code):

``` ruby
class SportValidator < ActiveModel::Validator
  def validate(record)
    if record.sport_id.blank?
      record.errors.add :sport, "can't be blank"
    else
      # check if sport is accessible in the db to the current user and if not add other validation error
    end
  end
end

class League < ActiveRecord::Base
  belongs_to :sport

  validates :name, presence: true

  # validate that sport exists in the db and sport_id is not nil
  validates_with SportValidator
end
```

**Comment by johnnncodes** [comment]
@lgebhardt - Thank you! Tried your suggestion above and I'm now able to return this error when the sport doesn't exist in the database:

```
{
    "errors": [
        {
            "title": "doesn't exist",
            "detail": "sport - doesn't exist",
            "id": null,
            "href": null,
            "code": 100,
            "source": {
                "pointer": "/data/relationships/sport"
            },
            "links": null,
            "status": "422",
            "meta": null
        }
    ]
}
```
