### ISSUE TITLE
Mixing authorization errors and validation errors

### ISSUE THREAD

**Issue by johnnncodes** [JSONAPI-Resources/jsonapi-resources#623]
I have a league, team and user resource. Teams belong to a league and a league belongs to a user. When creating a team, I need to validate that the league being assocatiated with the team is owned by the current authenticated user. Name and league is also required.

If an API client executes this request (let's say that the authenticated user is not the owner of the league):

`POST /teams`

```
{
  "data": {
    "type": "teams",
    "attributes": {
      "name": ""
    },
    "relationships": {
      "league": {
        "data": {
          "type": "leagues",
          "id": "1"
        }
      }
    }
  }
}
```

I think the API needs to respond with a 400 status code and an array of authorization and validation errors like this:

```
HTTP/1.1 400 Bad Request
Content-Type: application/vnd.api+json

{
  "errors": [
    {
      "status": "403",
      "source": { "pointer": "/data/relationships/league" },
      "detail": "you're not the owner of that league."
    },
    {
      "status": "422",
      "source": { "pointer": "/data/attributes/name" },
      "detail": "name is required."
    }
  ]
}
```

Reference - http://jsonapi.org/examples/#error-objects-multiple-errors

Is this currently possible when using jsonapi-resources library?

**Comment by lgebhardt** [comment]
It's possible, but maybe not out of the box. If you authenticate the league as part of the request setup it wouldn't perform the validation of the name. So you wouldn't get both errors in the response. 

However both could be considered validation errors so it should be possible to respond with both errors ( though I think they would both be 422). You would create a custom validator for the team that checks ownership of the league. That in turn would require access to the context so you would need to get that into the model, which could be done using a gem such as https://github.com/steveklabnik/request_store.

I'm sure there are other options as well.

**Comment by lgebhardt** [comment]
What I wrote above should work, but an even easier way might be to override the `_save` method on the team resource. You could authenticate the league and add the error if needed. Then still allow the system to run through the other validations.

**Comment by johnnncodes** [comment]
@igebhardt Thank a lot! :) I'll try your suggestions.

Are you guys planning to support this out of the box?

**Comment by lgebhardt** [comment]
We don't have any plans to change this behavior, but we're open to suggestions. I'm just not sure one size fits all.
