### ISSUE TITLE
A double quote in a filter value causes crash

### ISSUE THREAD

**Issue by theirishpenguin** [JSONAPI-Resources/jsonapi-resources#628]
Because the filter verification attempts to CSV parse the value (even if it is not a legal CSV string) it crashes upon being supplied a double quote.

The problem has been added as an integration test case in a PR https://github.com/cerebris/jsonapi-resources/pull/629/files

... which can be run using...

```
bundle exec rake test TEST=test/integration/requests/request_test.rb TESTOPTS="--name=test_filter_with_value_containing_double_quote -v"
```

A potential solution has also been supplied in that PR - rescuing the resulting "Malformed CSV" error. Rescuing is less desirable than checking for the validity of the CSV string upfront but AFAIK the latter is not possible. If the added code fails to parse the CSV then it simply treats it as a scalar value.

One thing this workaround does not handle is presence of multiple comma delimited double quotes in the filter value, eg.

```
filter_value = '",","'
```

I don't have a full understanding of the requirements for comma delimited arguments supplied to jsonapi-resources in a filter - do they need to be valid CSV or is this just how jsonapi-resources implements a comma delimited filter value?  I may have completely misunderstood the rules on jsonapi filter values.

Also the added test case only asserts that the server does not blow up when supplied a double quote as an argument. A better test case to actually retrieve a resource with a double quote in the filtered attribute would be required if this approach is in the right direction.

**Comment by lgebhardt** [comment]
The spec leaves it up to the implementation as to how to process the filters. 

I'd like to consider some alternatives instead of handling the exception and then reverting to treating it as a string. We could have a setting for how to treat id based filters and other filters. By default the ids would use CSV and regular filters would be strings or hashes. We could allow this to be set per filter as well. I'll try to get something together soon.

**Comment by theirishpenguin** [comment]
Sounds good. I agree with your initial thinking about treating id based filters and regular filters differently.

**Comment by NuckChorris** [comment]
Was progress ever made on this, or is there a known workaround?  This is really frustrating our fulltext search, since users love to use double quotes in searches...

**Comment by lgebhardt** [comment]
@NuckChorris Could you please try out  #937. It's against master, but there aren't too many differences with beta.
