### ISSUE TITLE
Support for non-ActiveRecord (related) resources

### ISSUE THREAD

**Issue by digitalcora** [JSONAPI-Resources/jsonapi-resources#630]
Related to #561.

Suppose I have a resource whose corresponding model is not an ActiveRecord – maybe a plain object synthesized from a complex database query. If I want to implement this as an independent resource, I can override `find`, `find_count`, and `find_by_key` on the resource class. But if I want to implement it as a "related resource" that another resource has-many of, the only available option seems to be overriding `records_for` on the "parent" resource, and that doesn't work in this case because JSONAPI::Resources still tries to do ActiveRecord filtering on the result of that method.

Right now I am working around this by using a `jsonapi_resources ... only: :index` route nested under the parent route (so it ends up being the same path as the related-resources route would be), combined with a `context` override to make the parent resource ID available. This then allows the `find` override to work.

It seems surprising/counter-intuitive in any case that overriding `find` works in some cases but is completely ignored in others – I would hope that if I want to take full control over how the underlying data is fetched, there would be a single obvious point to do that, which would work for all cases. Are there any plans currently around making it easier to support non-ActiveRecord resources?

**Comment by davidgoli** [comment]
:+1: also related to #627

**Comment by davidgoli** [comment]
and #545

**Comment by lgebhardt** [comment]
There are really several options here.

1) The `records_for` method calls a method on the model named after the relationship. So you could add a method on the model that implements the logic you need. Note that because this is on the model you do not have access to the context. 

2) There's a method on the resource that's dynamically created for each relationship (which is actually what calls `records_for`) named after the relationship (for example `records_for_comments` or `record_for_author`). This still returns an ActiveRecord Relation.

3) You can override the dynamically created method that's named after the relationship (for example `comments` or `author`). These methods return Resources so you can bypass the ActiveResource code. I think this is what you will want to do.

Because options 2 and 3 are based on overriding dynamically created methods I'm not surprised they aren't obvious. I'm wondering if allowing a callable block on the relationship would make sense.

**Comment by digitalcora** [comment]
Thanks @lgebhardt for clarifying. With option 3 I'm not sure how one would apply filtering/sorting, as is possible with `find` and `find_count` overrides. It doesn't look like these methods receive any options.

**Comment by will3216** [comment]
I am seeing something similar to what @grantovich is seeing. I have a non-activerecord model which does not respond to `where`. This is a dynamodb table, so I am only supporting the `#show` method right now. In my resource:
```ruby
module Api
  module V1
    class RelatedContentResource <  JSONAPI::Resource
      # cached_object :key_method, expires_in: :expires_method

      primary_key :combined_key
      attributes :combined_key, :article_uid, :brand_uid, :related_content_profile_id, :data

      def creatable_fields(_context=nil)

      end

      def find(filters, options={})

      end

      def find_by_key(combined_key, options={})
        context = options[:context]
        hash, range = combined_key.split('-_-')
        model = RelatedContent.find_by_key(hash, range, !!context[:consistent_read])
        fail JSONAPI::Exceptions::RecordNotFound.new(key) if model.nil?
        self.resource_for_model(model).new(model, context)
      end

      def records(_options={})

      end
    end
  end
end
```

In here, I was just going to intercept what these methods are getting passed, so I can recreate the correct behavior, but I was surprised by the error I received:

```
exception: "undefined method `where' for RelatedContent:Class",
backtrace:
/Users/william/.rvm/gems/ruby-2.2.2@jigsaw/gems/jsonapi-resources-0.7.0/lib/jsonapi/resource.rb:582:in `find_by_key'
/Users/william/.rvm/gems/ruby-2.2.2@jigsaw/gems/jsonapi-resources-0.7.0/lib/jsonapi/operation.rb:82:in `apply'
/Users/william/.rvm/gems/ruby-2.2.2@jigsaw/gems/jsonapi-resources-0.7.0/lib/jsonapi/active_record_operations_processor.rb:23:in `block in process_operation'
/Users/william/.rvm/gems/ruby-2.2.2@jigsaw/gems/jsonapi-resources-0.7.0/lib/jsonapi/operations_processor.rb:90:in `with_default_handling'
/Users/william/.rvm/gems/ruby-2.2.2@jigsaw/gems/jsonapi-resources-0.7.0/lib/jsonapi/active_record_operations_processor.rb:21:in `process_operation'
```

I was expecting the operations processor to call the user defined resource's `find_by_key` method, not the parent's method.

**Comment by will3216** [comment]
Never mind, I figured out what I was doing wrong!
