### ISSUE TITLE
Raising Errors

### ISSUE THREAD

**Issue by A-Helberg** [JSONAPI-Resources/jsonapi-resources#638]
When you raise and error that has been added to `config.exception_class_whitelist`

The [OperationsProcessor](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/operations_processor.rb#L96) checks wether the Error is whitelisted and then raises it. It then gets rescued from by the `process_request` method in [ActsAsResourceController](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/acts_as_resource_controller.rb#L56) where `handle_exceptions` is called.

In the source it specifies that you should override `handle_exceptions` to handle your custom Errors, but in the README is says that Errors added to the whitelist could be handled using a `rescue_from`.

I have not been able to get an Error to bubble so that `rescue_from` could handle it without overriding `handle_exceptions`. Is there something I'm missing or is the README outdated, if that is the case I'm more than happy to open a PR to update the README.

**Comment by A-Helberg** [comment]
BTW. This is in v0.7.0, it seems the code in master for `handle_exceptions` solves this! 

For anyone finding this and using v0.7.0 just use this adapted version of `handle_exceptions` and place it in your base controller:

``` ruby
  def handle_exceptions(e)
    case e
    when JSONAPI::Exceptions::Error
      render_errors(e.errors)
    else
      if JSONAPI.configuration.exception_class_whitelist.any? { |k| e.class.ancestors.include?(k) }
        fail e
      else
        internal_server_error = JSONAPI::Exceptions::InternalServerError.new(e)
        Rails.logger.error { "Internal Server Error: #{e.message} #{e.backtrace.join("\n")}" }
        render_errors(internal_server_error.errors)
      end
    end
  end
```

**Comment by glennr** [comment]
I'm also getting this error with 0.7.0 but its unclear which release this will be fixed in ?

**Comment by A-Helberg** [comment]
@glennr I think this was fixed on December 15 2015 by @lgebhardt

 It is part of the [0.7.1.beta1](https://github.com/cerebris/jsonapi-resources/releases/tag/v0.7.1.beta1) release so it should be part of 0.7.1, I just don't know when that will be released
