### ISSUE TITLE
Rails5.0beta3 breakage: ActionDispatch::Request.parameter_parser does not get our parameter parser

### ISSUE THREAD

**Issue by olleolleolle** [JSONAPI-Resources/jsonapi-resources#641]
[mime_types.rb](https://github.com/cerebris/jsonapi-resources/blob/rails5/lib/jsonapi/mime_types.rb) works with 5.0beta2, but breaks in beta3. 

We used to change DEFAULT_PARSER in-place. 

With beta3, the ActionDispatch::Request.parameter_parser does not get our newly-freedom-patched-in symbol in that hash.

**Comment by acorncom** [comment]
Looks like this was fixed by https://github.com/cerebris/jsonapi-resources/pull/642

**Comment by olleolleolle** [comment]
Yes! Thanks, yay!
