### ISSUE TITLE
STI subclass with `model_name` causes warning

### ISSUE THREAD

**Issue by digitalcora** [JSONAPI-Resources/jsonapi-resources#654]
This is admittedly a bit of an unusual situation, and (for reasons I don't yet understand) appears to still work as intended, so I'm mostly just documenting it here to provide a public reference point.

Consider the following models and resources:

``` ruby
class Machine < ActiveRecord::Base
  has_many :parts
end

class Part < ActiveRecord::Base
  belongs_to :machine
end

class Gadget < Part
  # ...
end

class PartResource < JSONAPI::Resource
  has_one :machine
end

class WidgetResource < PartResource
  model_name 'Gadget'
end
```

On definition of the `WidgetResource` class, JR issues the following warning:

```
[MODEL NOT FOUND] Model could not be found for WidgetResource. If this a base Resource declare it as abstract.
```

This is caused by the `inherited` hook in `JSONAPI::Resource`, which ends up calling `_model_class`, and since this happens before `model_name` is called, the model class cannot be found. Since the call is related to associations, a workaround is to define the `has_one :machine` on each subclass instead of the superclass. Although, as I mentioned, even with the warning the association still seems to work.

**Comment by charliemaffitt** [comment]
I'm noticing this same behavior.

**Comment by marisawallace** [comment]
I've seeing this as well.

**Comment by stevenharman** [comment]
Per d46a080, this was closed. Can anyone confirm/deny?

**Comment by marisawallace** [comment]
@stevenharman I don't remember seeing this issue anytime recently. I have no proof that it's fixed, but AFAIK it's no longer an issue, and okay to close.

**Comment by digitalcora** [comment]
I no longer work on (or have access to) the project where this issue originally came up, so I can't say whether the extraneous log line still occurs there. I will trust @maxkwallace on this one =)

**Comment by JulienItard** [comment]
Hello,
I just update 0.8.1 to 0.9.0 and i have the same issue. The bug is still here.
