### ISSUE TITLE
has_one doesn't work with ember

### ISSUE THREAD

**Issue by ivanjolic95** [JSONAPI-Resources/jsonapi-resources#655]
I've implemented backend models like:

```
class A
  has_one :b
end

class B
  belongs_to :a
end
```

and resources like this:

```
class AResouce
  has_one :b
end

class BResource
  has_one :a
end
```

In frontend (ember) I've used:

model A

```
export default DS.Model.extend({
  b: DS.belongsTo('b'),
});
```

model B

```
export default DS.Model.extend({
  a: DS.belongsTo('a'),
});
```

as ember documentation defines one-to-one relatiships.

However relationship does not work. Even though there are no errors, when I call `a.b` or `b.a` in rails, I get a nil. Everything else works, I've just no idea how to make one to one relationship that works in backend and frontend. What am I doing wrong?

**Comment by wongpeiyi** [comment]
You need to set `always_include_linkage_data: true` – Ember expects the `relationships { data: { id }}` to be set for `belongsTo` to work

**Comment by bmac** [comment]
@ivanjolic95 I'd also recommend you add an `inverse` property to these 1 to 1 relationships (Especially if there is another hasMany relationship of the same type on the model). I've seen cases where Ember Data heuristics do not correctly detect a 1 to 1 relationships and ends up incorrectly removing records when it tries to keep relationships in sync.

``` js
export default DS.Model.extend({
  b: DS.belongsTo('b', { inverse: 'a' }),
});
```

**Comment by lcpriest** [comment]
Thanks @wongpeiyi, exactly what I was looking for!
