### ISSUE TITLE
Persist linked data

### ISSUE THREAD

**Issue by lessless** [JSONAPI-Resources/jsonapi-resources#663]
Hello, 

We run into very common use case of creating relating resource into same request, like `User` and `Profile`.
Currently JSON-API doesn't provide any recommendations, but afaik team is looking forward to putting this into next release.
Meanwhile, can you advise the best way to store [linked](http://jsonapi.org/format/#document-compound-documents) data alongside with new record?

**Comment by lgebhardt** [comment]
An new spec is expected to be added to JSON API that supports multiple operations. This will allow us to implement this sort of functionality. Until then I don't have a great solution for you. One idea would be to keep the profile as a JSON field in the User resource instead of as a separate resource. I understand if that isn't appealing. Other suggestions I can come up with would not be compliant with the current spec.

**Comment by lessless** [comment]
@lgebhardt right now I'm trying to leverage the  `accepts_nested_attributes_for`  power:  `profile` is transferred to backend as a simple attribute  and then should be unpacked there.
Inside `UserResource` I just set up a getter to avoid a  non-existent attribute reading error, but there is another problem:  despite the fact that  `UserResource.creatable_fields` returns an array that includes `:profile` field, in the end, operation throws `105 - not permitted` error. 

Can you think of any gotchas that we might run into?

**Comment by lgebhardt** [comment]
I think the only place that would arise is from https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/request.rb#L545 if it's not declared as an attribute on the resource. I've never used `accepts_nested_attributes_for`, but it looks like the issue is before that comes into play.

**Comment by lessless** [comment]
I messed up with the `json_key_format`, but after fix everything worked as
expected and jsonapi-resources creates a new profile as expected!
Awesome work, thanks!

**Comment by utilityboy** [comment]
@lessless mind sharing a gist of how you implemented this?

**Comment by travisofthenorth** [comment]
@lessless I have also been struggling with this issue, and it would be great to get a quick rundown/gist of how you implemented it.
