### ISSUE TITLE
POST an inherited model on a relationship cause a "type mismatch" error

### ISSUE THREAD

**Issue by davidherer** [JSONAPI-Resources/jsonapi-resources#666]
Hello and thank you for this great library.
I have a Prestation, an Activity which inherits from Prestation, and a Demand with N SelectedPrestations.
A SelectedPrestation has one Prestation.
When I want to POST a new SelectedPrestation with an Activity, I got a "Type mismatch" error because it expects a Prestation type.
By default Ember Data send the model with the specialized type (even if the model definition use the abstract name).
Did you face this kind of problem? Do you have any idea to solve it?
Thanks a lot
David

**Comment by barelyknown** [comment]
You can change the type serialized by Ember Data by implementing the `payloadKeyFromModelName` function in a serializer. I'm not sure about your exact situation, but that might be a simple answer.

**Comment by davidherer** [comment]
Thank you, it works ! 
But I'm still wondering if I will not have problem when I will legitimately send specialized types to their endpoints (api/v1/activities will receive Prestation type... I have to give a try).
I thought JR could deduce that the type is inherited so allowed. 
Do you think it would be better if JR handles this job? 
How do you deal with relationships and inherited models usually?

**Comment by barelyknown** [comment]
If you want to create a subclass, you should POST to a matching controller. That's the most straight forward answer.

**Comment by davidherer** [comment]
Maybe I'm not clear (or I don't understand ;)
I talk about post a normal model which contains a relation subclass.

Here a piece of JSON I send to JR:

```
{
"data":
  {"attributes":
    {"day":1,"order":1},
    "relationships": {
       "prestation":{
         "data":{
           "type":"**activities**",
             // it only works with "prestations" while "activities" is a subclass of "prestations"
           "id":"5439"
          }
        } 
    },
    "type":"selected-prestations"}
  }
}
```

The SelectedPrestation resource

```
class Api::V1::SelectedPrestationResource < Api::V1::BaseResource
    attributes  :day, :order
    has_one :prestation
end
```

And my Activity resource which inherits from a Prestation

```
class Api::V1::ActivityResource < Api::V1::PrestationResource
end
```

**Comment by barelyknown** [comment]
Oh, OK. It looks like you need to declare that the `prestation` is polymorphic.

``` ruby
has_one :prestation, polymorphic: true
```

**Comment by davidherer** [comment]
Thank you @barelyknown ;) it works well
