### ISSUE TITLE
What timing are you expecting for JSONAPI 1.0 and support (at least partial) from jsonapi-resources?

### ISSUE THREAD

**Issue by barelyknown** [JSONAPI-Resources/jsonapi-resources#67]
I'm working on a new application, and I need to make a decision pretty soon about which variant of the json:api specification it will be based on. I saw that RC2 was published by @dgeb earlier this week and that @lgebhardt pushed a branch of this library with partial support. Which direction would you recommend I go? If possible, I'd really like to conform to V1 of the spec...

**Comment by dgeb** [comment]
@barelyknown I've been trying to coordinate with the other two leads on the spec, but it's been a rough week to schedule. I am absolutely committed to pushing the spec to 1.0 soon and would bet that RC2 will be close to final. Unfortunately, there are still a few loose ends and coordination has been challenging.

Last but not least, we're committed to ensuring jsonapi-resources conforms to the 1.0 spec.

**Comment by barelyknown** [comment]
OK, let me know how I can help. I'm going to try to put this new app on the 1.0 spec, so I'll delay as long as possible and then switch to the branch that'll support 1.0 as soon as I hear from you and @lgebhardt that it makes sense to do so.

**Comment by xdmx** [comment]
I really wish the final 1.0 will also support pagination, in my opinion it's quite a fundamental piece in order to have a good spec for the real world™

**Comment by barelyknown** [comment]
Any update on this? I have a meeting a bit later today where we're discussing the standard to settle on.

**Comment by dgeb** [comment]
@barelyknown we've had our meeting and resolved all the big decisions. It's now up to me to finish writing the RC2 PR in the next couple days.

@xdmx pagination will be covered by the 1.0 spec in a flexible but still useful way.

**Comment by barelyknown** [comment]
@dgeb Great. Thanks. I'll see if we can stall for a week.

**Comment by xdmx** [comment]
@dgeb awesome, thank you for your precious work on the json api spec

**Comment by dgeb** [comment]
As referenced in #76, I've [opened a PR in JSON API](https://github.com/json-api/json-api/pull/341) to allow for review of the upcoming spec changes. Work has already begun here in the [jsonapi_rc2 branch](https://github.com/cerebris/jsonapi-resources/tree/jsonapi_rc2) to support these changes.

**Comment by dgeb** [comment]
Update: RC2 branches have been merged into both JSON API and JSONAPI::Resources. Hoping to push out 1.0 final in the next few weeks!

**Comment by stevenharman** [comment]
![stephen-colbert-and-kermit-excited](https://cloud.githubusercontent.com/assets/48658/6288971/f921c1b2-b8ea-11e4-9f57-a9fcc0f5668b.gif)
