### ISSUE TITLE
Error Objects are invalid according to the JSON API Schema

### ISSUE THREAD

**Issue by halilim** [JSONAPI-Resources/jsonapi-resources#675]
I'm not sure if this is normal or not but, currently some (all?) errors are invalid according to the [JSON API Schema](http://jsonapi.org/schema).

An example error generated in a test:

``` json
{
  "errors": [
    {
      "title": "Missing Parameter",
      "detail": "The required parameter, data, is missing.",
      "id": null,
      "href": null,
      "code": "106",
      "source": null,
      "links": null,
      "status": "400",
      "meta": null
    }
  ]
}
```

Some issues according to the [spec](http://jsonapi.org/format):
- `id` must be a string
- `href` is not a valid member of an error object
- `source`, `links` and `meta` must be an object 

I'm using `json-schema` gem in the tests but the same results can be observed using another tool; e.g.  http://jsonschemalint.com/draft4/# by pasting the contents of http://jsonapi.org/schema into the left side ("JSON Schema") and the error JSON into the right side.

**Comment by ScottSmix** [comment]
+1
