### ISSUE TITLE
Rails 5 branch?

### ISSUE THREAD

**Issue by jocubeit** [JSONAPI-Resources/jsonapi-resources#682]
README mentions a Rails 5 branch, can you tell me which branch is the one mentioned?

**Comment by jocubeit** [comment]
`Git error: command`git rev-parse --verify rails5`in directory
/Users/kodemunki/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/cache/bundler/git/jsonapi-resources-edb7d837384ada9355770f6c0b30f7267951e60b has failed.
Ref 'rails5' was not found. Perhaps you mispelled it?`

**Comment by utilityboy** [comment]
@JurgenJocubeit I believe that branch has been merged into master per d298a40

**Comment by lgebhardt** [comment]
Sorry, I forgot to take the note out. As @utilityboy says the rails5 branch has been merged.
