### ISSUE TITLE
Create a Global Universal System(GUS)

### ISSUE THREAD

**Issue by felix8lim** [JSONAPI-Resources/jsonapi-resources#688]
Hi All developers,

I would like to start a project in which the primary objective is to identify every human on Earth from birth. Reasons as below:
1. no matter how far our technology advance, we are no able to know how many people on Earth at this moment alive,  gonna to die soon or coming in how many days into birth. 
2. When we left basic available unused or not utilized properly in the beginning stage, then how are we the benefits are gonna be equally and fairly distributed among us.
3. When we can account and identify for everyone (eg by birth cert, DNA or fingerprint) then we can give them the required help and rights that we advocate so strongly efficiency

There are many charities, foundations and NGOs already in place but none can 99.99%(the sentinelese is only race I wish to leave out for they are living happily 100% alone) simply know how to identify every living human beings they are being founded in first place. We are still living in a world governed ineffectively and economy are mainly run by big corporations we can do nothing the way they wish to profit only certain individuals. 

In this internet age, I hope that soon we can come out with a complete system like WWW as a platform to access every information and  also identify,categorized, grade and review everything that is already in the market or soon to be. Then in a systematically and progressive way like MMORPG game model that a certain path can be laid out clearly of their current status, like a dashboard of yr qualification, financial, social connections etc) and indicate options available to improve in future. 

As I only know the existence of most IT technologies and their features, but I 'm not tech savy enough to manage thing like website, blog, setting community in media FB, start crowdfund/source events etc. Therefore I would like to have IT professionals at this stage to volunteer setting up the right channels in the IT community to get things done. I understand that all will have their commitment to different kind of task/project on hand but for sure these will also have its' place in the GUS I intend to work out. 

We know that the influence of internet can help to elect presidents, overthrow governments through media, but the existence of violence protest, riots, revolutions in blood should also reduced with better integration of IT in the when we need IT to govern our life. Poll, survey, petition are in progress everyday but they lack the speed to create new milestones to effectively change the laws, policies, regulations in time. 

I do not wish to promise immediate or huge fortune to those that are willing to sacrifice their knowledge, time, resources in return. But the few examples I list now should be motivation that any charity/NGO is started in first place but totally differently from them in my way.
1. We can create a place for anyone on earth that from birth they are guarantee to get basic necessities in food,shelter, medical, education, till their legal age.  
2. Anyone can vote to execute events that affect other life through democratic process regardless of current boundary. eg war, acceptance of GMO, set limit of production on vehicles/ poultry which pollute and reduce with target, full disclosure of risk of new services/products that we only see the benefits corporations sell but never the mass negative consequence that are set to be monitored(just look at the timeline that risk of cars, new medicine, chemicals, or even ham and bacon, tobacco, etc take to be regulated/banned after they are invented. profited before being controlled/banned.  
3. Our model of economy will never have enough jobs to keep everyone happy but with concept of universal income monthly regardless of employment status to keep one sufficient to live/ work in acceptable conditions of their interest.(food, shelter guaranteed). People of higher qualification will get additional and all those in niche industry won;t end up doing minimum pay wages or jobless in worst situation.
4. No job interview as you can choose any place to work and progress by merit equally. 
5. Everyone will get more time to learn skills required/interested rather than only when in profession. eg. no policeman required if there is no crime but there could be citizen are certified and trained living as normal citizen to be group when necessary to fight crime.  
6. A place for everyone in a tightly controlled world with common sense, moral, code of conduct drawn clearly and managed with facts and statistics and even for the out of mind or extremists on Earth. But with education of the population reach a higher level and standards, we can truly have countries or continents where people are totally free from laws and governments rules and can still be peaceful and happy. Measures only taken when necessary and readily available. 

More details can be found in my google link and I not only invite professional in the IT industry to come in, but also experts in all fields that we will need for advice and support in the later stages. 
https://plus.google.com/103161605064965362019/posts/4D6Ue1fZKHD

Feel free to add yr comments/feedback/suggestions even if negative and forgive my messy write up:) People are free to copy this concept and work on their own or partner me at this initial stage. Volunteers/sponsors/ who wish to collaborate in term of skills/fund/resources please contact me limstfelix@gmail.com skype:felix.lim1 or +66628431808 (bangkok)

**Comment by lgebhardt** [comment]
I'm going to close this. It's not a reflection on the merits of the proposed idea (which I haven't considered), but rather this is not an issue with this project. There are other places much more appropriate for things like this. Might I suggest reddit.
