### ISSUE TITLE
"type" reference in Relationship

### ISSUE THREAD

**Issue by tiagopog** [JSONAPI-Resources/jsonapi-resources#689]
Hi there,

I'm probably missing something, so I would like to know if there is any particular reason to grab the relation's type by:

`@type = class_name.underscore.pluralize.to_sym`

Instead of something like this:

`@type = resource_klass._type.to_sym`

IMHO it would make more sense to grab it from `resource_klass` than `class_name` in order to avoid incoherences such as:

Having this value for `type` at `relationship` member:

![screen shot 2016-04-26 at 3 42 29 pm](https://cloud.githubusercontent.com/assets/760933/14830159/8eac09ee-0bc5-11e6-9051-62c667d27158.png)

And this one at `included` member:

![screen shot 2016-04-26 at 3 45 29 pm](https://cloud.githubusercontent.com/assets/760933/14830224/f001ad70-0bc5-11e6-9e77-5a410cbd81bf.png)

Thoughts?

**Comment by lgebhardt** [comment]
I don't remember why it was done this way. I'll blame coding without coffee. See if the PR works for you.

**Comment by tiagopog** [comment]
Awesome! Thanks @lgebhardt
