### ISSUE TITLE
Is there a write-only method for resources?

### ISSUE THREAD

**Issue by lcpriest** [JSONAPI-Resources/jsonapi-resources#690]
My current workaround is the following. I need to create a `DelightedIntegration` with the API token, but I don't want it exposed through the API after the initial save.

```
class DelightedIntegrationResource < IntegrationResource
  attribute :api_token

  def api_token;end
end
```

**Comment by vrybas** [comment]
@lcpriest, you can define `.fetchable_fields`

``` ruby
class DelightedIntegrationResource < IntegrationResource
  attribute :api_token

  class << self
    def fetchable_fields(context)
      super - [:api_token]
    end
  end
end
```

**Comment by lcpriest** [comment]
Thanks!

**Comment by lcpriest** [comment]
For future readers, the provided result did not work for me, but the following did:

```
class DelightedIntegrationResource < IntegrationResource
  attribute :api_token

  def fetchable_fields
    super - [:api_token]
  end
end

```

**Comment by vrybas** [comment]
@lcpriest ah, the singature of `.fetchable_fields` has changed after `0.7.0`

https://github.com/cerebris/jsonapi-resources/tree/v0.7.0#fetchable-attributes

https://github.com/cerebris/jsonapi-resources#fetchable-attributes

Are you on `master`?

**Comment by lcpriest** [comment]
rails5 branch, my mistake!
