### ISSUE TITLE
Trouble with custom_links

### ISSUE THREAD

**Issue by MrPhantomT** [JSONAPI-Resources/jsonapi-resources#696]
Hello. 
I tried add some custom links with following code:

``` ruby
class ProfileResource < JSONAPI::Resource
...
def custom_links(options)
   { some_link_name: "some_url" }
end
...
end
```

But them doesn't added to json. And `custom_links` method does't call. I used v0.7.0 of jsonapi-resources.
Can you tell me is it bug or I doing something wrong.

And I noticed that exists method for `jsonapi_resource` for individual resource but self link for that resource generated with `id` and it can't be used.

**Comment by ersinakinci** [comment]
I had this problem, too. It appears that the documentation on the main page refers to master branch, which has the feature, whereas 0.7.0 doesn't. (Note that `custom_links` doesn't appear here: https://github.com/cerebris/jsonapi-resources/blob/v0.7.0/lib/jsonapi/resource_serializer.rb)
