### ISSUE TITLE
Retrieving all the resources on a paginated resource

### ISSUE THREAD

**Issue by Rolilink** [JSONAPI-Resources/jsonapi-resources#702]
I have a paginated resource with `paginator :paged` there is a way to bring all the resources and still have the pagination (not removing the paginator)? right now doing an ajax brings a set of records with default length.

**Comment by lgebhardt** [comment]
@Rolilink I'm sorry, but I don't quite understand. Are you looking to return all resources sometimes and paginated at others?

It's possible, and encouraged if needed, to write your own [custom paginators](https://github.com/cerebris/jsonapi-resources#custom-paginators). With a custom paginator a lot of options would be open to you.

**Comment by Rolilink** [comment]
thanks @lgebhardt I did that maybe I can contribute adding the new paginator
