### ISSUE TITLE
namespaced models and routes don't work

### ISSUE THREAD

**Issue by sashazykov** [JSONAPI-Resources/jsonapi-resources#704]
I am getting this error after record is loaded from database:

```
Internal Server Error: undefined method `_type' for nil:NilClass /jsonapi-resources-0.7.0/lib/jsonapi/resource_serializer.rb:19:in `initialize'
```

code:

``` ruby
module V2
  module Delivery
    class DriverResource < JSONAPI::Resource
      model_name '::Delivery::Driver'
    end
  end
end

module V2
  class DriversController < JSONAPI::ResourceController
  end
end

Rails.application.routes.draw do
  namespace :api, module: nil do
    namespace :v2 do
      namespace :delivery, path: nil  do
        jsonapi_resources :drivers
      end
    end
  end
end
```

**Comment by lgebhardt** [comment]
Your resource namespace doesn't match the controller, which it should.

Also, the `path` in your namespace isn't something I can remember testing. It seems like this could cause issues, but I haven't looked into it.

**Comment by jufemaiz** [comment]
Hi @lgebhardt I can confirm that you're pretty much correct.
1. resource namespaces need to match controllers.
2. jsonapi-resources currently isn't properly supporting path: nil in rails routes for generation of urls within the resource response. Will raise an issue on this shortly.
