### ISSUE TITLE
updating singular resource

### ISSUE THREAD

**Issue by workgena** [JSONAPI-Resources/jsonapi-resources#705]
According to this issue #686 i managed to create singular resource.

But update action fails this:

https://github.com/cerebris/jsonapi-resources/blob/v0.7.0/lib/jsonapi/request.rb#L611

request.rb:
fail JSONAPI::Exceptions::MissingKey.new if data[:id].nil?

But singular resource does not have ID.

Thx.

**Comment by senid231** [comment]
JSON API spec says that data object MUST contain id
but singleton resource is not mentioned in spec
[json-api/json-api Issue#1046](https://github.com/json-api/json-api/issues/1046)
