### ISSUE TITLE
JSONAPI::ResourceSerializer does not follow config.route_format

### ISSUE THREAD

**Issue by Fedcomp** [JSONAPI-Resources/jsonapi-resources#713]
``` ruby
render json: JSONAPI::ResourceSerializer
  .new(
    Api::V1::SessionsResource,
    include: ['country', 'state', 'city', 'phone-numbers']
  ).serialize_to_hash(Api::V1::SessionsResource.new(@resource, nil))
```

This way i cant get my phone numbers, but when i change `phone-numbers` to `phone_numbers` it works. However my `JSONAPI.configure { config.route_format = :dasherized_route }` and everywhere else i may use only relationships/attributes only in that format.

So i just guess `JSONAPI::ResourceSerializer`does not follow `config.route_format`

**Comment by lgebhardt** [comment]
The serializer expects fields and includes to be in the normal underscored format. The formatters are applied before ResourceSerializer is called in the normal workflow. Since you are manually calling the Serializer you will need to handle that step.
