### ISSUE TITLE
Feasibility of new method called process_request_and_yield

### ISSUE THREAD

**Issue by billxinli** [JSONAPI-Resources/jsonapi-resources#715]
Problem: JR gives about 90% of the lifting power to get what we need, however there are 10% of the use case where custom end point is better than POSTing to the same end point 10000 times.
Solution: Create custom end point, however, this will lose? all the abilities that JR provides, like includes, filters, etc.

Is it possible/feasible to add a new method called something along the lines of `process_request_and_yield` (which is a copy of `process_request` from `ActsAsResourceController` which can be called from the controller as such:

```
  def custom_method
    params[:id] = params[:job_id]
    params[:action] = 'show'
    process_request_and_yield do |operation_results|
      model = operation_results.results&.first&.resource&._model
      if model
        model.cure_cancer!
        model.send_email!
        model.do_delayed_job!
      end
    end
  end
```

```
  def process_request_and_yield
    @request = JSONAPI::Request.new(params, context: context,
      key_formatter: key_formatter,
      server_error_callbacks: (self.class.server_error_callbacks || []))
    unless @request.errors.empty?
      render_errors(@request.errors)
    else
      operation_results = create_operations_processor.process(@request)
      yield operation_results
      render_results(operation_results)
    end

  rescue => e
    handle_exceptions(e)
  end
```

Or am I approaching this from a totally wrong perspective?

**Comment by lgebhardt** [comment]
@billxinli We have added the concept of processors in #694. Processors may help you with a place to alter the way an operation is handled. So far this only in the master branch and has not been released yet. It will not provide support to custom end points, though I think you could more easily create a custom operation and a processor method to apply it. 

Of course a custom method would not be compliant with the JSON API spec.

As to whether you are approaching it wrong, I don't know. There isn't currently a way to update multiple resources in one request. This is a planned extension to the spec and we fully plan to support it in JR. But if you need this now you will probably need to add a custom end point.
