### ISSUE TITLE
Error: Key is not included in URL

### ISSUE THREAD

**Issue by lcpriest** [JSONAPI-Resources/jsonapi-resources#717]
`title: "Key is not included in URL"`
`detail: "The URL does not support the key 946591862"`

I can't find anything in the documentation explaining what this actually means - what does "Key" refer to here?

I'm bumping into it in my Controller tests, for context.

The following code triggers it.

```
sign_in users(:one)
put :update, id: model_id , params: { data: update_attributes, id: model_id }
```

**Comment by lcpriest** [comment]
Ah. The issue I have is that I was using different ids inside and outside the data hash

**Comment by UsamaShahzad7** [comment]
Thanks for commenting here after finding the solution. It really is a life saver.
