### ISSUE TITLE
Null values excluded from response

### ISSUE THREAD

**Issue by Keqi** [JSONAPI-Resources/jsonapi-resources#729]
Is there any configuration flag or handy way to return only attributes which aren't null?

For example:

```
{
  "name": "Jon Brown",
  "age": 45,
  "address": null,
  "additional_information": {
    "gender": "male",
    "hobby": null
  }
}
```

That would transform to:

```
{
  "name": "Jon Brown",
  "age": 45,
  "additional_information": {
    "gender": "male"
  }
}
```

**Comment by bpatram** [comment]
Have you tried taking a look at the [`fetchable_fields` configuration](https://github.com/cerebris/jsonapi-resources#fetchable-attributes) on your resource? From there you can remove attributes that are `nil`/`null` from the array it returns. 

You can also define your own getter method for your `additional_information` attribute to remove any thing that is `nil`/`null`.

**Comment by lgebhardt** [comment]
There isn't a configuration flag for this. Try overriding the `fetchable_fields` method on your resource (https://github.com/cerebris/jsonapi-resources#fetchable-attributes):

``` ruby
class AuthorResource < JSONAPI::Resource
  def fetchable_fields
    super.collect do |field|
      field unless self.class._attributes.has_key?(field) && public_send(field).nil?
    end
  end
end
```

This is untested, but it should be close.

The `additional_information` hash looks to be something you have added as an attribute on your resource. Nulls would need to be filtered in this step as well.

**Comment by Keqi** [comment]
Thank you, super useful. I am closing issue :)
