### ISSUE TITLE
"MODULE NOT FOUND" Error for inherited resource 

### ISSUE THREAD

**Issue by MrPhantomT** [JSONAPI-Resources/jsonapi-resources#730]
Hello. I found bug by my opinion.
When we have some inherited resource, which not mapping directly to model, we meets next warning 

``` ruby
[MODEL NOT FOUND] Model could not be found for Api::V2::SomeResource. If this a base Resource declare it as abstract.
```

I made some research and found that this happens in method [inherited](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource.rb#L320) when copies relationships to subclass in method [_add_relationship](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource.rb#L864) and trying to access `_model_class`, which call method `_model_name` but `@_model_name` still doesn't set and try discover model by resource name and can't find it.

example:

``` ruby
class Api::V2::SomeResource < Api::V2::SomeBaseResource
    model_name 'DifferentModelName'   
...
end
```

Thanks.

**Comment by lgebhardt** [comment]
Is `Api::V2::SomeBaseResource` declared as [abstract](https://github.com/cerebris/jsonapi-resources#abstract-resources)?

**Comment by MrPhantomT** [comment]
No, it is not abstract.

**Comment by lgebhardt** [comment]
Is it possible to refactor to make the base class abstract?

**Comment by MrPhantomT** [comment]
@lgebhardt Sorry for the delay in replying. Yes, it is working. Thanks
