### ISSUE TITLE
Build caching into JSONAPI::ResourceSerializer

### ISSUE THREAD

**Issue by kellysutton** [JSONAPI-Resources/jsonapi-resources#74]
Much like the 0.8.x versions of ActiveModel::Serializer, I propose that JSONAPI::ResourceSerializer should support the `cached` directive to enable caching of responses via `Rails.cache`. 

The cache keys themselves should be based upon `@model.cache_key`.

There will be some gotchas with caching that will need to be tested for, namely around serializing multiple resources into a single payload, and the caching of any resources sideloaded via the `include` param.

I'll see if I can't put something together and open a PR.

**Comment by thibaudgg** [comment]
:+1:

**Comment by kellysutton** [comment]
(Sorry about the delay here. I've been busy. If anyone else wants to take a crack at this, feel free.)

**Comment by DavidMikeSimon** [comment]
I think PR #712 has resolved this.

**Comment by lgebhardt** [comment]
Caching was added in 0.9
