### ISSUE TITLE
PUT vs PATCH

### ISSUE THREAD

**Issue by brancusi** [JSONAPI-Resources/jsonapi-resources#742]
Hi,

I am having an issue when trying to update a record. The client is built in ember, and 2.6.0 makes PUT requests when updating, but this is being rejected by JR.

Is there any advice to get this working again?

I'm getting: `The resource object does not contain a key.`

Thanks

**Comment by dgeb** [comment]
@brancusi Are you using the JSONAPI adapter? It should send [updates via PATCH](https://github.com/emberjs/data/blob/master/addon/adapters/json-api.js#L140) as per the spec.

**Comment by brancusi** [comment]
@dgeb, sorry something was wrong with my setup. Once I cleared bower and npm cache and reinstalled, everything worked.

Thanks
