### ISSUE TITLE
Method to manually generate errors?

### ISSUE THREAD

**Issue by lcpriest** [JSONAPI-Resources/jsonapi-resources#745]
```
post = Post.find(1)
JSONAPI::ResourceSerializer.new(PostResource).serialize_to_hash(PostResource.new(post, nil))
```

This method is used to generate json for a post object - is there a similar one for generating an error hash for an object?

I have a devise controller for inviting users that is not a jsonapi controller but I would like to return JSON in the correct format anyway.

**Comment by lcpriest** [comment]
Found it:

```
  def error_response
    JSONAPI::ErrorsOperationResult.new(422, JSONAPI::Exceptions::ValidationErrors.new(resource).errors)
  end

  def success_response
    JSONAPI::ResourceSerializer.new(UserResource).serialize_to_hash(resource)
  end
```

For other readers - this is probably not encouraged and I will be figuring out how to undo this in future.

**Comment by seanwash** [comment]
@lcpriest I'm curious as to what your approach to this was. Mind sharing?

**Comment by lcpriest** [comment]
@seanwash I'm not sure I follow the question - I use those two methods in the create endpoint.

```
  def create
    @user = invitation_manager.invite(invitation_params)
    if @user.errors.any?
      render json: error_response, status: :unprocessable_entity
    else
      render json: success_response
    end
  end
```

**Comment by seanwash** [comment]
@lcpriest Sorry, I was referring more to 

> For other readers - this is probably not encouraged and I will be figuring out how to undo this in future.
