### ISSUE TITLE
Support to-many relationships as collection objects

### ISSUE THREAD

**Issue by kellysutton** [JSONAPI-Resources/jsonapi-resources#75]
Currently, adding objects to a to-many relationship using the collection object passes incorrectly data (namely, the collection object) to the target model. Most target models then blow up, since they are expecting an array of IDs.

Example object with a linked collection object:

``` json
//...
  {
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "comments": {
        "href": "http://example.com/comments/5,12,17,20",
        "ids": [ "5", "12", "17", "20" ],
        "type": "comments"
      }
    }
  }
//...
```

Expected result: `JSONAPI::ResourceController` correctly enforces the type constraint and then properly sanitizes and flattens the collection object.

**Comment by evolve2k** [comment]
@kellysutton not quite sure what you're asking for here. You happy we close this issue, just so many open issues on this repo currently that small requests are cluttering out the bigger focus areas.

Note to maintainers: Close. kellysutton can reopen if he feels strongly it still needs addressing and provide more info at that point.
