### ISSUE TITLE
records_for_xxx isn't considered when using ?includes=xxx param

### ISSUE THREAD

**Issue by ianpetzer** [JSONAPI-Resources/jsonapi-resources#758]
Hi there,

I've defined a resource as:

```
has_many :countries

def records_for_countries
   Country.where(published: true)
end
```

This works great until I try use the include parameter to sideload the relationships and then the records_for_countries method is ignored.

I'm trying to define an entity that composes all of the critical data that is needed for my app. A resource that my ember app uses to pull in all the common entities that are shared by the different entities in my app.

Is there any way to get the ?includes=xxx to make use the records_for_xxx method?

**Comment by lgebhardt** [comment]
Can you override `apply_includes` to also add the `countries` to the generated relation?

**Comment by ianpetzer** [comment]
Hi,

Yes I can. 

Thanks so much!
