### ISSUE TITLE
New JsonApi spec

### ISSUE THREAD

**Issue by miguelsan** [JSONAPI-Resources/jsonapi-resources#76]
Hi guys, the jsonapi spec [is undergoing major changes](https://github.com/json-api/json-api/pull/341). Are you aware of them? Will you have any plans about it?

I'd love to be able to keep using this gem in the future.

**Comment by lgebhardt** [comment]
@miguelsan, yes we are very much aware of the changes. I've got a branch (https://github.com/cerebris/jsonapi-resources/tree/jsonapi_rc2) where I've started bringing this gem into compliance with the proposed changes.

**Comment by stevenharman** [comment]
Perhaps we could close this issues and track https://github.com/cerebris/jsonapi-resources/issues/67 instead?

**Comment by dgeb** [comment]
@stevenharman good idea - I just updated #67 with the relevant details from here.
