### ISSUE TITLE
Context not available in relationship request

### ISSUE THREAD

**Issue by koraykoska** [JSONAPI-Resources/jsonapi-resources#763]
If we do a Request like `/posts/1/tags` and filter these tags with `?filter[name]=green`, the `context` is not available within this `apply` block for the filter. If I request `/tags` and apply the same filter, the response is exactly what I expect.

Is this behaviour expected? Could we get somehow around this?

Example filter:

``` Ruby
filter :name, apply: -> (records, value, _options) {
  return records.where(name: value) if self.context[:current_user].guest == false
  return records.where(name: 'yellow')
}
```

**Comment by Ybrin** [comment]
#392

**Comment by koraykoska** [comment]
#392

**Comment by lgebhardt** [comment]
@Ybrin Please let me know if #779 fixes your problem.
