### ISSUE TITLE
Authorization?

### ISSUE THREAD

**Issue by shellandbull** [JSONAPI-Resources/jsonapi-resources#766]
Hello guys,

I've been looking at the wiki/project and can't find any documentation in regards to restricting some actions in a controller based on some characteristics in the request, i.e:

I'm using `json-api-resources` for a resource called `tickets` and I want to restrict write actions to only those requests coming from users that are administrators. How could I go on and accomplish this?

**Comment by bmichelsen** [comment]
Hi there!

From the authorization discussion at #16 there are (at least) two viable options:
- [jsonapi-authorization](https://github.com/venuu/jsonapi-authorization)
- [pundit-resources](https://github.com/togglepro/pundit-resources)

Also, have a look at the excellent comment by @valscion that [explains the differences](https://github.com/cerebris/jsonapi-resources/issues/16#issuecomment-222438975) between the two approaches.

Hope that gets you started!

**Comment by shellandbull** [comment]
@bmichelsen @lgebhardt

I was looking at [this](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/processor.rb#L55) And I think we can get away with building validation primitives into the framework in a very simple _and_ lightweight manner:

How about we just add another callback called `validate` that yields the request object - coming from the controller - and lets the end user validate agains't whatever he wants i,e: ip address, params, session, etc?

My only concern would be how to let the users actually inject errors to the errors payload in case the request is valid - any takers? I'm happy to implement this one since I need it for a project 🌞 If you guys are happy with this we can open a proper issue with a `TODO` list, etc.

So at a resource level you could define something like

``` ruby
validate do |request, errors|
  errors.add(:access, "you don't have access to this application") if request. remote_ip.match(/a-blacklisted-ip-address/)
end
```

The user doesn't need to raise exceptions or anything else, just touch an `errors` object, you can instantiate a pundit policy if you want there...pretty much anything 🌞

**Comment by lgebhardt** [comment]
@mariogintili I would put remote_ip checks more as an Authentication concern and as such could be handled earlier in the stack as a controller callback. Though I'm sure a case could be made for controlling updating a particular resource based on ip address.

Are you proposing `validate` on the processor or the resource?

**Comment by shellandbull** [comment]
@lgebhardt the remote_ip example was banal and just to showcase an example use case for some developers -

> Are you proposing validate on the processor or the resource?

Proposing a `validate` on the processor that yields 2 things:
- The `context` Which I originally proposed as the `request` but you can set the request to be a part of the context and not the other way around 😄 
- An `errors` object. Corresponding to a tree so it's compliant with [JSON-API's errors](http://jsonapi.org/examples/#error-objects-basics)

[EDIT]

> I would put remote_ip checks more as an Authentication concern and as such could be handled earlier in the stack as a controller callback

I thought about that too, but it's a bit weird to define callbacks for actions that are not explictly implemented in the controller - since JSON-API takes over everything - don't you think?

**Comment by lgebhardt** [comment]
@mariogintili I understand the the remote_ip example isn't the focus of your issue, but what I was getting at is do we need access to the request object in the processor? I think adding it to the context as you mention would be adequate for the few use cases where it's needed.

As it is now an exception should be raised when an error is encountered in the processor. This will be converted in the  `OperationDispatcher` into an error object. This currently limits the system to one error for a response, though multiple model validations will result in multiple errors.

If we add an `errors` object and a `validate` method how would we integrate them into the `process` method? I can see a few ways.

**Comment by shellandbull** [comment]
> I think adding it to the context as you mention would be adequate for the few use cases where it's needed.

Yep I agree with this too :)

> This currently limits the system to one error for a response, though multiple model validations will result in multiple errors.

Looks like too much coupling to a resource, since in light of today [JSON-API doesn't specify to what the `errors` payload refers to](http://jsonapi.org/format/#error-objects), this could easily be:
- Things related to the parameters when trying to create a resource, i.e:

``` ruby
  errors: { name: ['too long', 'must contain only alphanumeric characters'] }
```
- Things related to the request, i.e:

``` ruby
  errors: { ip: ['not allowed'] }
```
- Etcetera

``` ruby
  errors: { whatever: ['foobar'] }
```

To further quote

> Error objects provide additional information about problems encountered while performing an operation

So it looks like something that should be fit into the processor 😄

> If we add an errors object and a validate method how would we integrate them into the process method? I can see a few ways.

Implementation wise, I've had great experiences with [ActiveModel's errors object](http://api.rubyonrails.org/classes/ActiveModel/Errors.html) More than happy to listen to better suggestions, I'm not very familiar with the architechture of this project to be honest

**Comment by lgebhardt** [comment]
@mariogintili Just to be clear I'm not opposed to the `errors` object concept at all. I'm just looking to understand how it will fit into the code base and what it's capabilities will be.

Are you proposing something like the example below for `process`?

``` ruby
    def process
      validate

      if @errors.empty?
        run_callbacks :operation do
          run_callbacks operation_type do
            @result = send(operation_type)
          end
        end
      end

      unless @errors.empty?
        @result = JSONAPI::ErrorsOperationResult.new(@errors[0].code, @errors)
      end

    rescue JSONAPI::Exceptions::Error => e
      @result = JSONAPI::ErrorsOperationResult.new(e.errors[0].code, e.errors)
    end

    def validate

    end
```

**Comment by shellandbull** [comment]
@lgebhardt Yeah that looks like a great starting point 😄 using that template method then developers could do something like

``` ruby
def validate(errors, context)
  errors.add(:name, "needs to be valid") if context.params.fetch(:modelname, {}).fetch(:name).empty?
end
```

**Comment by lgebhardt** [comment]
`context` is already an attribute on Processor, and `errors` could be as well. So we could avoid requiring them as arguments. So this is possible:

``` ruby
def validate
  # assume @errors was initialized to []
  @errors.add(:name, "needs to be valid") if @context.params.fetch(:modelname, {}).fetch(:name).empty?
end
```

Note that this could also easily be done using the `operation` callbacks:

``` ruby
def around_operation
  errors = []
  errors.add(:name, "needs to be valid") if @context.params.fetch(:modelname, {}).fetch(:name).empty?

  yield

  unless errors.empty?
    @result = JSONAPI::ErrorsOperationResult.new(errors[0].code, errors)
  end
end
```

Also note that in the above examples it would probably be better to let the model handle validations of whether `name` is empty. Just mentioning this for people new to Rails and JR who might be looking for examples of how to do things. In this case `validate` is for the operation and not the model.
