### ISSUE TITLE
use_relationship_reflection not working

### ISSUE THREAD

**Issue by nightreapper** [JSONAPI-Resources/jsonapi-resources#768]
Is my config

```
JSONAPI.configure do |config|
  config.use_relationship_reflection = false
end
```

or

```
JSONAPI.configure do |config|
  config.use_relationship_reflection = true
end
```

`undefined method`use_relationship_reflection=' for #JSONAPI::Configuration:0x007fb353eef968 (NoMethodError)`

in VERSION 7.0 and VERSION 0.7.1.beta2

**Comment by lgebhardt** [comment]
@nightreapper That option is only in the master branch at this point. I will be making a release from master shortly.
