### ISSUE TITLE
How should polymorphic relationships be handled?

### ISSUE THREAD

**Issue by barelyknown** [JSONAPI-Resources/jsonapi-resources#77]
I have a class with a polymorphic relationship.

``` ruby
class Identification < ActiveRecord::Base
  belongs_to :identified, polymorphic: true
end
```

I would like to do something like this:

``` ruby
class IdentificationResource < BaseResource
  has_one :identified, polymorphic: true
end
```

This doesn't appear to be supported by `jsonapi-resources` yet (I checked `master` and `jsonapi_rc2`), but since polymorphism is supported in RC2, it seems like we should add it.

What are you thinking for this feature? I'd be happy to help.

**Comment by lgebhardt** [comment]
@barelyknown I was planning on adding polymorphism support to `jsonapi-resources` in the future. If you want to tackle adding support to the `jsonapi_rc2` branch that would be nice. I haven't given the implementation details a whole lot of thought, but if you need someone to bounce some ideas off of let me know.

**Comment by vrybas** [comment]
@barelyknown does #274 covers this issue?

**Comment by samselikoff** [comment]
@lgebhardt I believe this can be closed

**Comment by jufemaiz** [comment]
@samselikoff what's the approach to use?

**Comment by vrybas** [comment]
@jufemaiz see #274
