### ISSUE TITLE
Exceptions from serialization are not routed to on_server_error callback

### ISSUE THREAD

**Issue by al2o3cr** [JSONAPI-Resources/jsonapi-resources#780]
The callback(s) specified using `on_server_error` are not invoked when a resource's serializer raises an exception. Execution instead proceeds through the `handle_exceptions` method added from `JSONAPI::ActsAsResourceController`. Is this behavior intentional?

In our particular case, this behavior caused serialization failures to be only logged despite a block in `on_server_error` that we thought was also routing them to Sentry. We worked around the issue with the following code:

``` ruby
class Api::ThingiesController < ApplicationController
  authorize_resource
  include JSONAPI::ActsAsResourceController

  on_server_error :handle_error

  def self.handle_error(error)
    ErrorHandler.notify_detailed(exception: error, message: "Error in thingy API: #{error.message}",)
  end

  def handle_exceptions(error)
    self.class.handle_error(error)
    super
  end
end
```

**Comment by mmartinson** [comment]
This feature could use some attention. See #734

**Comment by stevenharman** [comment]
I _think_ this can be closed as of https://github.com/cerebris/jsonapi-resources/commit/4c856ef59d80afd2484eedb20e350330688d04e5, yes?
