### ISSUE TITLE
on_save_failed callback needed

### ISSUE THREAD

**Issue by senid231** [JSONAPI-Resources/jsonapi-resources#791]
simle example: login resource with only `POST` route

``` ruby
class LoginResource < JSONAPI::Resource
  model_name 'LoginForm'
  attributes :login, :password
end

class User < ActiveRecord::Base
  MAX_ATTEMPTS = 5

  def max_attempts_reached?
    self.attempts >= MAX_ATTEMPTS
  end

  def increment_attempts!
    self.increment!(:attempts)
  end
end

class LoginForm
  include ActiveModel::Model
  attr_accessor :login, :password

  validates_presence_of :login, :password
  validate do
    if user && user.max_attempts_reached?
      errors.add(:base, :too_many_login_attempts)
    elsif user.nil? || user.password != password
      errors.add(:base, :login_or_password_invalid)
    end
  end

  def user
    @user ||= User.find_by(login: login)
  end

  def _save
    user.touch(:last_login_at)
  end
end
```

it will be good to have possibility to increment attempts when login was failed
how can i do this?
Operations for create/update/destroy are wrapped in transaction
we need a callback outside of transaction with access to resource

**Comment by lgebhardt** [comment]
You could override the `create` method on the controller, allow the error to propagate up and then update the login count.

Another option would be to make a LoginAttemptResource and serialize that instead of an error. You could use it to communicate the remaining attempts and the time they could try again as well as the token.

**Comment by senid231** [comment]
the idea is to return 422 with error in response and do something in callback
