### ISSUE TITLE
Problems creating a resource and its relationships at the same time

### ISSUE THREAD

**Issue by ezilocchi** [JSONAPI-Resources/jsonapi-resources#792]
I have these models:

``` ruby
class Address
end

class Event
  belongs_to :address
end
```

and these resources

``` ruby
class AddressResource < JSONAPI::Resource
  attributes :id,
    :name
end

class EventResource < JSONAPI::Resource
  attributes :id,
    :name,
    :created_at,
    :updated_at

  has_one :address
end
```

Given that no addresses or events exist, when I perform `POST /events` with this payload

``` json
         {
          "data": {
            "type": "events",
            "attributes": {
              "name": "My Event",
              "start-at": "2016-07-30T00:11:21Z",
            },
            "relationships": {
              "address": {
                "name": "My Place",
              }
            }
          }
        }
```

I'm getting this error:

``` json
{
    "errors": [
        {
            "title": "must exist",
            "detail": "address - must exist",
            "code": "100",
            "source": {
                "pointer": "/data/relationships/address"
            },
            "status": "422"
        }
    ]
}
```

Shouldn't it insert both rows in the database? Doing it from the console:

```
irb(main):008:0> e = Event.new(name: 'my event', start_at: 2.days.ago, address: Address.new(name: 'my address'))
=> #<Event id: nil, name: "my event", start_at: "2016-08-03 13:44:56", created_at: nil, updated_at: nil, url: nil, address_id: nil>
irb(main):009:0> e.save!
   (0.1ms)  BEGIN
  SQL (0.3ms)  INSERT INTO "addresses" ("name", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["name", "asfd"], ["created_at", 2016-08-05 13:44:58 UTC], ["updated_at", 2016-08-05 13:44:58 UTC]]
  SQL (2.5ms)  INSERT INTO "events" ("name", "start_at", "created_at", "updated_at", "address_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "my event"], ["start_at", 2016-08-03 13:44:56 UTC], ["created_at", 2016-08-05 13:44:58 UTC], ["updated_at", 2016-08-05 13:44:58 UTC], ["address_id", 2]]
   (0.4ms)  COMMIT
```

**Comment by lgebhardt** [comment]
The JSON API spec does not support creating dependent objects. There will be a new version which supports multiple operations. We will be adding support for that in JR once the spec is finalized.

**Comment by Subtletree** [comment]
I know this isn't specific to jsonapi-resources but is there a recommended solution for this in the meantime?

For situations like the one above you could just save the event and then save the address afterwards using the returned event id. But what about for a large application form with dozens of nested models?

**Comment by ezilocchi** [comment]
@Subtletree thanks for the proposal, anyway I have some concerns about this:
`For situations like the one above you could just save the event and then save the address afterwards using the returned event id`. 
1. You cannot handle this as a business and database transaction. If you save the event and it passes, then you attempt to save the address and it fails, your database will end with data inconsistency.
2. You need to perform syncronous requests, since you need to wait for the response for the event creation in order to create the address

**Comment by lgebhardt** [comment]
> I know this isn't specific to jsonapi-resources but is there a recommended solution for this in the meantime?

I'm hoping to have a prototype version that supports operations out fairly soon. The goal is to test out ideas for the upcoming spec, so it obviously won't be production ready. Other than testing with that I don't have a solution for the mean time.

**Comment by Subtletree** [comment]
@ezilocchi Oh yeah I 100% agree. It's definitely far from an ideal solution, I'm just trying to think of any methods to deal with this in the meantime.

@lgebhardt That sounds awesome, I'll jump on the prototype for testing as soon as you've got it. Loving jsonapi-resources btw, thanks heaps!
