### ISSUE TITLE
Support for models with namespaces

### ISSUE THREAD

**Issue by achan** [JSONAPI-Resources/jsonapi-resources#81]
Am I missing something or is it not possible to specify a model with a namespace for a given `Resource`?

For example, how would I create a resource for `Test::User`?

**Comment by achan** [comment]
I see it now... sorry.

For anyone wondering, it would be like this:

``` ruby
class UserResource < JSONAPI::Resource
  model_name 'Test::User'
  ...
end
```

**Comment by webpapaya** [comment]
if you have namespaced models how can the type be prefixed? (eg. test-user)

**Comment by lgebhardt** [comment]
I'm not sure I'm following. I hope this helps. You can specify the model for the resource as shown above. You could create a resource named TestUserResource and if you set the formatting rules to use dasherized keys it will come out as `test-user`.

**Comment by webpapaya** [comment]
Ah ok thanks I think I completely missed a point. I thought that the type gets extracted from the model and not the resource name.

**Comment by nathanpalmer** [comment]
I'm having trouble getting this to work properly. Over half of our models are namespaced and I'm experiencing inconsistencies. See this example:

`/api/project_resource.rb`

``` ruby
class API::ProjectResource
  has_many :people
end
```

`/api/project/people_resource.rb`

``` ruby
class API::Project::PeopleResource
  has_one :main_product, class_name: 'Product'
  has_one :secondary_product, class_name: 'Product'
end
```

`/api/product_resource.rb`

``` ruby
class API::ProductResource
end
```

1) In order for it to find the resource for one of our models it must be in a sub directory (which I prefer) as you can see from the `/api/project/` directory

2) Sometimes it's looking for the product_resource under `/api/project` and sometimes it's not. The easiest way for me to replicate it is to include the main_product and then right afterward change it to include the secondary product. It usually fails right then with this error

`JSONAPI: Could not find resource 'api/project/Product'. (Class API::Project::ProductResource not found)`

**Comment by rolandoalvarado** [comment]
Still having issue with relating resource with namespace. Anyone have a solution regarding this one?
