### ISSUE TITLE
Sort by association with postgres not working

### ISSUE THREAD

**Issue by arcreative** [JSONAPI-Resources/jsonapi-resources#810]
I have followed the belongs_to/has_many/sortable_fields instruction as in the readme, but I still get `PG::UndefinedColumn: ERROR:  column users.location.name does not exist`.  Is this not supported in postgres, or am I doing something wrong?

**Comment by aldhsu** [comment]
@arcreative which version of JR are you using? Sorting on relationship fields is only enabled in `> 0.7.0`.

**Comment by arcreative** [comment]
Thanks, I'm using `0.7.0`

**Comment by arcreative** [comment]
And if you need more information, let me know!

**Comment by arcreative** [comment]
Maybe misunderstood that--do you mean > `0.7.0` or >= `0.7.0`?

**Comment by arcreative** [comment]
`0.7.0`, realized I was looking at the documentation for master, thanks for clearing that up :-)
