### ISSUE TITLE
Documentation for sparse fieldsets

### ISSUE THREAD

**Issue by arcreative** [JSONAPI-Resources/jsonapi-resources#813]
Super awesome that this was considered and included, but it's not documented anywhere!  Just figured I would try it for fun, and lo and behold `fields[users]=first_name,last_name,email` works perfectly!

**Comment by utilityboy** [comment]
@arcreative https://github.com/cerebris/jsonapi-resources/wiki/JSONAPI::Resources-Querystring-Examples

**Comment by arcreative** [comment]
Ok cool, just feels like it should be in the readme.  There's _so much_ in the readme that I don't tend to go anywhere else.  Would suggest either adding it there or removing all but the basics from the readme to maintain consistency.

**Comment by utilityboy** [comment]
Agreed. There is an open PR and it's been on my todo list to move this into the readme for a while. I'll get to it today.

**Comment by evolve2k** [comment]
Ping. Sounds like this is almost solved.. can we get it ticked off,..  get this issue list down a little.

Thanks @utilityboy :)
