### ISSUE TITLE
Docs site

### ISSUE THREAD

**Issue by utilityboy** [JSONAPI-Resources/jsonapi-resources#837]
@lgebhardt and @dgeb I've been adding a little documentation here and there but now that 0.8.0 is out the door, I'd like to make a concerted effort to spearheading/contributing to a gh-pages documentation site for this gem. 

Thoughts?

**Comment by lgebhardt** [comment]
@utilityboy That would be great. I think it would probably be best if we published the pages from the `gh-pages` branch instead of the docs folder in master. That would let us keep the pages accurate to the current released version instead of master, which creates problems with the current readme approach. However I'm new to pages, so maybe that's not a good idea.

**Comment by lgebhardt** [comment]
I went ahead and turned on pages generated from the gh-pages branch and imported the readme (from master) as a starting point. The URL is http://cerebris.github.io/jsonapi-resources/.

This was only to try out gh-pages and create a branch that PRs can be made against. Obviously we will want to completely redo the content of the site.

**Comment by utilityboy** [comment]
@lgebhardt that's fine.  I'll work off that branch on my fork.  Thanks!

**Comment by lgebhardt** [comment]
@utilityboy Thanks for doing this. And feel free to start with a clean slate - wiping the existing files is fine and expected.

**Comment by utilityboy** [comment]
@lgebhard will do.  One thing I would like to do is come up with some sort of domain model for examples so they're consistent.  Right now we have authors and books and cars... oh my!

I was going to use a coffee shop as an example so there's no overlap or confusion with existing stuff.  Also, I love coffee.

**Comment by lgebhardt** [comment]
@utilityboy I love coffee. Having a consistent domain model will be an improvement. The current ones come from the tests where I found having several different domain models for testing different configurations was helpful. But it's certainly not ideal for the docs.

**Comment by evolve2k** [comment]
Just making a note. Please include this in a future FAQ.
- How do I Include relationships in create action responses but not on other action responses https://github.com/cerebris/jsonapi-resources/issues/871
