### ISSUE TITLE
URL encoding

### ISSUE THREAD

**Issue by Keqi** [JSONAPI-Resources/jsonapi-resources#851]
Is there a flag/option to turn off url encoding? For example in pagination links.

**Comment by lgebhardt** [comment]
Sorry, no. The code is using the `to_query` method to convert the query params. You would need to patch https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/link_builder.rb#L34 and https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/link_builder.rb#L39. If you do choose to do this note that `to_query` also sorts the parameters in a consistent way for caching.

Why exactly do you want this?
