### ISSUE TITLE
How does the nesting of routes work?

### ISSUE THREAD

**Issue by romanchukenator** [JSONAPI-Resources/jsonapi-resources#857]
As in, `cars/:car_id/wheels/:wheel_id`

I'm only getting to `cars/:car_id/wheels`

**Comment by lgebhardt** [comment]
It doesn't work that way. You get:

```
cars
cars/1
cars/1/relationships/wheels
```

but deep nesting isn't supported.

**Comment by romanchukenator** [comment]
Gaaaaaaaaaaaaaaaaaah.

Okay, cool. Thanks for the quick reply!
