### ISSUE TITLE
Depend on only those parts of rails that are needed

### ISSUE THREAD

**Issue by benarmston** [JSONAPI-Resources/jsonapi-resources#859]
I've just added jsonapi-resources as a dependency to a project.  After `bundle install`ing my project now has dependencies on sprockets, actioncable, actionmailer and all of their dependencies.  None of which my project actually needs.

jsonapi-resources should only depend on those parts of rails that it actually uses.

**Comment by evolve2k** [comment]
Hi @benarmston please see: https://github.com/cerebris/jsonapi-resources/issues/811, same issue. Could u possibly add to the conversation there and close this ticket just to keep all the discussions in one place. Thx.

**Comment by quinn** [comment]
PR: https://github.com/cerebris/jsonapi-resources/pull/860

**Comment by quinn** [comment]
@benarmston This should be fixed in master.

**Comment by evolve2k** [comment]
This Issues has been resolved per #860 above.
@lgebhardt, this ticket can be closed.
