### ISSUE TITLE
Is duplicate relationship check required?

### ISSUE THREAD

**Issue by barelyknown** [JSONAPI-Resources/jsonapi-resources#861]
Is the new duplicate relationship check (https://github.com/cerebris/jsonapi-resources/blob/0534288afe482f2c5cb1cb231061479761b594eb/lib/jsonapi/resource.rb#L1080) needed? I have a one set of resources built on an STI model (`TenderResource`, `BrokerTenderResource`, `CustomerTenderResource`). The `TenderResource` classes declare a `has_one` relationship to another STI model, but the class_name of that relationship differs for each of the `TenderResource` subclasses.

I haven't figured out any way to support the behavior that I want without declaring the has_one relationship in both the superclass (`TenderResource`), and then overriding it in each subclass (`BrokerTenderResource` and `CustomerTenderResource`), but that generates the warning.

cc @lgebhardt

**Comment by lgebhardt** [comment]
I'm not sure it's needed, but it is helpful in some cases. I've found it particularly helpful when a base class implements a relationship and the subclass also unintentionally implements the relationship. Modifying the relationship in one place may not produce the desired results and tracking it down can waste time. Looks like you found the use case where it's desirable to have it declared in both.

What do you want to do?

**Comment by barelyknown** [comment]
I see the benefit of the warning, and I think that you're right that it should be the default. I just implemented `check_duplicate_relationship_name` in the superclass (`TenderResource`) and had it skip the relationships that I did not want to hear warnings about.

**Comment by lgebhardt** [comment]
Sounds like a good solution.
