### ISSUE TITLE
commit missing from release 0.8.0 gem.

### ISSUE THREAD

**Issue by jimsynz** [JSONAPI-Resources/jsonapi-resources#862]
Hi there.

I ran into an issue where resources routes are throwing 500's for some mounted engines, and eventually found my way back to https://github.com/cerebris/jsonapi-resources/commit/ed0588783ef154b14fbcf34d0d3f858b69ea282c which fixes the issue. What's interesting about this is that I am running 0.8.0 in my project:

```
$ gem pristine jsonapi-resources
Restoring gems to pristine condition...
Restored jsonapi-resources-0.8.0
$ at "$(bundle show jsonapi-resources)/lib/jsonapi/link_builder.rb" | grep -A6 def\ engine_resources_path_name_from_class
    def engine_resources_path_name_from_class(klass)
      scopes         = module_scopes_from_class(klass)[1..-1]
      base_path_name = scopes.map { |scope| scope.underscore }.join("_")
      end_path_name  = klass._type.to_s
      "#{ base_path_name }_#{ end_path_name }_path"
    end
```

According to the compare view, the change in question is in the `v0.8.0` tag.

**Comment by lgebhardt** [comment]
Should be fixed with the 0.8.1 release.
