### ISSUE TITLE
Support for Rails 4.0.x in v0.8.1?

### ISSUE THREAD

**Issue by davidstosik** [JSONAPI-Resources/jsonapi-resources#865]
Hello,

JR's readme still states, in v0.8.1, that it is _designed to work with Rails 4.0+_.
Unfortunately, that is not the case since v0.8.0.
In [resource_serializer.rb#L176](https://github.com/cerebris/jsonapi-resources/blob/v0.8.1/lib/jsonapi/resource_serializer.rb#L176), there is a call to `Hash#compact`, which is only supported by Rails 4.1.x. ([See the `Hash#compact` method on Rails API doc.](http://apidock.com/rails/v4.1.8/Hash/compact)).

I understand that Rails 4.0 is getting old, so maybe the easiest is to drop its support. My temporary workaround will be to backport the `Hash#compact` monkey patch.

**Comment by lgebhardt** [comment]
Sorry, I guess I missed updating the Readme. In 0.8 we are only supporting (and testing) back to rails 4.1. And support is being dropped for 4.1 (see #856) in 0.9.
