### ISSUE TITLE
Move Configuration section of the README under installation to enhance UX and reduce silly questions.

### ISSUE THREAD

**Issue by evolve2k** [JSONAPI-Resources/jsonapi-resources#867]
Just had a bit of an insight. When @lgebhardt  showed me config.always_include_to_one_linkage_data I was like, I never saw that anywhere!! 

Went to the readme and threw it in and then realised oh darn there is all this config info nicely avaiable but it's at the bottom of the doc.

I think as the README is so long and you jump from installation into usage, once u add the usage code then it's like why am I getting these errors??

Basic errors are 1. related entities are not included?? 2. json key format isn't right. 3. json route format ... this one is crazy.. after I set the key format and the route didnt change I literally though that ur library only supported dasherize for routes and Ive even been telling ppl so (soz).
I've literally added this to my routes to fix what I thought was gaps in ur library..

I had this from the Useage section of the README
jsonapi_resources :expense_items

I then researched Rails docs and added these to support camelCase as a workaround
post 'expenseItems' => 'expense_items#create'
patch 'expenseItems/:id' => 'expense_items#update'
delete 'expenseItems/:id' => 'expense_items#destroy'

Where I have been going wrong is I stopped reading for that when I saw in the README under Key Format

> By default JR uses dasherized keys as per the JSON API naming recommendations. This can be changed by specifying a different key formatter.
> and thought that was that.

Yes im silly, but I've had 3 other devs pair with me on this and none of us found the config we kept just skimming the rest of teh README! lol!

Im thinking the answer is just to move the Configuration section right up the doc to under Installation.

Another solution is to add a installation generator and push that file into my config folder.

Getting this info earlier in the README will improve project UX greatly and probably stop a lot of silly questions you are getting from ppl following install instructions, jumping through the usage and then hitting into errors that could have been addressed by knowing all the config options available that were being missed as they are at the bottom of a really long README.

**Comment by lgebhardt** [comment]
See #837. Hopefully we'll get this up soon. Splitting the docs into multiple pages should allow for more in depth content. I'd love to have some pages to describe app setup, which would cover things like formatters, namespaces, and configuration options. In the mean time I'm always willing to take a PR to improve the Readme.

**Comment by utilityboy** [comment]
I'll throw a few hours on the weekend at this. We can discuss the structure as a starting point and I'll get some placeholders in.
