### ISSUE TITLE
Top level links

### ISSUE THREAD

**Issue by lgebhardt** [JSONAPI-Resources/jsonapi-resources#87]
Support creation of the top level links hash.

I think this should be done in the `setup` of the `request` object and provided to the `serializer` in the initializer. Otherwise the serializer will require full knowledge of the request in order to create the proper links.

Links should include a full query string, including `filter`, `sort`, and `page parameters.

**Comment by sineed** [comment]
@lgebhardt I decided to start implementing this and I found this branch https://github.com/cerebris/jsonapi-resources/tree/toplevel_links. So I have a question: do you continue to implement top-level links or I can help with something?

**Comment by lgebhardt** [comment]
I think that branch is likely to be very out of date, and it would be better to just start again. Feel free to look at the branch, but if I remember I didn't get very far on it, and the spec has completely changed regarding top level links.

**Comment by mmartinson** [comment]
any status on this?

**Comment by lgebhardt** [comment]
@mmartinson sorry to say I haven't done any work on this one yet (well since the very out of date branch listed above).

**Comment by mmartinson** [comment]
It's something I might look into for my own project. If I was going to write something that might make it for a PR, is there are starting point for this that you have considered. Or any approaches that you have ruled out?

**Comment by lgebhardt** [comment]
A few thoughts:
- A configuration option for whether to support top level links globally
- Maybe a config option to determine which of the optional links to produce. I'd rather just have it all or nothing to start. But if there's a good reason I'm open to making them configurable.
- The serializer should have options for any info it needs to construct the `related` links. It may already have all it needs with the `@base_url` option and access to the configuration.
- Constructing the `self` and pagination links is going to be where I see most of the work. I think if the serializer is provided with the `fields`, `include`, and `page` parameters from the request it should be straight forward.
- We can add some methods on the Paginators to help with the link building based on the current params.

This is as far as I've really thought about it. I'm sure I'm missing some stuff that will be obvious once we start coding this. If you wish to produce a PR to handle this it would be very much appreciated. I'd also be glad to collaborate on it.

There will probably be a bit of overlap with populating the `meta` sections with pagination data. We should consider #126 as we design this.

**Comment by barelyknown** [comment]
What's everyone thinking now about pagination links in the top level `links` object? There are a couple of issues that reference it, but it doesn't look like any PRs are merged. Can we organize an effort to get these in?

**Comment by senid231** [comment]
+1 for optional top level links

**Comment by lgebhardt** [comment]
As I said in #126 we hope to add top level links in a similar manner to the way top level meta is now implemented. This will probably be the next feature I work on.

**Comment by bartocc** [comment]
Am I wrong or has this been fixed in 0.4.1 ?

I can see the top level links hash in my server response with the 'first', 'last' and 'next' keys.

I don't know how to use those links with ember-data 0.13.5 though. If you have any guidance ...

**Comment by lgebhardt** [comment]
The paginators do output top level links now. I don't have any guidance for using them with ember-data. Hopefully someone else can chime in.

**Comment by john-griffin** [comment]
Ember data does not currently support JSON API pagination links. You can see progress here as "Sugar for pagination" https://github.com/emberjs/data/issues/2905

**Comment by lgebhardt** [comment]
Closing as links were added a while ago

**Comment by ballPointPenguin** [comment]
As of 0.10.2 I do not see a top level "links" object, nor a way to configure one to be included. This is not regarding any kind of meta or pagination information, just the basic, default top level "links" that is shown here https://jsonapi.org/format/#fetching-resources-responses-200

```json
{
  "links": {
    "self": "http://example.com/articles"
  },
  "data": []
}
```
