### ISSUE TITLE
Conditional configuration for not whitelisting exceptions

### ISSUE THREAD

**Issue by Petesta** [JSONAPI-Resources/jsonapi-resources#887]
Currently, `jsonapi-resources` doesn't allow propagation of errors unless specified in `exception_class_whitelist`. So if there are any connection issues or others, then they wouldn't be intercepted. With gems like `sentry-raven` they expect the errors to be caught through the middleware but they won't unless we whitelist all errors.

I was wondering if it would make sense to include a conditional configuration option that would allow us to avoid having to whitelist errors.

https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/acts_as_resource_controller.rb#L63-L82

https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/acts_as_resource_controller.rb#L261-L278

``` ruby
def process_request
  return unless verify_accept_header

  @request = JSONAPI::RequestParser.new(params, context: context,
                                        key_formatter: key_formatter,
                                        server_error_callbacks: (self.class.server_error_callbacks || []))

  unless @request.errors.empty?
    render_errors(@request.errors)
  else
    operations = @request.operations
    unless JSONAPI.configuration.resource_cache.nil?
      operations.each {|op| op.options[:cache_serializer] = resource_serializer }
    end
    results = process_operations(operations)
    render_results(results)
  end
rescue => e
  handle_exceptions(e)
end


def handle_exceptions(e)
  case e
  when JSONAPI::Exceptions::Error
    render_errors(e.errors)
  elsif JSONAPI.configuration.propagate_errors || JSONAPI.configuration.exception_class_whitelisted?(e)
    fail e
  else
    (self.class.server_error_callbacks || []).each { |callback|
      safe_run_callback(callback, e)
    }

    internal_server_error = JSONAPI::Exceptions::InternalServerError.new(e)
    Rails.logger.error { "Internal Server Error: #{e.message} #{e.backtrace.join("\n")}" }
    render_errors(internal_server_error.errors)
  end
end
```

We would check to see if the flag has been set, in this case I just named it `propagate_errors`, and make a call out to `fail`?

**Comment by Petesta** [comment]
This is something I'd be willing to add.

**Comment by lgebhardt** [comment]
Seems useful to me. What do you think about making the `exception_class_whitelisted?` handle consideration of the new option? We could rename it something like `whitelist_all_exceptions` so it's clear it would override `exception_class_whitelist`. The only code changes would be in the Configuration class.

**Comment by Petesta** [comment]
That seems perfectly fine to me. I'll make a PR for it and let me know what you think.
