### ISSUE TITLE
Non active record models as resources?

### ISSUE THREAD

**Issue by lcmen** [JSONAPI-Resources/jsonapi-resources#891]
Hi,
Is it possible to use non active record models (i.e. PORO) as a model backing the resource with `has_many` / `has_one` relationships?

Basically I have a virtual model on the FE which does not exist on it's own in the database. It's more like an overview which is generated during fetch (that resource is suppose to be read only).

To give you more concrete example:

``` ruby
# app/resources/post_resource.rb
class PostResource < JSONAPI::Resource
  has_one :stats
end

# app/resources/stats_resource.rb
class StatsResource < JSONAPI::Resource
  # I would like here to use `Stats` object (PORO) which will generate
  # some statistics for each post when asked for `/post/post_id/stats`
end
```

Can I achieve something like this?

**Comment by lgebhardt** [comment]
Yes, you can use POROs. You will need to override some of the resource methods. There's a simple example in the tests: [resource](https://github.com/cerebris/jsonapi-resources/blob/master/test/fixtures/active_record.rb#L1106) and [PORO](https://github.com/cerebris/jsonapi-resources/blob/master/test/fixtures/active_record.rb#L452)

At a minimum you will need to override the `self.find` and `self.find_by_key` methods for a read only model. To save changes you might need to override `_save`.

**Comment by lcmen** [comment]
@lgebhardt thank you for your reply and links. How about connecting PORO with AR model like in my example? Is it doable?

Currently I got error that `Association named 'xx' was not found on yy; perhaps you misspelled it?`

UPDATE: I think the problem is with my request - I'm calling `/posts/post_id?include=stats` which tries to preload association. Are there any workarounds?

UPDATE 2: I found that I can override `self.find_by_key` in parent resource and remove that include like this:

``` ruby
  def self.find_by_key(key, options = {})
    options.fetch(:include_directives).include_directives[:include_related].delete(:stats)
    super
  end
```

UPDATE 3: I found that it's better to override `self.apply_includes` like this:

``` ruby
  def self.apply_includes(records, options = {})
    if options[:include_directives]
      # Deep copy as I'm not sure how to make a new IncludeDirectives object
      # that I can modify
      options = Marshal.load(Marshal.dump(options))
      options[:include_directives].include_directives[:include_related].delete(:stats)
    end
    super
  end
```

It removes association from preloading but still return it under `included` (solution from #2 didn't do that).

I have a feeling it still hacky and there is better way to do it.

**Comment by lgebhardt** [comment]
@lowski I think how you are doing it with `apply_includes` is the correct way. It is a bit hacky, but I think it's the cleanest way with the current architecture of the project. I'm not sure any way of mixing POROs with AR models won't feel hacky.

**Comment by lcmen** [comment]
@lgebhardt thanks for your reply. Everything is clear, we can close this issue.

**Comment by pkoch** [comment]
Got here from Google search. Is there a better/preferred way now, or should I just follow suit with @lowski's approach?
