### ISSUE TITLE
Handling validates_confirmation_of

### ISSUE THREAD

**Issue by maha99tests** [JSONAPI-Resources/jsonapi-resources#897]
I'm sorry if this is a repeat issue, but I looked through the docs and couldn't find anything about handling validates_confirmation_of .

Currently any attempt to save a user via the JSON API in my project fails because of this.

Is there a way to conveniently handle this in JSON API right now?

**Comment by lgebhardt** [comment]
I guess the first thing I'd ask is if this should be handled by the API. If possible I would rather put this logic on the client making the call in the case of a password confirmation.

But assuming you do want the server to handle the confirmation you could add a new attribute for the password confirmation to your resource. If you remove this from the `fetchable_attributes` it will be a write only attribute.

``` ruby
class UserResource < JSONAPI::Resource
  attributes :name, :email, :password, :password_confirmation

  # Never return the password details
  def fetchable_fields
    super - [: password_confirmation, :password]
  end
end
```

Assuming the fields exist on your model that should work. A good way to think of the resource is simply as a passthrough filter for your models.

**Comment by maha99tests** [comment]
Thank you, my stupidity, I had set everything but used the wrong name for the confirmation field in ember.js . Closing this issue with a brown paper bag over my head lol.
