### ISSUE TITLE
Applying filter doesn't work

### ISSUE THREAD

**Issue by pauldoerwald** [JSONAPI-Resources/jsonapi-resources#898]
Hi,

I'm having a situation where I'm trying to apply a filter, and it's simply not happening. The syntax is essentially this:

    class Api::V1::BucketResource < JSONAPI::Resource
      model_name 'Store'
      attributes :jsonbody, :bucket
      filter :bucket, apply: :apply_bucket_filter
      ...
      def apply_bucket_filter(records, value, _options)
        Rails.logger.info "Show me that I made it here"
        records.where(store: value[0])
      end
      ...
    end

The important point about this is that the actual model, named `Store`, does not have a `bucket` column, it has a `store` column. Since `store` is a reserved word in Ember.js, I am using this approach to "rename" it. The problem is that the filter is never called — that is, the `Rails.logger.info` text never appears in my logs.

I've tried removing `:bucket` from `attributes:`, I've added `bucket` setters and getters in both the resource and the model, and basically, there's no combination I can find where I am able to filter by bucket.

In order to see if I'm missing the point completely, I tried a different model, where the filter was on a real database column, and everything worked as I expected. I'm thus pretty sure my syntax is right, but I must be missing some kind of nuance about how to apply filters when it's not a real database column.

What am I doing wrong here? 

Paul.

**Comment by lgebhardt** [comment]
put `self.` before `apply_bucket_filter`:

``` ruby
class Api::V1::BucketResource < JSONAPI::Resource
  model_name 'Store'
  attributes :jsonbody, :bucket
  filter :bucket, apply: :apply_bucket_filter
  ...
  def self.apply_bucket_filter(records, value, _options)
    Rails.logger.info "Show me that I made it here"
    records.where(store: value[0])
  end
  ...
end
```

**Comment by pauldoerwald** [comment]
I'm afraid that wasn't the answer, but I found the problem. It was in how I was making the request. My bad. So sorry for the trouble :-(.

**Comment by ruslankhaertdinov** [comment]
@pauldoerwald  I have similar issue: there are no `activated` column, but I want to filter by this param. Could you please explain how you fix your own issue?
```
class CameraResource < ApplicationResource
  attributes :activated

  filter :activated, apply: :activated_filter

  def self.activated_filter(records, value, _options)
    records.activated
  end
end
```
My request: `get "/cameras?filter[activated]=true"`
And I got this `column cameras.activated does not exist` error.

Thanks advance.

@lgebhardt sorry for wrong mentioning.

**Comment by pauldoerwald** [comment]
@ruslankhaertdinov As I mentioned above, it was a syntax error on my part with the request. The rest of your error isn't consistent with mine; my `apply_bucket_filter` wasn't even running. Given that you don't have a `Camera#activated` column, and I assume you can determine whether a camera is activated by column information, I'd rewrite your callback as:

    def self.activated_filter(records, value, _options)
      records.where(state: 'activated')
    end

replacing `state:activated` by whatever query you need; the JSONAPI `filter` expects a Relation which it can further qualify with where clauses.

**Comment by ruslankhaertdinov** [comment]
@pauldoerwald Thanks for your response, but unfortunately even if I write this:
```
filter :activated, apply: :activated_filter

def self.activated_filter(records, value, _options)
  records.none
end
```
I got same error. Looks like `apply` option not applied...

**Comment by pauldoerwald** [comment]
Oh yes, you don't need the `self.`. Sorry I forgot to remove that from my email.

My ultimate solution looked like this:

    filter :bucket, apply: ->(records, value, _options) {
      records.where(store: value[0])
    }

The inline approach worked. I can't recall if I was able to get the other approach working or not. Given that I closed the ticket, I suspect the problem was between the keyboard and the chair with the format of my query.
