### ISSUE TITLE
Sorting by method return

### ISSUE THREAD

**Issue by romanchukenator** [JSONAPI-Resources/jsonapi-resources#900]
Hey guys, sorting questions. As in this weirdly simple example, looking to sort by ```identifier```.

```
attributes :identifier

def identifier
  @model.identifier
end
```

I've tried this, too:

```
def self.sortable_fields(context)
  super(context) << :"identifier"
end
```

No dice. Help?

**Comment by lgebhardt** [comment]
I would think that would work, though you shouldn't need the getter on your resource since it's named the same as your model attribute. I would look into `apply_sort` with a debugger and see what the AR relation looks like.
