### ISSUE TITLE
Start keeping track of a changelog

### ISSUE THREAD

**Issue by warmwaffles** [JSONAPI-Resources/jsonapi-resources#906]
It would probably be wise to add one http://keepachangelog.com/en/0.3.0/

**Comment by lgebhardt** [comment]
Where would you expect to see the CHANGELOG file? Keep in mind we have release branches, a beta branch and the master branch. We will also have a documentation site up very soon (hopefully next week).

We do keep change release notes in https://github.com/cerebris/jsonapi-resources/releases, which I see is currently missing the notes for the 0.9.0 beta release. If we added some of the concepts from the linked paged to the release notes would that be adequate?

**Comment by warmwaffles** [comment]
Most projects I've encountered have it stored in the root directory as `CHANGELOG` 

example: https://github.com/plataformatec/devise/blob/master/CHANGELOG.md

Friend of mine linked me this https://github.com/skywinder/github-changelog-generator which I think scrapes the releases and then spits out a change log.

Overall just want to see a place where features added, deprecated, removed can be found without having to page through a bunch of stuff.
