### ISSUE TITLE
Prevent expensive queries with query analysis + max depth

### ISSUE THREAD

**Issue by esiegel** [JSONAPI-Resources/jsonapi-resources#908]
Is there any way of preventing a malicious or erroneous query from being run?

I worry that by allowing including associated resources, which in turn can include more resources, could potentially allow for extremely large DB queries and result sets.  This is especially true since all included resources are not paginated; not arguing that they should be, just saying that it allows for unbounded results.

From the graphql community I have seen people:
1.  Set a max inclusion depth.
2.  Perform query analysis by summing the fields and associations, with weightings, and supplying a cutoff number.
3.  Only allow specific queries, and then call them by name.
4.  Be very careful on what can and cannot be included
5.  Disallow including (not graphql, but jsonapi solution)
6.  Stop worrying because this is an internal api with trusted clients.

Right now I'm living with solution 4, but I know that eventually something will sneak in.  Mostly just wondering what other people are doing and if there is a sanctioned why to do it in this library.

thanks again for a great library.

**Comment by merrywhether** [comment]
I have this same concern as I'm considering different API implementations. Any word on this?

**Comment by lgebhardt** [comment]
I have the same concerns. I'm currently considering the best way(s) to handle this.

Without any new features to the project you could implement some of your options:

> 1. Set a max inclusion depth.

You could override the `apply_includes` method on your resource to check the depth of the requested includes.

> 2. Perform query analysis by summing the fields and associations, with weightings, and supplying a cutoff number.

Override `find_records` on your resource to perform the query analysis to check against a threshold complexity.

> 5. Disallow including (not graphql, but jsonapi solution)

You can omit the included relationships by [removing them from fields](http://jsonapi-resources.com/v0.8/guide/resources.html#Fetchable-Attributes). Not a complete solution, but it might be workable in some cases.

> 6. Stop worrying because this is an internal api with trusted clients.

Nothing could go wrong with this :wink:

**Comment by esiegel** [comment]
Thanks for the suggested solutions - they definitely seems like the way to go in the short term.

I know you're still considering next steps for an official solution, but for now I'll leave this issue open in case others want to chime in.
