### ISSUE TITLE
Have any way to set a filter params required?

### ISSUE THREAD

**Issue by zfben** [JSONAPI-Resources/jsonapi-resources#910]
Like `attribute :user_id, required: true`, and query must include `filters[user_id]`.

**Comment by lgebhardt** [comment]
There is not a way to specify a required filter. The [`default` option](http://jsonapi-resources.com/v0.8/guide/resources.html#Default-Filters) on `filter` might get a similar result if you default the `user_id` to the current user.

**Comment by machty** [comment]
I need this too, but possibly for invalid reasons.

In my case I have Retailers and Locations. My client-facing apps have no need for a `/retailers` endpoint; rather, I just need to query `locations` by `filter[retailer_id]=__`. The currently-authorized user has permissions to manage locations belonging to specific retailer_ids (JR handles the authorization logic for this well), but I still don't want to allow the app to query ALL the checkout locations. I ended up doing this hacky solution in the LocationResource

```
  filter :retailer_id, default: 'this_param_is_required'
```

This hackishly results in empty results if no query is provided. It'd be nice to more idiomatically error when filter is absent.

**Comment by samselikoff** [comment]
I need this too! Maybe we could keep it open as a feature request, or others could share some sort of escape hatch. I would actually prefer to respond with a 403 if a certain param isn't present.
