### ISSUE TITLE
Render custom error messages

### ISSUE THREAD

**Issue by AntoineDewaele** [JSONAPI-Resources/jsonapi-resources#919]
Is there a way to render custom error messages when I override a controller method ?
Or am I forced to do that ?
`render json: { errors: [{ status: '422', title: 'Unprocessable entity', detail: 'Invalid email or password' }]}, status: :unprocessable_entity`

**Comment by lgebhardt** [comment]
It will depend on how you have overridden the controller and what type of error you are trying render. If you use the standard errors and OperationResults it should be easy. Every `OperationResult` has a `to_hash` method that will serialize to a hash, which can be returned as json. Each `Error` also has a `to_hash` method.
