### ISSUE TITLE
Can't filter multiple dates with "BETWEEN"

### ISSUE THREAD

**Issue by garrett-thompson** [JSONAPI-Resources/jsonapi-resources#922]
My filter kinda looks like this:
```
filter :created_at, apply: -> (records, value, _options) {
    if value.length == 1
      records.where("model.created_at = #{value[0]}")
    elsif value.length == 2
      records.where("model.created_at BETWEEN SYMMETRIC #{value[0]} AND #{value[1]}")
    end
  }
```
but this is resulting in:
```
WHERE "accounts"."created_at" IN ('2016-11-30', '2017-01-01')
```

**Comment by garrett-thompson** [comment]
Nevermind... still had `:created_at` listed in my general `:filters` so my code was being overwritten with the default behavior

**Comment by jamesdixon** [comment]
@mellogarrett I know this is really old but how did you end up getting this implemented? I can't seem to get two filters of the same name to come through and also can't define filters that aren't actually attributes
