### ISSUE TITLE
Sideloading namespaced models working erratically 

### ISSUE THREAD

**Issue by joshuacronemeyer** [JSONAPI-Resources/jsonapi-resources#925]
Hi, I have a user resource for a namespaced user model with 2 has_many associations: addresses and credit_cards. When I request a user and include addresses everything works fine. When I request user and include the credit_cards I get a 400 bad request. My understanding is that the server should respond with a 400 when I've requested to include something that isn't available (like it says [here](http://jsonapi.org/format/#fetching-includes)) But i've setup the associations in the same way, so I'm not sure the models which are identical behave differently.

I created [a dummy rails app](https://github.com/joshuacronemeyer/jsonapi_resource_namespaces) with tests that illustrate this issue. Specifically Core::UsersControllerTest#test_should_get_user_from_api_with_credit_card_association and Core::UsersControllerTest#test_should_get_user_from_api_with_both_associations are failing. Any help determining if I'm doing something wrong or this is a bug would be appreciated, and thanks in advance!

**Comment by lgebhardt** [comment]
You've got a few errors in your tests:

1) the default format for keys is dasherized, so in your includes `credit_cards` should be `credit-cards`. This is in keeping with the JSON API recommendation. You can change this by choosing a different formatter. http://jsonapi-resources.com/v0.9/guide/formating.html#Key-Format

2) you have a space in the include `addresses, credit_cards`, which resolves to [`addresses`,` credit_card`]. Omit the space in addition to dasherizing `credit card`: `addresses,credit-cards`.

That should get you 3 out of 4 passing tests. The last one is simply that line 23 testing for data that isn't returned with no related credit card.

**Comment by joshuacronemeyer** [comment]
This is great, thanks for the extra hand holding and quick response! I'll
try that when I get to the office. Timing couldn't be better as I'm trying
to prepare a presentation to my team on jsonapi for later today.
