### ISSUE TITLE
JR 0.9 breaks when using `sort` at the same time as including a has_one association

### ISSUE THREAD

**Issue by NuckChorris** [JSONAPI-Resources/jsonapi-resources#933]
So, we're experiencing a really really bizarre bug... If we have a request, let's say this one:

`GET /reviews?filter[anime_id]=10052&include=user,user.favorite_character&sort=-likes_count`

You'd rightfully assume that it would do `sort(likes_count: :desc)`, right?  It did so in JR 0.8, but in 0.9 we're getting `characters.likes_count` — which doesn't exist!  I've managed to track down the case that triggers this: if an included association is a `has_one` association in AR, it always attempts to apply the sort property to that, no matter how deeply nested or whether the column exists.

We've seen this consistently across multiple resources since we started using the JR 0.9 beta.  We're using Rails 4.2.1

**Comment by lgebhardt** [comment]
@NuckChorris Please check out #935 and see if it fixes the issue for you.

**Comment by NuckChorris** [comment]
Wow, that was fast!  Huge thanks, that patch seems to work perfectly!
