### ISSUE TITLE
Question: Does a project exist for integration with Elasticsearch?

### ISSUE THREAD

**Issue by shamil614** [JSONAPI-Resources/jsonapi-resources#934]
I ask because I know there's a project for integrating Pundit
https://github.com/togglepro/pundit-resources

But I couldn't find one that help with integration with Elasticsearch so I wrote some custom code for a integration at work. Before I embark down a refactor / gem-ification of the lib code, I figured I should ask here.

BTW,
great work on the project! ❤️

**Comment by lgebhardt** [comment]
@shamil614 Thanks. I haven't seen a project that integrates elasticsearch with JR, though #468 has a discussion about it.

**Comment by shamil614** [comment]
Thank you. I was not able to find that thread earlier. I'll close this and pick up the thread in #468
