### ISSUE TITLE
HTTP/1.1 415 Unsupported Media Type

### ISSUE THREAD

**Issue by deantomlinson** [JSONAPI-Resources/jsonapi-resources#94]
This probably isn't an issue but I am trying to get your example apps to work by following your process and I keep getting this error when I copy the curl command to create a resource.  

> curl -i -H "Accept: application/json" -H 'Content-Type:application/json' -X POST -d '{"contacts": {"first_name":"John", "last_name":"Doe", "email":"john.doe@boring.test"}}' http://localhost:3000/contacts
> HTTP/1.1 415 Unsupported Media Type 
> X-Frame-Options: SAMEORIGIN
> X-Xss-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> Content-Type: application/json; charset=utf-8
> Cache-Control: no-cache
> X-Request-Id: 9b829ade-c674-49d6-9213-139312154469
> X-Runtime: 0.051207
> Server: WEBrick/1.3.1 (Ruby/2.1.5/2014-11-13)
> Date: Sat, 28 Feb 2015 21:32:03 GMT
> Content-Length: 292
> Connection: Keep-Alive

{"errors":[{"title":"Unsupported media type","detail":"All requests that create or update resources must use the 'application/vnd.api+json' Content-Type. This request specified 'application/json.'","id":null,"href":null,"code":415,"path":null,"links":null,"status":"unsupported_media_type"}]}% 

And the server log shows:

Processing by ContactsController#create as JSON
  Parameters: {"contacts"=>{"first_name"=>"John", "last_name"=>"Doe", "email"=>"john.doe@boring.test"}, "contact"=>{}}
Can't verify CSRF token authenticity
Filter chain halted as :ensure_correct_media_type rendered or redirected
Completed 415 Unsupported Media Type in 1ms (Views: 0.3ms | ActiveRecord: 2.0ms)

I am pretty sure that I am doing something wrong here but wanted to post here so that if others are having the same issue they can hopefully find an quick answer.  If I clone the repo it works.  I have tried multiple versions of rails with no luck too.

Thanks

**Comment by lgebhardt** [comment]
The problem is the code has been updated since the example apps were written. There have been a few changes that break the curl command as it's been documented. The first is JR now enforces the JSON-API media type requirement, which is the cause of the error you are getting. Once you fix that however you will run into issues because the data format has been changed (and may still be changing) in JSON-API.

I'll see if I can update the example app early next week to reflect these changes. Sorry for the confusion.

**Comment by deantomlinson** [comment]
Thank you for taking the time to explain what is going on.  I understand that that JSON API is nearing version 1, so you are working to stay compatible with the evolving spec.  I appreciate the examples that you have and would appreciate you updating them when it makes sense to do so.  Thanks
