### ISSUE TITLE
Filtering by multiple attributes?

### ISSUE THREAD

**Issue by bryanvero** [JSONAPI-Resources/jsonapi-resources#953]
What is the proper syntax to employ multiple filters at the same time with an AND relationship?

**Comment by lgebhardt** [comment]
`http://localhost:3000/contacts?filter[name-last]=Doe&filter[name-first]=John` 

though with curl you will probably need to escape it as:

`http://localhost:3000/contacts?filter%5Bname-last%5D=Doe&filter%5Bname-first%5D=John`

**Comment by lgebhardt** [comment]
You will of course also need to declare this filters on your resource.

**Comment by bryanvero** [comment]
Got it. I am writing my own filters. In my case, only one filter is being used to limit the results rather than both. How can I debug what is going on here?

**Comment by lgebhardt** [comment]
You can debug by overriding `self.apply_filters` on your resource. See https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource.rb#L693 for the source.
