### ISSUE TITLE
Extending controller methods

### ISSUE THREAD

**Issue by RitterNorbert** [JSONAPI-Resources/jsonapi-resources#957]
Hi

I am trying to implement this awesome gem to our new microservice.

I have to do a request which calls the create endpoint for a registration then after it's created it has to make two calls to two other microservices. 

What would be the best way to extend the controller methods?

**Comment by lgebhardt** [comment]
@RitterNorbert JR deviates a bit from regular rails in that it's probably best to not extend the controller methods, and instead rely on the [Operation Processors](http://jsonapi-resources.com/v0.8/guide/operation_processors.html) callbacks. The reason being is the processor will potentially be invoked from several controllers (reflected relationships). In addition when support for multiple operations is finished multiple controllers might be updating a resource.
