### ISSUE TITLE
Mention default is dasherize for key_format

### ISSUE THREAD

**Issue by daniely** [JSONAPI-Resources/jsonapi-resources#967]
I don't know if it's just me but it took me awhile to realize that I need to send my `PUT` request with dasherized field names. It would have been very helpful for me if the guide mentioned this when it shows the first examples of "attributes".

**If desired** I can submit a PR with updated section in the guide.

**Comment by dreamable** [comment]
I have similar issues. Why JR use dasherized field name, is it's required by JSON API spec, is it a bug?

**Comment by dreamable** [comment]
I saw the spec recommend to use "-" instead of "_", why? Most language prefer variable name with "_". Using "-" will cause a lot of trouble for converting them.

**Comment by daniely** [comment]
I think you're misunderstanding? The preference is for names like `first-name` instead of `first_name`. As for the reason, I don't know why.

Closing as this has been opened long enough without any official response.
