### ISSUE TITLE
J-R and Ancestry, sitting in a tree...

### ISSUE THREAD

**Issue by walterdavis** [JSONAPI-Resources/jsonapi-resources#981]
This quote from the documentation

> eager_load_on_include - if set to false, will not include this relationship in join SQL when requested via an include. You usually want to leave this on, but it will break ‘relationships’ which are not active record, for example if you want to expose a tree using the ancestry gem or similar, or the SQL query becomes too large to handle. Defaults to true if not set.

Suggests that someone has tried what I want to do, which is to explore an Ancestry-backed tree using this API. Links would include children (in the Ancestry sense of that term), the parent, etc.

Can anyone point me to an example of integrating these two gems?

Thanks!

**Comment by olleolleolle** [comment]
Hey @walterdavis!

In order to connect with the rest of the community, you can access [the Gitter chat channel](https://gitter.im/cerebris/jsonapi-resources?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge), where questions are on-topic and welcome.

There's a [question](https://github.com/cerebris/jsonapi-resources/labels/question) Label for Issues in this repository, but the chat channel has more interaction.

Good luck!

**Comment by nagirrab** [comment]
Hey @walterdavis, as the guy who wrote that bit, but who doesn't hang out on the chat channel, I figure I'd respond here.

The good news, is it basically works out the box if you set that flag. E.g I have it set up as such:

    class Tree
      has_ancestry
    end

    class TreeResource < JSONAPI::Resource
      relationship :subtree, to: :many, eager_load_on_include: false
      relationship :children, to: :many, eager_load_on_include: false
      relationship :parent, to: :one, always_include_linkage_data: true, eager_load_on_include: false
    end

Hope this helps!

**Comment by walterdavis** [comment]
This is brilliant, and much nicer than what I bodged together for a demo. I will be able to move ahead with real code now!

Walter

**Comment by walterdavis** [comment]
Did you need to create additional resources for Child or Subtree? I am getting an error at startup when I try to duplicate your technique above. `JSONAPI: Could not find resource 'child'. (Class ChildResource not found) (NameError)`. I feel like I'm missing something in my understanding of how these two gems want to work together. If it matters, I'm using Rails 5 for this experiment...

**Comment by nagirrab** [comment]
Oh, my bad, it'll get confused about the actual type, you need to do:

    class Tree
      has_ancestry
    end

    class TreeResource < JSONAPI::Resource
      relationship :subtree, to: :many, eager_load_on_include: false, class_name: "Tree"
      relationship :children, to: :many, eager_load_on_include: false, class_name: "Tree"
      relationship :parent, to: :one, always_include_linkage_data: true, eager_load_on_include: false, class_name: "Tree"
    end

**Comment by walterdavis** [comment]
Thanks. That works perfectly.
