### ISSUE TITLE
Related Resources do not appear to sort by their default sort criteria

### ISSUE THREAD

**Issue by joegaudet** [JSONAPI-Resources/jsonapi-resources#989]
```ruby
class Foo < JSONAPI::Resource

    has_many :bar

end

class Bar < JSONAPI::Resource

    attributes :position

     self.default_sort
        [{field: :position, direction: :asc}]
    end

end
```

I would expect 

GET /foos/1/bars

to be sorted by position in ascending order, however they appear to be sorted by primary key.

My work around for the time being is to override records_for_bars and have it return a sorted relationship.

Let me know if there is anything I can do to help.

.joe

**Comment by Vince-Smith** [comment]
It looks like this issue can be closed. Was fixed in gh-990 https://github.com/cerebris/jsonapi-resources/commit/600a818f4c4ca119ec8fde4993dfe712b7381c94
