### ISSUE TITLE
self link swapping rails multiword namespace _s for -s, giving wrong url

### ISSUE THREAD

**Issue by nruth** [JSONAPI-Resources/jsonapi-resources#995]
With a default install of `jsonapi-resources (0.9.0)`, Rails 4.2, and a route like:

```
namespace :example_namespace do
  jsonapi_resources :entry_routes
end
```

I'm seeing self links like

`http://localhost:3000/example-namespace/entry-routes/2` instead of
`http://localhost:3000/example_namespace/entry-routes/2`

So the dasherized_key default is fine for the resource, but it's changing the app's urls unexpectedly.

My actual routes are slightly more complicated, but I believe this is what's giving me problems.

**Comment by lgebhardt** [comment]
The namespace is treated as part of the route so it's formatted with the route_formatter along with the resource name. You could create a custom route formatter that treats the namespace as underscored.

**Comment by nruth** [comment]
Thanks for the suggestion! I changed my routes to be -'d in the end but will take another look and see if I can feed anything back to the docs.
