### ISSUE TITLE
raw hash data being re-formatted between formatter and setter

### ISSUE THREAD

**Issue by nruth** [JSONAPI-Resources/jsonapi-resources#996]
Rails 4.2, jsonapi-resources: 0.9.0

Part of my ember app submits a json hash as an attribute rather than creating lots of extra models. This is stored in postgres as jsonb.

I've noticed bugs since moving from mirage to rails (with jsonapi-resources) re: missing data. For example, an options hash that is submitted as:

`{"atLeast": 3}`

but for some reason (the bug) it's being stored as

`{"at_least": 3}`

To debug this I added a setter to the resource, and a custom serializer, and poked both with binding.pry / debugger to see what values were being passed in.

```
class RawValueFormatter < JSONAPI::ValueFormatter
  def self.format(raw_value)
    raw_value
  end

  def self.unformat(raw_value)
    # binding.pry
    raw_value
  end
end
```

```
# in the resource class
def options=(new_options)
  # binding.pry
  @model.options = new_options
end
```

The serializer receives the expected raw_value  `{"atLeast": 3}`, but the setter receives the other unexpected format.

Stringifying the data before submission seems like a work-around, but seems a bit strange.

**Comment by lgebhardt** [comment]
@nruth I'm not sure why your keys are being reformatted. I just tested some JSON attributes and the keys are not being altered, though I was doing it with the sqlite db and storing the json in a string field. I tried it both with a value formatter and setter/getters to handle the json.

```ruby
class JsonValueFormatter < JSONAPI::ValueFormatter
  class << self
    def format(raw_value)
      JSON.parse(raw_value)
    end

    def unformat(value)
      return if value.nil?
      value.to_s
    end
  end
end

class FooResource < JSONAPI::Resource
  attribute :extra_data
  attribute :extra_extra_data, format: :json

  def extra_data
    JSON.parse(_model.extra_data)
  end

  def extra_data=(extra_data)
    _model.extra_data = extra_data.to_s
  end
end
```

**Comment by nruth** [comment]
Thank you for checking! I guess it's application specific then, and sorry for the run-around. We have AMS in the app so perhaps that is interfering.
I'll try and reproduce this as a JR test case / in a new rails app, but closing the ticket as can't promise when that will happen. 

In case anyone else picks this up and wants a quick work-around, I found that stringifying the object worked: an ember transform that json-encodes on submission, and API parsing back to object before saving to pg.

**Comment by htcicek** [comment]
@lgebhardt 

Believe we ran into this issue ourselves and the cause seems to be the deep transformation of keys after parsing params.
https://github.com/cerebris/jsonapi-resources/blob/e92afc690f5c53da6f4fa5e91ca72a50873390be/lib/jsonapi/request.rb#L518-L522

We have a jsonb object with a case-sensitive key along the lines of `aB`, and the keyformatter unformats it to `a_b`.

Given that the `parse_params` method already unformats values, and unformats the attribute keys, the `deep_transform_keys` seems extraneous, and is mutating nested data.

That being said, stringifying the input data and parsing it seems to work as a workaround.
